### ISSUE TITLE
Unexpected Typescript error with many filters/maps

### ISSUE THREAD

**Issue by jzabinski-dolios** [ReactiveX/rxjs#6651] opened 2021-10-21 17:00 UTC
## Bug Report

**Current Behavior**
Too many operators seem to trick Typescript into thinking that an overall pipe returns type 'unknown' instead of the intended type.

**Expected behavior**
The intended return type of a pipe should be known if defined.

**Reproduction**

- REPL or Repo link:
https://stackblitz.com/edit/rxjs-bug-10-21?file=index.ts

**Environment**
- Runtime: Chrome
- RxJS version: 7.3

**Additional context/Screenshots**
The .ts file in the repro defines a pipe built from document scroll. (It is mostly taken from a pipe used in production, and is somewhat arbitrary.)

The pipe:
```
fromEvent(document, 'scroll')
  .pipe(
    // Filter for events that have actually been used
    filter<Event>(event => event.eventPhase === Event.AT_TARGET),
    // Current scroll top
    map<Event, number | null>(() => window.pageYOffset || null),
    // Filter for valid value
    filter<number | null, number>((val): val is number => !!val),
    // Convert to absolute distance from scrollTop
    map<number, number>(num => Math.abs(num)),
    filter<number>(top => top !== 0),
    // Filter for whether we have just finished scrolling to a new element
    filter<number>((top) => top % 150 === 0),
    // Convert scroll value to item index number
    map<number, number>((scrollIndex) => scrollIndex / 150),
    // Filter for whether we have scrolled to the last element
    filter<number>((itemIndex) => itemIndex === 5),
    map<number, number | null>(() => window.pageYOffset || null),
    // Uncomment below to produce a Typescript error.
    filter<number | null, number>((val): val is number => val !== null)
  )
  .subscribe((num) => {
    const val: ReturnVal = { num };
    console.log(val.num);
  });
```

Notice that the last pipe operator defines `filter<number | null, number>`, explicitly declaring that the function will return a `number`. But Typescript complains that the value sent to `next` is `unknown`.

<img width="582" alt="Screen Shot 2021-10-21 at 12 50 11 PM" src="https://user-images.githubusercontent.com/74222375/138323034-eb11b7f4-8d23-45d2-8272-93befdda6bc2.png">

  Try commenting out the last `filter`. Notice that Typescript is happy. Try commenting out any of the filters in the repro from line 16 to line 28. Notice that Typescript is happy.

<img width="566" alt="Screen Shot 2021-10-21 at 12 56 21 PM" src="https://user-images.githubusercontent.com/74222375/138323359-83efdd3b-ef1f-4f5e-a116-47110030d533.png">

**Comment by kwonoj** [comment] 2021-10-21 17:24
Dupe of https://github.com/ReactiveX/rxjs/issues/5599 .

**Closed by kwonoj** 2021-10-21 17:24 UTC
