### ISSUE TITLE
shareReplay not cleaning up subscriptions.

### ISSUE THREAD

**Issue by QimatLuo** [ReactiveX/rxjs#5132] opened 2019-11-11 08:33 UTC
## Bug Report

**Current Behavior**
The log keeps showing 'tick' every 1000ms after **unsubscribe**.

**Reproduction**
- https://stackblitz.com/edit/rxjs-zf58vt?devtoolsheight=60
```js
const { interval } = require('rxjs');
const { tap, shareReplay } = require('rxjs/operators');

const source = interval(1000).pipe(
  tap(() => console.log('tick')),
  shareReplay(1),
);

const sub = source.subscribe(x => console.log(x));

sub.unsubscribe();
```

**Expected behavior**
Should do nothing after **unsubscribe**

**Environment**
- Runtime: Node10, Chrome78
- RxJS version: 6.5.3

**Possible Solution**
I don't know.

**Additional context/Screenshots**
I saw this bug has been reported before https://github.com/ReactiveX/rxjs/issues/3336
And the PR already merged https://github.com/ReactiveX/rxjs/pull/4059
But I still get the same problem even though I re-install rxjs.

**Comment by jgbpercy** [comment] 2019-11-11 09:18
I believe this is working as intended - see this article by @cartant from the RxJS core team for more details: https://blog.angularindepth.com/rxjs-whats-changed-with-sharereplay-65c098843e95

Specifically, you can get the behavior you want by changing the argument to shareReplay from `1` to `{ bufferSize: 1, refCount: true }`. The `refCount` option will ensure that shareReplay unsubscribes when the reference count of subscribers to `source` drops to zero.

**Comment by cartant** [comment] 2019-11-11 09:34
Closing as working-as-intended.

**Closed by cartant** 2019-11-11 09:34 UTC

**Comment by QimatLuo** [comment] 2019-11-12 02:15
@jgbpercy - Thanks.
