### ISSUE TITLE
Documentation outdated?

### ISSUE THREAD

**Issue by Karasuni** [ReactiveX/rxjs#2530] opened 2017-04-07 12:09 UTC
At [this page documenting the `.do()` call](http://reactivex.io/documentation/operators/do.html).

> do/tap, doOnNext/tapOnNext, doOnError/tapOnError, doOnCompleted/tapOnCompleted, and finally are found in each of the following distributions:
> 
> rx.js
> rx.all.js
> rx.all.compat.js
> rx.compat.js
> rx.lite.js
> rx.lite.compat.js

Even though `doOnNext`, `doOnError` and `doOnCompleted` are not found in the latest version of RxJS.

Same with [this page on `.delay()`](http://reactivex.io/documentation/operators/delay.html).

> delay, delaySubscription, and delayWithSelector require rx.lite.js or rx.lite.compat.js and are found in each of the following distributions:
> 
> rx.all.js
> rx.all.compat.js
> rx.time.js (requires rx.js or rx.compat.js)

But my TypesScript definitions only complete to `.delay()` and `.delayWhen()`.

There are some of the issues I've found with the official documentation.

**Comment by kwonoj** [comment] 2017-04-07 14:25
closing as dupe of https://github.com/ReactiveX/rxjs/issues/2369.

**Closed by kwonoj** 2017-04-07 14:25 UTC
