### ISSUE TITLE
startWith Deprecation warning

### ISSUE THREAD

**Issue by internalsystemerror** [ReactiveX/rxjs#4772] opened 2019-05-11 17:01 UTC
I can't find any documentation on what is actually deprecated, but I believe this is related to: https://github.com/ReactiveX/rxjs/issues/4723.

## Bug Report

**Current Behavior**
startWith is deprecated: use {@link scheduled} and {@link concatAll} (e.g. `scheduled([[a, b, c], source], schedul
er).pipe(concatAll())`)

**Reproduction**
```js
startWith(null);
```

**Expected behavior**
No deprecation warning

**Environment**
- RxJS version: 6.5.2

**Comment by cartant** [comment] 2019-05-12 00:10
The problem is related to the issue you referenced only in that some operators and observable creators that have signatures that include a `Scheduler` parameter have those signatures deprecated.

In your case, `startWith(null)` is matching [this signature](https://github.com/ReactiveX/rxjs/blob/26e16d7e82379cd09fc87ed1315ebd36b82d6f33/src/internal/operators/startWith.ts#L8):

```ts
export function startWith<T>(scheduler: SchedulerLike): MonoTypeOperatorFunction<T>;
```

And it only matches that signature because you most likely have `"strictNullChecks": false` in your TypeScript configuration - either explicitly or implicitly.

Given that this is not a problem for in situations in which `strictNullChecks` are enabled, IMO, the deprecation should be left in place and a TSLint flag should be used to suppress the warning:

```ts
// tslint:disable-next-line:deprecation
startWith(null)
```

**Comment by internalsystemerror** [comment] 2019-05-13 10:31
Do you mean in tslint.json? I don't see that setting but I will try adding it and see if it makes a difference. The warning fires for undefined aswell as null too.

**Comment by cartant** [comment] 2019-05-13 11:57
The comment I mentioned is a [rule flag](https://palantir.github.io/tslint/usage/rule-flags/) and goes into the source - immediately above the line that effects the error.

Or you can configure the `deprecation` rule to be either `off` or a `warning` in the [`tslint.json` file](https://github.com/cartant/tslint-config/blob/8762de7b34565fb506c2e6a0cd78433e269ac857/tslint.json#L18):

```json
"deprecation": { "severity": "warning" },
```

Without `strictNullChecks` enabled, both `undefined` and `null` will match the `Scheduler` parameter in the deprecated signature. Enabling `strictNullChecks` is recommended, IMO.

**Comment by internalsystemerror** [comment] 2019-05-17 16:22
I wish I'd known about strictNullChecks when we started this application ... Unfortunately this is not an easy switch for us and thus I won't be able to confirm whether this resolves the problem for some time.

**Comment by cartant** [comment] 2019-05-24 02:34
@internalsystemerror Regarding enabling `strictNullChecks`, you might find this relevant/interesting/helpful: https://code.visualstudio.com/blogs/2019/05/23/strict-null

**Comment by internalsystemerror** [comment] 2019-05-24 11:25
@cartant thankyou ... its the part "(I will add that if you are starting a new TypeScript project, do your future self a favor and start with "strict": true as the default.)" that I wish I'd have known :D. Definately going to be using that going forward and retrospectively on this current application when possible.

**Comment by orjandesmet** [comment] 2019-05-28 08:27
The deprecation warning also disappears when typing the `null` in startWith.
By default it's typed `any`, so I guess the compiler doesn't know it's not meant to be a SchedulerLike.

```
startWith(<string>null); // In case your stream emits strings
```

**Comment by benlesh** [comment] 2019-05-28 22:22
@cartant, I haven't checked... is this something we can remedy by changing the order of typings for `startWith`?

**Comment by cartant** [comment] 2019-05-28 22:44
@benlesh I don't see how it could be rearranged without changing the behaviour of the types. ATM, a lone scheduler argument is seen as a scheduler. If the order is changed, it will be seen as a value - as far as the type system is concerned. Admittedly, this is a pretty unlikely use case, but the signature that's causing the problem is there because it's behaviour supported by the implementation.

If you want to fix the 90% case - that is, fixed for at least 90% of the people not using `strictNullChecks` - removing the signature that takes a scheduler as a single argument is probably the best that can be done.

**Comment by wulfsberg** [comment] 2019-06-11 13:41
Coming from Angular, I run into it when using a pattern like
```
this.myFormControl.valueChanges.pipe(
    startWith(this.myFormControl.value)
  )
```
since `FormControl`s are typed as `any`. I suspect that the false positive with `any` is more common than actually using the deprecated single-argument scheduler, so I'll cast a vote for removing the signature.

**Comment by Routhinator** [comment] 2019-06-20 15:18
For me, I hit this and read this thread, and found that typeing the reference made the issue go away without any further problems.

```
    this.activities = this.activityListForm.valueChanges.pipe(
      debounceTime(500),
      startWith(this.activityListForm.value as object),
      switchMap(formFilter => this.activityService.list(formFilter, this.pageSize)),
      share()
    );
```

**Comment by Ismaestro** [comment] 2019-07-16 13:22
```
startWith(null as string)
```

**Comment by MatissJanis** [comment] 2019-10-25 06:28
Here's another hacky fix:
```typescript
const nullValue = null;
startWith(nullValue);
```

**Comment by Domvel** [comment] 2019-11-22 13:43
No hacks (obfuscating) or cheats (tslint:disable comments) please. Also null is not a string. (no cast). What's the problem if I expect (and my type is set to) optionally null? e.g. An array which could contain null values. But the deprecated error on using `startWith(null)` will not disappear if I change my type to fit it. Also when the type is `any`.
Why exactly is it marked as deprecated and what's the problem? In simple words and examples.

**Comment by dcanning** [comment] 2020-02-18 04:00
I have `"strictNullChecks": true` in tsconfig.json and I'm still getting this error when using `startWith(null)`

**Comment by Wildhammer** [comment] 2020-04-20 18:20
startWith<any,any>(blah)

**Comment by cartant** [comment] 2021-03-13 23:03
Closing this because it's addressed in https://github.com/ReactiveX/rxjs/pull/6114.

**Closed by cartant** 2021-03-13 23:03 UTC
