### ISSUE TITLE
Compiler error with Typescript 2.4.1

### ISSUE THREAD

**Issue by mattbishop** [ReactiveX/rxjs#2704] opened 2017-06-28 03:26 UTC
I am using rxjs in a Typescript project. Today I tried updating to TS 2.4.1 and am now receiving this compiler error:
```Error:(22, 14) TS2415:Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.```

Also: 
```Error:(47, 48) TS2345:Argument of type 'this' is not assignable to parameter of type 'Observable<T>'.
  Type 'Subject<T>' is not assignable to type 'Observable<T>'.
    Types of property 'lift' are incompatible.
      Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
        Type 'Observable<T>' is not assignable to type 'Observable<R>'.
          Type 'T' is not assignable to type 'R'.```

**Comment by kwonoj** [comment] 2017-06-28 03:26
dupe of https://github.com/ReactiveX/rxjs/issues/2699 , https://github.com/ReactiveX/rxjs/issues/2539, https://github.com/ReactiveX/rxjs/issues/2700 . https://github.com/ReactiveX/rxjs/issues/2701 https://github.com/ReactiveX/rxjs/issues/2702 https://github.com/ReactiveX/rxjs/issues/2703

**Closed by kwonoj** 2017-06-28 03:26 UTC
