### ISSUE TITLE
auditTime does not emit last value

### ISSUE THREAD

**Issue by ronag** [ReactiveX/rxjs#3430] opened 2018-03-13 12:22 UTC
Similar to https://github.com/ReactiveX/rxjs/issues/3351. `auditTime` does not emit the last value emitted by a completed source.

Looking at the test spec it is not defined if this is the intended behavior or not. However, we've twice encountered this thinking it's very strange behaviour.

```js
> Observable.timer(1000).auditTime(500).subscribe(x => console.log('value', x), undefined, () => console.log('complete')) && null
null
> complete
```

**Comment by benlesh** [comment] 2018-03-15 18:10
`audit` was,  by design, made to audit the last value only at the time of audit, not at time of completion... so to make it do this would be a new feature, which I'm open to discussing, but it's not a bug.

**Comment by pbadenski** [comment] 2018-04-10 15:18
Possible duplicate of https://github.com/ReactiveX/rxjs/issues/1777

**Comment by llorenspujol** [comment] 2020-01-23 13:34
I think this feature is interesting for many things.
`auditTime` is pretty useful for back-pressuring streams, for example a server-data stream. In this use cases you, almost every time, want to get the last value when this stream completes.

**Possible solution**:
What about using the same configuration options that `throttleTime` has? `config: {leading: boolean, trailing:boolean}` with the defaults to `{leading: false, trailing: false}`. This way `auditTime` will still work the same way by default and we would have the ability to emit optionally the leading and trailing stream items.

**Comment by cartant** [comment] 2021-05-01 07:39
Closing this 'cause, IIRC, the behaviour was changed in v7. See this test:

https://github.com/ReactiveX/rxjs/blob/f3d2e802276545683f488a37a4f094ed4e0230d1/spec/operators/auditTime-spec.ts#L69-L83

And this change https://github.com/ReactiveX/rxjs/pull/5799

**Closed by cartant** 2021-05-01 07:39 UTC
Labels: type: discussion
