### ISSUE TITLE
import {Observable} from 'rxjs/Observable' doesn't work

### ISSUE THREAD

**Issue by whitecolor** [ReactiveX/rxjs#1713] opened 2016-05-17 12:44 UTC
**RxJS version:**
5.0.0-beta.7

**Code to reproduce:**
```js
import {Observable} from 'rxjs/Observable'
console.log('typeof Observalbe.of is', typeof Observable.of)
```
http://www.webpackbin.com/N1rc5TXzZ

**Expected behavior:**
`Observable.of` should be function

**Actual behavior:**
`Observable.of` is undefined

**Additional information:**

Also I would expect `Observable` be available as default export:
```js
import Observable from 'rxjs/Observable'
```

**And if it is not valid use use, examples in docs should be fixed.*

**Comment by kwonoj** [comment] 2016-05-18 04:29
Currently, importing bare `Observable` only will not import neither static creation method nor operators at all, so to make `Observable.of` work it is required to import `of` as well. Bit while ago there was sort of discussion to import essential static creation method by default but hasn't been landed due to it's causing circular dependency issues (https://github.com/ReactiveX/rxjs/pull/922#issuecomment-162967611) and expectation's user who imports bare Observable will picks up only necessary operators as needed instead of providing out of box behaviors, which `Rx` import already does.

**Comment by dwilt** [comment] 2016-06-21 09:31
**RxJS version:**
5.0.0-beta.6

I'm running into this issue as well. I haven't been able to find an example anywhere that is working.

**Comment by kwonoj** [comment] 2016-06-21 15:15
@dwilt would you able to share bit more about issue you're experiencing? importing operator via `add/` does not work?

**Comment by kwonoj** [comment] 2016-06-24 20:44
As this is current expected behavior, let me close issue. @dwilt , if your issue persists after importing each operator, please feel freely file a new issue with reproducible code.

**Closed by kwonoj** 2016-06-24 20:44 UTC
