### ISSUE TITLE
Class 'Subject<T>' incorrectly extends base class 'Observable<T>' with TypeScript 2.4

### ISSUE THREAD

**Issue by zoltantarcsay** [ReactiveX/rxjs#2705] opened 2017-06-28 07:20 UTC
**RxJS version:** 
5.4.1

**Code to reproduce:** 
Save this line this to a TypeScript file (test.ts):
`import {Subject} from 'rxjs/Subject';`
Then compile:
`tsc  test.ts`

**Expected behavior:**
No errors

**Actual behavior:**
Compilation error:

```text
node_modules/rxjs/Subject.d.ts(16,22): error TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.
```

**Additional information:**
TypeScript version: 2.4.1

TypeScript 2.4 introduced stricter checks for generics (see [this blog post](https://blogs.msdn.microsoft.com/typescript/2017/06/27/announcing-typescript-2-4/))

(Looks like this could be a typo in Observable#lift)

**Comment by kwonoj** [comment] 2017-06-28 07:23
dupe of #2699 , #2539, #2700 . #2701 #2702 #2703 https://github.com/ReactiveX/rxjs/issues/2704

**Closed by kwonoj** 2017-06-28 07:23 UTC

**Comment by grafox** [comment] 2017-08-07 17:04
update TS. That's it

**Comment by ws6** [comment] 2017-08-07 18:17
upgrade ts won't help. according to ts webpage, I added --noStrictGenericChecks to suppress the error message.

tsc --noStrictGenericChecks

**Comment by Argon2000** [comment] 2017-08-08 06:41
Got this error WHEN i updated to TS 2.4.2

**Comment by Argon2000** [comment] 2017-08-08 07:03
Fixed by updating RxJS to 5.4.2

**Comment by micaz** [comment] 2017-08-10 07:16
@Argon2000 
It Work for me, Thank You

**Comment by andrewmur** [comment] 2017-08-10 09:22
Didn't worked for me with typescript 2.4.2 & RxJS 5.4.2
Started to work after the downgrading the typescript to 5.4.0

**Comment by dearfog** [comment] 2017-08-11 13:21
@andrewmur  what you have downgraded TypeScript  or RxJS??

**Comment by andrewmur** [comment] 2017-08-11 14:32
TypeScript to 5.4.0

**Comment by maximilian02** [comment] 2017-08-11 19:54
I've deleted Rxjs node_module folder, and ran again npm install. That made the magic.

**Comment by theBull** [comment] 2017-08-12 23:03
@andrewmur I don't believe there is a Typescript version 5.4.0, latest version (as of right now) is 2.4.2 - perhaps you got it confused with the latest version of RxJS which is currently 5.4.3?

**Comment by andrewmur** [comment] 2017-08-14 09:54
@theBull srry for typo & confuse. Yeap I meant downgrade to typescript 2.4.0

**Comment by tramel-woodard** [comment] 2017-08-14 10:45
Anyone installing from a package.json file, try changing your typescript devDependency from:
`"typescript": "^2.0.3"` to **`"typescript": "2.4.0"`** specifically.

Then delete the `typescript` package from your `node_modules` folder and then retry **npm install**.

**Comment by kwonoj** [comment] 2017-08-14 11:55
I am seeing incorrect information's shared in this issue's comment - anyone still experiences compilation issue with **LATEST RxJS**, please confirm

1. if there are any other copy of RxJS v5 stays under *node_modules* which isn't latest, should be checked by physical lookup 
2. if above is not case and compilation fail occurred with *strict generic check*, confirm any user code inherits have correct type definition of base classes.

(check detail at https://github.com/ReactiveX/rxjs/issues/2726#issuecomment-313713212)

RxJS itself has fixed its own issue of library regarding this type definition issue and remaining failure mostly shoud be those cases listed above. If you're certain library has still failing, please don't hesitate to create new issue with repo have smallest code can reproduce issue.

I'm locking this issue itself to avoid further confusions.
