### ISSUE TITLE
ERROR in node_modules/rxjs/internal/Observable.d.ts(14,49): error TS2304: Cannot find name 'HttpEvent'. node_modules/rxjs/internal/Observable.d.ts(14,65): error TS1183: An implementation cannot be declared in ambient contexts.

### ISSUE THREAD

**Issue by nilamshirke** [ReactiveX/rxjs#4457] opened 2019-01-08 06:59 UTC
Hi,

I'm using  "rxjs": "~6.3.3" and "typescript": "~3.1.6" in my project. 

I'm getting below error on build. Compilation gets failed.

I saw Observable.d.ts source code where there is error on line no.14 for HttpEvent there is no reference for this class.

```export declare class Observable<T> implements Subscribable<T> {
  map(arg0: (response: any) => any): Observable<HttpEvent<any>> {
    throw new Error("Method not implemented.");
  }```


ERROR in node_modules/rxjs/internal/Observable.d.ts(14,49): error TS2304: Cannot find name 'HttpEvent'.
node_modules/rxjs/internal/Observable.d.ts(14,65): error TS1183: An implementation cannot be declared in ambient contexts.

**Comment by kwonoj** [comment] 2019-01-08 07:00
Please provide details to reproduce issues, using issue templates.

**Comment by kwonoj** [comment] 2019-04-23 17:17
I'm closing this issue for now due to lacks of detail to determine furtuer.

**Closed by kwonoj** 2019-04-23 17:17 UTC
Labels: status: needs info
