### ISSUE TITLE
Provide named exports

### ISSUE THREAD

**Issue by thiagogcm** [ReactiveX/rxjs#3745] opened 2018-05-25 04:25 UTC
**RxJS version:**
6.2.0
**Code to reproduce:**

    import { range } from 'rxjs';
    import { map, filter } from 'rxjs/operators';

    range(1, 10).pipe(
        filter(n => n % 2 !== 0),
        map(n => n * n),
    ).subscribe(v => console.log(v));
**Expected behavior:**
No error
**Actual behavior:**
SyntaxError: The requested module 'rxjs' does not provide an export named 'range'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:89:21)
**Additional information:**
Running on NodeJS 10.2.1 with the flag --experimental-modules the following code works as expected:
    
    import range from 'rxjs';
    import map from 'rxjs/operators';
    import filter from 'rxjs/operators';

    range.range(1, 10).pipe(
        filter.filter(n => n % 2 !== 0),
        map.map(n => n * n),
    ).subscribe(v => console.log(v));

**Comment by natmegs** [comment] 2018-05-25 17:12
Hey @thiagogcm I'm having trouble reproducing the error you're seeing. The reproduction code seems to work for me in Node, and I have a [stackblitz reproduction](https://stackblitz.com/edit/typescript-knzprf) which also seems to be working as expected. Do you have any more information about your environment? Are you running this in Node or in the browser?

**Comment by thiagogcm** [comment] 2018-05-25 17:39
Hi @natmegs Thanks for looking into it.

Im running pure javascript code on NodeJS (linux) 10.2.1 and one detail I forgot to mention: The second snippet only works when I change the file type to `mjs`

    node --experimental-modules index.mjs

**Comment by kwonoj** [comment] 2018-05-25 17:47
@thiagogcm how did you run first example then? node 10's esm would only work with mjs in experimental, as you already indicated second example ran by manually renaming it.

**Comment by thiagogcm** [comment] 2018-05-25 18:44
I am unable to run the first example regardless the file extension.

**Comment by kwonoj** [comment] 2018-05-25 18:49
I guess issue in here is trying to use js module with experimental which supposed to break for some cases. I.e https://github.com/nodejs/node/issues/16474 shows similar cases you described, and as we officially don't offer esm modules yet there isn't any actual way to run rx via native esm.

I'm closing this issue as expected to not work at the moment, we will definitely support native module one time with our packages and please check with those stable node features.

**Closed by kwonoj** 2018-05-25 18:49 UTC

**Comment by thiagogcm** [comment] 2018-05-26 00:13
Fair enough. As the second code snippet works fine I opened this issue to make sure I was not missing anything. Thanks
