### ISSUE TITLE
6.5.x endWith() Regression

### ISSUE THREAD

**Issue by dairyisscary** [ReactiveX/rxjs#4751] opened 2019-05-01 02:12 UTC
## Bug Report

**Current Behavior**
`endWith` throws `TypeError`.
> TypeError: You provided '2' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

**Reproduction**
https://jsfiddle.net/1Lz8m4bx/1/

```js
 of(1).pipe(endWith(2)).subscribe(console.log);
```

**Expected behavior**
Should not throw :)

**Environment**
- Runtime: Chrome latest
- RxJS version: 6.5.1 (seems to be in 6.5.0 as well)

**Possible Solution**
After investigating a bit, I believe [this line](https://github.com/ReactiveX/rxjs/blob/master/src/internal/operators/endWith.ts#L65) in the implementation of `endWith` isn't quite right:
```ts
// current implemention:
export function endWith<T>(...array: Array<T | SchedulerLike>): MonoTypeOperatorFunction<T> {
  return (source: Observable<T>) => concat(source, ...(array as any[])) as Observable<T>;
}

// Maybe something like this (I wouldn't be surprised if that allows the removal of the type assertion):
export function endWith<T>(...array: Array<T | SchedulerLike>): MonoTypeOperatorFunction<T> {
  return (source: Observable<T>) => concat(source, of(...array)) as Observable<T>;
}
```

**Comment by cartant** [comment] 2019-05-01 02:13
Closing, as this appears to be a dupe of the issue resolved in https://github.com/ReactiveX/rxjs/pull/4735

**Closed by cartant** 2019-05-01 02:13 UTC
