### ISSUE TITLE
Rename `of`

### ISSUE THREAD

**Issue by helmbold** [ReactiveX/rxjs#4897] opened 2019-07-02 07:42 UTC
In the past the [`of`](https://rxjs.dev/api/index/function/of) method was nice to read and self-explanatory:

```javascript
Observable.of(1, 2, 3)
```

But without `Observable` in front of `of` there is hardly any meaning in `of`. The code was reduced to meaninglessness.

```javascript
of(1, 2, 3)  // What "1, 2, 3"? Doesn't make sense!
```

I suggest to either reintroduce `Observable.of(...)` or to rename it to something like `observableOf`. However I would prefer the former because it is a bit more concise and you can always start with `Observable.` and can see what methods are available in your IDE.

**Comment by cartant** [comment] 2019-07-02 08:05
This discussion has already been had: https://github.com/ReactiveX/rxjs/issues/3747

**Comment by helmbold** [comment] 2019-07-02 09:01
@cartant I'm aware of this issue, but it had another goal (rename `of` to `just`). It wasn't not about the missing context `Observable.` in front of `of` provided. And if you read the comments, you'll see that I'm not the only one finding `of` without context meaningless.

Imagine more frameworks would follow this route and you would have your code full of `of`'s, and `from`s and the like without any context. That would be almost impossible to read.

**Comment by BioPhoton** [comment] 2019-08-12 01:18
Am I missing something or would we end up in a similar situation with your 'just' renaming?
A project full of justs without context.

Please let me know your thoughts.

**Comment by helmbold** [comment] 2019-08-13 10:20
`just` without context (namely `Observable`) wouldn't be any better than `of`. Since there are seemingly technical reasons (I guess tree-shaking) for not using `Observerble.of` anymore, I suggest to go with:

```
observerbleOf(1, 2, 3)
```

**Comment by cartant** [comment] 2019-08-13 11:17
Closing as a dupe of https://github.com/ReactiveX/rxjs/issues/3747

**Closed by cartant** 2019-08-13 11:17 UTC
