### ISSUE TITLE
Add a static delay

### ISSUE THREAD

**Issue by Dorus** [ReactiveX/rxjs#2089] opened 2016-10-28 00:14 UTC
Often i find myself writing `Rx.Observable.empty().delay(1000)` It would be more elegant to have a static delay Observable that is empty complete after the delay. Like `Rx.Observable.delay(1000)`.

**Comment by kwonoj** [comment] 2016-10-28 00:32
I usually use Observable.timer() (.map() or .skip() if needed) to kick off delayed emission. Static operator is obviously seems shorthanded, but seems there's way to achieve intended behavior without requiring lot of operators. Would you mind able to share bit details of usecase for suggested creation method, for example it can gives fairly reduced code for certain cases or other benefits I couldn't think of?

**Comment by trxcllnt** [comment] 2016-10-28 05:57
`Observable.timer(1000)` will wait 1000ms, emit `0`, then complete.

**Comment by jayphelps** [comment] 2016-10-28 07:47
Semantically, I think `Observable.empty().delay(1000)` is far more clear what it will do than what one might guess `Observable.delay(1000)` would do. I'd prefer to keep the status quo.

**Comment by staltz** [comment] 2016-10-28 13:55
I'm generally against adding any new operators or statics.

**Comment by blesh** [comment] 2016-10-28 16:59
I totally understand the desire here. But I think the others have answered this request thoroughly. In particular, @jayphelps is correct I think. `Observable.empty().delay(1000)` is just explicit enough to make it easy to understand what's going to happen.

We always appreciate the suggestions, and I hope you continue to think of ways we can improve RxJS! Thanks again, @Dorus! I'm going to close this, but feel free to continue to comment if you feel your case wasn't interpreted well enough.

**Closed by blesh** 2016-10-28 16:59 UTC

**Comment by Dorus** [comment] 2016-10-28 17:20
I've been thinking, and where i missed this operator most was when i see code that want to delay subscriptions. Like `Rx.Observable.empty().delay(1000).concat(other)`.

Perhaps a better (non-static) operator to do this would `delaySubscription`. An operator available in RxJs 4, and marked as "Not yet implemented" in the migration doc.

Anyway i'm find with closing this, I can follow the reasoning here and will certainly continue to bring up suggestions if i think they're valuable enough @blesh :)
