### ISSUE TITLE
Timer operator does not work correctly on certain dates

### ISSUE THREAD

**Issue by bretbas** [ReactiveX/rxjs#5694] opened 2020-09-04 18:19 UTC
## Bug Report

**Current Behavior**
The timer operator is emit value immediately when we pass the current date(now) with adding from 75 to 99 days

**Reproduction**
https://stackblitz.com/edit/angular-ivy-uuf9za?file=src/app/app.component.ts

**Comment by kwonoj** [comment] 2020-09-04 18:24
I believe this is dupe of https://github.com/ReactiveX/rxjs/issues/3015.

**Comment by bretbas** [comment] 2020-09-05 05:13
@kwonoj , But if this problem is due to overflow, then why does it work with dates adding days more than 99?

**Comment by kwonoj** [comment] 2020-09-05 05:21
>  then why does it work with dates adding days more than 99?

it does not. If you only subscribe to date(100) for example,

```
const {timer} = require('rxjs');
const {mapTo} = require('rxjs/operators');

const addDays = (date, days) => {
  const d = new Date(date);
  d.setDate(d.getDate() + days);
  return d;
}

const now = new Date(Date.now());

const days = [
  timer(addDays(now, 74))
    .pipe(mapTo(74)),
  timer(addDays(now, 75))
    .pipe(mapTo(75)),
  timer(addDays(now, 99))
    .pipe(mapTo(99)),
  timer(addDays(now, 100))
    .pipe(mapTo(100))
]

days[3].subscribe((x) => console.log(x));
```

it emits warning

```
(node:13908) TimeoutOverflowWarning: 8643599998 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(Use `node --trace-warnings ...` to show where the warning was created)
100
```

and duration falls back to default but not sync, so it emits asynchronously. If it correctly works, opening up page should not write any output since date due is set to more than one month.

**Comment by kwonoj** [comment] 2020-09-05 05:21
closing as dupe.

**Closed by kwonoj** 2020-09-05 05:21 UTC
