### ISSUE TITLE
The import of deo file is not working 

### ISSUE THREAD

**Issue by evghenitirulnic** [ReactiveX/rxjs#5900] opened 2020-11-20 18:31 UTC
## Bug Report

**Current Behavior**
error: TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Operator } from './src/internal/Operator.ts';
         ~~~~~~~~
    at https://raw.githubusercontent.com/DenoBRComunitty/rxjs/master/mod.ts:15:10

**Reproduction**
- REPL or Repo link:

import { Observable } from 'https://raw.githubusercontent.com/DenoBRComunitty/rxjs/master/mod.ts';
on deno --version
deno 1.5.3 (ab7b8ba, release, x86_64-apple-darwin)
v8 8.7.220.3
typescript 4.0.5
(you can use https://stackblitz.com/ to create one to attach here)

```js
var your => (code) => here;
```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

**Environment**
- Runtime: [e.g. Node v${x}, Chrome v${x}]
- RxJS version:
- (If bug is related) Loader, build configuration: [e.g webpack, angular-cli version, config]

**Possible Solution**
<!--- Only if you have suggestions on a fix for the bug -->

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by kwonoj** [comment] 2020-11-20 18:35
Closing as dupe of https://github.com/ReactiveX/rxjs/issues/5486

Also `DenoBRcommunity` is not maintained by rxjs.

**Closed by kwonoj** 2020-11-20 18:35 UTC
