### ISSUE TITLE
Subject.onNext not a function?

### ISSUE THREAD

**Issue by thunderkid** [ReactiveX/RxJS#1057] opened 2015-12-14 20:47 UTC
I'm trying to get Rx Subjects to work following the RxJs docs. I'm using:

        import * as Rx from 'rxjs';
        var subject = new Rx.Subject();

        var subscription = subject.subscribe(
            function (x) {
                console.log('Next: ' + x);
            },
            function (err) {
                console.log('Error: ' + err);
            },
            function () {
                console.log('Completed');
            });
    
        subject.onNext(42);

But typescript tells me onNext is not a function, and if I force it with subject:any, the browser also tells me `subject.onNext is not a function`. Has the syntax changed?

**Comment by blesh** [comment] 2015-12-14 20:50
Due to changes to accommodate the ES7 Observable spec, the API has changed for observables:

- `onNext` -> `next`
- `onError` -> `error`
- `onCompleted` -> `complete`

I apologize for any confusion. We're working on a migration strategy (probably documentation) to land during the early stages of beta.

**Comment by blesh** [comment] 2015-12-14 22:57
@thunderkid I'm going to close this one for now, as it's not a bug, and I _hope_ that my previous comment addresses your concerns.

**Closed** 2015-12-14 22:57 UTC

**Comment by thunderkid** [comment] 2015-12-14 23:13
Yes, that fixed it. Thanks. (btw I also noticed bufferWithTime doesn't seem to be there. I'm assuming it's been replaced with bufferTime.)

**Comment by blesh** [comment] 2015-12-15 00:28
@thunderkid ... made this today... just for you: https://github.com/ReactiveX/RxJS/blob/master/MIGRATION.md

;)

It's a first go, so I expect it will be improved over the next month or so.

**Comment by thunderkid** [comment] 2015-12-15 00:59
Brilliant, thanks. That'll remove a bit of guesswork. What's the eta of the 5.0 stable release?

**Comment by nikkwong** [comment] 2016-02-18 06:47
Don't you guys think this should be apparent in the docs? 

https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/subjects/subject.md

**Comment by dholth** [comment] 2016-09-24 22:28
It would be handy if this was updated too: https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/subjects/subject.md

**Comment by dholth** [comment] 2016-09-24 22:39
I didn't realize https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/subjects/subject.md was a different thing than this one, the former has better Google-Fu.

**Comment by KunmyonChoi** [comment] 2016-11-23 01:25
Do you guys have a plan to give a hint on this document? 
https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/observer.md

**Comment by kwonoj** [comment] 2016-11-23 01:27
@KunmyonChoi it already does. https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md#observer-interface-changes-also-subjects . Please note given repo is for RxJS v4, does not contain v5 related changes.

**Comment by ORESoftware** [comment] 2016-12-30 07:30
oh shit I thought it was completed instead of complete, d'oh!

**Comment by ORESoftware** [comment] 2016-12-30 07:31
honestly, I think it would just be better to alias all of them with the old function names, dunno though

**Comment by facelesspanda** [comment] 2016-12-30 09:57
@ORESoftware that would really confuse newcomers. Starting working with a library that's a rewrite of an old one means not dealing with the old one at all. It's a complete rewrite, meaning it's not the same thing, meaning don't get their APIs mingled.
You should never take your knowledge for granted when you change major versions of a dependency.

**Comment by ORESoftware** [comment] 2016-12-30 10:21
@facelesspanda I am not a huge fan of aliasing, for many reasons, but in this case these methods will never change purpose, so onNext and next should do the same thing, it would be hugely convenient to just make onNext an alias of next, etc.
