### ISSUE TITLE
HttpClient with "pipe" sends multiple GET requests even if the first one did not fail

### ISSUE THREAD

**Issue by usarskyy** [ReactiveX/rxjs#4857] opened 2019-06-12 14:21 UTC
## Bug Report

This is a copy of https://github.com/ngrx/platform/issues/1940
One of the committers says this might be an `rxjs` issue 

**Current Behavior**

My Angular 8 app is hosted on http://localhost:4200/
My API is hosted on http://localhost:6002/

I am trying to send a HTTP GET request from Angular app to API. Before GET request is issued, browser sends preflight OPTIONS request to get CORS policy.

The problem is that when I add "retry" to my "pipe", I start getting multiple API requests. By some reason RxJs treats preflight OPTIONS request as failed GET request and makes a retry.

![2019_06_12_10_38_26_Oebb EvuZd_C_Users_l028705_Documents_SOURCE_evuzd_Oebb EvuZd_ _Oebb Evuzd](https://user-images.githubusercontent.com/1206777/59358548-11038980-8d2d-11e9-8fe8-c1ed54397984.png)

![2019_06_12_10_37_26_DevTools_localhost_4200_anmeldung_returnUrl_2Fzugliste](https://user-images.githubusercontent.com/1206777/59358561-16f96a80-8d2d-11e9-91de-178e516e5689.png)

**Reproduction**

Described above

**Expected behavior**

It looks like `retry` cannot correctly detect whether a request was successful or it has failed. This issue is reproducible  only if a client and API are hosted on different domains.

I expect that only one single GET request is sent.

**Environment**

Win7 SP1
Chromium 68.0.3440.106
NgRx 8.0.0-rc.1
RxJs 6.5.2
Angular 8.0.0

**Comment by kwonoj** [comment] 2019-06-12 14:34
Looks dupe of https://github.com/angular/angular/issues/20879 when 204 with no body, httpclient errors out so retry triggers.

**Comment by usarskyy** [comment] 2019-06-12 14:56
Thanks! I couldn't find that issue yesterday.
You may close this ticket, I will copy all the info into Angular bug tracker.

**Closed** 2019-06-12 14:58 UTC
