### ISSUE TITLE
Improve type inference of `pluck` operator

### ISSUE THREAD

**Issue by aboyton** [ReactiveX/rxjs#2881] opened 2017-09-28 22:19 UTC
**RxJS version:**
5.4.3

**Code to reproduce:**

```ts
const obs = Observable.of([{ a: { b: 1 } }]);
const a = obs.pluck('a');
```

**Expected behavior:**
`a` be of type `Observable<{b: 1}>`.

**Actual behavior:**
`a` is of type `Observable<{}>`

**Additional information:**
While I realise that I can provide the type of the return value to `pluck`, doing so doesn't give me any type safety. Instead, this could be inferred, at least for an arbitrary level of nesting. Anyone who goes beyond this level of nesting wouldn't be able to use type inference, very similarly to the current state of things.

```ts
type Pluck<T, K extends keyof T> = T[K];

export function pluck<
  T,
  P1 extends keyof T
>(
  this: Observable<T>,
  property1: P1,
): Observable<Pluck<T, P1>>;

export function pluck<
  T,
  P1 extends keyof T,
  P2 extends keyof T[P1]
>(
  this: Observable<T>,
  property1: P1,
  property2: P2,
): Observable<Pluck<Pluck<T, P1>, P2>>;

export function pluck<
  T,
  P1 extends keyof T,
  P2 extends keyof T[P1],
  P3 extends keyof T[P1][P2]
>(
  this: Observable<T>,
  property1: P1,
  property2: P2,
  property3: P3,
): Observable<Pluck<Pluck<Pluck<T, P1>, P2>, P3>>;

export function pluck<
  T,
  P1 extends keyof T,
  P2 extends keyof T[P1],
  P3 extends keyof T[P1][P2],
  P4 extends keyof T[P1][P2][P3]
>(
  this: Observable<T>,
  property1: P1,
  property2: P2,
  property3: P3,
  property4: P4,
): Observable<Pluck<Pluck<Pluck<Pluck<T, P1>, P2>, P3>, P4>>;
export function pluck<T>(
  this: Observable<T>,
  ...properties: string[]
): Observable<any> {
  return higherOrder(...properties)(this);
}
```

**Comment by kwonoj** [comment] 2017-09-28 22:22
Surprisingly, our 5 version is based on TS compiler doesn't support `keyof`. it's dupe of https://github.com/ReactiveX/rxjs/issues/2295, while we will revisit this probably in 6 with bumped up TSC version (due to some changes around runtime inherited `error` etcs we consider bump up as breaking) but we can't do this in 5.

**Closed by kwonoj** 2017-09-28 22:22 UTC

**Comment by aboyton** [comment] 2017-09-29 03:20
Sorry, I'm a bit confused by the tickets. #2295 and #2179 are both closed (thus I didn't find them when searching). Is there an open ticket that's tagged with `RxJS 6.0` so we make sure that this isn't forgotten about?

I noticed #2759 which has fixes to the type of an operator (`mergeAll()`) that's planned for the 6.0 release is still open.

**Comment by kwonoj** [comment] 2017-09-29 03:22
> Is there an open ticket that's tagged with RxJS 6.0 so we make sure that this isn't forgotten about

I'm planning to reopen one of original issue after we stabilize 6 branch and create separate label. For now it's closed as not actionable. There's mixed issues between some are opened and some are not and it's simply we haven't gone through all issues.

**Comment by aboyton** [comment] 2018-03-22 02:53
Is this ready to be reopened?
