### ISSUE TITLE
Fresh install unrunnable

### ISSUE THREAD

**Issue by pselle** [ReactiveX/RxJS#366] opened 2015-09-21 20:15 UTC
I tried updating my upstream and was unable to run any build commands. When checking out a fresh repo, I got the same errors:

```
$ npm install
npm ERR! install Couldn't read dependencies
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3

npm ERR! Invalid name: "@reactivex/rxjs"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pselle200/Projects/freshRx/npm-debug.log
```

Looks like `@reactivex/rxjs` is an invalid name. How are you all resolving this as you're working on it? I also updated my node, but that didn't solve the issue.

**Comment by blesh** [comment] 2015-09-22 05:24
It looks like you're running Node v 4? What version of NPM are you using?

`@reactivex/rxjs` should be a valid name, unless NPM changed something... 

cc/ @jeffbcross @igorminar ... have you seen anything like this?

**Comment by blesh** [comment] 2015-09-22 07:48
FWIW: I've only been using Node v 0.12.0 for development... I'll try 4 when I get a chance, but it might be a while.

**Comment by staltz** [comment] 2015-09-22 07:54
Come on, Ben, it's just a matter of doing `nvm install v4.1.0`.

I tried reproducing this by deleting node_modules and running `npm install` with node v4.1.0 and npm v2.14.3 and everything worked as it should (my git HEAD is on upstream master right now). I don't think it's a problem of npm not recognizing scoped packages.

**Comment by pselle** [comment] 2015-09-22 13:43
I had the issue _before_ I upgraded node as well. Removing the `@` and `/` from the name allow `npm install` to run.. until it puked without  babel.
```
sh: babel: command not found

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build_cjs"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! reactivexrxjs@0.0.0-prealpha.3 build_cjs: `rm -rf dist/cjs && babel dist/es6 --out-dir dist/cjs --modules common --sourceMaps --loose all`
npm ERR! spawn ENOENT
```
plus a lot more error not worth posting bc the babel is the important part. Is babel now a global install dependency? I started https://github.com/ReactiveX/RxJS/wiki/Getting-Started and can update it as things are found

**Comment by pselle** [comment] 2015-09-22 13:46
The `prepublish` script runs on `npm install` – is this what you all are looking for?

**Comment by staltz** [comment] 2015-09-22 13:50
> Is babel now a global install dependency?

Shouldn't be, I don't have babel globally installed and everything seems ok to me.

**Comment by pselle** [comment] 2015-09-22 14:02
Reading up on the npm docs ... name is okay, but I've seen some issues filed with scoped packages ex https://github.com/npm/npm/issues/9109

**Comment by pselle** [comment] 2015-09-22 14:06
Sounds like the name thing may be an issue with my machine/npm, if no one can replicate. Changing the name in package.json so I can install works, after I remove the prepublish line.

As for prepublish, I suspect it's trying to run babel before that package is actually installed (race condition?). Running install without prepublish available and _then_ running prepublish once packages are installed works just fine.

**Comment by blesh** [comment] 2015-09-22 14:08
> Come on, Ben, it's just a matter of doing nvm install v4.1.0.

Haha.. I don't have nvm because I had some issues reinstalling it last time I nuked Node after I broke it playing around.

**Comment by jeffbcross** [comment] 2015-09-22 15:56
Scoped packages were introduced in npm 2, so the original issue is an npm version issue. http://blog.npmjs.org/post/98131109725/npm200

I'm surprised `prepublish` is running when installing the package, but this may also be related to the npm version. Prepublish should only run when running `npm install` or `npm publish` from _within_ the RxJS repo. The prepublish script _does_ require global babel and tsc (probably shouldn't), but those scripts shouldn't be running for consumers of the package. I just installed the package locally using npm 2.10.1, and prepublish didn't run.

We should specify the required npm version in the package.json to require 2.0+.

**Comment by pselle** [comment] 2015-09-22 16:10
@jeffbcross Ok cool, I'm not consuming, I'm in the RxJS repo. So global babel and tsc are required.

**Comment by blesh** [comment] 2015-09-23 22:34
@pselle  is this still an issue for you? I've been unable to reproduce..

**Comment by pselle** [comment] 2015-09-24 03:12
Yeah I think we can close, seems like the name thing is on my other machine... got this one working without the name issue. 

As for global dependencies, I updated https://github.com/ReactiveX/RxJS/wiki/Getting-Started that the project now requires global babel and browserify in order to contribute, because those need to exist to run `npm install` up to you core folk if that's how you like it (I lean no).

**Comment by pselle** [comment] 2015-09-24 03:14
(fwiw, it does not require global tsc _shrug_ or that was installed already in the source that I updated from the upstream)

**Comment by staltz** [comment] 2015-10-07 07:44
@blesh We can close this.

**Closed** 2015-10-07 16:30 UTC
