### ISSUE TITLE
The decision tree widget uses older operator/function names

### ISSUE THREAD

**Issue by mtaran-google** [ReactiveX/rxjs#3900] opened 2018-07-06 23:30 UTC
### Documentation Related To Component:

https://github.com/ReactiveX/rxjs/blob/master/doc/decision-tree-widget/tree.yml

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

See above. This uses some older syntax (e.g. `Observable.throw` instead of `throwError`). I also couldn't discover any version of it on google (aside from the github source) by searching for some of the included strings, so it seems to not be very discoverable. This is a bit of a shame, since it could be a great resource. What would be the process for either improving its visibility or removing it since it's yet another thing to keep up to date with API changes?

**Comment by cartant** [comment] 2018-07-06 23:31
This seems to be a dupe of https://github.com/ReactiveX/rxjs/issues/3866 and see also https://github.com/ReactiveX/rxjs-docs/issues/251.

**Comment by mtaran-google** [comment] 2018-07-06 23:34
Thanks! I guess I didn't look hard enough to find that name for it.

Then perhaps we can leave the question of discoverability to those bugs. Instead I'd like to focus on how best to update it -- would there be any concerns if I sent a PR renaming the legacy creation operator usages to their modern equivalents?

**Comment by cartant** [comment] 2018-07-06 23:37
Sure. Focusing on updating it sounds good to me, as I'd like to see it reinstated. I'd welcome a PR.

**Comment by ladyleet** [comment] 2018-07-11 14:38
@cartant should we close this?

**Comment by cartant** [comment] 2018-07-11 22:19
@ladyleet This is the issue for https://github.com/ReactiveX/rxjs/pull/3912. That PR has not been merged - which, incidentally, contains [some discussion](https://github.com/ReactiveX/rxjs/pull/3912#issuecomment-403732688) about the `/doc` directory and what its purpose is supposed to be.

I guess this could be closed. I don't know whether or not there's a particular policy regarding issues remaining open until their associated PR is closed. I tend to leave them open until the PR is merged; typically by including, for example, `Closes #3900` in a commit message.

**Closed** 2019-01-26 23:05 UTC
