### ISSUE TITLE
rxjs.dev very often inaccessible

### ISSUE THREAD

**Issue by ebeloded** [ReactiveX/rxjs#7414] opened 2023-12-20 21:56 UTC
### Describe the bug

I've been referencing documentation from [rxjs.dev](https://rxjs.dev/) for years now and I find that the website is quite often inaccessible. The issue appears to be related to service workers and can be reproduced in Chrome/Arc/Safari.

![2023-12-20 at 13 53 25](https://github.com/ReactiveX/rxjs/assets/5859177/72838f7b-5ffd-4ec5-989a-a76a655be83c)
![2023-12-20 at 13 48 40](https://github.com/ReactiveX/rxjs/assets/5859177/ed4700f1-9292-4395-8cf5-25b4c193e97f)

Here's a video showing the issue. The website can only be loaded with CMD+SHIFT+R

https://github.com/ReactiveX/rxjs/assets/5859177/be3521af-b460-4637-bde0-a72776a980d0

**Comment by jakovljevic-mladen** [comment] 2023-12-21 21:46
Hi @ebeloded, I don't really know how to reproduce this issue on my machine. Any chance to help me with providing some more details?

BTW, even though it seems like that https://rxjs.dev/index.html works correctly, you should probably be accessing RxJS docs site by using https://rxjs.dev/ domain.

**Comment by ebeloded** [comment] 2023-12-21 21:56
Hey. Thanks for getting back to me. Not that I'm not accessing "index.html" - it's what the service worker is requesting.

As for reproduction (in Chrome):
1. Open Guest profile (which works more like a normal profile when it comes to SW)
2. Open rxjs.dev
3. Reload the page

Here's a video of me doing just that:

https://github.com/ReactiveX/rxjs/assets/5859177/ad7b3453-955f-419c-b395-aaaaea48e6b3

**Comment by jakovljevic-mladen** [comment] 2023-12-22 09:15
I'm sorry, but this is what I get:

https://github.com/ReactiveX/rxjs/assets/28087049/4cb8a708-f135-4334-a567-2662369902b9

Is it possible that some Chrome plug-in is causing this behaviour? Or some OS settings that you have since it affects other browsers?

**Comment by benlesh** [comment] 2024-02-20 16:31
I suspect this is something to do with the service worker going bad. You'll need to open up dev tools to uninstall the service worker.

I don't use Safari, so I've used ChatGPT to generate instructions on how to uninstall the service worker:

## Uninstall Service Worker for `rxjs.dev` in Safari on macOS

### Step 1: Access Preferences
- Open **Safari** Preferences either through the Safari menu (`Safari > Preferences`) or using the shortcut `Command + ,`.

### Step 2: Enable Developer Menu
- Navigate to the **Advanced** tab in the Preferences window.
- Check the option at the bottom to **Show Develop menu in menu bar**.

### Step 3: Manage Service Workers
- With the **Develop menu** now visible, navigate to `rxjs.dev` in Safari.
- Click on the **Develop** menu in the menu bar, hover over the website you're inspecting to find options related to service workers.
    - If available, look for options like **Empty Caches** or specific service worker management options under this menu.
    - For direct service worker management, select **Service Workers** from the Develop menu if the option is available, to see and potentially unregister service workers.

### Step 4: Clear Website Data
- If direct management of service workers isn't visible, you can clear website data for `rxjs.dev` as a workaround:
    - Go to Safari Preferences > **Privacy**, then select **Manage Website Data**.
    - Search for `rxjs.dev`, select it, and click **Remove** to clear data, which includes cached data and potentially unregistering service workers.

### Step 5: Restart Safari
- Quit and restart Safari to ensure all changes take effect.

**Comment by benlesh** [comment] 2024-02-20 16:32
On Chrome, it's as simple as going to the Application tab in dev tools and clearing local data. Just make sure you have "uninstall service worker" checked.

**Comment by jakovljevic-mladen** [comment] 2024-02-21 08:14
I completely forgot about the service worker 🙈 The image also shows that an error happens in `ngsw-worker.js` file suggesting that worker may be causing the issue...

@ebeloded, can you please try Ben's suggestion and let us know?

**Comment by ofek** [comment] 2024-04-22 02:05
The website is also down for me

**Comment by jakovljevic-mladen** [comment] 2024-04-22 07:26
@ofek, have you tried Ben's suggestion?

**Comment by jakovljevic-mladen** [comment] 2024-04-23 08:11
@ebeloded, thanks for letting us know. I will close this ticket in that case.

@ofek, if your issue persists, please open a new ticket.

**Closed by jakovljevic-mladen** 2024-04-23 08:11 UTC

**Comment by 0xju4nm4** [comment] 2025-05-21 16:23
Hey guys, my entire team is not able to access the website from many different machines across the world... Would you be able to fix this?
