### ISSUE TITLE
converting examples from Rx4 to Rx5

### ISSUE THREAD

**Issue by stefanre1** [ReactiveX/rxjs#2763] opened 2017-07-21 21:52 UTC
Is there any plans to convert the examples which are mentioned [here](https://github.com/Reactive-Extensions/RxJS/tree/master/examples) to Working Rx version 5? It would be of great helpful. :)

**Comment by paulpdaniels** [comment] 2017-07-21 22:03
Are there any ones in particular you are having trouble with? The structure should still be mostly correct, its just that the operator names have changed in some cases.

**Comment by stefanre1** [comment] 2017-07-21 22:16
Thanks for the reply. I did convert some of them. But I found it hard for the 'crop' example.  in which the following code is used
`SingleAssignmentDisposable = Rx.SingleAssignmentDisposable,
    BinaryDisposable = Rx.BinaryDisposable,
    Disposable = Rx.Disposable,
    inherits = Rx.internals.inherits;`

So most part of the example depends on it. Any help or suggestion would be great.

**Comment by paulpdaniels** [comment] 2017-07-21 22:30
So for that one, you should just not use the included `RequestAnimationFrameScheduler` and use instead the `animationFrameScheduler` that ships with this library.

**Comment by stefanre1** [comment] 2017-07-22 09:48
Thanks. That solved the issue :) :+1:

**Comment by benlesh** [comment] 2017-07-25 21:08
closing as it appears the issue is solved?

**Closed** 2017-07-25 21:08 UTC
