### ISSUE TITLE
ajax() type signature error (TS) when string provided

### ISSUE THREAD

**Issue by staltz** [ReactiveX/RxJS#1382] opened 2016-02-23 20:39 UTC
John Lindquist reported that

```ts
import {Observable} from 'rxjs/Rx.DOM';
Observable.ajax('http://swapi.co/api/people/1/')
    .subscribe();
```

gives TS compile error
```
ERROR in ./src/main.ts
(2,1): error TS2346: Supplied parameters do not match any signature of call target.
```

---

Solution suggestion:
I think the type signature should be changed like this:

```diff
 export interface AjaxCreationMethod {
-  (): <T>(urlOrRequest: string | AjaxRequest) => Observable<T>;
+  <T>(urlOrRequest: string | AjaxRequest): Observable<T>;
   get: <T>(url: string, resultSelector?: (response: AjaxResponse) => T, headers?: Object) => Observable<T>;
   post: <T>(url: string, body?: any, headers?: Object) => Observable<T>;
   put: <T>(url: string, body?: any, headers?: Object) => Observable<T>;
   delete: <T>(url: string, headers?: Object) => Observable<T>;
   getJSON: <T, R>(url: string, resultSelector?: (data: T) => R, headers?: Object) => Observable<R>;
 }
```

**Comment by kwonoj** [comment] 2016-02-23 21:22
I also noticed this while migrating test cases, simply deferred definition changes after test cases are checked in. This should be trivial changes, I'll take this up around today.

**Comment by staltz** [comment] 2016-02-23 21:24
We really need to have TS type tests in place. Otherwise TS users might see errors like this. I suppose your #1364 will fix that?

**Comment by kwonoj** [comment] 2016-02-23 21:29
#1364 is initial setup to prepare type definition test, so only partially covers for it (because consume definition via test cases can resolve most frequent usage). My plan is leveraging typescript-based test cases to add bunch of type definition test only check if it's written as intended - https://github.com/ReactiveX/RxJS/pull/1189 is one of examples what'll be added in further. In general, I also #1364 to be landed to start further tasks regarding type definition enhancement. Just need it to be reviewed & approved since it introduce broad number of changes along impacting development cycle.

**Closed** 2016-02-24 07:43 UTC
Labels: status: PRs welcome, type: type output
