### ISSUE TITLE
Union type issue in behavior subject constructor (ts strict mode)

### ISSUE THREAD

**Issue by X4V1** [ReactiveX/rxjs#6406] opened 2021-05-17 12:08 UTC
Context:
- Typescript 4.2.4
- RxJS 7.0.1
- Node 14.14
- tsconfig:
```json
{
  "compilerOptions": {
    "target": "esnext",
    "strict": true,
    "moduleResolution": "node"
  }
}
```

What I'm trying to achieve:
- Create a BehaviorSubject with a Union type as the generic type and pass one of combined type in the construction

Code to reproduce:
```ts
interface A {
    kind: 'a',
    something: boolean;
}
interface B {
    kind: 'b'
}
type Union = A | B;

const a: A = {kind: 'a', something: true};
const myUnionSubject$: BehaviorSubject<Union> = new BehaviorSubject(a); // Throw the following error:
// Error:(43, 7) TS2322: Type 'BehaviorSubject<A>' is not assignable to type 'BehaviorSubject<MyUnion>'.
//   Types of property 'observers' are incompatible.
//     Type 'Observer<A>[]' is not assignable to type 'Observer<MyUnion>[]'.
//       Type 'Observer<A>' is not assignable to type 'Observer<MyUnion>'.
//         Type 'MyUnion' is not assignable to type 'A'.
//           Type 'B' is not assignable to type 'A'.
myUnionSubject$.next(a); // Working fine
```

Result:
Error:(44, 7) TS2322: Type 'BehaviorSubject\<A\>' is not assignable to type 'BehaviorSubject\<Union\>'.

Expected behavior:
- To not trow a typescript Error

Findings:
- setting "compilerOptions.strictBindCallApply" to false seems to remove the error.

Any idea how to get rid of that error without turning off the strict mode or strictBindCallApply ?

**Comment by voliva** [comment] 2021-05-17 12:53
The problem is that BehaviourSubject has a function next() on its generic.... From a type point of view, it's more or less equivalent to:

```ts
interface BehaviorSubject<T> {
  next: (value: T) => void
}

const myUnionSubject: BehaviorSubject<'a' | 'b'> = new BehaviorSubject<'a'>();
```

The `next()` type of `new BehaviorSubject('a')` is a function that can only receive 'a': `(value: 'a') => void`, but it's being assigned to a variable whose `next()` type is a function that can receive both 'a' and 'b': `(value: 'a' | 'b') => void`.

So Typescript doesn't allow this assignment, because then you could call `next('b')` which is not accepted by `BehaviorSubject<'a'>`

I don't have any easy suggestion for working around this.... other than casting it:

```ts
const myUnionSubject: BehaviorSubject<'a' | 'b'> = new BehaviorSubject<'a'>() as BehaviorSubject<'a' | 'b'>;
```

**Comment by benlesh** [comment] 2021-05-17 14:22
TypeScript is just a pain sometimes. You'll need to do:

```ts
const myUnionSubject$ = new BehaviorSubject<Union>(a)
```

or

```ts
const myUnionSubject$ = new BehaviorSubject(a as Union)
```

**Closed by benlesh** 2021-05-17 14:22 UTC

**Comment by X4V1** [comment] 2021-05-17 14:28
Thank you for your suggestions. Indeed it was an error in my usage of typescript. Specifying the type next to the constructor solve the issue. 👍

**Comment by adaico** [comment] 2022-11-25 18:14
This work around doesn't work with overriding. My base abstract class says that BehaviourSubject have to return 'a' or 'b'. But I want to narrow output in inheritor down to 'a'.
