### ISSUE TITLE
Filter operator predicate overwrites the observable's type

### ISSUE THREAD

**Issue by elsmr** [ReactiveX/rxjs#4559] opened 2019-02-12 15:22 UTC
## Bug Report

**Current Behavior**
The type of the first argument of the predicate passed to the filter operator will overwrite the observable's type. The linked stackblitz shows the issue very clearly, hover the variable name to see its type.

**Reproduction**

```js
// type of filteredNumber$ is Observable<any>
const filteredNumber$ = of(5).pipe(filter((num: any) => true));
```

Reproduction with possible solution: https://stackblitz.com/edit/rxjs-filter-typing?file=index.ts&view=editor

**Expected behavior**

The filter operator does not affect the type of the observable it is used on.

```js
// type of filteredNumber$ is Observable<number>
const filteredNumber$ = of(5).pipe(filter((num: any) => true));
```

**Environment**
- Runtime: any
- RxJS version: 6.4.0

**Possible Solution**

Use a second type parameter for the predicate argument, so it doesn't affect the return type:

```ts
type newFilterType = <T, R extends T = T>(predicate: (value: R, index: number) => boolean, thisArg?: any) => MonoTypeOperatorFunction<T>
```

**Context**

Came across this issue when trying to use `filter(Boolean)`. Noticed the type of the observable was lost after the filter operator. I'm willing to submit a PR with a solution if that's useful 😄

**Comment by eliasmeire** [comment] 2019-02-12 16:20
`distinctUntilChanged` has the same issue, added it to the stackblitz. There are probably some more operators I'm not thinking of 😛

**Comment by cartant** [comment] 2019-02-13 00:33
By explicitly declaring the type as `any` you have widened it. So this is the expected behaviour.

**Comment by eliasmeire** [comment] 2019-02-13 16:01
I understand, in my example it's pretty explicit but in practice it can be less intuitive:

```
// type of filteredNumber$ is Observable<any>
const filteredNumber$ = of(5).pipe(filter(Boolean));
```

or

```
import { filterPredicate } from 'dependency-without-typedef';

// type of filteredNumber$ is Observable<any>
const filteredNumber$ = of(5).pipe(filter(filterPredicate));
```

Personally I didn't expect filter to have any effect on the type of the Observable.

**Comment by jgbpercy** [comment] 2019-02-13 16:25
`filter` (and `distinctUntilChanged`) emissions will always be a subset of their inputs, so they "real" types must also be a subset of the input types. Given that, it seems like ideally the typings for these should never be able to widen types, whatever predicates are passed? And if that can be achieved in a way that doesn't break anything else then that's the way it should be?

If there's something wrong with that logic, or if there's some strong consistency-based reason for inferring filter's output type from the arg type then ok, but otherwise it seems like a simple question of whether @eliasmeire 's possible solution breaks any other type behavior (e.g. can it be added in a way that doesn't stop you from being able to *narrow* the type, which you definitely should be able to)?

**Comment by cartant** [comment] 2019-02-13 19:51
The problem is that the inference of the type parameter for filter will first come from the callback passed. If the type can be inferred from that callback, then that's what will be used. This all happens before `pipe` is even considered.

Essentially it is:

```ts
const op = filter((num: any) => true); // OperatorFunction<any, any>
const filteredNumber$ = of(5).pipe(op); // Observable<any>
```

It's the first step that is the problem. You have introduced an `OperatorFunction` that is specifically typed as `any`. And that is compatible with the `number` from the source observable, so TypeScript is happy.

Because it's an `OperatorFunction<any, any>`, the type of the `Observable` that's returned by `pipe` will be `any`. `pipe` has no idea about the semantics of `filter`, it just uses the second type parameter from `OperatorFunction` as the type for the `Observable` that is returned or input into the next operator.

AFAICT, there is nothing that can be done about this and the behavior is expected.

**Comment by cartant** [comment] 2019-02-13 20:06
@eliasmeire I'm not sure that your proposed solution solves the problem. It doesn't appear to solve it for me. `filter` already has a signature similar to yours:

```ts
export declare function filter<T, S extends T>(predicate: (value: T, index: number) => value is S, thisArg?: any): OperatorFunction<T, S>;

```

And adding `S extends T = T` does not appear to solve the problem, AFAICT.

**Comment by jgbpercy** [comment] 2019-02-14 09:01
Yeah, sorry, good explanation @cartant - here's a stackblitz showing the problem https://stackblitz.com/edit/rxjs-pxbhzr

**Comment by benlesh** [comment] 2020-09-04 02:39
The `filter(Boolean)` bit is fixed now, and the rest is working as expected.

**Closed by benlesh** 2020-09-04 02:39 UTC
