### ISSUE TITLE
Examples in Introduction do not work

### ISSUE THREAD

**Issue by wzup** [ReactiveX/rxjs#4658] opened 2019-03-21 11:51 UTC
## Bug Report

I'm testing `rxjs` in a browser.

**Current Behavior**

Your examples
https://rxjs-dev.firebaseapp.com/guide/overview#first-examples
https://stackblitz.com/run?devtoolsheight=50
do not work.

1. Click a button.
2. Nothing happens. No `Clicked!` gets printed in console.

**Reproduction**

```js
const { fromEvent } = rxjs;

const button = document.getElementById('btn');
fromEvent(button, 'click').subscribe(() => console.log('Clicked!')); // "Clicked!" is never printed.
```

```html
<body class="body">

<div class="block">
    <button id="btn">CLICK</button>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/rxjs/6.4.0/rxjs.umd.js"></script>
<script src="js/scripts.js"></script>
</body>
```

**Expected behavior**

1. I click a button.
2. `Clicked!` is printed in console. 

As in this clear and obvious code
```
const button = document.querySelector('button');
button.addEventListener('click', () => console.log('Clicked!'));
```

Your examples here https://rxjs-dev.firebaseapp.com/guide/overview#first-examples compare common code with `rxJS` version. You claim we should expect the same result.
But common code works well.
**rxJS** doesn't work.

**Environment**

- Runtime: 
Node: v11.6.0
Chrome: 72.0.3626.121 (Official Build) (64-bit)

- RxJS version:
6.4.0
From here https://cdnjs.cloudflare.com/ajax/libs/rxjs/6.4.0/rxjs.umd.js

**Possible Solution**

**Additional context/Screenshots**

![Screen Shot 2019-03-21 at 13 48 49](https://user-images.githubusercontent.com/3880497/54750440-5c037a00-4be0-11e9-9883-74a931579d70.png)

**Comment by dzhavat** [comment] 2019-03-21 17:06
Related to #4605

**Comment by cartant** [comment] 2019-03-24 02:06
Closing this as a dupe of #4605 - as mentioned in the above comment.

The `index.html` in the StackBlitz project is empty. If the relevant content is added, the example works.

**Closed by cartant** 2019-03-24 02:06 UTC
