### ISSUE TITLE
TestScheduler.expectObservable sees no results from Promises

### ISSUE THREAD

**Issue by adimit** [ReactiveX/rxjs#3462] opened 2018-03-22 11:49 UTC
**RxJS version:** 5.5.6

**Code to reproduce:**
I have an observable source, and a function f which turns source elements into Promises. I want to apply that function to the source and write a test for that, using chai:

```
import { TestScheduler } from 'rxjs/testing/TestScheduler';
import 'rxjs/add/operator/mergeAll';
// expect is from chai

const marbles = new TestScheduler((a, b) => expect(a).to.deep.equal(b));
const source = marbles.createColdObservable('a-a-a-a');
const map = source.mergeMap(async a => a);
marbles.expectObservable(map).toBe('a-a-a-a');
marbles.flush();
```
 **Expected behavior:**

The expected result is for the test to pass, as per documentation of `mergeMap`.

**Actual behavior:**

The actual result is:

```
AssertionError: expected [] to deeply equal [ Array(4) ]
```
No promise returned, or all promises returned and gave an empty result?

**Additional information:**

If we substitute the `mergeMap` line with

```
const map = source.mergeMap(a => Observable.of(a));
```
or
```
const map = source.mergeMap(a => Observable.of((b => b)(a)));
```
everything is fine.

But as soon as the promise needs to return:
```
const map = source.mergeMap(a => Observable.fromPromise((async b => b)(a)));
```
The resulting stream is again empty.

I'm using karma/chai to execute this in a ChromiumHeadless instance.
* karma: 1.7.1
* chai: 3.5.3
* Chromium 63.0.3239.108 Fedora Project

I had previously asked the same question [on Stackoverflow](https://stackoverflow.com/questions/49402414).

**Comment by kwonoj** [comment] 2018-03-22 15:52
Closing as dupe of https://github.com/ReactiveX/rxjs/issues/701 . Unfortunately there is no way to synchronously handle promise in testscheduler.

**Closed by kwonoj** 2018-03-22 15:52 UTC

**Comment by adimit** [comment] 2018-03-23 11:41
OK, thanks. Sorry for creating noise.
