### ISSUE TITLE
error TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'

### ISSUE THREAD

**Issue by msolvaag** [ReactiveX/rxjs#2717] opened 2017-07-02 05:46 UTC
**RxJS version: 5.4.1**
**Typescript version: 2.4.1**
```
ERROR in 
..\node_modules\rxjs\Subject.d.ts
(16,22): error TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.
```

Typescript is getting stricter.  The lift method for Subject is not compatible with Observable.lift

**Comment by kwonoj** [comment] 2017-07-02 06:25
dupe of #2699 , #2539, #2700 . #2701 #2702 #2703 https://github.com/ReactiveX/rxjs/issues/2704 https://github.com/ReactiveX/rxjs/issues/2705 https://github.com/ReactiveX/rxjs/issues/2706 https://github.com/ReactiveX/rxjs/issues/2707 https://github.com/ReactiveX/rxjs/issues/2716

**Closed by kwonoj** 2017-07-02 06:25 UTC
