### ISSUE TITLE
Subject compiles wrong or do I make a mistake?

### ISSUE THREAD

**Issue by nachtgold** [ReactiveX/rxjs#2815] opened 2017-08-28 00:09 UTC
I created a simple service. It should send "visible" broadcasts to all subscribers. After compiling it, I got the error message: 

> ERROR TypeError: Subject_1.Subject is not a constructor
    at new VisibleService (visible.service.js:24)

But when I add `.default` to the line `this.source = new Subject_1.Subject();` the problems disappears.

**RxJS version:**
rxjs@5.4.3 loaded by systemjs@0.20.18 and compiled by typescript 2.4.2

**Code to reproduce:**
```
import { Injectable } from '@angular/core';
import { Subject }    from 'rxjs/Subject';

@Injectable()
export class VisibleService {
  private source = new Subject<boolean>();

  onDataChange(data: boolean) {
    this.source.next(data);
  }

  observer = this.source.asObservable();
}
```

**Expected behavior:**
```System.register(["@angular/core", "rxjs/Subject"], function (exports_1, context_1) {
    "use strict";
    var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
        var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
        if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
        else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
        return c > 3 && r && Object.defineProperty(target, key, r), r;
    };
    var __moduleName = context_1 && context_1.id;
    var core_1, Subject_1, VisibleService;
    return {
        setters: [
            function (core_1_1) {
                core_1 = core_1_1;
            },
            function (Subject_1_1) {
                Subject_1 = Subject_1_1;
            }
        ],
        execute: function () {
            VisibleService = (function () {
                //import { BehaviorSubject } from "rxjs/BehaviorSubject"
                function VisibleService() {
                    this.source = new Subject_1.default.Subject();
                    this.observer = this.source.asObservable();
                }
                //private source = new BehaviorSubject<boolean>(false);
                VisibleService.prototype.onDataChange = function (data) {
                    this.source.next(data);
                };
                VisibleService = __decorate([
                    core_1.Injectable()
                ], VisibleService);
                return VisibleService;
            }());
            exports_1("VisibleService", VisibleService);
        }
    };
});
```
**Actual behavior:**
```System.register(["@angular/core", "rxjs/Subject"], function (exports_1, context_1) {
    "use strict";
    var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
        var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
        if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
        else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
        return c > 3 && r && Object.defineProperty(target, key, r), r;
    };
    var __moduleName = context_1 && context_1.id;
    var core_1, Subject_1, VisibleService;
    return {
        setters: [
            function (core_1_1) {
                core_1 = core_1_1;
            },
            function (Subject_1_1) {
                Subject_1 = Subject_1_1;
            }
        ],
        execute: function () {
            VisibleService = (function () {
                //import { BehaviorSubject } from "rxjs/BehaviorSubject"
                function VisibleService() {
                    this.source = new Subject_1.Subject();
                    this.observer = this.source.asObservable();
                }
                //private source = new BehaviorSubject<boolean>(false);
                VisibleService.prototype.onDataChange = function (data) {
                    this.source.next(data);
                };
                VisibleService = __decorate([
                    core_1.Injectable()
                ], VisibleService);
                return VisibleService;
            }());
            exports_1("VisibleService", VisibleService);
        }
    };
});
```
**Additional information:**
My tsconfig.json:
```
{
    "compilerOptions": {
        "baseUrl": "../js/3rd",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "lib": ["es2017", "dom"],
        "module": "System",
        "outDir": "../js",
        "target": "ES5"
    }
}
```

**Comment by kwonoj** [comment] 2017-08-28 01:11
This seems like some configuration related with systemjs / tsconfig, but can't tell where exactly it is.

1. What happens if you build with plain TSC without systemjs? If it fails, tsconfig is culprit to look into.
2. Is there any module interop config in systemjs / or any bundler? 

RxJS does export everything as named, so not having `default` is legit and expected behavior.

**Comment by nachtgold** [comment] 2017-08-28 05:44
I added my tsconfig.json, I forgot that.

My knowledge is very basic, but when I build without systemjs, how must I load the result, to test if it works?

Thats the result:
```
"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
Object.defineProperty(exports, "__esModule", { value: true });
var core_1 = require("@angular/core");
var Subject_1 = require("rxjs/Subject");
//import { BehaviorSubject } from "rxjs/BehaviorSubject"
var VisibleService = (function () {
    function VisibleService() {
        this.source = new Subject_1.Subject();
        this.observer = this.source.asObservable();
    }
    //private source = new BehaviorSubject<boolean>(false);
    VisibleService.prototype.onDataChange = function (data) {
        this.source.next(data);
    };
    VisibleService = __decorate([
        core_1.Injectable()
    ], VisibleService);
    return VisibleService;
}());
exports.VisibleService = VisibleService;
```

**Comment by kwonoj** [comment] 2017-08-28 05:50
You can rule out by not invloving any angular/systemjs but creating plain ts with rx only to verify it first, by creating subject only as snippet does. If it still doesn't work, then rx does something wrong. If not, probably some config or behavior of systemjs need to be looked into.

**Comment by nachtgold** [comment] 2017-08-28 18:14
Oh it was so easy 👍 I removed the systemjs module setting and it works. I thought, using that module for compiling is related to the usage of the systemjs loading system. But it seams unrelated and that is ok for me. 

Sooo .. do anybody know a difference between the default module and the systemjs module as compiling platform?

**Comment by kwonoj** [comment] 2017-08-28 18:16
I do not have knowledge around systemjs (I nearly do not use it), so can't answer those question. Maybe systemjs can answer this? (https://github.com/systemjs/systemjs)

**Comment by kwonoj** [comment] 2017-08-28 18:17
Actually there seems question already: https://github.com/systemjs/systemjs/issues/1675

@nachtgold , would you confirm this is issue you're experiencing?

**Comment by nachtgold** [comment] 2017-08-28 18:23
It could be, I will post my issue here with the details. They should decide if it helps them. And after that , the issue could be closed.

**Comment by kwonoj** [comment] 2018-02-21 17:17
So far this looks like systemjs side issue and there's not much actionable on our end, closing and track via upstream issue.

**Closed by kwonoj** 2018-02-21 17:17 UTC
Labels: status: more information needed
