### ISSUE TITLE
.cache() requeries API

### ISSUE THREAD

**Issue by SuperManitu** [ReactiveX/RxJS#1417] opened 2016-03-02 10:52 UTC
This is my reopening of the issue #1405
My main issue is gone with saving `getStuff().cache()` to a local is gone, but I still get aborted requeries of the API, that should not be thrown because the code is in the `getStuff()` method.
Here is a screenshot of Chrome's network tab: http://qs.lc/sb5k0 (plants is the URL)
I have no idea, why they are aborted and I have no idea why they are queried at all.
Thanks.

**Comment by SuperManitu** [comment] 2016-03-02 11:26
Ok, in addition to that, when I have a second service, taking the ModelStream and querying additional information for the contents of the observable and cache an observable of a data structure like this:
```typescript
export class dataStructure
{
constructor(public model : Model, public information : Observable<secondModel>){}
}
```
I get cascading updates resulting in an endless loop. The root of the loop is the `Observable.of` method. The function that im calling gets called once, but the Observable.of creates an infinite amount of Observables. Shouldn't `cache()` make an observable hot? Event putting `share()` all over the method didn't help.

**Comment by SuperManitu** [comment] 2016-03-02 11:33
Ok, I found the issue with the cascading updates:
````typescript
private getParameters() : Observable<ParameterObservableArray>
    {
        return this.plantService.PlantStream
        .map<ParameterObservableArray>(plant => {
            return new ParameterObservableArray(
                plant,
                this.getParametersOfPlant(plant).cache() //the .cache() was missing
            );
        });
    }
```
I had to cache the subqueries too (so now I have a global variable that stores `getParameters().cache()` and the function itself caches)

But I still have the requering (that is not that bad, but I don't think it should be there)

**Comment by SuperManitu** [comment] 2016-03-02 16:05
OK, I made a third service, adding additional information to the additional information of the second service (thus creating a meta-meta-stream) and I get the aborted requeries there as well. So only the one in the middle doesnt do so

**Comment by trxcllnt** [comment] 2016-03-02 20:00
@SuperManitu do you have an isolated repro example (in plunkr, jsbin, esbin, etc.) we can see and run? That'll help us determine whether there's a bug in Rx or if you need to something differently.

**Comment by SuperManitu** [comment] 2016-03-02 22:49
I tried here: https://plnkr.co/edit/0nw7hDqtSRjycBmNcV6X?p=preview
but I can't get it working, but something like this is my setup

**Comment by SuperManitu** [comment] 2016-03-03 13:51
https://plnkr.co/edit/0nw7hDqtSRjycBmNcV6X?p=preview
it's working now. If you look in the console, you see two times an url, in a part of the code that should be cached

**Comment by SuperManitu** [comment] 2016-03-03 14:24
I found my issue, I had a get property that was taking the stored Observable and transforms it like this:
`this.stream.flatMap<Model>(array => Observable.from(array, x => x))`
Is this intended? Seems odd to me, caching this value, too. And I have a location in my code where I'm not able to cache it. Does this mean I have to accept the additional calls?

**Comment by blesh** [comment] 2016-03-04 21:01
@SuperManitu We're going to need code that can reproduce this issue that is actually using the latest version of RxJS 5. This appears to be some version of RxJS 5 that is associated to Angular 2 beta.0... I'm not sure how stale that is, but it's probably several versions behind.

**Comment by blesh** [comment] 2016-03-04 21:04
Since I can't reproduce this in current versions of RxJS 5. I'm not sure what course of action to take here. I'm going to close this for now, @SuperManitu. If you can come up with minimal code that reproduces this in RxJS 5.0.0-beta.2, then please do reopen, as we'd definitely want to fix it ASAP.

**Closed by blesh** 2016-03-04 21:04 UTC
Labels: type: question
