### ISSUE TITLE
timer doesn't work properly for large intervals

### ISSUE THREAD

**Issue by bengry** [ReactiveX/rxjs#5155] opened 2019-11-20 14:58 UTC
## Bug Report

**Current Behavior**
If you start a `timer` with a time longer then 24 days, it emits all values **immediattely**. Using any time for up to 24 days (or even some fraction between 24 and 25 days, it breaks somewhere in the middle).

**Reproduction**
- REPL or Repo link: https://codesandbox.io/s/serene-franklin-cuj64 (I used a `take(100)` here just to limit the amount of output).

```js
import { timer } from "rxjs";
import { tap, take } from "rxjs/operators";
import ms from "ms";

timer(0, ms("25 days")) // if you change this to 24, it works fine (supposedly, I didn't wait 24 days to see the next emittion, but it doesn't do it immediattely)
  .pipe(
    tap(e => {
      console.log("tap", e, new Date());
    }),
  )
  .subscribe();

```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

**Environment**
- Runtime: Chrome v78
- RxJS version: `6.5.3`, also tried with `6.3.3`, `6.0.0` and even `7.0.0-alpha.0`

**Comment by kwonoj** [comment] 2019-11-20 15:00
Dupe of https://github.com/ReactiveX/rxjs/issues/3015

**Closed by kwonoj** 2019-11-20 15:00 UTC
