### ISSUE TITLE
fromEvent + debounceTime : manually triggered keyUp event - set event.target as null if element is not in DOM

### ISSUE THREAD

**Issue by kievsash** [ReactiveX/rxjs#4788] opened 2019-05-16 10:37 UTC
## Bug Report

**Current Behavior**
if element not in dom - debounceTime removes event.target

**Reproduction**
https://codepen.io/kievsash/pen/byqZpP?editors=1010

```
const mockInput = document.createElement('input');
//document.body.appendChild(mockInput);
mockInput.value = 'test';
mockInput.dispatchEvent(new KeyboardEvent('keyup', {'key': 'y'}));

const search$ = fromEvent(mockInput, 'keyup').pipe(
  
  tap((e) => console.log('event target1:', e.target)), // here i see input
  debounceTime(1000),
  tap((e) => console.log('event target2:', e.target)), // here i see null
  
  map((event) => event.target && event.target.value)
);

search$.subscribe();

mockInput.dispatchEvent(new KeyboardEvent('keyup', {'key': 'y'}));

```

**Expected behavior**
I expect event.target to work event without element in DOM.

**Environment**
- Runtime: [e.g. Node v${x}, Chrome v${x}]
- RxJS version: 6.5

**Possible Solution**
document.body.appendChild(mockInput); // anyway I use it for unit tests

**Additional**
Found something similar: https://github.com/ReactiveX/rxjs/issues/1577

**Comment by cartant** [comment] 2019-05-16 10:52
Closing this because it's not an RxJS issue. The problem can be reproduced with `setTimeout`, so RxJS is behaving as expected:

```
const e = new KeyboardEvent('keyup', { key: 'y' });
mockInput.dispatchEvent(e);
setTimeout(() => console.log(e.target), 1000);
```

**Closed by cartant** 2019-05-16 10:52 UTC
