### ISSUE TITLE
asObservable() eats exceptions 

### ISSUE THREAD

**Issue by mike-bresnahan** [ReactiveX/rxjs#2596] opened 2017-05-09 14:40 UTC
Use of asObservable() causes exceptions thrown by observers to be eaten.

rxjs@5.3.0

```javascript
let subject = new BehaviorSubject<boolean>(null);
subject.asObservable().subscribe(b => {
    throw new Error('yuk');
});
```

Expected: An exception to be thrown
Observed: No exception is thrown

If I remove the call to asObservable(), an exception is thrown.

**Comment by kwonoj** [comment] 2017-05-09 14:42
let me close this as dupe of https://github.com/ReactiveX/rxjs/issues/2565.

**Closed by kwonoj** 2017-05-09 14:42 UTC
