### ISSUE TITLE
Problem with rxjs in last days?

### ISSUE THREAD

**Issue by montella1507** [ReactiveX/rxjs#2977] opened 2017-10-19 06:31 UTC
Hello i would like to ask you for help, because it could be a bug in rxjs?

My switchMap operator does not behave as it behaved 2 days ago (only node_modules reinstalled yesterday):
https://github.com/angular/angular/issues/19799  (Minimal reproduction repo included.)

Thank you for your answer.

**Comment by TomasRup** [comment] 2017-10-19 11:48
Same here. We were using "^5.4.1", changed to "5.4.1", now it works.

**Comment by montella1507** [comment] 2017-10-19 12:05
I will try to pin version to 5.4.3 (we have ^5.4.3 in package.json ) so we may have installed version 5.5.0 and there may be bugs...

**Comment by montella1507** [comment] 2017-10-19 12:16
I can  propably  confirm it works with version < 5.5.0 .. with 5.5.0 even the primitive  Observable.of(value).switchMap(data=>..) doesn't work..  

But let me try it again to be 100% sure.

**Comment by montella1507** [comment] 2017-10-19 12:22
OK. i can confirm. 

< 5.5.0 works
5.5.0 errors in rxjs namespace

**Comment by stas-kh** [comment] 2017-10-19 12:34
Guys, we have the same problem in our app that uses Angular 4 and RxJS.
We fixed the version 4.3.0 in package.json as a temporary fix.

**Comment by evestraw** [comment] 2017-10-19 13:05
i think 5.5.0 should be released as 6.0.0 because of breaking changes

**Comment by montella1507** [comment] 2017-10-19 13:20
Yeah.. that is the one of the biggest problems of NPM+javascript... 

1) Source-code distributed submodules of submodules of...
2) No idea about semver of developers 
3) Range versions 
:-(

It tooks 50% of developing time on fixing bugs in dependencies..

**Comment by jayphelps** [comment] 2017-10-20 23:44
Hey all, I'm not a maintainer but, could someone include the text of the error they are actually getting? https://github.com/angular/angular/issues/19799 doesn't include the error either.

**Comment by benlesh** [comment] 2017-10-21 05:28
These are unforeseen breaking changes, and they will be fixed. This issue appears to be a duplicate of #2984.

I can see a lot of people are frustrated, my sincere apologies for any problems this may have created. If you hit this issue for now just pin to 5.4.

I'm closing this as a duplicate, but rest assured we will fix it.

**Closed by benlesh** 2017-10-21 05:28 UTC

**Comment by montella1507** [comment] 2017-10-21 16:59
Your work is very appreciated. Thank you.
