### ISSUE TITLE
RxJS 6 require('rxjs-compat/...

### ISSUE THREAD

**Issue by kripton69** [ReactiveX/rxjs#5050] opened 2019-10-02 11:11 UTC
Hi.
We have a Angular Application v7, and we do all steps to migrate rxjs from 5 to 6. After this we uninstall the rxjs-compat.
While compiling the angular app we get a error because it does not find the rxjs/operators.
We went to check the folder of the rxjs and all operator need rxjs-compat.

What's need to do for fix this issue?

**Comment by cartant** [comment] 2019-10-02 11:53
`rxjs/operators` is also a file and importing said file does not involve `rxjs-compat`. It sounds to me like you have a deep import - i.e. it sounds like you are importing something within the directory.

**Comment by cartant** [comment] 2019-10-02 11:59
It sounds like you have imports like `import { map } from "rxjs/operators/map". You cannot do this without having to use `rxjs-compat`. You can only have imports like "import { map } from "rxjs/operators" - which resolve to the `index.d.ts` file in that directory. And that file has no references to `rxjs-compat`. It imports operators from the `internal` directory.

**Comment by kripton69** [comment] 2019-10-02 12:54
We imports all operators like you say: "import { map } from "rxjs/operators".
But the problem is on node_modules/rxjs/operators, like you see on image.

"export * from 'rxjs-compat/operators/auditTime';"

<img width="1615" alt="Screenshot 2019-10-02 at 13 48 49" src="https://user-images.githubusercontent.com/6799536/66045439-ac5a7d80-e51b-11e9-87d1-53d584ddb2ba.png">

**Comment by BioPhoton** [comment] 2019-10-02 16:24
Hi @kambing86 

I checked your image. Maybe you have a wrong import in your application.
The import goes like this:
´import {auditTime} from 'rxjs/operators';`  => which references `rxjs/operators/index` => which exports auditTime from `../internal/operators/auditTime`.

Here the links to the source code of v6:
- https://github.com/ReactiveX/rxjs/tree/6.x/src/operators (the index file)
- https://github.com/ReactiveX/rxjs/blob/06fb73555375095bb55cdd02287bea5f9c0ddafc/src/operators/index.ts#L4 the export (the export)
- https://github.com/ReactiveX/rxjs/blob/06fb73555375095bb55cdd02287bea5f9c0ddafc/src/internal/operators/auditTime.ts (the operator)

Maybe reinstall everything and restart your IDE? :D

You can find good articles about migration online. Or you can try to search for answers on StackBlitz. 

As the issue is more related to support you could close this issue. 

Feel free to still comment on this issue and ask further question.
:)

**Closed** 2019-10-02 16:39 UTC
