### ISSUE TITLE
Concurrent exhaustMap?

### ISSUE THREAD

**Issue by ronag** [ReactiveX/rxjs#1337] opened 2016-02-12 17:33 UTC
Something on the roadmap or is it possible to emulate it using existing operators?

**Comment by blesh** [comment] 2016-02-12 18:30
Congratulations on the issue number `1337`!

... can you give us an example of the expected behavior?  is it really just `.map().exhaust()`?

**Comment by trxcllnt** [comment] 2016-02-12 21:44
@blesh I think @ronag is noticing the lack of a `concurrent` value in `exhaust` and `exhaustMap` (like we have in `mergeMap`). We should probably add it to `switch` and `switchMap` while we're at it.

**Comment by blesh** [comment] 2016-02-18 03:49
>  We should probably add it to switch and switchMap while we're at it.

Agree, it sounds useful and reasonable.

**Comment by blesh** [comment] 2017-02-21 04:54
Closing due to lack of interest.

**Closed by blesh** 2017-02-21 04:54 UTC
