### ISSUE TITLE
Property 'connnect' does not exist on type 'Observable<any>'.ts(2339)

### ISSUE THREAD

**Issue by s97712** [ReactiveX/rxjs#4714] opened 2019-04-14 08:33 UTC
### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [x] error(s) in example
- [ ] needs example

### Description Of The Issue

Typescript compiler error in this [example](https://rxjs.dev/guide/subject#multicasted-observables) ([stackblitz](https://stackblitz.com/edit/pjsuid?file=index.ts))

**Comment by Ghostfly** [comment] 2019-04-14 11:58
Seems like there is a missing cast to ConnectableObservable

(multicasted as ConnectableObservable<number>).connect(); should fix it (with import)

**Comment by s97712** [comment] 2019-04-15 01:57
Maybe can add type define for `pipe`
```
pipe<A>(op1: UnaryFunction<Observable<T>, ConnectableObservable<A>>): ConnectableObservable<A>;

pipe<A, B>(op1: OperatorFunction<T, A>, op2: UnaryFunction<Observable<T>, ConnectableObservable<B>>): ConnectableObservable<B>;

pipe<A, B, C>(op1: OperatorFunction<T, A>, op2: OperatorFunction<T, B>, op3: UnaryFunction<Observable<T>, ConnectableObservable<C>>): ConnectableObservable<C>;

...
```

**Comment by ArsalanWahid** [comment] 2019-04-29 07:09
I have the same problem and the even the stackblitz sample gives the same error and using the ConnectableObservable does not work

**Comment by Ghostfly** [comment] 2019-04-29 07:56
Last line should be : (multicasted as ConnectableObservable<number[]>).connect(); as ConnectableObservable requires a generic interface, works without error after.

**Comment by ArsalanWahid** [comment] 2019-04-29 12:41
Thanks @Ghostfly  working now

**Comment by thorn0** [comment] 2019-05-15 12:12
duplicate of #2972

**Closed** 2019-05-15 12:24 UTC
