### ISSUE TITLE
Cannot opt-in import operator's Type Definitions from 'rxjs/add/operator/***'

### ISSUE THREAD

**Issue by saneyuki** [ReactiveX/RxJS#1193] opened 2016-01-14 18:24 UTC
At `5.0.0-beta.1`, We can success to compile the following code.
However, this code should not success the compilation because the code does not import `rxjs/add/operator/map`.

```typescript
import {Observable} from 'rxjs';

// The compilation should not success
// because this code does not import 'rxjs/add/operator/map'.
Observable.timer(1).map(() => {}).subscribe(() => {});
```
I'm not sure this problem is a higher priority issue, but I think this may be a problem.

@kwonoj @david-driscoll  Do you recognize this problem?

**Comment by saneyuki** [comment] 2016-01-14 18:29
> Do you recognize this problem?

Ah, My intention was "Have you already know this problem?"

**Comment by kwonoj** [comment] 2016-01-14 18:39
That's expected currently, by the way it works. So answer is yes, I do aware of it.

Solving this is not trivial though. What we want (and do) is allowing import operator module dynamically, and for this we also want to bring type definition to be dynamically provided per import, while type definition is typically expected to be published statically. It's also somewhat related with operator import itself, if you look into `add/*`, you can see it's using prototype patching at runtime. Means at compile time, TypeScript does not able to do much. I was once thought about using mixin / ambient class merging for modular operator supports those behavior, but that also had couple of drawbacks at the moment.

**Comment by kwonoj** [comment] 2016-01-14 18:43
You may refer issue at https://github.com/ReactiveX/RxJS/issues/642, not directly related but somewhat related. It's also hit by statically published type information, so extended operator definition's not supported at the moment.

**Comment by kwonoj** [comment] 2016-01-14 20:40
Just adding few additional details from TypeScript side support so far I know
- Extension method : on discussion
- traits : probably won't
- ES7 bind operator (`::`) : on discussion

Those are mechanics I was considered as possible solutions related to some of type / modularity issues but all of them are not in our hand at this moment. It's still possible there's elegant way that I haven't thought about.

**Comment by kwonoj** [comment] 2016-01-14 22:59
Noticed this https://github.com/Microsoft/TypeScript/pull/6213 too, might be feasible solutions..

**Comment by blesh** [comment] 2016-01-15 20:07
So to clarify this issue, the issue is that TypeScript thinks it's okay to use `map` even if map isn't there because we didn't import it?

**Comment by kwonoj** [comment] 2016-01-15 20:09
Yes, that's correct by `Observable` already have all type defintions of `CoreOperator` regardless of importing actual operator or not.

**Comment by kwonoj** [comment] 2016-01-16 01:09
I'm assigning myself for evaluating once typescript side changes arrives.

**Comment by masaeedu** [comment] 2016-01-16 02:00
@kwonoj If you're doing that refactoring, it might be a good idea to deduplicate the method signatures at the same time. I was discussing this with @david-driscoll in the gitter chat room, but essentially, it is possible to define the signature of the operator functions in an interface, then import that interface in `CoreOperators`, `Observable` and wherever else a member of that type is needed.

Once the [feature](https://github.com/Microsoft/TypeScript/pull/6213) you mentioned lands, you'd change the patch generator to simply re-export the interface like so:

    import {map} from '../operators/map';

    declare module "../Observable" {
        interface Observable<T> {
            map: map<T, U>;
        }
    }

The interfaces themselves could be generated to expand out the `...` parameters up to certain number of arguments, and can be evolved separately from the implementation (so long as the implementation is still assignable to the interface). I've done some work on this in https://github.com/masaeedu/RxJS/tree/operator-typing-fixes

**Comment by kwonoj** [comment] 2016-01-16 02:05
Thanks for details. Yes, that was my intended evaluation to let patch operator contains declarations and each (Observable, i.e) imports it to add necessarily. Appreciate for suggestion!

**Comment by saneyuki** [comment] 2016-01-29 05:41
After #1262 now, we can use the feature https://github.com/Microsoft/TypeScript/pull/6213 !

**Comment by kwonoj** [comment] 2016-01-29 05:42
I'm already trying on it locally and found some interesting issues compiler complains. Think need some more time to triage and align changes to make this work.

**Comment by kwonoj** [comment] 2016-01-29 05:45
Meanwhile, anyone having PR for this would be welcome :) Error I'm experiencing may be my stupid mistake somewhere.

**Comment by masaeedu** [comment] 2016-01-29 05:57
@kwonoj I'm trying this and it seems to work correctly (after removing the `buffer` stub from `Observable.ts`): 

```
import {Observable} from '../../Observable';
import {buffer} from '../../operator/buffer';

Observable.prototype.buffer = buffer;

declare module '../../observable' {
    interface Observable {
        buffer: (closingNotifier: Observable<any>) => Observable<T[]>;
    }
}

export var _void: void;
```

That said, I don't see how we can incorporate this change into the automatically generated patch files yet. Ideally we would export an interface definition in every operator file that looks like this:

```
// src/operator/buffer.ts
...
export interface buffer<T> {
    (closingNotifier: Observable<any>) => Observable<T[]>
}
...
```

And then the generated patch files could just declare that `Observable` has this method like so:

```
...

declare module '../../observable' {
    interface Observable {
        buffer: buffer<T>;
    }
}
...
```

This would mean we don't need to try and interpolate the specific signature for each operator into the generated patch file. My understanding was that @david-driscoll is working on creating these interfaces.

**Comment by kwonoj** [comment] 2016-01-29 05:58
@masaeedu We're no longer use script to generate patch file, so that's not concern :)

**Comment by masaeedu** [comment] 2016-01-29 06:03
@kwonoj Ok. So for now you'd just be looking for all stubs moved to appropriate patch files?

**Comment by kwonoj** [comment] 2016-01-29 06:04
and sharing error I'm experiencing, 

add/map.ts
```diff
import {Observable} from '../../Observable';
import {map} from '../../operator/map';

Observable.prototype.map = map;

+declare module '../../observable' {
+    interface Observable {
+       map: <R>(project: (x: T, ix?: number) => R, thisArg?: any) => Observable<R>;
+    }
+}

export var _void: void;
```

observable.ts
```diff 
 every: (predicate: (value: T, index: number) => boolean, thisArg?: any) => Observable<T>;
-map: <R>(project: (x: T, ix?: number) => R, thisArg?: any) => Observable<R>;
 mapTo: <R>(value: R) => Observable<R>;
```

and all derived class from observable starts to complain like..
>src/observable/EmptyObservable.ts(6,14): error TS2415: Class 'EmptyObservable<T>' incorrectly extends base class 'Observable<T>'.
  Property '_subscribe' is protected but type 'EmptyObservable<T>' is not a class derived from 'Observable<T>'.

**Comment by kwonoj** [comment] 2016-01-29 06:06
> you'd just be looking for all stubs moved to appropriate patch files

: Yes, I expect so. Organization now will be

`CoreOperators` contains interface still, `Observable` does not contain stub definition but each patch  operator will be.

**Comment by masaeedu** [comment] 2016-01-29 19:17
Looks like a bug to me. I've opened Microsoft/TypeScript#6731

**Comment by kwonoj** [comment] 2016-01-29 19:17
Cool, thanks.

**Comment by masaeedu** [comment] 2016-02-01 21:47
@kwonoj Ok, they've fixed the bugs and the fix should be in tomorrow's nightly. I've moved all the stubs over and the project builds and passes tests if I build TypeScript from source. Will PR tomorrow once the nightly comes out.

**Comment by kwonoj** [comment] 2016-02-01 23:35
I'll check typescript version update and bump it up, as well as including few operator changes to actually verify it works.

**Comment by kwonoj** [comment] 2016-03-10 06:14
Closed via https://github.com/ReactiveX/RxJS/pull/1388.

**Closed by kwonoj** 2016-03-10 06:14 UTC
Labels: priority: low, status: PRs welcome, type: type output
