### ISSUE TITLE
No documentation for ajax operators?

### ISSUE THREAD

**Issue by wldcordeiro** [ReactiveX/rxjs#2689] opened 2017-06-22 03:23 UTC
**RxJS version:** 5.4.0

**Code to reproduce:** N/A

**Expected behavior:** Looking at the documentation available [here](http://reactivex.io) I would expect to find a reference for the `ajax` operators.

**Actual behavior:** As far as I can tell there are no reference docs. There are some on the classes but not the operators like `switchMap` for example.

**Comment by kwonoj** [comment] 2017-06-22 03:25
dupe of https://github.com/ReactiveX/rxjs/issues/2656

**Closed by kwonoj** 2017-06-22 03:25 UTC
