### ISSUE TITLE
Is there a way to resolve promise stream and return all resolved data as Array

### ISSUE THREAD

**Issue by maple-leaf** [ReactiveX/rxjs#1982] opened 2016-09-27 10:18 UTC
This is the [codepen](http://codepen.io/maple-leaf/pen/ZpBzoO?editors=1010#0).

The demo is going to fetch an array contains all news id, and then fetch 10 news range by pager.

Here's two problems I have now:

1,  fetchedNews$ should return an array which is desired, but actually it just return each news one by one.

2, fetchedNews$ return obserable of each promiseObserable which make me  subscribe inside subscribe.

so what I want is like this: `fetchedNews$.subscribe(news => console.log(news);) `. News should be an array which contains all resolved news. Thanks :-)

**Comment by trxcllnt** [comment] 2016-09-27 11:12
`Observable.forkJoin` is your friend here. Promises and `fetch` don't support cancelation, which means you'll have a bunch of pending network requests that will negatively impact performance if the user pages through results quick enough. I've substituted `Observable.ajax.getJSON` for `fetch`, so as to keep everything in Observable land.

```es6
const { Observable } = Rx;
const { ajax: { getJSON }} = Observable;

var availableNews$ = getJSON('https://hacker-news.firebaseio.com/v0/topstories.json?print=pretty');
var pager$ = new Rx.Subject();
var fetchedNews$ = Observable
  .combineLatest(availableNews$, pager$, (news, {current, items_per_page}) => {
    return news.slice((current - 1) * items_per_page, items_per_page);
  })
  .switchMap((ids) => Observable.forkJoin(ids.map((id) => {
    return getJSON(`https://hacker-news.firebaseio.com/v0/item/${id}.json?print=pretty`);
  })));

pager$.subscribe(v => {
  document.querySelector('#pager').textContent = JSON.stringify(v);
});

fetchedNews$.subscribe(stories => {
   document.querySelector('#news').textContent = JSON.stringify(stories);  
});

pager$.next({current: 1, items_per_page: 10})
```

**Comment by maple-leaf** [comment] 2016-09-28 01:43
Your solution is amazing! Thanks. But I am new to rxjs,  some operators, like switchMap, forkJoin, getJSON , is really like invisible stars in the amazing sky. They can't be easily reached by reading rxjs doc. Or maybe it is my problem.

**Comment by maple-leaf** [comment] 2016-09-28 03:29
@trxcllnt  I find an issue of your solution, the request will fire twice when use `getJSON`, but ok when use `fetch`.

**Comment by blesh** [comment] 2016-09-28 07:23
Check to make sure you're not subscribing to the `fetchedNew$` twice.

**Comment by maple-leaf** [comment] 2016-09-29 01:38
@blesh I can confirm that fetchedNews$ is being subscribed here only:

    fetchedNews$.subscribe(stories => {
       document.querySelector('#news').textContent = JSON.stringify(stories);  
    });
And you can check the code [here](http://codepen.io/maple-leaf/pen/ZpBzoO?editors=1010#0) at codepen.

**Comment by trxcllnt** [comment] 2016-09-29 01:58
@maple-leaf I've confirmed the `ajaxGet` Observable is only creating a single XHR for these requests. This seems like a bug with codepen.

**Comment by maple-leaf** [comment] 2016-09-29 04:06
@trxcllnt I find what causing the double request. when request firebaseio resource,  an `options request` will be sent before real `get request`. Sorry for the misleading, and thanks for helping. :-)

**Comment by maple-leaf** [comment] 2016-09-29 05:32
but it's strange that `getJSON` will raise a `options` request while `fetch` just normally `get`

**Comment by blesh** [comment] 2016-10-03 21:14
@maple-leaf ... `fetch` and `getJSON` are two wildly different things. `fetch` has all sorts of custom configuration you can provide to it, and behaviors around things like caching, etc. Everything in this lib is built around XHR, which is lower-level.

Since this is a question and not an issue with the library, I'm going to close this. But feel free to continue discussion if you choose.

**Closed by blesh** 2016-10-03 21:14 UTC
