### ISSUE TITLE
Upgrade to rxjs 7 issue on this.schedulerActionCtor undefined

### ISSUE THREAD

**Issue by brendonco** [ReactiveX/rxjs#6360] opened 2021-05-05 08:49 UTC
Error in using Subject - this.schedulerActionCtor undefined

**Environment**
- Runtime: [e.g. Node v12.16.0, Chrome Version 89.0.4389.90 (Official Build) (32-bit)]
- RxJS version: 7

![image](https://user-images.githubusercontent.com/6521691/117116920-82390380-adc1-11eb-968c-c810384e14cc.png)

![image](https://user-images.githubusercontent.com/6521691/117117151-c88e6280-adc1-11eb-83b5-4925294950b3.png)

Steps to reproduce:

```
import React, { useEffect } from 'react';
import { Subject } from 'rxjs';
import { debounceTime, buffer } from 'rxjs/operators';

const SearchSubject = new Subject();
const debounceSearch$ = SearchSubject.pipe(debounceTime(1000));
const Search$ = SearchSubject.pipe(buffer(debounceSearch$));

 useEffect(() => {
    const SearchSubscriber$ = Search$.subscribe((value) => {
      const search = value[value.length - 1];

      dispatch(action(search));
    });

    // cleanup
    return () => {
      SearchSubscriber$.unsubscribe();
    };
  }, [dispatch]);

```

**Comment by cartant** [comment] 2021-05-05 08:56
This really needs a minimal reproduction to be actionable.

**Comment by brendonco** [comment] 2021-05-06 01:48
@cartant Apology for the missing steps.  Added the steps above.  schedulerActionCtor is undefined on initialize. Might need to check whether this method is defined before initializing it.

**Comment by cartant** [comment] 2021-05-06 02:44
Thanks. However, this is such a fundamental failure, I think you'd have to provide a reproduction that involves your build process. Or at least explain how you are building this. The only place that `QueueScheduler` is created is here:

https://github.com/ReactiveX/rxjs/blob/e19e104d011233d83bc10c37f1ee0b3ac6e15612/src/internal/scheduler/queue.ts#L67

And you can see that the ctor is passed. This applies to _all_ of the schedulers.

Also, your repro doesn't involve the `queueScheduler`, so I cannot see how it can effect the error message you've included in the issue.

FWIW, I cannot reproduce the problem with:

```ts
import { Subject } from "rxjs";
import { debounceTime, buffer } from "rxjs/operators";

const searchSubject = new Subject();
const debounceSearch$ = searchSubject.pipe(debounceTime(1000));
const search$ = searchSubject.pipe(buffer(debounceSearch$));
const subscription = search$.subscribe();

searchSubject.next("f");
searchSubject.next("fo");
searchSubject.next("foo");

setTimeout(() => {
  subscription.unsubscribe();
}, 5e3);
```

**Comment by cartant** [comment] 2021-05-06 08:59
Also, it's worth noting that the `Scheduler` ctor has not changed (other than an internal property being renamed) from v6:

https://github.com/ReactiveX/rxjs/blob/881cacdc99a7ebae219b595004c632f7358f730d/src/internal/Scheduler.ts#L33-L36

to v7:

https://github.com/ReactiveX/rxjs/blob/f9d29f7e75ff9394e3f4f79cfd4688593eb757c9/src/internal/Scheduler.ts#L28-L30

and the `queueScheduler` declaration:

https://github.com/ReactiveX/rxjs/blob/881cacdc99a7ebae219b595004c632f7358f730d/src/internal/scheduler/queue.ts#L66

has not changed either:

https://github.com/ReactiveX/rxjs/blob/f9d29f7e75ff9394e3f4f79cfd4688593eb757c9/src/internal/scheduler/queue.ts#L67

**Comment by hapablap21** [comment] 2021-05-11 13:57
Unsure about your setup, I had this issue attempting to upgrade to rxjs v7 with the redux-observable package.  The issue is in redux-observable, apparently: https://github.com/redux-observable/redux-observable/issues/735

**Comment by cartant** [comment] 2021-05-11 21:49
Closing this 'cause the most likely explanation is that redux-observable is being used and that package is relying upon private implementation details.

**Closed by cartant** 2021-05-11 21:49 UTC
