### ISSUE TITLE
Bluebird warning on PromiseObservable.ts

### ISSUE THREAD

**Issue by fredguile** [ReactiveX/rxjs#2402] opened 2017-02-22 16:30 UTC
Hi, I noticed this recurring Bluebird warning message when using Observable.fromPromise():

```
Warning: a promise was created in a handler at opt/app/node_modules/rxjs/src/observable/PromiseObservable.ts:67:26 but was not returned from it, see http://goo.gl/rRqMUw
    at new Promise (/opt/app/node_modules/bluebird/js/release/promise.js:77:14)
````

Nothing broken except this warning, so I guess it's a simple task to refactor PromiseObservable to always return something or null (<http://goo.gl/rRqMUw>)

**RxJS version:**
5.1.1

**Code to reproduce:**
use Observable.fromPromise

**Expected behavior:**
shouldn't trigger the Bluebird warning

**Actual behavior:**
triggering "a promise was created in a handler at but was not returned from it" when using with Bluebird

**Comment by kwonoj** [comment] 2017-02-22 16:46
Hi @fredguile, thx for report. Let me close this issue as dupe of https://github.com/ReactiveX/rxjs/issues/2343, can be tracked in single place.

**Closed by kwonoj** 2017-02-22 16:46 UTC
