### ISSUE TITLE
Pipe changes type of Subject to Observable

### ISSUE THREAD

**Issue by mytee306** [ReactiveX/rxjs#4659] opened 2019-03-21 21:44 UTC
#4379 Was swept under the rug. Let's fix this, it is a pain for people using RxJS. For example you cannot build your Angular app for production unless you type the the variable `as any`, it can really throw people off.

## Bug Report

**Current Behavior**

```ts
const subject$ = new Subject().pipe() // :: Observable
```

**Reproduction**
- [Stackblitz link](https://stackblitz.com/edit/rxjs-subject-type-issue)

```ts
import { Subject } from "rxjs"

const subject$ = new Subject().pipe()

subject$.next() // ❌

```

**Expected behavior**

Type is preserved after piping, be it a `Subject`, `BehaviorSubject`, `ReplaySubject` etc.

**Environment**
- Runtime: [e.g. Node ^8, Chrome ^60]
- RxJS version: ^6

**Possible Solution**

#4379 is quite vague about what is in the heart of the problem

Are there are known obstacles which stand in the way of resolving this issue?

**Additional context/Screenshots**

![in vscode](https://i.imgur.com/BugKpiZ.png)

**Comment by kwonoj** [comment] 2019-03-21 21:49
This is exact dupe of issue you referred: it is designed behavior to provide new `observable` when operator is chained (when `pipe` invoked). It's not changing just types but actually gives observables in runtime. We don't have immediate plan to change this designed behavior.

**Closed by kwonoj** 2019-03-21 21:49 UTC

**Comment by mytee306** [comment] 2019-03-22 22:43
> This is exact dupe of issue you referred: it is designed behavior to provide new `observable` when operator is chained (when `pipe` invoked). It's not changing just types but actually gives observables in runtime. We don't have immediate plan to change this designed behavior.

Of course pipe returns a new `Observable`, however a `Subject` is just a specialized type of `Observable`

**Comment by kwonoj** [comment] 2019-03-22 22:46
yes and yes. This is based on internal architecture of lift to create new instance of observable, until we revisit internal architectures it wont' be achievable easily, also there are some discussion / argument around behavior for carry-overing custom observable implementation over chained operators. So in short, we don't consider to change this in short amount of time until we get more clear sense around technical/behavioral exploration.

**Comment by mytee306** [comment] 2019-03-22 22:49
> yes and yes. This is based on internal architecture of lift to create new instance of observable, until we revisit internal architectures it wont' be achievable easily, also there are some discussion / argument around behavior for carry-overing custom observable implementation over chained operators. So in short, we don't consider to change this in short amount of time until we get more clear sense around technical/behavioral exploration.

Thank you for providing further insight, I've got a clearer picture of the matter at hand. What is your suggestion to work around the issue currently, is there a better way than just adding `as any`?

**Comment by mytee306** [comment] 2019-03-22 22:52
@kwonoj It may be good for other devs to reopen the issue so that we can track progress
