### ISSUE TITLE
drag and drop bug.

### ISSUE THREAD

**Issue by lili21** [ReactiveX/rxjs#2761] opened 2017-07-21 04:02 UTC
**RxJS version:**
5.0.3

**Code to reproduce:**
[jsbin](http://jsbin.com/wusuneqebi/edit?js,console,output)

**Expected behavior:**
- `mouseup` event only be added once.
- after `mouseup` event, subscribe won't be called. 

**Actual behavior:**
- every time, just after `drag` and `drop`, `mouseup` event be added. 
- You can play it around, `drag` one over another, repeat it. You will notice that `mouseup` event does not stop the `drag` 

**Additional information:**

**Comment by kwonoj** [comment] 2017-07-21 04:08
are you saying `mousedrag::completed` is not called when `mounseup` emitted for `after `mouseup` event, subscribe won't be called.` or otherwise?

**Comment by lili21** [comment] 2017-07-21 04:14
@kwonoj I know the `completed` won't be called. what I mean is after `mouseup` event. the `mousemove` event shouldn't `drag` the element. But that's not always true. You can play the demo around,

**Comment by kwonoj** [comment] 2017-07-21 04:17
![hybrid](https://user-images.githubusercontent.com/1210596/28448906-9667add6-6d90-11e7-8fab-ccbd99d37817.gif)

I just tried your demo, only add `console.log(pos)` in subscription and confirmed subscription is not called once `up` event fired. Check above screen record.

**Comment by kwonoj** [comment] 2017-07-21 04:22
and reason it keeps creating up is each time mousedown event emits, you're creating new observable internally adds eventlistener in `up` event. I believe this is user level code, not library side issue - closing for now. If you believe this is bug in library, please share isolated code snippet causes growing addition to eventlistener.

Lastly, for event binding you can use `fromEvent / fromEventPattern` instead of creating observable directly.

**Comment by lili21** [comment] 2017-07-21 04:23
If you just drag one element , then every is fine.You should drag one over anther, and repeat it. Like drag `target1` over 'target2`, drag `target2` over `target1` .
 BTW, have you notice there are multi `up` logs ? Is it a bug ?

**Closed by kwonoj** 2017-07-21 04:22 UTC
Labels: status: more information needed

**Comment by kwonoj** [comment] 2017-07-21 04:24
I just commented above - it's not library, you're creating multiple observable keeps adding eventlistener into target.

**Comment by lili21** [comment] 2017-07-21 04:25
Please don't close It . Could you tell me what software are you using to make screen shot to git. I can take a screen shot there will be a bug like what I said.

**Comment by kwonoj** [comment] 2017-07-21 04:27
@lili21 I noticed multiple `up`, and digging into it as commented your code keep creating eventlistener. This issue repo is to triage / report library side issue, while this is user code.  As issue template suggests, it is better for you and for us that this question is placed in [StackOverflow](http://stackoverflow.com/questions/tagged/rxjs5) or some chat channel instead.

**Comment by lili21** [comment] 2017-07-21 04:29
actually I don't care the multiple `up` very much, I care more about the `drag` and `drop` work as expected. which does not.

**Comment by lili21** [comment] 2017-07-21 04:30
and why my code keep creating eventlistener ? because of `takeUntil` ?

**Comment by paulpdaniels** [comment] 2017-07-21 04:45
It keeps creating an eventlistener because each mouse down maps to a `mousemove.takeUntil(mouseUp)` combo. The problem is this:

```javascript

  var mouseup   = Rx.Observable.create(ob => {
    target.addEventListener('mouseup', e => {
      console.log('up')
      ob.next(e)
    })
  })

```

As was pointed out you would be better off using the `fromEvent` pattern as the code above does not clean up the subscription on unsubscribe. Thus you keep generating new mouseup handlers everytime there is a mouse down event.

**Comment by lili21** [comment] 2017-07-21 04:48
@paulpdaniels Thanks. understand that now.
Unfortunately I can't use `fromEvent` in my real application code.

**Comment by lili21** [comment] 2017-07-21 05:07
![drag-drop-iloveimg-compressed](https://user-images.githubusercontent.com/4456380/28449782-5353b528-6e15-11e7-8f92-0d3f99494510.gif)

@kwonoj  after `mouseup` event,

**Comment by lili21** [comment] 2017-07-21 06:11
figured that out, when dragging red block "over" black block, the red block is below black block because of the default `z-index` value. so the `mouseup` event is fired on black block ,not red block.
