### ISSUE TITLE
Union of Observables cannot have piped operators

### ISSUE THREAD

**Issue by bowenni** [ReactiveX/rxjs#3388] opened 2018-03-07 00:10 UTC
**RxJS version:**
I tested on both v5.5 and v6.0

**Code to reproduce:**
```ts
(foo as Observable<number>).pipe(filter(_=>true));
(foo as Observable<string>).pipe(filter(_=>true));
(foo as Observable<number|string>).pipe(filter(_=>true));
(foo as Observable<number>|Observable<string>).pipe(filter(_=>true));
```

**Expected behavior:**
All build or all fail.

**Actual behavior:**
Line 1-3 build, line 4 fails with "TS2554: Expected 0 arguments, but got 1."

**Additional information:**

**Comment by benlesh** [comment] 2018-03-08 04:10
This seems like something that would have to be fixed on the TypeScript side of things. 🤔

**Comment by cartant** [comment] 2018-03-09 00:29
@bowenni The issue isn't an RxJS problem. And I doubt that it's a TypeScript problem, either; it's just how the resolution of overload signatures works for union types.

To see what's going on, have a look at the overload signatures for `pipe`. For `Observable<number>`, `pipe` will have signatures like:

```ts
pipe(): Observable<number>
pipe<A>(op1: OperatorFunction<number, A>): Observable<A>
...
```

And for `Observable<string>`, `pipe` will have signatures like:

```ts
pipe(): Observable<string>
pipe<A>(op1: OperatorFunction<string, A>): Observable<A>
...
```

For the union type - `Observabe<number> | Observable<string>` - the only `pipe` signature that's common to both is the first - the signature that with no parameters - so that's the only one that's available.

**Comment by bowenni** [comment] 2018-03-14 00:27
Thanks @cartant. That makes sense.

The error message is super confusing though.

**Comment by benlesh** [comment] 2018-03-15 18:36
The real fix here is to cast the source observable to `Observable<any>` or even `Observable<string|number>`, because in this case you're basically saying "I don't care what type of value is coming in, I'm going to do X with it".

**Closed by benlesh** 2018-03-15 18:36 UTC
Labels: resolution: wontfix
