### ISSUE TITLE
File permissions in node_modules/rxjs

### ISSUE THREAD

**Issue by fdubost** [ReactiveX/rxjs#2687] opened 2017-06-21 07:46 UTC
**RxJS version:** 5.4.1

**Code to reproduce:** We upgrade RxJS from 5.2.0 to 5.4.1 via yarn

**Expected behavior:** File permissions should be 644 in node_modules/rxjs (it works in 5.2.0)

**Actual behavior:** In 5.4.1, file permissions is 640

**Additional information:** This is problematic for us because the user who deploys the code and installs the dependencies is not the same as the one who runs the server

Thanks for your help.

**Comment by fdubost** [comment] 2017-06-21 08:09
Some other informations :
yarn 0.22.0
npm 4.2.0
node 7.8.0

**Comment by kwonoj** [comment] 2017-06-21 13:01
dupe of https://github.com/ReactiveX/rxjs/issues/2522 .

**Closed by kwonoj** 2017-06-21 13:01 UTC
