### ISSUE TITLE
Invoking function returned by bindNodeCallback causes unexpected compiler error

### ISSUE THREAD

**Issue by kmdupr33** [ReactiveX/rxjs#1799] opened 2016-07-04 02:36 UTC
**RxJS version:**

5.0.0-beta9

**Code to reproduce:**

```typescript
import * as fs from 'fs';
var readFileAsObservable = Rx.Observable.bindNodeCallback(fs.readFile);
var result = readFileAsObservable('./roadNames.txt', 'utf8');
result.subscribe(x => console.log(x), e => console.error(e));
```

**Expected behavior:**

Compile without error

**Actual behavior:**

Compiling causes error:

>bug.ts(5,14): error TS2346: Supplied parameters do not match any signature of call target.

**Additional information:**

The "Code to reproduce" here is exactly the sample code from the docs that demonstrate how to use `bindNodeCallback`.

**Comment by kwonoj** [comment] 2016-07-04 05:45
This is caused by current type definition's of `bindNodeCallback` infers type to `readFile` to `<string, buffer>` automatically, falls back to returning function to `(in: string) => Observable<Buffer>`. 

As an immediate workaround, you may specify type explicitly such  as

`var readFileAsObservable = Rx.Observable.bindNodeCallback<string>(fs.readFile);`

but feeling type definition might need to be updated, especially current generic `<T>` is hiding generic type of class `Observable`.

**Comment by kmdupr33** [comment] 2016-07-04 15:40
Thanks! Y'all do excellent work!

**Comment by kwonoj** [comment] 2016-07-04 21:04
/cc @david-driscoll for visibility also. 

At first sight (haven't explored yet), there isn't simple way to support function could have different return types (for example, `fs.readFile(): string | buffer`) by parameters. I'd like to use this issue to enhance type definition at least, such as removing repeated generics `<T>`.

**Comment by kwonoj** [comment] 2016-07-18 18:16
> current generic <T> is hiding generic type of class Observable.

: I've visited this and just noticed it's mostly by static method not able to reference class type params. 
At this moment, it's required to explicitly casting where necessary, closing issue. Once if I find better way to enhance, I'll come up with separate PR.

**Closed by kwonoj** 2016-07-18 18:16 UTC
Labels: type: type output
