### ISSUE TITLE
Incorrect typingspath in package.json of reactivex/rxjs@5.5.2

### ISSUE THREAD

**Issue by kollster** [ReactiveX/rxjs#3032] opened 2017-11-01 12:03 UTC
**RxJS version:**
5.5.2
 
**Code to reproduce:**
```npm install @reactivex/rxjs```

**Expected behavior:**
TypeScript should pick up typings for the package automatically as a ```typings```-entry is found in package.json.

**Actual behavior:**
TypeScript cannot find the typings file as the path in the ```typings```-entry in package.json is incorrect.
```"typings": "./dist/package/typings/Rx.d.ts"``` is an invalid path.

**Additional information:**
As far as I can see, the correct entry in package should be
```"typings": "./dist/package/Rx.d.ts"```

**Comment by kwonoj** [comment] 2017-11-01 15:31
dupe of https://github.com/ReactiveX/rxjs/issues/3005 .

**Closed by kwonoj** 2017-11-01 15:31 UTC
