### ISSUE TITLE
Cache operator

### ISSUE THREAD

**Issue by hrattls** [ReactiveX/rxjs#5930] opened 2020-12-11 14:23 UTC
I want to cache http results for a given time period.
I tried to use the shareReplay operator for this, but this operator clears the buffer after the given time window and then stops emitting values.
New subscribers do not receive any value.
I expected that the wrapped observable was queried again after the given timewindow elapses. 
For now I solved this with my own custom operator: 
```
function myCacheOperator<T>(duration: number): (s: Observable<T>) => Observable<T> {
  let innerSubject: ReplaySubject<T>;
  let refreshDate: Date;

  return (source: Observable<T>) => {
    // return observable which emits when inner observable emits
    return new Observable<T>(subscriber => {
      if (!refreshDate || new Date().getTime() > refreshDate.getTime() + duration) {
        refreshDate = new Date();
        innerSubject = new ReplaySubject<T>(1);
        // call source observable to get value and pass the result to the innerSubject.
        source.pipe(take(1)).subscribe(innerSubject);
      }
      // subscribe to innerSubject and pass result to extenal subscriber
      innerSubject.pipe(take(1)).subscribe(subscriber);
    });
  };
}
```

Usage:
```
  // Cache  result for 5 minutes
  private cache$ = this.httpClient.get<any>(this.API_URL).pipe(myCacheOperator(5 * 60 * 1000));

  getValue():Observable<any>{
    return  this.cache$;
  }
```

**Comment by chernodub** [comment] 2020-12-23 06:12
Same here 🤕, seems like an unexpected behavior since we can't reactivate the producer 
`rxjs 6.6.2`
https://stackblitz.com/edit/rxjs-etdzzg

**Comment by cartant** [comment] 2021-03-14 02:08
Closing this because v7 has a [`share` operator](https://github.com/ReactiveX/rxjs/blob/b50926274d748c563b8371fa46e80f68250b762e/src/internal/operators/share.ts) and that operator is going to be extended to handle this scenario - see [this comment](https://github.com/ReactiveX/rxjs/issues/4033#issuecomment-782508348)

**Closed by cartant** 2021-03-14 02:08 UTC
