### ISSUE TITLE
rxjs 6.4.0 does not compile with Create React App (@babel/plugin-transform-typescript) due to exporting a const enum

### ISSUE THREAD

**Issue by BrianMitchL** [ReactiveX/rxjs#4555] opened 2019-02-10 19:02 UTC
## Bug Report

**Current Behavior**
In RxJS 6.4.0, the `NotificationKind` const enum was used:
https://github.com/ReactiveX/rxjs/blob/6c4f57bd2fda929aa894dbb5e7172bb48de35fa6/src/internal/Notification.ts#L7

Unfortunately, babel [does not support const enums](https://babeljs.io/docs/en/babel-plugin-transform-typescript#caveats), so any application that is compiled with it will not compile. This is the TypeScript compiler used in create-react-app apps. The errors presents itself when the TypeScript `skipLibCheck` flag is set to false.

```
Type error: Ambient const enums are not allowed when the '--isolatedModules' flag is provided.  TS1209

    1 | import { PartialObserver } from './types';
    2 | import { Observable } from './Observable';
  > 3 | export declare const enum NotificationKind {
      |                           ^
    4 |     NEXT = "N",
    5 |     ERROR = "E",
    6 |     COMPLETE = "C" 
```

**Reproduction**
- REPL or Repo link:
https://github.com/BrianMitchL/rxjs-cra-compile-error

The [6.4.0](
https://github.com/BrianMitchL/rxjs-cra-compile-error/tree/6.4.0) branch errors when running `npm run start`
when the [6.3.3](
https://github.com/BrianMitchL/rxjs-cra-compile-error/tree/6.3.3) branch works.

**Expected behavior**
I would expect the application to compile with RxJS 6.4.0 when using the babel compiler.

**Environment**
- Runtime: Tested with Node v10.15.0 and v11.9.0
- RxJS version: 6.4.0
- Other related libraries: 
    `typescript@3.3.3`
    `react-scripts@2.1.3`

**Possible Solution**
This might be a good place to use a union string type. Instead of

```ts
export const enum NotificationKind {
  NEXT = 'N',
  ERROR = 'E',
  COMPLETE = 'C',
}
```

the following would be used

```ts
export type NotificationKind = 'NEXT' | 'ERROR' | 'COMPLETE';
```

**Comment by kwonoj** [comment] 2019-02-10 19:07
Closing as dupe of https://github.com/ReactiveX/rxjs/issues/4538 fyi we were using string based literal and moved to enum, while we may go back to non const enum.

**Closed by kwonoj** 2019-02-10 19:07 UTC

**Comment by BrianMitchL** [comment] 2019-02-10 19:13
I was asked to open a new issue https://github.com/ReactiveX/rxjs/issues/4538#issuecomment-461403319

But it really is the same root cause in the end.

**Comment by cartant** [comment] 2019-02-10 19:29
@BrianMitchL Your including the `isolatedModules`-related error makes this look like a dupe, but it might not be. If construction enums not supported in the Babel transform (which makes the transform far less useful, IMO) this isn't a dupe and you will still have a problem if the exporting of the const enum in https://github.com/ReactiveX/rxjs/pull/4514 solves the isolatedModules`-related error. I suspect you see that error because `tsc` (or something) is used for type checking before the Babel transformation.

**Comment by kwonoj** [comment] 2019-02-10 19:32
I think this is dupe as both of then are caused by not supporting const enum, while path it causes are different: it is true babel doesn't support const enum so regardless of isolatedmodules this'll occur as soon as we use const enum though.

**Comment by kwonoj** [comment] 2019-02-10 19:32
Which means we can't use const enum.

**Comment by BrianMitchL** [comment] 2019-02-10 19:33
As I understand the CRA compile process. `tsc` is run for checking in your IDE, and only `babel` is run at compile time. `babel` doesn't do checking, just straight compiling, and is throws an error when encountering a `const enum`.

**Comment by cartant** [comment] 2019-02-10 22:05
@kwonoj

> Closing as dupe of #4538

Yeah. You are completely correct. The use of the term 'ambient' in the error message confused me - as the term has a different meaning for `.d.ts` files.

It's clear to me now that the problem stems from the fact that when transpiling a single file, it's not possible to know which literal value should be used to replace a reference to a const enum.

I'll add a script that runs a transpilation (with no output and with `isolatedModules` set to `true`) when Travis performs its full validation. And I'll replace the const enum with a string-literal union type.
