### ISSUE TITLE
rxjs.dev 503 error after browsing several pages

### ISSUE THREAD

**Issue by cedricss** [ReactiveX/rxjs#4482] opened 2019-01-21 15:16 UTC
#### Documentation Related To Component:

https://rxjs.dev/

#### Please check those that apply

- [x] error(s) 

### Chrome example

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/802010/51482551-0274ff80-1d97-11e9-8104-a8f19eb8e2ff.png">

<img width="986" alt="image" src="https://user-images.githubusercontent.com/802010/51482383-972b2d80-1d96-11e9-8ed2-e5e8da7066e7.png">

After opening several https://rxjs.dev/ pages, I ended up with a 503 error. It's unclear what trigger the error: it can be right after visiting only few pages or continue to work for a long time.

I tried:
-  ✅ to check the "bypass (service worker) for network": the page is successfully loaded
-  ⚠️  to click on "Unregister (the service worker)": it temporarily solves the issue. After a while, the 503 is raised again.
- ❌ to click on "Update (the service worker)": it doesn't solve the issue

### Safari example

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/802010/51483039-5af8cc80-1d98-11e9-8307-d877a3f95d12.png">

I ended up having the issue on Safari too, again after opening several pages.

### Notes

- In my case, the rxjs.dev pages are opened from an external website (not from the documentation itself), from links like:

```
<a href="https://rxjs.dev/api/operators/map" target="_blank">map</a>
```

- This 503 error is similar to the closed issue https://github.com/ReactiveX/rxjs/issues/4178

**Comment by benlesh** [comment] 2019-01-22 23:12
cc @petebacondarwin ... has angular.io had this issue and resolved it?

**Comment by JWO719** [comment] 2019-01-23 19:50
AFAIK #4178 isn't deployed yet. I remember that @gkalpak updated the SW, I'm not sure if this is the correct/working version. But nevertheless this behavior exists for at least 3 months and this is the first related issue. Therefore I'd suggest re-checking this after the next deployment

**Comment by gkalpak** [comment] 2019-01-23 20:02
Wow, rxjs.dev still runs the old SW. #4201 hasn't indeed been deployed yet 🤔

**Comment by JWO719** [comment] 2019-01-31 07:03
After the recent deployment of the docs website, I can't reproduce this problem. Therefore I'll close this issue. Please reopen, if it still occurs.

**Closed by JWO719** 2019-01-31 07:03 UTC
Labels: type: bug, type: docs
