### ISSUE TITLE
combineLatest object signature is deprecated 

### ISSUE THREAD

**Issue by ArielGueta** [ReactiveX/rxjs#7080] opened 2022-10-06 06:03 UTC
### Describe the bug

When using the object signature with `combineLatest` it seems like it's going to the wrong signature and mark it as deprecated:

<img width="242" alt="Screen Shot 2022-10-06 at 9 02 07" src="https://user-images.githubusercontent.com/20522870/194226190-4b34dc39-c02d-4e90-bc02-06a889d4e659.png">

<img width="563" alt="Screen Shot 2022-10-06 at 9 02 59" src="https://user-images.githubusercontent.com/20522870/194226285-ab4e660e-ca2f-4638-a501-4de8e35e9c39.png">

### Expected behavior

It should work

### Version

7.5.0

**Comment by rbirkgit** [comment] 2023-02-22 01:15
I am confused. Is this a bug or not? I understand if it may be tricky to fix, or need to be prioritized. I Just want to know first if the object signature is deprecated or not?

**Comment by jakovljevic-mladen** [comment] 2023-09-25 13:51
Hey everyone. It looks like this issue was caused by a bug in the IDE mentioned in the previous comment. It seems like the bug is fixed now.

We had other similar reports in the past. Please try it out with the latest version of the IDE and report back if you think this was a mistake.

**Closed by jakovljevic-mladen** 2023-09-25 13:51 UTC
