### ISSUE TITLE
issue when importing/using Rxjs with 5.5.3 version

### ISSUE THREAD

**Issue by srcook1** [ReactiveX/rxjs#3155] opened 2017-12-03 19:47 UTC
**RxJS version:**
5.5.3

**Code to reproduce:**
import Rx from 'rxjs/Rx';  //same with from 'rxjs'
let observable = new Rx.Subject();

**Expected behavior:**
a new Rx.Subject is created

**Actual behavior:**
no Rx.Subject is created, get an error:
TypeError: Cannot read property 'Subject' of undefined

**Additional information:**
This was working fine with 5.5.2 code, and broke with 5.5.3
node v8.9.1
breaks when running using babel, ex: node -r babel-register foo.js
works when running es modules nativly, ex: node --experimental-modules foo.mjs

**Comment by kwonoj** [comment] 2017-12-03 20:11
This may related with https://github.com/ReactiveX/rxjs/pull/3025, haven't verified though. /cc @jasonaden .

**Comment by bridzius** [comment] 2017-12-04 11:40
Can be fixed by doing `import * as Rx from "rxjs/Rx"`.

The documentation should be fixed to reflect this, since the default import is still used.

**Comment by steveci** [comment] 2017-12-04 12:29
Has import of the default been deprecated/removed or will it this be fixed in 5.5.4?

**Comment by salemdar** [comment] 2017-12-04 12:48
Quick fix:
Path should be changed from `rxjs/operators/index.js` to `rxjs/operators.js`

But this is a breaking change for many people and should have been versioned accordingly. What are the plans for for *5.0.4*?

**Comment by benlesh** [comment] 2017-12-04 16:58
> But this is a breaking change for many people and should have been versioned accordingly. 

It is a regression, not an intentional breaking change. We'll try to get it fixed as soon as we can.

**Comment by jasonaden** [comment] 2017-12-04 18:23
The steps above don't repro the issue for me. Can someone please provide a way to reproduce this? Ideally create a repo with the problem so we can clone and see the issue. There must be something with environments or tools that I'm not seeing when simply using the above steps.

@srcook1 @askielboe @salemdar

**Comment by srcook1** [comment] 2017-12-04 18:47
https://github.com/srcook1/rxjs_issue_demo

@jasonaden

**Comment by steveblue** [comment] 2017-12-04 19:00
`rxjs/operators/index.js` is missing in rxjs 5.5.3 That seems to be the culprit in breaking our build. This should not have been changed! Now we have a library that was built on 5.5.2 that is breaking.

**Comment by jondot** [comment] 2017-12-05 14:24
I can verify this happening on React Native.

**Comment by paranoidjk** [comment] 2017-12-05 14:30
same problem here.

**Comment by benlesh** [comment] 2017-12-05 20:20
Apparently 5.5.3 was built with the wrong (newer) version of TypeScript, and that's what's causing the issue. Will build properly and publish again soon.

**Comment by benlesh** [comment] 2017-12-05 20:44
This should be resolved in 5.5.4 now.

**Closed by benlesh** 2017-12-05 20:44 UTC
