### ISSUE TITLE
animationFrameScheduler throws in SSR mode

### ISSUE THREAD

**Issue by DmitryEfimenko** [ReactiveX/rxjs#5940] opened 2020-12-20 10:40 UTC
## Bug Report

**Current Behavior**
My Angular app is using a 3rd party library: [ngx-highlightjs](https://github.com/MurhafSousli/ngx-highlightjs) and it throws an error when running the app in SSR mode:
> requestAnimationFrame is not defined

Digging into the stack trace revealed it's due to the use of [this line](https://github.com/MurhafSousli/ngx-highlightjs/blob/1371ba643ddc7ae26f708c1edcfddd0ec21b4150/projects/ngx-highlightjs/src/lib/highlight.ts#L110): 
```ts
animationFrameScheduler.schedule(() =>
  // ...
);
```

**Reproduction**
- Repo link: I will update this shortly

**Expected behavior**
I'm actually not sure if it should be the responsibility of rxjs to make `animationFrameScheduler` work in NodeJS or if it should be the responsibility of the library author to write SSR-friendly implementation.

It looks like there are **[a lot of similar issues in the wild](https://www.google.com/search?q=animationFrameScheduler+ssr&rlz=1C1CHBF_enUS740US740&oq=animationFrameScheduler+ssr&aqs=chrome.0.69i59.991j0j7&sourceid=chrome&ie=UTF-8)** so my first impression is for this issue to be fixed at the rxjs level. Then all these other issues will miraculously be resolved! ✨

**Environment**
- Runtime: Node v12
- RxJS version: 6.6.3
- angular/core: 9.1.13 (in case this is relevant)

**Comment by kwonoj** [comment] 2020-12-20 23:01
Same as `ajaxObservable` which requires proper polyfill to XHR on node.js which doesn't support it out of the box, I believe this should be polyfilled by each application if it's needed to be used on runtime does not have suport for it.

**Comment by waterplea** [comment] 2020-12-21 17:11
Since RxJS positions itself not as a browser but as a multiplatform library, I believe a check for availability and fallback to setTimeout could be built in. I see that new `animationFrames` Observable also tries to access global `requestAnimationFrame`. Do you think this should be addressed, @benlesh or is it working by design and we should be careful using it cross-platform?

**Comment by cartant** [comment] 2021-03-14 02:10
IMO

> working by design

So I'm closing this.

**Closed by cartant** 2021-03-14 02:10 UTC

**Comment by DmitryEfimenko** [comment] 2021-03-14 06:10
great argumentation.

**Comment by waterplea** [comment] 2021-03-14 06:30
@cartant I see that new `animationFrames` function uses global const `animationFrameProvider` which has a `delegate` property, which is `undefined`. In that case it falls back to global rAF functions. Are we supposed to mutate that variable in SSR environment with a fallback to avoid this issue? Is this how this `delegate` was supposed to be used?

**Comment by cartant** [comment] 2021-03-14 06:38
`animationFrameProvider` is internal, ATM, and is for testing purposes. It's possible that it might be exposed at some stage, but there is no plan to do so.

Fundamentally, it's not RxJS's responsibility to detect and mock features that applications might be using that are not available in particular environments. As OJ mentioned the same could be said for XHR, fetch, WebSockets, etc.
