### ISSUE TITLE
lift signature issue returns on new typescript version

### ISSUE THREAD

**Issue by ritox842** [ReactiveX/rxjs#2726] opened 2017-07-06 08:57 UTC
On version 5.4.2 there's a bug fix:

> Subject: lift signature is now appropriate for stricter TypeScript 2.4 checks (#2722) (9804de7)

I'm using typescript  version 2.4.1 and I'm getting this bug again...

What can I do?

**Comment by ericeslinger** [comment] 2017-07-06 19:38
yeah, I'm having the same issue - rolling back to typescript@2.4.0 for now.

**Comment by kwonoj** [comment] 2017-07-07 13:31
If you're experiencing this still, please provide minial repo have single rxjs dependency can repro this issues.

**Comment by ericeslinger** [comment] 2017-07-07 14:10
super-minimal test case here: https://github.com/ericeslinger/lift-example

```
git clone https://github.com/ericeslinger/lift-example.git
cd lift-example && npm i && npm test
```

All I really do is implement lift thusly:

```
export class ExtendedObservable<T> extends Observable<T> {
  lift(operator) {
    const observable = new ExtendedObservable();
    observable.operator = operator;
    return observable;
  }
}
```

which isn't precisely what I'm doing in my actual work, but seems like a pretty minimal reproduction.

this is confirmed to work when I install typescript@2.4.0 and fail under 2.4.1 (to test in the repo, `npm i typescript@2.4.0 && npm test` )

**Comment by kwonoj** [comment] 2017-07-07 15:24
@ericeslinger your example isn't cases of lib's incorrect type signature, it's expected TS behavior.

Note TS 2.4.1 enables *strict generic check*, reason why your code works on prior version of compiler. Signature of base `lift` is `lift<R>(operator: Operator<T, R>): Observable<R>`, and inherited lift is inferred by compiler as `life(operator:any): ExtendedObservable<{}>`, so there is type incompatibility occurs. 

Correcting it by explicit casting like 
```
lift<T>(operator): Observable<T> {
    const observable = new ExtendedObservable() as Observable<T>;
    (observable as any).operator = operator;
    return observable;
  }
```

resolves issue. (*Note: above snippet is only for illustration*)

I'll leave this issue opened bit more to see if there's any remaining issue around library itself - meanwhile, anyone experience similar issues please check 2 things

- Is there any dependency still have old version of Rx in somewhere?
: you have to physically check node_modules for this. To isolate this, simplest way is create minimal reproducible repo.

- Is this caused by library code?
: If so, it should happen by using variant of observable inherited object, like Subject. If not, check if user code have compatible types.

**Comment by GulinSS** [comment] 2017-07-12 12:26
See https://github.com/ReactiveX/rxjs/pull/2722#issuecomment-314734447
Looks like need update `.d.ts` also

**Comment by kwonoj** [comment] 2017-07-12 13:08
@GulinSS `d.ts` type definition is auto-generated and already updated.

![image](https://user-images.githubusercontent.com/1210596/28119093-79056f86-66c8-11e7-8423-5415932f641f.png)

Pleasd check above comment, and share reproducible repo for code ensure if there is no dupe pkg, or user code has incompatible types.

**Comment by GulinSS** [comment] 2017-07-13 06:44
@kwonoj, did deeper investigation, the issue was in ionic-native dep which referenced to older rxjs version

**Comment by kwonoj** [comment] 2017-07-17 22:29
as I do not see further report related with library code itself, I'm closing this issue for now. Anyone experiences similar issue and confirmed if it's not coming from old pkg version or user code, feel freely create new issue with reproducible repo.

**Closed by kwonoj** 2017-07-17 22:29 UTC
Labels: status: more information needed
