### ISSUE TITLE
asap scheduler throws error with limiting interval via take

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/rxjs#2594] opened 2017-05-07 04:36 UTC
**RxJS version:**
5.3.1

**Code to reproduce:**
```js
Rx.Observable.interval(100, Rx.Scheduler.asap).take(3).subscribe((x) => {
  console.log(x);
});
```

**Expected behavior:**

**Actual behavior:**

**Additional information:**
```
Error: executing a cancelled action
    at AsapAction.AsyncAction.execute (C:\github\test\node_modules\rxjs\scheduler\AsyncAction.js:83:20)
    at AsapScheduler.flush (C:\github\test\node_modules\rxjs\scheduler\AsapScheduler.js:22:32)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by kwonoj** [comment] 2017-05-07 04:36
Seems this was happening in 5.3.0 as well, not a regression between patches.

**Comment by trxcllnt** [comment] 2017-05-07 22:32
@kwonoj I'll take a look

**Comment by dreamershl** [comment] 2017-06-03 08:53
I encounter this issue too. And find it may be caused by the AnimationFrameAction unmatched requestAsyncId/recycleAsyncId process. 

in request, if the delay positive value, it will call the super method, the AsynAction will just use the "setInterval". But in the  recycleAsyncID triggered by the "unsubscribe", the checking **"delay === null && this.delay > 0"** will be false. So the corresponding "clearInterval" isn't properly called.

"this.delay" becomes null is because the "AsyncAction._unsubscribe" function set it null first before the "recycleAsyncId"

```javascript
protected _unsubscribe() {

    const id = this.id;
    const scheduler = this.scheduler;
    const actions = scheduler.actions;
    const index = actions.indexOf(this);

    this.work  = null;
    this.delay = null;
    this.state = null;
    this.pending = false;
    this.scheduler = null;

    if (index !== -1) {
      actions.splice(index, 1);
    }

    if (id != null) {
      this.id = this.recycleAsyncId(scheduler, id, null);
    }
  }
```



 
```javascript
       AnimationFrameAction.prototype.requestAsyncId = function (scheduler, id, delay) {
        if (delay === void 0) { delay = 0; }
        // If delay is greater than 0, request as an async action.
        if (delay !== null && delay > 0) {
            return _super.prototype.requestAsyncId.call(this, scheduler, id, delay);
        }
        // Push the action to the end of the scheduler queue.
        scheduler.actions.push(this);
        // If an animation frame has already been requested, don't request another
        // one. If an animation frame hasn't been requested yet, request one. Return
        // the current animation frame request id.
        return scheduler.scheduled || (scheduler.scheduled = AnimationFrame.requestAnimationFrame(scheduler.flush.bind(scheduler, null)));
    };
    AnimationFrameAction.prototype.recycleAsyncId = function (scheduler, id, delay) {
        if (delay === void 0) { delay = 0; }
        // If delay exists and is greater than 0, or if the delay is null (the
        // action wasn't rescheduled) but was originally scheduled as an async
        // action, then recycle as an async action.
        if ((delay !== null && delay > 0) || (delay === null && this.delay > 0)) {
            return _super.prototype.recycleAsyncId.call(this, scheduler, id, delay);
        }
        // If the scheduler queue is empty, cancel the requested animation frame and
        // set the scheduled flag to undefined so the next AnimationFrameAction will
        // request its own.
        if (scheduler.actions.length === 0) {
            AnimationFrame.cancelAnimationFrame(id);
            scheduler.scheduled = undefined;
        }
        // Return undefined so the action knows to request a new async id if it's rescheduled.
        return undefined;
    };
```

**Comment by trxcllnt** [comment] 2017-06-03 20:42
@dreamershl oh thanks, great catch! will have the fix PR'd soon

**Comment by trxcllnt** [comment] 2017-06-03 21:32
@dreamershl @kwonoj PR in #2638

**Comment by rangelke** [comment] 2017-06-11 14:07
@trxcllnt Thanks!
I noticed this issue too but didn't know if it was my lack of Scheduler knowledge or not. I'll upgrade ASAP when it gets merged!

**Closed** 2017-06-14 17:55 UTC
Labels: type: bug
