### ISSUE TITLE
fromEventPattern does not pass multiple arguments from event callbacks

### ISSUE THREAD

**Issue by raycarter** [ReactiveX/rxjs#3048] opened 2017-11-05 16:18 UTC
**RxJS version:**
5.5.2
**Code to reproduce:**
```javascript
const EventEmitter = require('events').EventEmitter;
const Observable = require('rxjs').Observable;

const emitter = new EventEmitter();

const obs = Observable.fromEventPattern(function(handler) {
  emitter.on('test', handler);
});

obs.subscribe(args => {
  console.log(args); // 'a', expected ['a', 'b', 'c']
});

emitter.emit('test', 'a', 'b', 'c');
```
**Expected behavior:**
A group of arguments is expected in `subscribe` (here expected ['a', 'b', 'c']).
**Actual behavior:**
Only the first argument is emtted (here 'a').
**Additional information:**
I think it could be common to create Observables from events and a lot of events pass more than one arguments in its callback functions. It is useful to let rxjs collect all of the arguments and pass them to `subscribe`. If I am wrong here about how to use rxjs in this situation, please give me a hint how I should do it correctly or which other operators should be used for events with multiple arguments. Thanks a lot!

**Comment by kwonoj** [comment] 2017-11-05 17:22
dupe of https://github.com/ReactiveX/rxjs/issues/2431.

**Closed by kwonoj** 2017-11-05 17:22 UTC
