### ISSUE TITLE
missing Observable import for visual studio

### ISSUE THREAD

**Issue by wizardnet972** [ReactiveX/rxjs#1696] opened 2016-05-09 05:06 UTC
In every *.d.ts under rx/add,
should add:
`import {Observable} from '../../Observable';`

for visual studio typescript compiler / intellisense compatibility.

**visual studio error message:**
Invalid module name in augmentation, module '../../Observable' cannot be found.

**for example:**
```
import { BufferSignature } from '../../operator/buffer';
declare module '../../Observable' {
    interface Observable<T> {
        buffer: BufferSignature<T>;
    }
}
```

**should be:**
```
import { BufferSignature } from '../../operator/buffer';
import {Observable} from '../../Observable';
declare module '../../Observable' {
    interface Observable<T> {
        buffer: BufferSignature<T>;
    }
}
```

based on https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#augmenting-globalmodule-scope-from-modules

**Comment by kwonoj** [comment] 2016-05-09 05:08
I don't think there's strong difference between visual studio to other editor configurations since compilation goes through typescript compiler. Would you be able to share what's tsc version and small code snippet able to reproduce issue?

**Comment by fedemarengo** [comment] 2016-05-09 07:53
Same issue and looks like same problem here: 
http://stackoverflow.com/questions/37030963/angular-2-2-0-0-rc-1-property-map-does-not-exist-on-type-observableresponse

**Comment by ZenSoftware** [comment] 2016-05-10 02:53
I wrote the following in a [different git repo](https://github.com/Reactive-Extensions/RxJS/issues/1226#issuecomment-218019827) (apparently it's was the wrong repo to discuss RxJS v5).

# Rx Operators Cannot Resolve Observable - Visual Studio 2015 & Typescript

There seems to be a problem with the node module resolutions with all the Rx operators in Visual Studio 2015.  No matter what I try, I can not seem to get rid of these typescript errors.  For example, when using the RxJS map operator within [Angular2 Quickstart](https://github.com/angular/quickstart/blob/master/README.md) package, Visual Studio complains:

**Severity**: Error
**Code**: TS2664
**Description**: Invalid module name in augmentation, module '../../Observable' cannot be found. TypeScript Virtual Projects
**Project File**: C:\Angular2-Quickstart\node_modules\rxjs\add\operator\map.d.ts
**Line**: 2

I have several other npm packages that my typescript project does not complain about.  Just the RxJS operators.  For some reason, when I browse to any type definition file under  _"node_modules\rxjs\add\operator"_ all of them are showing the above error on the line with 
`declare module '../../Observable' {`

My project compiles fine using both the typescript's CLI and Visual Studio's built in compiler, but I am getting a flood of these errors in Visual Studio's error window.  It also breaks Typescript's intellisense.  I have attempted to include a reference path to Rx.KitchenSink.  But I just get more of the same errors.  Unfortunately nothing seems to be solving this issue.
`/// <reference path="../node_modules/rxjs/Rx.KitchenSink.d.ts"/>`

My tsconfig.json:
```
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  }
```
  
My typings.json:
```
  "ambientDependencies": {
    "es6-shim": "registry:dt/es6-shim#0.31.2+20160317120654"
    ...
  }
```
I am using the latest version of everything:
Windows 10
Visual Studio Enterprise 2015: Version 14.0.25123.00 Update 2
Typescript Version: 1.8.30.0
npm package: "rxjs": "5.0.0-beta.7"  _(Errors also occurs with 5.0.0-beta.6)_
Node: v6.1.0  _(I don't think it is relevant, but also occurs on a system with Node v5)_

I have a second system with a similar setup, the errors also occur there.

**Comment by vladima** [comment] 2016-05-10 02:57
Please see [this thread](https://github.com/Microsoft/TypeScript/issues/8518) for a description of the issue and workaround

**Comment by ZenSoftware** [comment] 2016-05-10 02:59
@vladima You are a life saver.  Thanks.

**Comment by kwonoj** [comment] 2016-05-10 23:09
Appreciate for workaround @vladima . One of reason I switched from VS is about using typescript.. wish VS15 will enhance support. 

Let me close this issue for now since it's tooling environment, @wizardnet972, please reopen / create new issue if there's something unresolved.

**Closed by kwonoj** 2016-05-10 23:09 UTC
