### ISSUE TITLE
Does not build with typescript 2.4.1

### ISSUE THREAD

**Issue by AlexViderman** [ReactiveX/rxjs#2699] opened 2017-06-27 18:29 UTC
**RxJS version:** 
5.4.1

**Code to reproduce:**

**Expected behavior:**
No issues with typescript 2.3.4

**Actual behavior:**
Upgraded my Angular 4 to typescript 2.4.1 and getting the following error on build:

```
[at-loader] Checking finished with 2 errors

Error in bail mode: [at-loader] ./node_modules/rxjs/Subject.d.ts:16:22
    TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.
```

**Additional information:**
Using it with Webpack 3 (Tried with 2 as well, same issue)

**Comment by kwonoj** [comment] 2017-06-27 18:31
It's dupe of https://github.com/ReactiveX/rxjs/issues/2539 and we're working on to bump up compiler version, but probably with next major.

**Closed by kwonoj** 2017-06-27 18:31 UTC

**Comment by AlexViderman** [comment] 2017-06-27 18:39
@kwonoj thank you

**Comment by satyadev1** [comment] 2017-10-16 13:36
Try going to tsconfig.json file in your project and add in 
"compilerOptions":{

"skipLibCheck": true

}
This worked for me.
