### ISSUE TITLE
expand() behavior

### ISSUE THREAD

**Issue by luisgabriel** [ReactiveX/RxJS#1310] opened 2016-02-05 20:01 UTC
Code:
```javascript
Rx.Observable.of(1, 2)
  .expand(function (x) {
    return Rx.Observable.of(x * 2, x * 3);
  })
  .take(8)
  .subscribe(function (x) { console.log(x); });
```

RxJS 4 output:
```
1
2
2
3
4
6
4
6
```

RxJS 5 output:
```
1
2
4
8
16
32
64
128
RangeError: Maximum call stack size exceeded
```

It seems like RxJS 4 uses a breadth-first approach while RxJS 5 uses depth-first. Is this expected?

**Comment by blesh** [comment] 2016-02-05 20:17
It's scheduling.  RxJS 5 defaults to recursive scheduling, where RxJS 4 defaulted to trampoline scheduling. This change was made for reasons of performance and debugging, which our two of our primary goals with this library.

**Comment by blesh** [comment] 2016-02-05 20:19
I'll close this since there isn't really an issue... but feel free to reopen if that doesn't adequately address your concerns.

**Closed by blesh** 2016-02-05 20:19 UTC

**Comment by luisgabriel** [comment] 2016-02-05 20:29
As `expand()` in RxJS 4 defaults also to the immediate scheduler, I was not sure it this was a scheduling issue.

I think we should, at least, add some documentation on the migration guide about this. What do you think?

**Comment by blesh** [comment] 2016-02-05 22:38
`expand` does, but `of` might not. I haven't checked.

**Comment by blesh** [comment] 2016-02-05 22:39
Confirmed. `Observable.of` in RxJS 4 defaults to `currentThread` scheduler, which is our `queue` scheduler.

**Comment by luisgabriel** [comment] 2016-02-09 20:40
@blesh Indeed. Both `of` and `expand` is using `currentThread` as default scheduler in RxJS 4 (`expand` doc is not up-to-date).

But I'm still having trouble to reproduce RxJS 5 behavior in RxJS 4.

### RxJS 5
Code:
```javascript
Rx.Observable.of(1, 2)
  .expand(function (x) {
    return Rx.Observable.of(x * 2, x * 3);
  })
  .take(8)
  .subscribe(function (x) { console.log(x); });
```

Output:
```
1
2
4
8
16
32
64
128
"error"
"RangeError: Maximum call stack size exceeded
```

### RxJS 4
Code:
```javascript
Rx.Observable.ofWithScheduler(Rx.Scheduler.immediate, 1, 2)
  .expand(function (x) {
    return Rx.Observable.ofWithScheduler(Rx.Scheduler.immediate, x * 2, x * 3);
  }, Rx.Scheduler.immediate)
  .take(8)
  .subscribe(function (x) { console.log(x); });
```

Output:
```
1
2
2
3
4
6
4
6
"error"
"RangeError: Maximum call stack size exceeded
```

Am I missing something?

**Comment by trxcllnt** [comment] 2016-02-09 20:54
@luisgabriel The RxJS 4 `expand` implementation [uses a trampoline internally](https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/linq/observable/expand.js#L13), so even if you specify the recursive scheduler, the events will always be processed breadth-first.

**Comment by luisgabriel** [comment] 2016-02-12 00:10
Thanks, @trxcllnt. Now it makes sense. I'll point out issue #30 also that have some background about the trampoline vs recursive scheduling (it can be useful in the future if someone else ends up in this thread).

**Comment by luisgabriel** [comment] 2016-02-12 00:14
@blesh @trxcllnt Which other operators suffers from the same "problems"? I think it's worth to add a note on the [migration guide](https://github.com/ReactiveX/RxJS/blob/master/MIGRATION.md) to make the users aware of the differences.

**Comment by trxcllnt** [comment] 2016-02-13 03:02
@luisgabriel `expand` is the most glaring, but since the default scheduling strategy changed from trampolining to recursion, all synchronous operations between Rx 4 and 5 are affected. This switch is a large part of our performance gains, but there will be slight inconsistencies like this.
