### ISSUE TITLE
Recommended Approach for CombineLatest with a Scheduler?

### ISSUE THREAD

**Issue by thatcort** [ReactiveX/rxjs#5622] opened 2020-08-03 14:12 UTC
## Bug Report

**Current Behavior**
All definitions for the combineLatest observable that include a Scheduler are deprecated. What is the recommended way to ensure a breadth-first approach to computing all its dependencies before notifying subscribers?

**Reproduction**
See: https://github.com/ReactiveX/rxjs/blob/master/src/internal/observable/combineLatest.ts (v7)
or  https://github.com/ReactiveX/rxjs/blob/6.x/src/internal/observable/combineLatest.ts (v6)

**Expected behavior**
I'm not sure if this is a documentation issue or a code issue, but this seems like a necessary thing that should be possible without deprecation warnings.

**Environment**
- Angular 8 with RxJS 6, but this seems unchanged in v7

**Comment by cartant** [comment] 2020-08-05 01:32
IIRC, the recommendation would be to use `scheduled`. Something like this:

```ts
combineLatest(
  scheduled(of("a", "b"), queueScheduler),
  scheduled(of(1, 2), queueScheduler)
)
  .pipe(subscribeOn(queueScheduler))
  .subscribe(console.log);
```

However,  AFAICT, passing observable sources to `scheduled` does not effect the expected behaviour. ATM, I am not sure why.

Regarding the documentation, the deprecation-related documentation is a WIP and is currently being reviewed. The docs will contain explanations of deprecated APIs and alternatives - with examples.

**Comment by thatcort** [comment] 2020-08-05 14:02
I'm definitely confused by how to compose schedulers, scheduled and subscribeOn to ensure tiers of computation happen in sequence. Better documentation, examples or articles would go a long way.

**Comment by cartant** [comment] 2020-08-06 12:02
> ... also seems to be a difference between `subscribeOn` and `observeOn`

`subscribeOn` ensures that subscription happens on the specified scheduler and `observeOn` ensures that notifications are emitted on the specified scheduler.

Regarding the snippets in my comment, the equivalent of:

```js
combineLatest(
  of("a", "b", queueScheduler),
  of(1, 2, queueScheduler),
  queueScheduler
).subscribe(console.log);
```

would be:

```js
combineLatest(
  scheduled(["a", "b"], queueScheduler),
  scheduled([1, 2], queueScheduler)
).pipe(subscribeOn(queueScheduler).subscribe(console.log);
```

The reason this behaves the way it does is that the subscriptions are scheduled using the `queueScheduler` - via `subscribeOn` - and the notifications from the array sources are recursively scheduled upon subscription - see here https://github.com/ReactiveX/rxjs/blob/8f32ffe3dbfc722e0f5279762dc8475adbabaade/src/internal/scheduled/scheduleArray.ts#L9-L18

When the subscription scheduled by `subscribeOn` occurs, there are two sources passed to `combineLatest` are subscribed to and those subscriptions are also scheduled to run on the `queueScheduler` - so they don't happen until the subscription to the `combineLatest` observable returns. When the subscriptions to the `scheduled` sources are then made the first schedules a `next` with an `"a"` and the second schedules a `next` with a `1` - but those notifications don't happen until the subscribes return. In this way, the two sources continue to emit interleaved notifications.

Wrapping an observable source in `scheduled` doesn't effect the same behaviour because the notifications are not recursively scheduled - see here https://github.com/ReactiveX/rxjs/blob/8f32ffe3dbfc722e0f5279762dc8475adbabaade/src/internal/scheduled/scheduleObservable.ts#L11-L15

That is, with `scheduled(of("a", "b"), queueScheduler)` the notifications are all scheduled separately upon subscription. That means that with this snippet:

```js
combineLatest(
  scheduled(of("a", "b"), queueScheduler),
  scheduled(of(1, 2), queueScheduler)
).pipe(subscribeOn(queueScheduler).subscribe(console.log);
```

The string and number notifications are not interleaved, so the behaviour is different.

I'm closing this, as the question was about the recommended way of dealing with the deprecations. I'm doing so not because this isn't important - it is! - rather, work on this is already underway and, IMO, this is something that has to be addressed before v7 can be released.

**Closed by cartant** 2020-08-06 12:02 UTC

**Comment by thatcort** [comment] 2020-08-06 21:01
@cartant Thanks for the thoughtful replies. I'm still confused, though... Apologies for asking for more of your time and I realize this is a digression from the deprecation issue, but here's a concrete example similar to what I'm trying to achieve:

Suppose we have a common source `a$ = interval(1000)` piped as follows: `combineLatest(a$.pipe(map(d => d * 2)), a$.pipe(map(d => d * 3))).map(([x, y]) => x + y)` is it possible to ensure that for every time `a$` fires, the `combineLatest` only fires once?

**Comment by cartant** [comment] 2020-08-07 00:08
@thatcort IDK how well your `combineLatest` snippet describes what it is that you are actually trying to do. Essentially, you are wanting `combineLatest` to behave in a manner contrary to its implementation. It's supposed to emit separate notifications. Using `subscribeOn` or `observeOn` is not going to change that.

In situations in which all sources are derived from a shared source - `a$`, in your snippet - and all sources emit a single notification derived from `a$`'s notification, `zip` would be more appropriate.

If that's not the case, you could use `debounce(0, asapScheduler)` after the `combineLatest` to debounce notifications that are emitted from `combineLatest` within a single turn through the event loop.

**Comment by thatcort** [comment] 2020-08-07 13:41
@cartant Thanks for the suggestion. Yes, zip would work in the example I gave. In my app there is a common source, but there are distinctUntilChanged checks before the combineLatest, so I can't be sure that all the inputs will fire for every update of a$. Thank you greatly for all your input. I'm slowly developing a better understanding of when schedulers are helpful and when they aren't. For my actual problem, I think I need to try a different approach.

**Comment by JontyMC** [comment] 2021-06-08 08:49
@thatcort did you come up with a different approach? We are hitting this issue and are just using a combineLatest with auditTime(0), was wondering whether there was a better way, as this approach doesn't work if one of the chain of observables also uses auditTime(0). I guess fundamentally this is a tricky issue to solve, because downstream you have no way of knowing if the changes were caused by a single upstream update. I did think perhaps if some data were added to the emissions so we could track what "version" the changes came from, then it might be possible to group the changes, however you don't know when you've got the last emission from the current change. Maybe a custom scheduler based on the source observable somehow?

**Comment by JontyMC** [comment] 2021-06-08 09:55
Having just re-read my own question, I think it makes sense to base the changes from the source. Something like this (not sure about naming):

```javascript
export function breadthFirstFromSource<T>(source: Observable<any>, observables: ObservableInput<T>[]): Observable<T[]> {
  return source.pipe(
    withLatestFrom(...observables),
    map(([_, ...rest]) => rest),
    distinctUntilChanged((x, y) => x.every((z, i) => z === y[i])),
  )
}
```

Is this the best way to solve this use case?

For your example above:

https://stackblitz.com/edit/combinelatest-breadthfirst-tdqurw?file=index.ts

**Comment by thatcort** [comment] 2021-06-10 20:11
Hi @JontyMC. I didn't end finding a fix and instead rewrote that code to track dependencies manually.
