### ISSUE TITLE
Compile errors with TS 2.4

### ISSUE THREAD

**Issue by felixfbecker** [ReactiveX/rxjs#2707] opened 2017-06-28 22:27 UTC
**RxJS version:** 5.4.1

Importing rxjs in TS 2.4 gives this error:
```
node_modules/@reactivex/rxjs/dist/cjs/Subject.d.ts(16,22): error TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.
node_modules/@reactivex/rxjs/dist/cjs/observable/dom/WebSocketSubject.d.ts(24,22): error TS2415: Class 'WebSocketSubject<T>' incorrectly extends base class 'AnonymousSubject<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => WebSocketSubject<R>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<T>'.
      Type 'WebSocketSubject<R>' is not assignable to type 'Observable<T>'.
        Types of property 'operator' are incompatible.
          Type 'Operator<any, R>' is not assignable to type 'Operator<any, T>'.
            Type 'R' is not assignable to type 'T'.
```

**Comment by kwonoj** [comment] 2017-06-28 22:34
dupe of #2699 , #2539, #2700 . #2701 #2702 #2703 https://github.com/ReactiveX/rxjs/issues/2704 https://github.com/ReactiveX/rxjs/issues/2705 https://github.com/ReactiveX/rxjs/issues/2706

**Closed by kwonoj** 2017-06-28 22:34 UTC

**Comment by felixfbecker** [comment] 2017-06-28 22:36
Sorry, only looked through open issues

**Comment by kwonoj** [comment] 2017-06-28 22:37
One issue is opened for tracking purpose. Rest of them are closed by dupe.
