### ISSUE TITLE
Class 'Subject<T>' incorrectly extends base class 'Observable<T>'

### ISSUE THREAD

**Issue by DudaevAR** [ReactiveX/rxjs#2718] opened 2017-07-02 21:02 UTC
**RxJS version:** 5.4.1

**Code to reproduce:** lift<R>(operator: Operator<T, R>): Observable<T>

**Actual behavior:** 
ERROR in .../node_modules/rxjs/Subject.d.ts (16,22): Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.

**Additional information:** You should replace on:
lift<R>(operator: Operator<T, R>): Observable< R >

**Comment by paulpdaniels** [comment] 2017-07-03 00:44
Duplicate of #2539

**Closed** 2017-07-05 00:03 UTC
