### ISSUE TITLE
7.0 bug, second switchMap gets executed hundreds of time initially

### ISSUE THREAD

**Issue by Evertt** [ReactiveX/rxjs#6167] opened 2021-03-22 16:31 UTC
## Bug Report

The code:

```typescript
import { defer, BehaviorSubject, of } from "rxjs";
import { shareReplay, switchMap } from "rxjs/operators";

const oneRandomNumber = defer(() => of(Math.floor(Math.random() * 20)));

const cache = { key: oneRandomNumber.pipe(shareReplay(1)) };

export const swr = () =>
  new BehaviorSubject(null).pipe(
    switchMap(() => cache.key),
    switchMap((number) => {
      console.log(number); // This logs hundreds of times on initial load
      return cache.key;
    })
  );

swr().subscribe();
```

[Link to demo](https://codesandbox.io/s/flamboyant-sky-np06v?file=/src/index.ts)

**Current Behavior**
I expect to see one log of a random number between 0 and 19.

**Expected behavior**
I see hundreds of logs those random numbers.

**Comment by josepot** [comment] 2021-03-22 17:05
I've narrowed down the issue. It's a problem with `shareReplay` with sync sources. When a second subscription gets created right after the observable has emitted the first value and before it has completed, then it re-subscribes to the source, rather than returning the latest emitted value.

For instance, the following snipped works perfectly fine:

```ts
import { Observable } from "rxjs";
import { shareReplay } from "rxjs/operators";

const source$ = new Observable(subscriber => {
  const token = setTimeout(() => {
    subscriber.next(Math.random());
    subscriber.complete();
  }, 0);

  return () => {
    clearTimeout(token);
  };
});

const randomNumber$ = source$.pipe(shareReplay(1));

randomNumber$.subscribe(x => {
  console.log(x);
  randomNumber$.subscribe(x => {
    console.log(x);
  });
});
```

However, this would likely hang your browser:

```ts
import { Observable } from "rxjs";
import { shareReplay } from "rxjs/operators";

const source$ = new Observable(subscriber => {
  subscriber.next(Math.random());
  subscriber.complete();
});

const randomNumber$ = source$.pipe(shareReplay(1));

randomNumber$.subscribe(x => {
  console.log(x);
  randomNumber$.subscribe(x => {
    console.log(x);
  });
});
```

And this also works fine:

```ts
import { Observable } from "rxjs";
import { shareReplay } from "rxjs/operators";

const source$ = new Observable(subscriber => {
  const token = setTimeout(() => {
    subscriber.next(Math.random());
    subscriber.complete();
  }, 0);

  return () => {
    clearTimeout(token);
  };
});

const randomNumber$ = source$.pipe(shareReplay(1));

randomNumber$.subscribe({
  next: x => {
    console.log(x);
  },
  complete: () => {
    randomNumber$.subscribe(x => console.log(x));
  }
});
```

**Comment by josepot** [comment] 2021-03-22 17:38
I went to fix this, but it turns out that @cartant beat me to it on #6151 .

**Comment by cartant** [comment] 2021-03-22 21:15
Closing as a (far-from-obvious) dupe of #6144.

**Closed by cartant** 2021-03-22 21:15 UTC
