### ISSUE TITLE
Implement join operator

### ISSUE THREAD

**Issue by trxcllnt** [ReactiveX/rxjs#1341] opened 2016-02-13 01:24 UTC
https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/join.md

**Comment by luisgabriel** [comment] 2016-02-13 03:42
@trxcllnt I can try to implement this one if you're not doing it already.

**Comment by trxcllnt** [comment] 2016-02-13 03:49
@luisgabriel go for it!

**Comment by benlesh** [comment] 2018-04-02 16:47
I'm going to close this for now. Given that with pipeable operators it's so easy for users to implement their own operators, and there's been very limited interest in implementing this particular operator.

**Comment by benlesh** [comment] 2018-04-02 16:48
Well, we did have #2194... if we can update that to the new repo structure, we can add it I suppose. :thinking: ... reopening

**Comment by BioPhoton** [comment] 2019-10-04 00:14
Hi @trxcllnt. As the issue is very old and nobody asked for it I kindly suggest to close it.

Please let me know if this also your opinion.

**Closed** 2019-10-04 00:31 UTC
Labels: type: discussion
