### ISSUE TITLE
tap operator incorrectly infers element type sometimes

### ISSUE THREAD

**Issue by Nachasic** [ReactiveX/rxjs#4114] opened 2018-09-07 16:26 UTC
## Bug Report
When inferring element type as the result of the `pipe`, last `tap` operator in pipe chain incorrectly infers element type from the expected type.

**Reproduction**
Since `EffectMap` expects each property to return `Subscribable` with `any` arbitrary element type, the last `tap` seems to pick up this `any` type instead of the element type from the input observable.

```typescript
type EffectMap = { [key: string]: Subscribable<any> };
type EffectBuilder<T> = {
    [key: string]: (stream: Observable<T>) => EffectMap
}
function factory<T>(spec: EffectBuilder<T>) { return false }

const thing = factory<number>({
   foo: stream$ => ({ // stream$ is Observable<number>
       BAR: stream$.pipe(
           tap(value => console.log(value)), // value is any instead of number
           // tap() // Uncommenting this will fix the issue for the first tap, but not the last
       )
   })
})
```

**Expected behavior**
`tap` operator propagates strong typings for values

**Environment**
- Runtime: Node v10.0.0
- RxJS version: 6.3.2
- Typescript version: 3.0.3

**Comment by cartant** [comment] 2018-09-09 02:07
This appears to be a TypeScript issue/bug.

Firstly, the return type of `tap` is inferred correctly in this scenario:

```ts
declare const s: Observable<number>;
const r = s.pipe(tap(value => console.log(value))); // Observable<number>
```

Secondly, if `map` is used - in the issue snippet - the return type is inferred correctly.

The difference is that the return type of `map`'s project function - `R` - is used in the operator's return type of `OperatorFunction<T, R>`. If the signatures of `tap` are messed with so that its `next` is replaced with a project function, the type is inferred correctly.

IMO, this is a TypeScript bug that's exposed by the more complicated inference scenario in the issue's snippet.

**Comment by cartant** [comment] 2018-09-09 05:49
The problem is the use of `Subscribable<any>` in `EffectMap`. That sees the `value` within `tap` inferred as any.

The same problem can be seen here:

```ts
declare const s: Observable<number>;
const r: Observable<any> = s.pipe(
  tap(value => console.log(value)) // value is inferred to be any
);
```

The problem does not occur with `map` because its return type is inferred from the `project` function's return type. That is, there's no need for `value` to be inferred from what's on the left-hand side of the assignment.

And it does not happen if an additional `tap` is added, because it's only the `value` in the *last* operator that's inferred from what's on the left-hand side of the assignment.

I don't think there's anything that can be done in RxJS to address this.

**Comment by cartant** [comment] 2018-09-27 11:48
Closing this, as I don't see that there is anything that can be done within RxJS to address the issue.

**Closed by cartant** 2018-09-27 11:48 UTC
