### ISSUE TITLE
Possible regression with "this" when subscribing.

### ISSUE THREAD

**Issue by Foxandxss** [ReactiveX/rxjs#2785] opened 2017-08-06 21:58 UTC
**RxJS version:**

5.3.0+

**Code to reproduce:**

http://plnkr.co/edit/73mzroEGzPflQbDW6epw

![](http://i.imgur.com/TB0922S.png)

**Expected behavior:**

If you swap to this [plunker](http://plnkr.co/edit/vMwp53hQ7CmMGnX6bAw1?p=preview) which uses 5.2.0 you can see instead:

![](http://i.imgur.com/rsVq0fE.png)

**Additional information:**

Sorry for the lack of information on the subject, not sure how I should explain it.

I am following a tutorial where you implements Observer in a class and then you subscribe like `foo$.subscribe(this);`.

In 5.2.0, if you log out "this" you can see all the class attributes, but from 5.3.0+ you don't.

**Comment by kwonoj** [comment] 2017-08-06 22:33
dupe of https://github.com/ReactiveX/rxjs/issues/2525.

**Closed by kwonoj** 2017-08-06 22:33 UTC
