### ISSUE TITLE
Issue with ReplaySubject as a subscriber when delay() is used (Beta.0)

### ISSUE THREAD

**Issue by TylorS** [ReactiveX/RxJS#1076] opened 2015-12-15 21:10 UTC
When using a ReplaySubject as a subscriber to another Observable, if `.delay()` is used in the Observable sequence the ReplaySubject never recieves any values.

Working verison without `delay()` - http://jsbin.com/gezaqe/85/edit
Non-working version with `delay()` - http://jsbin.com/gezaqe/edit?html,js,console

**Comment by staltz** [comment] 2015-12-16 14:52
@TylorS is this a JSBin problem? I wasn't able to reproduce it. The "non-working" worked for me after I refreshed, cleared, and ran it.

I also don't see how is this related to ReplaySubject.
```js
var number$ = Rx.Observable.fromArray([1, 2, 3])
  .concatMap(x => Rx.Observable.of(x).delay(500))
var replicatedNumber$ = new Rx.ReplaySubject(1)


replicatedNumber$.subscribe(x => {
  console.log(replicatedNumber$.isUnsubscribed)
  if (x === 2) {
    replicatedNumber$.unsubscribe()
  }
})

number$.subscribe(replicatedNumber$)

// This subscription is what matters for console.log output
// Other subscriptions, such as the one above, should be
// impossible to affect this subscription. number$ is a cold
// Observable and should work when subscribed.
number$.subscribe(x => console.log('number$: ' + x))
```

**Comment by TylorS** [comment] 2015-12-16 15:11
I'm having a similar problem in a codebase as well. I could be wrong, but I felt my issue is with the ReplaySubject I'm trying to use to replicate the number$. I apologize, I wasn't very clear in my description of the issue.

I'm currently having no issues receiving values from number$ in either version, but replicatedNumber$ never logs it's values when `delay()` is present in the concatMap attached to `number$`. However, it will log `--false--false--|` when `delay()` is removed from `number$`

**Comment by staltz** [comment] 2015-12-16 15:28
Ok, now I can reproduce it. The minimal code to reproduce it is:

```js
const number$ = Rx.Observable.of(1, 2, 3).delay(500);
const subject = new Rx.Subject();
subject.subscribe(x => console.log(x));
number$.subscribe(subject);
```

**Comment by TylorS** [comment] 2015-12-16 15:40
I can confirm that your example causes the same issue. http://jsbin.com/gezaqe/91/edit?html,js,console

**Comment by staltz** [comment] 2015-12-16 16:17
I think I figured the root cause.
@blesh seems to be shared subscriber issue again.

When `Observable.of(1,2,3)` completes, it unsubscribes, and those delayed message actions that were scheduled to happen (from the delay operator) will be cancelled. That's what I witnessed when looking at the debugger, although I'm curious why it didn't happen when I subscribe directly to `Rx.Observable.of(1, 2, 3).delay(500)`. Could be related to how Subject handles or is handled as the base Subscriber.

**Comment by blesh** [comment] 2015-12-17 08:27
Yeah. I'm going to try to prioritize refactoring the subscriber scheme in another branch over the holidays. I was just talking with @trxcllnt about this this afternoon.

**Comment by staltz** [comment] 2015-12-17 08:44
We can label this issue as bug.

**Comment by kwonoj** [comment] 2015-12-17 08:45
Marked as bug.

**Comment by blesh** [comment] 2015-12-23 19:00
The fixes for this bug should be covered in the changes @trxcllnt made over the last few days. I'd expect that PR to show up and land very shortly.

@trxcllnt, are there tests covering this bug, by chance? I'm fairly certain the changes to the Subscription scheme will fix the issue, but I'd like to be sure before I can close this after your changes are merged.

**Comment by trxcllnt** [comment] 2015-12-23 21:27
@blesh just ran the minimal test as a script on my local machine and it worked (printed values 1, 2, 3 after 500ms).

**Comment by blesh** [comment] 2016-01-15 20:49
@TylorS is this still an issue for you in `beta.1`? I believe this was resolved as of #1127 at the latest. Closing for now..

**Closed by blesh** 2016-01-15 20:49 UTC
Labels: type: bug

**Comment by TylorS** [comment] 2016-01-15 20:56
Seems to be working now @blesh 
Thank you!

**Comment by blesh** [comment] 2016-01-15 21:30
Great! I'm glad to hear it, @TylorS!
