### ISSUE TITLE
Duplicate entries in Observable documentation

### ISSUE THREAD

**Issue by camden-kid** [ReactiveX/rxjs#3637] opened 2018-05-04 12:42 UTC
At http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html there are many duplicate entries as can be seen in the example image:

![image](https://user-images.githubusercontent.com/890197/39628310-952891b8-4fa0-11e8-90b5-c2e9c2f7da7b.png)

**Comment by cartant** [comment] 2018-05-04 12:59
Duplicate of #3526.

**Closed** 2018-05-04 13:00 UTC
