### ISSUE TITLE
Add Equivalent to RxJava "Single"

### ISSUE THREAD

**Issue by sawthompson** [ReactiveX/rxjs#3424] opened 2018-03-12 17:57 UTC
I am currently working on a large project using Angular and rxjs, and my team has run into a number of bugs that could be avoided if we had an equivalent to RxJava's [Single](http://reactivex.io/documentation/single.html).

I think the Single is particularly important for Angular apps, because Angular's HttpClient RPCs return Observables that always complete after a single emission or error (aka, they are untyped Singles).

This leads to developers falsely assuming certain Observables are Singles. If HttpClient methods returned Singles instead, developers would no longer have to guess at the underlying source for an Observable.

If anyone is interested I am happy to provide some more specific examples of how this has caused problems for my team.

**Comment by kwonoj** [comment] 2018-03-12 17:59
Closing as dupe of https://github.com/ReactiveX/rxjs/issues/2469 . We are encouraging user-level custom implementation except if there's strong reason to be included in core.

**Closed by kwonoj** 2018-03-12 17:59 UTC
