### ISSUE TITLE
SwitchMap on forkJoined observable

### ISSUE THREAD

**Issue by sumigoma** [ReactiveX/rxjs#1392] opened 2016-02-26 00:01 UTC
I have an array of observables (ng2 http requests) that I would like to cancel simultaneously using switchMap, but I'm finding that wrapping a forkJoin in switchMap doesn't cause the inner observables to get unsubscribed and hence cancelled. (Obviously, this works if there is no forkJoin).

Is there a recommended way of doing something like this? and in general, would unsubscribing from a forkJoined observable cause the inner observables to be disposed as well?

**Comment by kwonoj** [comment] 2016-02-26 02:36
Maybe I'm saying dumb without knowing full picture, but is there specific reason to wrap observables with forkJoin? forkJoin's supposed to wait all provided observable completes and take last emitted value.

**Comment by sumigoma** [comment] 2016-02-26 08:09
The number of observables (ajax calls) I have is variable in my particular use case, and I thought forkJoin might be a way to cancel all of them at once (without having to have a handle to each one with a switchMap on each). If a switchMap is on a forkJoin, is it true that it has no way of completing/cancelling the wrapped observables? 

This may not be the right approach to this problem, but the alternative of keeping a dynamic array of observables seems sloppy (e.g. if I have ten ajax calls being made and the next "refresh" cycle has nine, I'd like to cancel all ten before moving on). Is switchMap not the right operator to use here?

**Comment by kwonoj** [comment] 2016-02-26 15:46
I'd still consider switchMap to get expected behavior, without involving forkJoin. It maybe helpful if you could share small snippet to replicate situation.

**Comment by trxcllnt** [comment] 2016-02-26 21:35
@sumigoma you're right, from what I can tell [here](https://github.com/ReactiveX/RxJS/blob/master/src/observable/ForkJoinObservable.ts#L39) forkJoin isn't keeping track of its inner subscriptions. @kwonoj @blesh this is certainly a bug and should be addressed asap.

**Comment by sumigoma** [comment] 2016-02-27 07:33
Thank you @kwonoj, I could share a snippet but I'm not sure how helpful it would be. If switchMap was able to cancel the inner subscriptions of a forkJoin, I could cancel numerous calls without having to keep a handle on each observable. e.g. If I have N ajax requests and I want to cancel all of them, but N is variable, the forkJoin would help me immensely.

@trxcllnt Thanks, I wasn't sure if this was by design or not.

**Comment by jonnydevlive** [comment] 2016-03-13 04:36
@trxcllnt does this mean that forkJoin isn't currently working? It suddenly stopped working for more as I upgraded my version of angular 2. Created a plunkr at http://plnkr.co/edit/zat8rfB0KqZtXeo1tvWS?p=preview to demonstrate what I'm trying to do.

**Comment by trxcllnt** [comment] 2016-03-13 05:08
@jonnydevlive from what I can tell, forkJoin works in the sense that it subscribes to the inner Observables, but it's broken because it doesn't unsubscribe from the inner Observables when it should. I'll work to get a fix in shortly.

**Comment by kwonoj** [comment] 2016-04-06 06:28
Closed via https://github.com/ReactiveX/rxjs/pull/1462.

**Closed by kwonoj** 2016-04-06 06:28 UTC
Labels: type: bug
