### ISSUE TITLE
"Cannot find module" errors with 5.5.0-beta.0

### ISSUE THREAD

**Issue by cartant** [ReactiveX/rxjs#2854] opened 2017-09-24 00:04 UTC
I've encountered a problem that seems to be related to the new package structure in 5.5.0-beta.0.

After updating to the beta (the only change made) my CI build is failing. For some reason, TSLint is failing when performing type-checked linting of a project that uses the beta, claiming that it cannot find numerous modules.

Strangely, this only seems to happen on Linux. The linting and tests are fine on my Windows and Mac computers.

Whether this is a TSLint issue or an RxJS beta issue is, at the moment, unclear.

**RxJS version:** 5.5.0-beta.0

**Code to reproduce:**

The TSLint command used to lint [the project](https://github.com/cartant/rxjs-etc/tree/lettable) is:

    tslint --project tsconfig.json --type-check source/**/*.ts

**Expected behavior:**

I would expect no errors to be effected.

**Actual behavior:**

See this [Travis log](https://travis-ci.org/cartant/rxjs-etc/builds/279073783). Errors like the following are effected:

    Error at source/let/debounceAfter.ts:8:24: Cannot find module 'rxjs/observable/concat'.

**Comment by kwonoj** [comment] 2017-09-24 00:05
This seems somewhat related with https://github.com/ReactiveX/rxjs/pull/2853.

I talked with @benlesh around this kind issues this morning, trying to isolate root cause for this.

**Comment by cartant** [comment] 2017-09-24 00:08
@kwonoj Thanks for the fast response. I'm going to have a closer look at this later today. Hopefully, it won't be too hard to find the problem.

**Comment by cartant** [comment] 2017-09-24 00:31
It's because there is no `operator` directory in the distribution. The actual directory name has an uppercase `O`. Changing this to a lowercase `o` fixes the operator-related errors.

However, there is also a problem with the `Observable` directory that is not as easily fixed. That directory is used with a lowercase `o` for imports like:

```ts
import { concat } from "rxjs/observable/concat";
```
But it's also used with an uppercase `O` for imports like:

```ts
import { Observable } from "rxjs/Observable";
```

The latter is resolved using the `rxjs/Observable/package.json` file in the distribution.

Clearly, renaming the `Observable` directory to `observable` will break the latter (on case-sensitive file systems).

**Comment by cartant** [comment] 2017-09-25 01:17
There is similar problem with the `Scheduler` directory in the beta. In the previous distribution, it was a file with an uppercase `S` and a directory with a lowercase `s`.

Short of using a `postinstall` script to create lowercase copies of the uppercase `Observable` and `Scheduler` directories, I don't see how this change to the distribution could be made non-breaking.

**Comment by kwonoj** [comment] 2017-09-25 01:18
>  I don't see how this change to the distribution could be made non-breaking.

It is reason 5.5 has released as `beta`, instead of public to avoid breaking public release without major semver. Does any of in-range public update automatically upgrades into 5.5b?

**Comment by cartant** [comment] 2017-09-25 01:39
@kwonoj

> It is reason 5.5 has released as beta, instead of public to avoid breaking public release without major semver. Does any of in-range public update automatically upgrades into 5.5b?

I understand that it's a beta and that's fine. The process is working as it should.

I would not expect any consumers to be automatically upgraded to the beta, as the semver is a pre-release. I've certainly not seen any automatic upgrades.

My comment was referring to whether it would be possible for the new packaging mechanism to be used in a non-breaking 5.5 non-beta release. And without using a `postinstall` script on case-sensitive file systems, I don't think it would be. Whether or not you would countenance such a thing, I don't know.

**Comment by kwonoj** [comment] 2017-09-25 01:43
yeah, I actually deleted the comment as I came to think I misunderstood question 😓 apologize.

> My comment was referring to whether it would be possible for the new packaging mechanism to be used in a non-breaking 5.5 non-beta release. 

Is there specific reason you're thinking it is not possible? I may not be able to fully answer this question though.

**Comment by cartant** [comment] 2017-09-25 02:07
No worries.

I don't think it's possible as there will be existing code with imports like this:

```ts
import { Observable } from "rxjs/Observable";
import { Scheduler } from "rxjs/Scheduler";
```

and like this:

```ts
import { timer } from "rxjs/observable/timer";
import { async } from "rxjs/scheduler/async";
```

With the first group of imports, the directories have an uppercase initial letter and, with the second, a lowercase initial letter. So, on case-insensitive file systems, there will need to be two directories. (It's the second group of imports that break in the beta, as there is no `observable` directory, etc.)

Unless it's possible to prepare an npm package that includes directories that differ only in case, the only non-breaking solution I can see would be to use a `postinstall` script that creates lowercase copies of the directories on case-sensitive file systems. Which sounds ... unpleasant.

This wasn't a problem in the previous release because the uppercase imports mapped to `.d.ts` files and the lowercase imports mapped to directories. But with the new mechanism, both are directories.

**Comment by benlesh** [comment] 2017-09-25 14:15
Yeah. this was part of an attempt to get better tree-shaking and bundling with webpack and/or rollup. It might be that we have to roll this change back and punt until a 6.0 release, as it might require breaking changes. :\

i've been unable to reproduce this issue thus far, but I was a little worried this might happen. cc @jasonaden @IgorMinar

**Comment by IgorMinar** [comment] 2017-09-25 18:57
My hypothesis based on what I see in logs/npm: both Windows and Mac has it's default filesystem to be case-insensitive (but case preserving), whereas Linux is by default case-sensitive.

This means that resolving `rxjs/observable/of` will fail on Linux if the `of` static helper is located in `rxjs/Observable/of`directory as is the case today.

As long as we want to support importing from both `rxjs/Observable` and `rxjs/observable/*`, we'll need to have two directories with different case present on the filesystem on linux, but on other case-insensitive filesystems the two directories would have to be merged into one.

@jasonaden says that he felt like we worked around all these issues because the rxjs test suite was passing after he made some adjustments due to this problem, but I think we missed something and should double check how this stuff is actually tested within the rxjs test suite.

**Comment by jasonaden** [comment] 2017-09-25 20:00
I'm testing this a bit more. TypeScript isn't resolving modules referenced as `rxjs/observable/*` to our `/Observable` directory. And it does appear to be a casing issue as I created a symlink from `/observable` to `/Observable` (and the same for Observer) and the Angular build that was previously failing now works.

**Comment by jasonaden** [comment] 2017-09-26 00:21
Looking into this more, there seems to be a solution that works. A few options were discussed before coming to this solution:

* Using a `symlink` in Linux as mentioned above. This is a bit of an ugly solution and may not work with tools such as unpkg.com.
* Copying files to the right place (case-sensitive directory names) after install. This is also not a good solution as it modifies the directory after install (not allowed for some corporations) and wouldn't work with unpkg.com.

Since neither of these solutions will work, I tried running the build on a case-sensitive operating system, then publishing from there to NPM. [Here](https://unpkg.com/rxjs-test@5.5.0-beta.0/) is my test I published showing that unpkg.com will work. I `npm install`ed on Linux, Mac and Windows. On Linux we get the case sensitive directory names and builds against Rx work. On Mac and Windows the directories are merged, and everything works.

So I think the solution, if we want to get this packaging update out, is to build on a case sensitive OS and publish from there. I would like to at least push out a `beta.1` this way and see if that fixes the current issues we're having testing the beta.

**Comment by intellix** [comment] 2017-09-26 10:22
I didn't want to say anything before beta.1 but didn't want to not say nothing either in case it's not related :) But with beta.0 I'm also getting errors from ng about the inability to find modules even with the uppercased O:

```
ERROR in /Sites/angular-cli-blue/node_modules/@angular/router/src/router.d.ts (10,28): Cannot find module 'rxjs/Observable'.
ERROR in /Sites/angular-cli-blue/node_modules/@angular/core/src/event_emitter.d.ts (8,25): Cannot find module 'rxjs/Subject'.
```

Not sure I was getting this yesterday as it was mostly errors about o -> O

**Comment by cartant** [comment] 2017-09-27 21:58
With 5.5.0-beta.1 and 5.5.0-beta.2, my Travis builds are now fine. Thanks.

**Closed** 2017-09-27 22:05 UTC
Labels: status: more information needed, type: bug

**Comment by aitboudad** [comment] 2017-09-28 00:49
The bundle size gets significantly larger `57kb` -> `119kb`!, maybe related to #2812 ?
