### ISSUE TITLE
Add second type parameter for error stream in Observables et all.

### ISSUE THREAD

**Issue by Drundia** [ReactiveX/rxjs#5354] opened 2020-03-16 12:04 UTC
## Feature Request

Currently notification coming on error stream are of `any` type. Here I request the addition of type parameter(s) to related classes to specify the type of values delivered on error stream.

**Is your feature request related to a problem? Please describe.**
Impossible to describe the types of error notifications in simple signature format.
Impossible to use type checking to verify that producer and consumer agree on the types of error notifications.

**Describe the solution you'd like**
Addition of type parameters for error stream as necessary.

**Describe alternatives you've considered**
It's possible to ignore the error stream altogether and deliver everything on the next stream and embed notification kind there. But it seems dirty.

**Comment by cartant** [comment] 2020-03-16 12:08
Closing as a dupe of #2646.

**Closed by cartant** 2020-03-16 12:08 UTC
