### ISSUE TITLE
Problem with SchedulerLike

### ISSUE THREAD

**Issue by mailok** [ReactiveX/rxjs#4850] opened 2019-06-10 17:44 UTC
## Bug Report

**Environment**
- Nodejs 12.4.0
- Chrome 74.0.3729.169 (Official Build) (64-bit)
- @angular-devkit/architect  0.800.2
- @angular-devkit/build-angular  0.800.2
- @angular-devkit/build-optimizer 0.800.2
- @angular-devkit/build-webpack 0.800.2
- @angular-devkit/core 8.0.2
- @angular-devkit/schematics  8.0.2
- @angular/cli   8.0.2
- @ngtools/webpack  8.0.2
- @schematics/angular  8.0.2
- @schematics/update  0.800.2
- rxjs 6.5.2
- typescript 3.4.5
- webpack  4.30.0

**Current Behavior**
What happens is that I updated my project from Angular 7 to Angular 8, and running the project gives me this error

**Additional context/Screenshots**
![Captura](https://user-images.githubusercontent.com/3769277/59214790-c98ec900-8b85-11e9-8174-3ec543c571a1.PNG)

**Comment by kwonoj** [comment] 2019-06-10 17:49
in your node_modules, is there any multiple version of rxjs installed?

**Comment by mailok** [comment] 2019-06-10 17:57
@kwonoj  I suppose not, this is my folder rxjs in node_modules:
![Captura1](https://user-images.githubusercontent.com/3769277/59215603-a107ce80-8b87-11e9-908a-15109e01c51c.PNG)
![Captura2](https://user-images.githubusercontent.com/3769277/59215604-a1a06500-8b87-11e9-8b09-d0bff20d232f.PNG)

**Comment by kwonoj** [comment] 2019-06-10 18:10
That only shows direct dep. What happens if you search all phsyical files / and `npm ls rxjs` both?

**Comment by mailok** [comment] 2019-06-10 18:35
@kwonoj  I get this, but I do not know how to interpret it

![Captura](https://user-images.githubusercontent.com/3769277/59217859-e24ead00-8b8c-11e9-8b6d-46bb1f06a894.PNG)

**Comment by kwonoj** [comment] 2019-06-10 19:03
So this is dupe of https://github.com/ReactiveX/rxjs/issues/4818 by having multiple versions of rxjs installes. You should have identical versions across, and as discussed in linked issue make sure devdeps you have bumps up version of rxjs to latest before you upgrade it.

**Closed by kwonoj** 2019-06-10 19:03 UTC
