### ISSUE TITLE
Observer don't add other function 

### ISSUE THREAD

**Issue by fukai007** [ReactiveX/rxjs#2738] opened 2017-07-11 08:49 UTC
**RxJS version:**
5.2.0
**Code to reproduce:**
```
var observer = {
			  next: x => {
                               // now  this  is  window
			  	console.log('Observer got a next value: ',x);
                                 this.callA()
                                 this.callB()
			  },
			  error: err => console.error('Observer got an error: ' + err),
			  complete: () => console.log('Observer got a complete notification'),
			  callA: x => console.log("callA------>"+x), 不能执行 -->window  bind绑定也不行
			  callB: x => console.log("callB------>"+x) 不能执行 -->window  bind绑定也不行
		};

		
		var observable = Rx.Observable.create(function (observer) {
		  observer.next(o);
		  setTimeout(() => {
		    observer.next(o);
		    observer.complete();
		  }, 1000);
		});
		
		observable.subscribe(observer);
```
**Expected behavior:**

**Actual behavior:**

**Additional information:**

**Comment by mpodlasin** [comment] 2017-07-11 10:16
If the mistake is that observer fails to call `callA` and `callB`, it is because you use arrow function - in that case `this` does not point to the observer itself. Rewrite `next` method to regular function, for example `next() { ... }` in ES6 or `next: function() { ... }` in ES5.

**Comment by kwonoj** [comment] 2017-07-11 13:38
I think this is dupe of https://github.com/ReactiveX/rxjs/issues/2525.

**Closed by kwonoj** 2017-07-11 13:38 UTC

**Comment by fukai007** [comment] 2017-07-13 04:34
Thank @mpodlasin & @kwonoj  , I find out.  this is my new code 
```
		let o = {
			a:100,
			b:200,
			c:300
		}
		/*
		 	 now   this is  observer and  next can call callA and callB function .don't use arrow function

		 * */
		var observer = {
			  next:function(x){
			  	console.log('Observer got a next value: ',x);
			  	this.callA(x);
			  	this.callB(x);
			  },
			  error: err => console.error('Observer got an error: ' + err),
			  complete: () => console.log('Observer got a complete notification'),
			  callA:function(x){console.log("callA------>"+x)},
			  callB:function(x){console.log("callB------>"+x)},
		};

		
		var observable = Rx.Observable.create(function (observer) {
		  observer.next(o);
		  observer.next(2);
		});
		
		observable.subscribe(observer);
```
