### ISSUE TITLE
Incompatibility v5.4.1 with Typescript 2.4: Type 'T' is not assignable to type 'R'

### ISSUE THREAD

**Issue by AlainD-** [ReactiveX/rxjs#2712] opened 2017-06-29 22:53 UTC
**RxJS version:**
5.4.1

**Code to reproduce:**
just create a project with dependency in package.json to
- rxjs: 5.4.1
- typescript: 2.4.1

**Expected behavior:**
no compilation error
**Actual behavior:**
```
ERROR in /Users/AlainD/Sites/toolsuite/node_modules/rxjs/Subject.d.ts (16,22): Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.
```
**Additional information:**
- I used a Angular project when reproducing the issue

**Comment by kwonoj** [comment] 2017-06-29 23:24
dupe of #2699 , #2539, #2700 . #2701 #2702 #2703 https://github.com/ReactiveX/rxjs/issues/2704 https://github.com/ReactiveX/rxjs/issues/2705 https://github.com/ReactiveX/rxjs/issues/2706 https://github.com/ReactiveX/rxjs/issues/2707

**Closed by kwonoj** 2017-06-29 23:24 UTC
