### ISSUE TITLE
Observable returned by factory in Observable.defer won't get unsubscribed

### ISSUE THREAD

**Issue by dmitrysteblyuk** [ReactiveX/rxjs#2542] opened 2017-04-10 16:22 UTC
**RxJS version:** 5.3.0

**Code to reproduce:**
Basically what the code below does is just creates an observable items$, which produces new array of items whenever newItemSubject emits a new value.

```
const newItemSubject = new Rx.Subject();

const newItems$ = newItemSubject
    .withLatestFrom(Rx.Observable.defer(() => items$))
    .map(([newItem, items]) => [...items, newItem]);

const items$ = Rx.Observable.timer(1000).mapTo([])
    .do(v => console.log('init values', v))
    .merge(newItems$)
    .share();

const subscr = items$.subscribe(items => console.log(items));

// This line for reproducing the bug only
subscr.unsubscribe();
```

**Expected behavior:**
Observable items$ should be unsubscribed from instantly with no logs in console.

**Actual behavior:**
Despite I dispose the only subscription right away I still can see 'init values' [] in console.

**Comment by JaminFarr** [comment] 2017-04-19 15:09
Ok, this is pretty confusing but I'm going to have a stab at it.

I don't think this has anything to do with `Observable.defer`, the issue is a shared observable subscribing to itself.

When subscribing to items$ the refCount of the share operator goes from 0 to 1 so share operator subscribes to it's source which is merged with newItems$.
newItems$ has items$ as one of it's sources so it subscribes to item$ again. At this point the share refCount goes from 1 to 2. As it already has a live subscription that is returned and used instead of creating a new subscription preventing an infinite loop.

Then the original subscription is unsubscribed the share refCount goes from 2 to 1. Because it doesn't go to 0 it does not unsubscribe from it's source, so newItems$ is never unsubscribed,

The final state is items$ is subscribed to newItems$ and items$ is subscribed to newItems$. It's a circular subscription with no way of being unsubscribed.

Changing the `.timer(1000)` to `.interval(1000)` shows the subscription remains live and continues to emit after the unsubscribe.

**Comment by dmitrysteblyuk** [comment] 2017-04-19 19:13
@JaminFarr Thank you for the answer, very explanatory!
Circular dependencies (subscriptions in this case) are true evil indeed = )
I knew a workaround for my problem without lazy initialization but it's nice to know now what caused this bug (in my code turned out) so as to avoid it in the future.

**Closed** 2017-04-19 19:14 UTC
Labels: type: question

**Comment by zjuasmn** [comment] 2017-10-27 01:57
I think there should be some way to solve the circular unsubscription issue by mark and sweep on the dependency graph. Current implementation of unsubscription is  `--refCount` and check, which
 is OK when the graph is a tree.
