### ISSUE TITLE
Missing marble image for endWith

### ISSUE THREAD

**Issue by moniuch** [ReactiveX/rxjs#3796] opened 2018-06-05 19:56 UTC
### Documentation Related To Component:
endWith

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [x] needs example (needs a marble diagram image)

### Description Of The Issue
- The diagram needs to be generated and made available at https://rxjs-dev.firebaseapp.com/img/endWith.png
- jsdoc needs to be updated with the image link

**Comment by martinsik** [comment] 2018-06-29 11:05
I think you can close this one. It should be fixed in #3846.

**Comment by JWO719** [comment] 2018-08-17 16:55
Basically you are right and I think this one could be resolved, but I would like to check in the next deployment if it is actually exisiting. So it will stay open, till we can full verify that it is working

**Comment by sajidali** [comment] 2019-01-19 04:01
@JWO719 long time, no fix. :(

**Comment by PowerKiKi** [comment] 2019-04-08 05:27
Please close this issue, as it is a duplicate of #4366.

**Closed** 2019-04-09 05:05 UTC
Labels: type: docs
