### ISSUE TITLE
Exported types incompatible with ESM when using TypeScript@next

### ISSUE THREAD

**Issue by AndrewLeedham** [ReactiveX/rxjs#6801] opened 2022-02-07 17:26 UTC
### Describe the bug

When importing `rxjs` in a project using TypeScript@next with the `"module": "nodenext"` ([experimental ESM support](https://www.typescriptlang.org/docs/handbook/esm-node.html)) it fails to locate the associated types. As seen in this TypeScript playground: [Playground Link](https://www.typescriptlang.org/play?target=99&moduleResolution=99&ts=4.6.0-dev.20220116#code/JYWwDg9gTgLgBAbzgeQEYGcCmUBuBDVAG0wBo4BlAV1QCtMBjeAXzgDMoIQ4ByKADxrpuAbiA).

### Expected behavior

TypeScript@next is experimental so I suppose I don't expect it to work. But the API seems fairly stable, so I am raising this issue to track the change. The `exports` spec defines an optional `types` field, which if used in rxjs resolved the issue (I have tried this with a patch locally).

### Reproduction code

```typescript
import { Observable, Subject } from 'rxjs';
```

### Reproduction URL

https://www.typescriptlang.org/play?target=99&moduleResolution=99&ts=4.6.0-dev.20220116#code/JYWwDg9gTgLgBAbzgeQEYGcCmUBuBDVAG0wBo4BlAV1QCtMBjeAXzgDMoIQ4ByKADxrpuAbiA

### Version

7.4.0

### Environment

- Node.js@16.13.2
- TypeScript@4.6.0-dev.20220204

### Additional context

Related discussion in the TypeScript repo: https://github.com/microsoft/TypeScript/issues/46452#issuecomment-1031564279

**Comment by kwonoj** [comment] 2022-02-07 17:28
This is mostly dupe of https://github.com/ReactiveX/rxjs/issues/4416. We don't offer native esm support in anywhere yet.

**Closed as completed** 2022-02-22 15:37 UTC

**Comment by sandrooco** [comment] 2022-03-09 12:19
@demurgos This was released just yesterday.
