### ISSUE TITLE
`distinctUntilChanged`  typing is not correct when second parameter is passed but first is `null` or `undefined`

### ISSUE THREAD

**Issue by peterbakonyi05** [ReactiveX/rxjs#2774] opened 2017-07-29 06:38 UTC
When `strictNullChecks` TS compiler option is `true` `distinctUntilChanged` throws typing error when only the second parameter is specified. However in the actual implementation both parameters are optional so the code will work with `strictNullChecks` `false`.

**RxJS version:** 5.4.2

**Code to reproduce:**
```
// make sure you use typescript ^2.2.0 and `strictNullChecks` option is true
Observable.timer(0, 100)
    .map(i => ({ value: i }))
    .distinctUntilChanged(null, (state: { value: number }) => state.value);
```

**Expected behavior:** Code compiles without any errors

**Actual behavior:** The below TS compiler error
```
[ts] Argument of type 'null' is not assignable to parameter of type '(x: number, y: number) => boolean'.
```

**Additional information:** It is possible to make it work if we force the type not to be `null` (.`distinctUntilChanged(null!, (state: { value: number }) => state.value);`) but ideally the typing should be correct.

**Comment by kwonoj** [comment] 2017-07-29 06:40
This is basically dupe of https://github.com/ReactiveX/rxjs/issues/2447. (operator's different, but crux's identical).

**Closed** 2018-03-16 21:36 UTC
