### ISSUE TITLE
ForkJoin returns Observable.empty if any of the sub-observables return empty (Bug?)

### ISSUE THREAD

**Issue by Erdromian** [ReactiveX/rxjs#2427] opened 2017-03-01 05:25 UTC
**RxJS version:**
5.1.1
(jsbin uses 5.0.3 I think)
**Code to reproduce:**
http://jsbin.com/dixunoheba/1/edit?js,console
```
let hasEmpty = [Rx.Observable.empty(), 
              Rx.Observable.of(undefined), 
              Rx.Observable.of(null), 
              Rx.Observable.of("T.T")]

Rx.Observable.forkJoin(hasEmpty).subscribe(found=>console.log(found))
```
**Expected behavior:**
Returning an array of any results.

```
[ undefined, null, "T.T"]
```
**Actual behavior:**
Returns nothing, presumably because the Observable.empty() just completes it.
```
```

**Additional information:**
If all the results of one of the sub-observables are filtered out, it does the same thing.  
I am not sure if this is intended.  It came as a surprise to me because I have been designing my Service calls to return Observable.empty if they have any problems.  If I want to use forkJoin on something like that, I would now need to pass through some garbage value to filter out of the array afterwards instead.  
Not ideal... :/

**Comment by kwonoj** [comment] 2017-03-01 05:41
Dupe of https://github.com/ReactiveX/rxjs/issues/2188#issuecomment-266521238 . Forkjoin have intended design behavior of collecting results only if all provided source emits its values. You can also check test cases describes its design. https://github.com/ReactiveX/rxjs/blob/master/spec/observables/forkJoin-spec.ts#L165

**Closed** 2017-03-01 05:59 UTC
