### ISSUE TITLE
Mocking input to withLatestFrom inside NgRx Effects tests fails when using Angular best practice

### ISSUE THREAD

**Issue by tomwhite007** [ReactiveX/rxjs#5159] opened 2019-11-22 11:18 UTC
## Bug Report

**Current Behavior**
Using recommended Angular [test pattern approach for NgRx Effects](https://ngrx.io/guide/effects/testing) fails if the Observable pipe uses a mocked value generated inside the unit test for a function returned by the `withLatestFrom` operator. Instead of the mocked value supplied, `withLatestFrom` returns the mocked function's previous value, which in the case of the Angular pattern is `undefined`.

NgRx Effects are my most common use case in Angular for `withLatestFrom`. But this issue also occurs in Angular components and services' unit tests because they all use the `beforeEach` - `TestBed.configureTestingModule()` pattern. This can be bypassed and Effects and other services can be instantiated inside unit tests, but this is not the recommended pattern.

All other RxJs pipe operators I've encountered have not had this problem with mocking inside Angular tests, both using Marbles and, `of()` or `from()`.

**Reproduction**
Repo link:
https://github.com/tomwhite007/withLastestFrom-mocking-issue

The repo has a readme describing more.
I've created example unit tests; one that consume a pipe containing `withLatestFrom` and another that does the same thing using `switchMap`.

**Expected behavior**
Should allow unit test mocking in the same way as other operators, such as `switchMap`, `map`, and `mergeMap`

**Environment**

- Angular: 8.3.18
- RxJS version: 6.4.0
- Jasmine: 3.4.0

**Comment by cartant** [comment] 2019-11-22 12:49
I've not used Angular for a while, so I could be on the wrong track, but I don't think this is an issue with RxJS. Rather, I think it's related to the Angular DI stuff.

IMO, `withLatestFrom` behaves differently to `switchMap` because the former involves a call that will be made to the store - [here](https://github.com/tomwhite007/withLastestFrom-mocking-issue/blob/756c8b542385fe3c501baa668ba39a1b8bd33391/src/app/%2Bstate/dummy-state.effects.ts#L18) - when `DummyStateEffects` is constructed.

**Comment by tomwhite007** [comment] 2019-11-25 13:54
Thanks for your response @cartant 

I presume the subscribe when the Source Observable is constructed is so that `withLatestFrom` can start watching, to remember the latest value? I can see the point in that. 

But, if the input source parameter to `withLatestFrom` changes (to another observable), surely it needs to switch to that? If it did that switch at the trigger point of getting the latest value for the stream, then it would behave more like the other pipe operators; all of which allow mocking against an instantiated Source Observable. Would you be interested in a PR in this direction?

I can't see any documentation, including JSDocs, that highlights this operator's unusual start point in time. At the very least, surely there needs to be a gotcha or special note about this behaviour in the docs? Happy to contribute on that alternatively, if you agree.

Do you not agree that all `pipe` operators should present to unit test harnesses in the same way - like an api? Thereby they exclude the need for separate specialised test harnesses to test observable streams if we accidentally include a special operator.

**Comment by kwonoj** [comment] 2019-11-25 15:03
I'm trying to understand issue but this looks natural behavior difference between 2 operators, given `withLatestFrom` accepts source observable and other operators like `switchMap` requires map-fn as name stands for.

> But, if the input source parameter to withLatestFrom changes (to another observable), surely it needs to switch to that?

Mind elaborate this? are you saying `withLatestFrom(someObs1)` and expect to change dynamically `someObs1` to something else later?

> Do you not agree that all pipe operators should present to unit test harnesses in the same way - like an api?

In general sense yes, but if I understand correctly this is behavior of `operator`, not about `pipe`.

**Comment by tomwhite007** [comment] 2019-11-26 14:29
Hello @kwonoj 

I'll try to respond to each of your points.

> I'm trying to understand issue but this looks natural behavior difference between 2 operators, given `withLatestFrom` accepts source observable and other operators like `switchMap` requires map-fn as name stands for.
> 

I agree, the behaviour in normal usage *is* natural. The problem is with mocking input functions for these parameters inside unit tests. With `switchMap`, you switch to another observable; the providing function of which is easily mocked after the Source Observable (stream root) is already instantiated. This is true of all operators I've encountered that can include a subscription to another observable - except for `withLatestFrom`.


> > *But, if the input source parameter to withLatestFrom changes (to another observable), 
surely it needs to switch to that?*
> 
> Mind elaborate this? are you saying `withLatestFrom(someObs1)` and expect to change dynamically `someObs1` to something else later?
> 

Yes, exactly; in Angular unit tests this is common practice.



> > *Do you not agree that all pipe operators should present to unit test harnesses in the same way - like an api?*
> 
> In general sense yes, but if I understand correctly this is behavior of `operator`, not about `pipe`.

My apologies for mixing terminology. Your right; I'm referring to all Pipeable Operators, not the pipe function.

**Comment by kwonoj** [comment] 2019-11-26 14:52
Thabks for clarification. Overall, in high level I do not think all operator should have consistent behavior for these kind. It's characteristics of operator, not something we gaurantee by contract.  All of operator does not accepts per-emission map fn / predicate will looks like this things like repeatWhen / mapTo / lot of others.

While you have mentioned it is common practice to swap given param of operator after once value is set, that doesn't look like right approach to me. It coindientally worked by some operator evaluate value per each emission, while some operator will not do. Each fixture setup should be done in a way conforms operator's expected behavior.

**Comment by kwonoj** [comment] 2019-11-26 14:54
In short I do not agree runtime operator behavior should change to conform some of unit test practices.

**Comment by cartant** [comment] 2019-11-26 20:06
> But, if the input source parameter to `withLatestFrom` changes (to another observable), surely it needs to switch to that?

If it changes, it's ignored. That's how functions work. This is not an RxJS problem. The responsibility for managing the order in which DI components are composed lies with Angular.

FWIW, when I used NgRx, I declared my effects as functions - rather than properties - so that observables were created when NgRx connected the effect to the store, rather than when the class was constructed.

Also, the latest version of NgRx has a `createEffect` function that's passed a callback that creates the effect's observable.

I suspect that either of these approaches might solve your problem.

In any case, this is an Angular/NgRx problem. It's not RxJS's responsibility.

**Comment by kwonoj** [comment] 2019-11-26 20:37
I'm closing this as I believe this is expected behavior as specific operator point of view.

**Closed by kwonoj** 2019-11-26 20:37 UTC

**Comment by tomwhite007** [comment] 2019-11-27 08:34
@kwonoj and @cartant Thanks for your time and this discussion. 

I hope this thread helps others who bump into this problem. 

For completeness, the error  from `withLatestFrom` looks like this:

`TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.`
