### ISSUE TITLE
rxjs 6 requires rxjs-compat

### ISSUE THREAD

**Issue by tamarbsh** [ReactiveX/rxjs#3896] opened 2018-07-05 06:47 UTC
## Bug Report
I'm creating new project in angular 6 And I added the rxjs@6.2.1 package.
when I run the command ng build in angular cli, I get the following error:
ERROR in node_modules/rxjs/operator.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Operator'.
This is the only error in console, Operator.d.ts file contains single line of code:
export * from 'rxjs-compat/Operator';
Removing and reinstalling all packages from node_modules also didn't worked.
Am I doing something wrong?

I do not want to install the rxjs-compat package, because it made me problems with other packages (lodash, jquery)

Additional information:
package.json
{
  "name": "client-app3",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.0.3",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "angular-highcharts": "^6.2.6",
    "bootstrap": "^3.3.7",
    "chalk": "^2.4.1",
    "core-js": "^2.5.4",
    "each-async": "^1.1.1",
    "indent-string": "^3.2.0",
    "jQuery-QueryBuilder": "^2.4.4",
    "jquery": "^3.3.1",
    "lodash": "^4.17.10",
    "ngx-bootstrap": "^3.0.1",
    "rxjs": "^6.2.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.8",
    "@angular/cli": "~6.0.8",
    "@angular/compiler-cli": "^6.0.3",
    "@angular/language-service": "^6.0.3",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/lodash": "^4.14.110",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  }
}
Thanks

**Comment by ladyleet** [comment] 2018-07-11 14:40
@tamarbsh hey thanks for submitting this! have you used any rxjs in your app yet or is this just in the setup of a brand new project?

**Comment by ThetaSinner** [comment] 2018-09-06 09:01
I'm seeing exactly the same thing upgrading to angular 6 from 5.2

**Comment by wldcordeiro** [comment] 2018-09-27 07:12
Not using Angular but I'm seeing the same thing. All my paths are resolving to `rxjs-compat` require calls. 🤔 It's turning into a pain because my bundle sizes are larger than they should be.

**Comment by capz** [comment] 2018-10-08 13:06
i am upgrading our rxjs and seeing the same thing after removing rxjs-compat
i can confirm that various d.ts files from rxjs are simply exporting * from rxjs-compat

**Comment by Ristaaf** [comment] 2018-10-09 05:03
Just a verification question, you have upgraded your imports when upgrading to rxjs6? You are not supposed to import anything from "rxjs/operator" for example. https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md

**Comment by getsundar** [comment] 2019-01-04 14:04
@Ristaaf 
hi.. even in the guide it has mentioned to import some pipeable operators from "rxjs/operators". Correct me if I am wrong. 

Anyone have solution for it after removing "rxjs/compat" package?

**Comment by Ristaaf** [comment] 2019-01-08 13:57
@getsundar 
Yes, you should import from "rxjs/operators", not from "rxjs/operator" which I was asking about, because if you try to import from rxjs/operator it needs compat, but rxjs/operators should not need compat!

**Comment by capz** [comment] 2019-01-09 10:23
> Just a verification question, you have upgraded your imports when upgrading to rxjs6? You are not supposed to import anything from "rxjs/operator" for example. https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md

there are no references to `rxjs/operator` in our code base, only `rxjs/operators`

I've finished the upgrade to the latest rxjs a few months ago, but we are still stuck with rxjs compat, this is not cool, guys.

**Comment by ty-mcfarland** [comment] 2019-01-17 23:41
How can I remove rxjs-compat when it is required by rxjs: ^6.3.3?

I have 100% updated my imports, resultSelectors, pipes, operators, all the things I can read about and think of, but after uninstalling rxjs-compat I get These errors when I run:

Module not found: Error: Can't resolve 'rxjs-compat/add/operator/toArray'
Module not found: Error: Can't resolve 'rxjs-compat/add/operator/take'

And after removing, I see the following in rxjs:^6.3.3:
**From Observable.d.ts:**
export * from 'rxjs-compat/Observable';

**From Observable.js:**
Object.defineProperty(exports, "__esModule", { value: true });
__export(require("rxjs-compat/Observable"));

rxjs-compat seems to be required by rxjs 6, regardless if I haven't fully completed the refactor.  This means I can't remove it :(

**Comment by cartant** [comment] 2019-01-17 23:53
The only import locations that can be used with `rxjs` without having `rxjs-compat` installed are:

```
... from 'rxjs';
... from 'rxjs/ajax';
... from 'rxjs/operators';
... from 'rxjs/testing';
... from 'rxjs/webSocket';
```

If you are using **any** other import locations, you need to have `rxjs-compat` installed.

You should check the imports used in your codebase. IMO, this issue should be closed unless a minimal, failing reproduction can be provided in which only the above-listed imports are used.

**Comment by ty-mcfarland** [comment] 2019-01-18 01:04
Understood.  I just don't have the time right now, I've been checking my codebase for 2 days now.  All I can do, and did, was show code that was downloaded using "npm -i --save-dev rxjs" that shows files in node_modules/rxjs that have dependencies on rxjs-compat and swear on everything I love that the only imports I'm using in this 200+ file project are 'rxjs' and 'rxjs/operators'.  That's why I could only say "I have 100% updated my imports, resultSelectors, pipes, operators, all the things I can read about and think of".  My builds can't resolve'./node_modules/rxjs/add/observable/of.js because Module not found: Error: Can't resolve 'rxjs-compat/add/observable/of' because I don't have rxjs-compat installed and rxjs is looking for it from Observable.js and Observable.d.ts.  Again, I apologize.

**Comment by cartant** [comment] 2019-01-18 01:20
I'll add an `rxjs-no-compat` rule to `rxjs-tslint-rules` later today. When that's done, you can run the rule to find any `rxjs-compat`-dependent imports. However, it ought to be trivial to write a RegExp-based search in any decent editor that would find problematic imports. You also need to be aware that if you have any dependencies that import from `rxjs-compat`-dependent locations, those dependencies will force the use of `rxjs-compat`.

**Closed** 2019-01-18 01:21 UTC

**Comment by ty-mcfarland** [comment] 2019-01-18 01:37
@cartant that'd be great, thank you!  When it becomes available, I'll update and if it uncovers something I feel I can't do anything about, I'll let you know.  Here, if it matters, are the results of my migrate script 'rxjs-5-to-6-migrate -p tsconfig.json (I also get the same result with the prod config):

Running the automatic migrations. Please, be patient and wait until the execution completes.
Cannot find any possible migrations

Thanks again for looking into it.

**Comment by cartant** [comment] 2019-01-18 03:14
@ty-mcfarland There is an `rxjs-no-compat` rule in [`rxjs-tslint-rules`](https://github.com/cartant/rxjs-tslint-rules) 4.15.0.

**Comment by ty-mcfarland** [comment] 2019-01-18 03:33
and when I have this:

"rulesDirectory": [
    "node_modules/codelyzer",
    "node_modules/rxjs-tslint-rules",
    "node_modules/rxjs-tslint"
  ],

I get 
Could not find implementations for the following rules specified in the configuration:
    rxjs-no-compat

And when I have this:
Could not find implementations for the following rules specified in the configuration:
    rxjs-collapse-imports
    rxjs-no-compat
    rxjs-pipeable-operators-only
    rxjs-no-static-observable-methods
    rxjs-proper-imports

So how do I use them together?

**Comment by cartant** [comment] 2019-01-18 03:36
Consult the README for `rxjs-tslint-rules`. Your configuration is not inline with the documentation.

**Comment by ty-mcfarland** [comment] 2019-01-22 14:23
Using the rxjs-tslint-rules, as suggested by cartant, I was able to successfully remove all dependencies to rxjs-compat.  I installed the rules, along with rxjs-tslint, added them to my tslint file, ran ./node_modules/.bin/tslint -c tslint.json -p tsconfig.json, resolved the issues it identified, uninstalled rxjs-compat, and was successful.  Thanks @cartant for the tip, it is appreciated.
