### ISSUE TITLE
Finally and share do not work as expected

### ISSUE THREAD

**Issue by pavadeli** [ReactiveX/RxJS#1063] opened 2015-12-15 08:40 UTC
The `finally` operator has some problems when used in combination with `share`. Some combinations work as expected, some don't.

###### Interval with `finally` works as expected:
```javascript
Rx.Observable.interval(100)
    .finally(() => console.log('finally 1'))
    .subscribe()
    .unsubscribe();
```
Console:
```
finally 1
```

###### Interval with `finally` and `share` does not work (nothing in log):
```javascript
Rx.Observable.interval(100)
    .finally(() => console.log('finally 1'))
    .share()
    .subscribe()
    .unsubscribe();
```
Console:
```
```

###### Subject with `finally` and `share` works as expected:
```javascript
new Rx.Subject()
    .finally(() => console.log('finally 1'))
    .share()
    .subscribe()
    .unsubscribe();
```
Console:
```
finally 1
```

###### Subject with two times `finally` and `share` does not work (nothing in log):
```javascript
new Rx.Subject()
    .finally(() => console.log('finally 1'))
    .finally(() => console.log('finally 2'))
    .share()
    .subscribe()
    .unsubscribe();
```
Console:
```
```

I tested this on *beta.0*. It does seem to work on a previous alpha (JSBin provides *alpha.8*, it works there). Unfortunately I don't understand enough of the inner workings to explain why this happens.

**Comment by pavadeli** [comment] 2015-12-15 10:32
The problem seems to be with `share` and not so much with `finally`. `Rx.Observable.merge` has the same kind of behaviour when combined with `share`.

###### `Rx.Observable.merge` with one child and `share` works as expected
```javascript
Rx.Observable
    .merge(
        Rx.Observable.interval(100)
    )
    .share()
    .subscribe(e => console.log(e));
```
Console:
```
1
2
3
4
...
```

###### `Rx.Observable.merge` with two children and `share` unsubscribe immediately
```javascript
Rx.Observable
    .merge(
        Rx.Observable.interval(100),
        Rx.Observable.interval(100)
    )
    .share()
    .subscribe(e => console.log(e));
```
Console:
```
```

**Comment by staltz** [comment] 2015-12-15 12:56
@blesh since I've been digging into share and ConnectableObservable, I volunteer to debug and fix this one, if it seems like a good priority in your opinion.

**Comment by blesh** [comment] 2015-12-15 20:36
@pavadeli @staltz ... this appears to be a problem with `ConnectableObservable` breaking the subscription chain. Pretty much any flavor of `multicast`, `publish`, `share`, etc. breaks `finally` if `finally` is before the mutlicast.

**Comment by blesh** [comment] 2015-12-15 20:37
I'm wondering if we ought to research moving away from the subscription chain, and back to a more traditional subscription composition? cc/ @trxcllnt

**Comment by blesh** [comment] 2015-12-15 20:37
(yes, I know this is just one issue, but I worry there may be others)

**Comment by pavadeli** [comment] 2015-12-16 08:23
@blesh Would that make debugging subscription and unsubscription behaviour a bit easier for mere mortals? In that case, yes, please... :innocent:

In the meantime, for anyone affected by this bug. The latest alpha that seems to work is *alpha.11*. Note: there have been some API changes since that version.
(I have not found an easy way to work around this bug. If anyone has an idea, please let me know.)

**Comment by trxcllnt** [comment] 2015-12-16 08:38
@blesh I'm also running into this issue with `ConnectableObservable`. We should probably fix that before moving everything away from the shared subscription list.

**Comment by staltz** [comment] 2015-12-16 09:12
@trxcllnt how do you reproduce your bug with `ConnectableObservable`?

**Comment by staltz** [comment] 2015-12-16 09:15
By the way, we haven't merged #1042 yet, it could fix some of these problems.

**Comment by staltz** [comment] 2015-12-16 12:15
After applying PR #1042, this works fine:

```js
Rx.Observable.interval(100).take(3)
    .finally(() => console.log('finally 1'))
    .finally(() => console.log('finally 2'))
    .share()
    .subscribe(x => console.log(x));
```
```
0
1
2
finally 2
finally 1
```

- - -

We still have a problem with this though:
```js
Rx.Observable
    .merge(
        Rx.Observable.interval(100),
        Rx.Observable.interval(100)
    )
    .share()
    .subscribe(e => console.log(e));
```

Might be a problem in ArrayObservable or mergeAll.

**Comment by pavadeli** [comment] 2015-12-16 12:41
@staltz Actually, that already worked in *beta.0*. Finally gets called on `complete`, but should also be called on `unsubscribe`. What about this case? We explicitly don't complete the source.
```javascript
Rx.Observable.interval(100)
    .finally(() => console.log('finally 1'))
    .share()
    .subscribe()
    .unsubscribe();
```

**Comment by staltz** [comment] 2015-12-16 12:44
Ah, I see. Yeah, it looks like the problem comes from the shared subscription architecture.

**Comment by trxcllnt** [comment] 2015-12-16 18:43
@staltz @blesh here's my (possibly related) problem with ConnectableObservable:

```es6
const src = Observable.interval(100)
  .multicast(new Subject())
  .refCount();

// throws `cannot subscribe to a disposed subject` when `of` emits the second value
Observable.of(1, 2, 3)
  .switchMap(_ => src)
  .subscribe(
    x => console.log(x),
    e => console.error(e)
  );
```

**Comment by staltz** [comment] 2016-01-06 08:57
This issue can be closed, a test was added.

**Closed** 2016-01-06 10:12 UTC
Labels: type: bug
