### ISSUE TITLE
Navbar active  wrong 

### ISSUE THREAD

**Issue by elfobella** [ReactiveX/rxjs#7136] opened 2022-12-27 18:01 UTC
### Describe the bug

If you mousedown any link and drag outside, it will active in css but it will not show

### Expected behavior

I think this is a css issue, active class should be removed

### Version

v7.8.0

**Comment by jakovljevic-mladen** [comment] 2022-12-28 08:30
Hello, thanks for opening the issue. I'm not completely sure what the issue is and how to reproduce it. Is it possible to add more info and post some screenshots as well?

Also, [issues](https://github.com/ReactiveX/rxjs/issues) should be used only to file core library bugs, so I'm gonna close it. If this is related to the docs app, please use [this section](https://github.com/ReactiveX/rxjs/discussions) to open a new section with more info.

Thanks.

**Closed by jakovljevic-mladen** 2022-12-28 08:30 UTC
