### ISSUE TITLE
Pipe operator cannot infer return type as ConnectableObservable

### ISSUE THREAD

**Issue by kasiditi** [ReactiveX/rxjs#2972] opened 2017-10-18 19:51 UTC
**RxJS version:** 5.5.0

**Code to reproduce:**

```ts
const obs = Observable.of(5);
const connectableObs = obs.pipe(
    publishReplay(1)
);
```

**Expected behavior:** The inferred type of `connectableObs` is `ConnectableObservable<number>`.

**Actual behavior:** The inferred type of `connectableObs` is `Observable<number>`.

**Additional information:**

TypeScript version: 2.5.3

My current workaround is to manually downcast the return value:

```ts
const obs = Observable.of(5);
const connectableObs = obs.pipe(
    publishReplay(1)
) as ConnectableObservable<number>;
```

Happy to send a PR, but not sure how should I fix this properly.

**Comment by cartant** [comment] 2017-10-19 06:21
The problem can be solved by adding additional overload signatures to `pipe`, allowing for the last operator to return a `ConnectableObservable`.

For example:

```ts
pipe<A>(op1: UnaryFunction<Observable<T>, ConnectableObservable<A>>): ConnectableObservable<A>;
pipe<A>(op1: OperatorFunction<T, A>): Observable<A>;
```

Using `ConnectableObservable` in the signtures for a method in `Observable` seems a little weird, as `ConnectableObservable` extends `Observable`, but this is only way I can see this working.

An import of `ConnectableObservable` would be necessary in `Observable.ts`, but as it's only used in the typings, the import is erased during transpilation.

The signatures for `publish` and `publishLast` would have to be changed, too, as it they do not specify `ConnectableObservable` in their return types.

Interestingly, adding such overload signatures to `pipe` seems to fix another problem with the inference of the `publishReplay`. Without them, the return type of the following:

```ts
const o = of(0).pipe(publishReplay(1));
```

is inferred as `Observable<any>` (note the `any`) and with them it's inferred as `ConnectableObservable<number>`.

**Comment by cartant** [comment] 2017-10-19 09:13
Actually, if the overload signatures for `pipe` are written like this:

```ts
pipe<A, OA extends Observable<A>>(op1: UnaryFunction<Observable<T>, OA>): OA;
pipe<A, B, OB extends Observable<B>>(op1: OperatorFunction<T, A>, op2: UnaryFunction<Observable<A>, OB>): OB;
// etc.
```

The problem can be solved without specific reference to `ConnectableObservable`.

This seems to be okay with the version of TypeScript (2.0) that RxJS uses, but I've not investigated this thoroughly.

**Comment by Dynalon** [comment] 2018-04-25 08:52
This issue still exists in rxjs 6.0 final. Reproduce:

```typescript
const connectableObservable = from([1, 2, 3]).pipe(publish());
connectableObservable.connect()
```

`tsc` will fail, saying `error TS2339: Property 'connect' does not exist on type 'Observable<any>'.`. Casting the `connectableObservable` to `any` and calling `.connect()` works as expected.

**Comment by lgleim** [comment] 2018-06-15 12:42
The root cause appears to be that pipe is typed to always return an `Observable<T>`, which means that it does not allow subtypes of Observable to be properly inferred.

**Comment by BasHamer** [comment] 2018-08-28 14:47
https://www.learnrxjs.io/operators/multicasting/publish.html did not work for me until doing this.

**Comment by samal84** [comment] 2018-09-12 15:39
I just ran into this issue while updating from rxjs 5 to 6. I see it has been a while since any activity here. Should we expect any fix in the future?

**Comment by ebrehault** [comment] 2018-10-12 13:46
Workaround:

```
(yourObs as ConnectableObservable<YourType>).connect()
```

**Comment by fljot** [comment] 2018-11-10 09:48
@ebrehault this looks like (type)safer workaround
https://github.com/ReactiveX/rxjs/issues/3595

@benlesh @cartant what do you say, is it possible to fix with the whole `pipe` approach?
And another question regarding piping and types: since there's a limited set of overload signatures for `pipe`, it means that that type-safe long pipelines are impossible? Can this topic be addressed in v7?

**Comment by simeyla** [comment] 2019-01-14 00:41
My preferred 'temporary' workaround is this static function:

```
export const connect = (obs: Observable<any> | ConnectableObservable<any>) =>
{
    if (obs instanceof ConnectableObservable)
    {
        return (obs as ConnectableObservable<any>).connect();
    }
    else 
    {
        throw Error('Not a connectable observable');
    }
}
```

Which is used simply like this (assigning is optional):

```
const subscription = connect(events$);
```

Or if you don't want a function just use `<any>` in the cast instead of the specific type:

   (events$ as ConnectableObservable<any>).connect();

In future when 'fixed' (RxJS 7+) then delete the function and the compiler will give you all the places to change.

Issues with other answers:

* Some have suggested casting with `as ConnectableObservable<MyEvent>` but that means you need to know what type it is solely for the purpose of running `connect()`. I often don't know the type of my observable, or it changes over time. Either way it does you no good whatsoever to be more specific since `connect()` isn't a generic function.
* A static `publish` function means you have `publish` at the *beginning* of your pipe instead of the end. With a very long pipe - it would be super easy to end up accidentally adding an additional multicast operator at the end of the pipe if you or someone else didn't see `publish` at the beginning. Unless you have a separate line to publish which is up to you:

     const publishedEvents = publish(events$);

**Comment by simeyla** [comment] 2019-01-14 01:52
I got myself super confused by this whole issue, so just wanted to add a couple findings that may help others - especially in understanding what is **not** the problem:

* First - this problem only applies to `publish` and not `publishReplay`
* `publishReplay` does NOT return a connected observable so no issue with the `pipe` there
* Ultimately the problem is that `publish()` in a pipe completely loses both the connectable nature of the observable and its type. (Typescript limitation from an earlier version AFAIK). 
* When you use `publish` typescript strips away **both** the ConnectableObservable type AND the fundamental type of your source.

In other words the type of `of(1,2,3).pipe(publish())` is `Observable<any>` instead of `ConnectableObservable<number>` (which is what it really is).

When `publish` is most useful you'll often have several 'child' streams that take the output of your primary source stream and transform it. So just by using `publish` in the `pipe` you lose the ability inside your operators to know what your incoming observable is.

@fljot's answer is most useful to solve this problem because all it does it to call the `publish` operator and in isolation typescript can properly figure out all the types. The key usefulness of this method is that **you don't need to explicitly provide (or even know) the type of your source observable**, so everything will ripple through nicely by itself.

So you can publish a stream, use it to create other streams and then `connect` to it.

The only recommendation I have for usage is to call it on a separate line like this:

```

// I used an underscore to suggest this is a temporary variable
const _stockQuotes$ = of(10, 11, 12, 11, 10);   
const publishedStockQuotes$ = publish(_stockQuotes$);  // function from @fjlot

// derivative streams - (publishedStockQuotes$ is Observable<number>)
const throttledStockQuotes$ = publishedStockQuotes$.pipe(throttleTime(5000));
const splitStockQuotes$ = publishedStockQuotes$.pipe(map(quote => quote / 2));   // 

publishedStockQuotes$.connect();   
```

---
@ebrehault your answer is misleading. The `connect()` method isn't generic, so the goal is not to have a 'typed connectable' observable when you call `connect()`, but a 'connectable' observable when you call `connect` AND a 'typed' observable when you create further streams.

     // connect(): Subscription;
    (yourObs as ConnectableObservable<any>).connect();

**Comment by jonrimmer** [comment] 2019-05-28 14:53
@simeyla Why do you claim `publishReplay()` doesn't return a `ConnectableObservable`?

It does: https://github.com/ReactiveX/rxjs/blob/6.5.2/src/internal/operators/publishReplay.ts#L24

**Comment by dudewad** [comment] 2019-07-10 20:15
I'm curious if this is considered a bug that's going to get fixed? I am fine type casting but would prefer not to.
I do want to point out though, that `pipe()` has always only returned `Observable<T>` in my experience -- if I'm wrong there, cool, I just wonder if justifying having an operator transform the output type of the piped observable leads to justifying doing it for all types?
What I mean by that is, I created a custom operator to convert an observable to a BehaviorSubject which gives caching. But this method requires the solution provided here -- typecasting to `BehaviorSubject<T>` at the end of the pipe. This is "fine", but ideally, if an operator is spitting out some subtype of Observable, that subtype, at least logically speaking, should be preserved.

**Comment by pie6k** [comment] 2020-03-24 20:48
Seems it's still an issue. Is there any update related to this?

![image](https://user-images.githubusercontent.com/7311462/77475449-227bd500-6e19-11ea-9f96-5a9efa1b7e72.png)

**Comment by codehunter13** [comment] 2020-11-24 13:54
still an issue????

**Comment by samal-rasmussen** [comment] 2020-11-24 14:35
ConnectableObservable is currently planned to be removed in v.8: https://github.com/ReactiveX/rxjs/issues/5431

**Comment by cartant** [comment] 2021-04-30 08:20
Closing this 'cause `ConnectableObservable` is deprecated in v7.

**Closed by cartant** 2021-04-30 08:20 UTC
