### ISSUE TITLE
can't chain connect() operator after beta0

### ISSUE THREAD

**Issue by cburgdorf** [ReactiveX/rxjs#1771] opened 2016-06-15 12:22 UTC
**RxJS version:** 5.0.0-beta9

**Code to reproduce:** 

http://jsbin.com/vuwucorela/1/edit?html,js,console

```
let myObservable = Rx.Observable.interval(500).publish().connect();

myObservable
    .subscribe(
      val   => console.log('subscriber 1: ' + val),
      error => console.error(error),
      ()    => console.log('completed')
    );
```
**Expected behavior:** Shouldn't throw error

**Actual behavior:** throws error

**Additional information:** Works with beta 0 (http://jsbin.com/mocunofaki/1/edit?html,js,console)

I noticed that one can actually get it to work after beta 0 with a little twist: 

```
let myObservable = Rx.Observable.interval(500).publish();
myObservable.connect();
```
By not chaining the `.connect()` call it seems to work again. But is that by design? If so, is there another operator that calls connect (such as `autoconnect`) behind the scenes that is allowed to be chained?

http://jsbin.com/roseviqixo/1/edit?html,js,console

**Comment by roganov** [comment] 2016-06-15 13:13
I'm pretty sure this is by design. `.connect()` returns a 'disposable' object (in pre-5 terms), not an observable.

**Comment by cburgdorf** [comment] 2016-06-15 13:47
Ok, interesting but that changed after `beta0` apparently. Shouldn't then there be an operator such as `autoconnect` that can be chained so that `publish().autoconnect()` becomes possible?

**Comment by roganov** [comment] 2016-06-15 17:07
@cburgdorf You should look at operator `share`.

**Comment by cburgdorf** [comment] 2016-06-15 17:16
Share uses `refCount` which means it connects as soon as there is a first subscriber. I'm looking for something that calls `connect` immediately.

Checkout this demo that uses beta-0.

http://jsbin.com/kopinutone/3/edit?html,js,console

Notice how it the first number that is logged to the console is 5 rather than 0. That's because the Observable emitted values even before there were any subscribers. That doesn't work with `refCount`.

**Comment by roganov** [comment] 2016-06-15 17:23
OK I see.

In this case you indeed will have to use the pattern you outlined above:
```
let myObservable = Rx.Observable.interval(500).publish();
myObservable.connect();
```

If it's a very common pattern in your project, you can probably define a little helper like this:
```
function start(obs) {
   const connectable = obs.publish();
   connectable.connect();
   return connectable;
} 

let myObservable = Rx.Observable.interval(500).let(start);
```

**Comment by roganov** [comment] 2016-06-15 17:28
But really this is pretty gross because now the connectable cannot be disposed.

**Comment by cburgdorf** [comment] 2016-06-15 17:38
That's true but in beta0 `connect` returned an `Observable` that was an `Disposable` at the same time. So you could simply chain `connect` and still disconnect later. I wonder why that changed.

See how I unsubscribe after 5 seconds: http://jsbin.com/lidafavora/edit?html,js,console

**Comment by blesh** [comment] 2016-06-16 22:04
Yeah, beta.0 had an experimental behavior we opted out of because it didn't make much sense. Calling `connect()` is meant to subscribe to the source observable, and should just return a subscription. It's the published observable that you want to subscribe to after that.

**Comment by trxcllnt** [comment] 2016-06-16 22:22
You can also use `multicast` with a selector to share a single source connection between multiple subscriptions and get autoConnect-style behavior:

```es6
Observable.defer(() => {
    console.log('subscribed to source');
    return Observable.range(0, 100)
  })
  .multicast(
    () => new Subject(),
    (shared) => Observable.merge(

      shared.filter((x) => x % 5 !== 0).do((x) =>
        console.log(`${x} is not a multiple of 5`)),

      shared.filter((x) => x % 5 === 0 && x % 7 !== 0).do((x) =>
        console.log(`${x} is a multiple of 5 but not of 7`))
    )
  )
  .subscribe(::console.log);
```

**Comment by blesh** [comment] 2016-06-17 00:55
> You can also use multicast with a selector 

/* next release. ;)

**Comment by blesh** [comment] 2016-06-30 22:12
I think this has been answered adequately, closing for now.

**Closed by blesh** 2016-06-30 22:12 UTC
