### ISSUE TITLE
DOC ISSUE | Not found Observables doc

### ISSUE THREAD

**Issue by abelardolg** [ReactiveX/rxjs#5597] opened 2020-07-20 09:24 UTC
### Documentation Related To Component:

Observables
### Please check those that apply

- [ ] typo
- [x ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in example
- [ ] needs example

### Description Of The Issue

At this [webpage](https://rxjs-dev.firebaseapp.com/guide/observable), at beginning, there is a table with two rows and two columns with "Promise", "Observable" and so forth.
When "Observable"  is clicked, it shows a 404 error: [destination link](https://rxjs-dev.firebaseapp.com/class/es6/Observable.js~Observable)

Best regards.

**Comment by niklas-wortmann** [comment] 2020-07-20 09:29
Good call, thanks for finding that. The right url would be https://rxjs.dev/api/index/class/Observable.

**Comment by abelardolg** [comment] 2020-07-20 09:30
Thanks for your prompt reply. 
Best regards.

**Comment by gabrielgeorge** [comment] 2020-07-20 23:10
@niklas-wortmann , do you want me to create a PR to fix this?

**Comment by niklas-wortmann** [comment] 2020-07-21 06:55
While I appreciate your interest in this issue. I don't think it makes a lot of sense to fix this right now as we are currently reworking the guide section, see #5592.

**Comment by abelardolg** [comment] 2020-07-21 08:21
Hi there,

I think these concepts should be learnt by adding more pictures. IMHO, I think there your doc is plenty of words rather graphical representations of the concepts. It could saturate newcomers like me. 

By other hand, I wonder why the name of "Observable"? I'm not able to set the relationship between an observable and this concept in the RxJS world. It's hard to understand for me why this name was chosen to describe this concept.

Best regards.

**Comment by cartant** [comment] 2021-04-30 08:54
Closing this 'cause the problem is fixed in the now-deployed v7 docs.

**Closed by cartant** 2021-04-30 08:54 UTC
Labels: type: docs
