### ISSUE TITLE
GroupedObservable not available in Rx namespace

### ISSUE THREAD

**Issue by duncanmak** [ReactiveX/rxjs#2130] opened 2016-11-15 00:49 UTC
I'm writing a function in Typescript that takes the result of an Observable `groupBy`, and I can only type the parameter as `Observable<any>` because I can't get to the `GroupedObservable` type.

Should it be exported in` Rx.ts`?

**RxJS version:**
5.0.0-rc.2

**Comment by kwonoj** [comment] 2016-11-15 01:01
Not sure if I understood correctly, is it not able to import type from `groupBy`?

`import {GroupedObservable} from 'rxjs/operator/groupby';`

**Comment by jayphelps** [comment] 2016-11-15 04:28
hmmm wonder if we should move the class (and any others like it) into `rxjs/observable` since that's prolly more obvious. e.g. `rxjs/observable/GroupedObservable`

**Comment by kwonoj** [comment] 2016-11-15 04:29
@jayphelps I think that's considerable ergonomics, just not sure if it need to be exported in top level (`rx`).

**Comment by jayphelps** [comment] 2016-11-15 04:34
@kwonoj yeah, we're not exporting any of the other operator-specific Observables from root, and I'd personally prefer not to have to export everything in the world at the root cause it makes us less flexible down the road as we consider kitchen sink stuff.

**Comment by kwonoj** [comment] 2016-12-25 06:52
Actually this issue https://github.com/ReactiveX/rxjs/issues/2207 reminded me about this one as well - if top level export is missing, UMD build won't have access to those. So if we're considering `GroupedObservable` as public interface, it probably need to be `Rx`, or vice versa. 

I've been waiting `internal` scope long time to avoid this kind of confusion (https://github.com/Microsoft/TypeScript/issues/5228) but seems it won't happen soon, so we may need control public exposure via top level `Rx` namespace.

**Comment by kwonoj** [comment] 2017-07-07 19:46
I'm closing this for now, first if it's for type definition it should work without top level export, otherwise it need to be discussed to be included in top level separately.

**Closed by kwonoj** 2017-07-07 19:46 UTC
Labels: type: discussion
