### ISSUE TITLE
Type mismatch in Subject against Observable detected by typescript 2.4.1

### ISSUE THREAD

**Issue by princemaple** [ReactiveX/rxjs#2703] opened 2017-06-28 02:42 UTC
When compiling with typescript 2.4.1, ts detects a type mismatch in `Subject`, extending the `Observable` class, that implements `lift` with a different method signature

**RxJS version:** 5.4.1

**Code to reproduce:** no code required

**Expected behavior:** types do match

**Actual behavior:** they don't

**Additional information:**
```
ERROR in /var/build/node_modules/rxjs/Subject.d.ts (16,22): Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.
```

**Comment by kwonoj** [comment] 2017-06-28 02:45
dupe of https://github.com/ReactiveX/rxjs/issues/2699 , https://github.com/ReactiveX/rxjs/issues/2539, https://github.com/ReactiveX/rxjs/issues/2700 . https://github.com/ReactiveX/rxjs/issues/2701 https://github.com/ReactiveX/rxjs/issues/2702

**Closed by kwonoj** 2017-06-28 02:45 UTC

**Comment by princemaple** [comment] 2017-06-28 02:50
Ah, sorry. Thanks!
