### ISSUE TITLE
Compiler error: AsyncSubject returns Observable, should return AsyncSubject.

### ISSUE THREAD

**Issue by raysuelzer** [ReactiveX/rxjs#2982] opened 2017-10-19 23:23 UTC
**RxJS version:**
5.5.0

**Code to reproduce:**
```
 import {AsyncSubject} from 'rxjs/Rx';
export class ShouldWork {
    subject: AsyncSubject<boolean> = new AsyncSubject<boolean>().map(t => t);
}

```
**Expected behavior:**
Should not throw typescript error.  Should know that return type is a subject not observable.
**Actual behavior:**
severity: 'Error'
message: 'Type 'Observable<boolean>' is not assignable to type 'AsyncSubject<boolean>'.
  Property 'value' is missing in type 'Observable<boolean>'.'
**Additional information:**
Occurs on Typescript versions: 2.4.0, 2.4.1, 2.5.3
Occurs even with --noStrictGenericChecks

**Comment by kwonoj** [comment] 2017-10-19 23:31
It is currently known expected design of extended variant of observable doesn't carry over its characteristics  via operator chain by creating new observables. Similar, or possible dupe of https://github.com/ReactiveX/rxjs/issues/2378.

**Closed by kwonoj** 2017-10-19 23:31 UTC

**Comment by raysuelzer** [comment] 2017-10-20 22:01
This only seems partially true to me, as all of the characteristics from my return object are carried over via operator chain except for .value.  I know there is a reason for this, but it is a big bummer that you can't use typescript with AsyncSubject because it thinks it is returning an Observable when it isn't. 

![image](https://user-images.githubusercontent.com/1176341/31843385-7c81f160-b5a7-11e7-904e-ff61982c4c83.png)
