### ISSUE TITLE
Export IScheduler, Scheduler, and TeardownLogic in the Rx module

### ISSUE THREAD

**Issue by Nava2** [ReactiveX/rxjs#2725] opened 2017-07-06 04:13 UTC
**RxJS version:** 5.4.1

**Code to reproduce:**

```typescript
import { IScheduler, TeardownLogic, Scheduler } from '@reactivex/rxjs';
```

**Expected behavior:**

Compiles when importing from the module, `@reactivex/rxjs`.

**Actual behavior:**

Does not compile as the symbols are not exported in `Rx.ts`. 

**Additional information:**

Currently, the only way to use the `IScheduler` (or `Scheduler`, `TeardownLogic`, etc.) is to import it via the full `dist` modules, i.e. `@reactivex/rxjs/dist/cjs/Scheduler`. The problem with this is that IDEs and users can get confused and accidentally import `src` directories which causes issues with compilation around duplicate types as the compiler finds multiple names for the same type.

Ultimately, this comes down to an "ergonomics" concern and it seems strange to _not_ export these types. 

I tried searching for issues surrounding the justification for what types are exported and what aren't, I didn't find any discussions. If there are known/discussed justifications, please point me to them!

**Comment by kwonoj** [comment] 2017-07-06 04:18
would you elaborate

> The problem with this is that Typescript then gets confused and starts finding duplicates of the definition for other types as the compiler finds multiple names for the same type.

this more? it'd better if you can share minimal repo can reproduce issue.

**Comment by Nava2** [comment] 2017-07-06 04:20
> would you elaborate
> > The problem with this is that Typescript then gets confused and starts finding duplicates of the definition for other types as the compiler finds multiple names for the same type.

No need, as it turns out. I accidentally used the `dist/src/` paths for one of the files, which caused the errors asked. 

I'll edit the question. Though, that was caused because the types are found twice in the same folder and aren't found in the default module. Thus, (in this case) WebStorm went searching and found them in the `dist/src` folder.

**Comment by kwonoj** [comment] 2017-07-06 04:24
Currently our scoped package `@reactivex/rxjs` intended to be fully-fledged package, which include all possible builds so for some editors, or some configuration would be possibly confused. In normal cases, using CJS package `rxjs` should be sufficient - which shouldn't have these kind of errors.

**Comment by Nava2** [comment] 2017-07-06 04:26
> Currently our scoped package @reactivex/rxjs intended to be fully-fledged package, which include all possible builds so for some editors, or some configuration would be possibly confused. In normal cases, using CJS package rxjs should be sufficient - which shouldn't have these kind of errors.

Are you implying that I should be using a different npm package? Though, the mentioned types are not exported [here](https://github.com/ReactiveX/rxjs/blob/master/src/Rx.ts) -- implying they will not be present in any configuration.

**Comment by kwonoj** [comment] 2017-07-06 04:27
What I'm saying is CJS package `rxjs` should have only single packages included, so it removes possibilities of same type definition staying around single package. It doesn't changes import ergonomics in your code.

**Comment by kwonoj** [comment] 2017-07-12 03:05
I'm closing issue as I believe issue itself was explained. Once if top level export is needed, it can be discussed separately.

**Closed by kwonoj** 2017-07-12 03:05 UTC

**Comment by Nava2** [comment] 2017-07-12 03:18
I ended up using the `rxjs` package instead. This didn't change anything, but it would be useful to have these interfaces exposed as creating custom schedulers depends on them. That being said, I'm okay if the answer is no as _most_ individuals will not be writing these schedulers.

**Comment by xogeny** [comment] 2017-10-03 23:07
@kwonoj I don't understand your response.  These interfaces are apparently not available in `rxjs`, correct?  Is that by design?  If so, why?  If not, is there some other reason they aren't currently included?  Speaking for myself, I think it would be quite useful.

**Comment by kwonoj** [comment] 2017-10-03 23:13
> These interfaces are apparently not available in rxjs, correct? 

No. Those are exported, but not `top level` exported so you just can't do like `import { IScheduler } from 'rxjs'`. You can import it from actual path of interface export module.

Not all of interface / implementations are exported in top level, those are limited and other supplimentals are exported in their own module level, but it is not prohibited to import it. This issue is simply module import is confused by specific package has duplicated export and user's configuration got confused somehow, reason I closed it and track top-level export issue separatly if it's necessary. So far I do not think top level export is needed.

**Comment by kwonoj** [comment] 2017-10-03 23:18
reference for above comment: https://github.com/ReactiveX/rxjs/blob/fb3694d0bae56545c4fa31fc2cf5bb6c603f9e83/src/Scheduler.ts#L4-L6

**Comment by xogeny** [comment] 2017-10-03 23:24
I think the confusion comes from the fact that you spend a lot of time telling people **why** it isn't exported from the top-level when it might be sufficient to just say "They aren't exported from the top level." and then tell them **how** to achieve what they want (at least that is true in my case).  So for anybody who wants to import these types, you do it with:

```
import { TeardownLogic } from 'rxjs/Subscription';
import { Scheduler, IScheduler } from 'rxjs/Scheduler';
```
