### ISSUE TITLE
Redo requests after a certain time / cache expiration

### ISSUE THREAD

**Issue by StefanKern** [ReactiveX/rxjs#6260] opened 2021-04-25 14:07 UTC
## Missing feature in rxjs 7

In rxjs v7 `publishReplay`, `refCount`, etc where deprecated and **`share`** and **`shareReplay`** are now the 'only' options when wanting use the result of an observable in multiple parts of the code, without redoing the complete 'observable'. An example for this is an API call, where the result is used in two places of the application, but you don't want to hit the network each time.

This was usually done with `publishReplay` and `refCount`. If you wanted to limit the time these requests where valid, you could set a `windowTime` in `publishReplay` and after "X"ms, the request repeated. (you also had to add a `take(1)` at the end, but that would be another question/issue). This solution was taken from SO: https://stackoverflow.com/a/54957061

**With `share` or `shareReplay`, you cannot reproduce the same behaviour.**

You can pass a windowTime to `shareReplay`, however after the time is exceeded, no more values are emitted at all!

## Example how it was working before:

```
export class AppComponent {
  name = "Angular " + VERSION.major;

  urlofApi = "https://api.github.com/search/repositories?q=helloWorld";

  testX = this.http.get(this.urlofApi).pipe(
    tap(() =>
      console.log(
        `++ api was newly called at ${new Date().toLocaleTimeString()} ++`
      )
    ),
    publishReplay(1, 5000),
    refCount(),
    take(1)
  );

  constructor(private http: HttpClient) {}

  test() {
    console.log("Requesting data from API");
    this.testX.pipe(take(1)).subscribe(() => console.log("completed"));
  }
}
```
rxjs: 6.6.3
Stackblitz: https://stackblitz.com/edit/angular-ivy-tyrbdw?file=src%2Fapp%2Fapp.component.ts
Result:
![image](https://user-images.githubusercontent.com/2032760/115996371-39be6080-a5df-11eb-8a6f-11d677dc718b.png)

Example with shareReplay
  ```
testX = this.http.get(this.urlofApi).pipe(
    tap(() =>
      console.log(
        `++ api was newly called at ${new Date().toLocaleTimeString()} ++`
      )
    ),
    shareReplay(1, 5000)
  );
```
rxjs": "^7.0.0-rc.2
Stackblitz: https://stackblitz.com/edit/angular-ivy-ggkvpw?file=src%2Fapp%2Fapp.component.ts
Result;
![image](https://user-images.githubusercontent.com/2032760/115996424-83a74680-a5df-11eb-94fc-0f228cc6933a.png)

**Note how the Observable doesn't emit anything anymore, after 5sec**.

## Expected behaviour:

Requests are repeated once the windowTime is exceeded.

**Comment by cartant** [comment] 2021-04-25 14:30
https://github.com/ReactiveX/rxjs/blob/7.0.0-rc.2/src/internal/operators/shareReplay.ts#L32-L39

**Comment by StefanKern** [comment] 2021-04-25 15:40
@cartant I cannot follow your comment. Tried setting refCount to true, and then it does the request each time.

Was it intended more as an internal comment?

PS: seems like I exceeded the limit for calling the github api with HelloWorld. Had to change the searchstring...

**Comment by cartant** [comment] 2021-04-26 07:38
I left the terse comment because it appeared to be a straightforward `refCount` issue - that's what's mentioned in the linked SO answer.

Looking at it more closely, I suspect that the behaviour upon which you are relying is a bug - see https://github.com/ReactiveX/rxjs/pull/5696 - as it makes no sense. Once a subject errors or completes, that's supposed to be it; the subject should not receive additional notifications from any source to which it is subscribed. And `publish` - and its variants - create a single subject when the operator itself is called; the subject is not reset when the source errors or completes.

Working as intended, AFAICT.

**Comment by StefanKern** [comment] 2021-04-26 07:57
I see, hmm but I'm kinda relaying on this functionallity. Is there a way to get the same behaviour with other functions?

To me, the usecase seems quite reasonable :)

**Comment by cartant** [comment] 2021-04-26 08:27
I don't have time, ATM. Ask on SO - or in discussions in the repo or both - and reference the original SO answer and my comment above. It's definitely relying on a bug, IMO, so I'm closing this.

**Closed by cartant** 2021-04-26 08:27 UTC

**Comment by josepot** [comment] 2021-04-26 09:37
Hi @StefanKern 

One thing that can be a bit surprising about `shareReplay` with `refCount` is that if the the source completes, then that's it: the resulting observable will never re-subscribe to the source, and every time that a new subscriber comes: it will replay the latest value(s) and the complete. I once [opened an issue](https://github.com/ReactiveX/rxjs/issues/5455) because I thought that was a bug :sweat_smile:.

So, since your source is an Observable that emits once and then it completes, then I would suggest enhancing it so that it doesn't complete, i.e: `concat(source, NEVER)`

Ok, sure, but then how do we make sure that the cached value stays alive for a certain amount of time :thinking:? 

I suggest using a pipeable operator like this:

```ts
const delayLatestUnsubscription = (ms: number) => <T>(source$: Observable<T>) => {
  let token = 0
  let cleanupFn: (() => void) = noop
  return new Observable<T>(observer => {
    const subscription = source$.subscribe(
      (v) => {
        observer.next(v)
      },
      (e) => {
        observer.error(e)
      },
      () => {
        observer.complete()
      }
    )
    cleanupFn()

    return () => {
      cleanupFn = () => {
        clearTimeout(token)
        cleanupFn = noop
        subscription.unsubscribe()
      }
      token = setTimeout(cleanupFn, ms)
    }
  })
}
``` 

[Let's put it together](https://stackblitz.com/edit/angular-ivy-zcyycj?file=src%2Fapp%2Fapp.component.ts):

```ts
@Component({
  selector: "my-app",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"]
})
export class AppComponent {
  name = "Angular " + VERSION.major;

  urlofApi = "https://api.github.com/search/repositories?q=helloWorld";

  testX = concat(
    this.http.get(this.urlofApi),
    NEVER
  ).pipe(
    tap(() =>
      console.log(
        `++ api was newly called at ${new Date().toLocaleTimeString()} ++`
      )
    ),
    shareReplay({
      bufferSize: 1,
      refCount: true
    }),
    delayLatestUnsubscription(5000),
  );

  constructor(private http: HttpClient) {}

  test() {
    console.log("Requesting data from API");
    this.testX.pipe(take(1)).subscribe(
      (value) => {
        console.log("value received", value)
      }
    );
  }
}
```

I think that this solution has the behavior that you were expecting and it works on both RxJS 6 and 7. I'm sure that there are other ways to get the same behavior, but this is the first one that came to mind. I hope this helps.

**Comment by martinsik** [comment] 2022-07-14 13:57
@StefanKern I updated the answer in https://stackoverflow.com/questions/54947878/temporarily-caching-http-responses-from-parametrised-requests-using-rxjs-and-an/54957061#54957061 and posted a different solution for RxJS 7.0+
