### ISSUE TITLE
typeerrors when using typescript 2.4.0

### ISSUE THREAD

**Issue by veeramarni** [ReactiveX/rxjs#2716] opened 2017-07-01 20:19 UTC
We are seeing typeerrors after upgrading typescript to 2.4.0 version in our project

**RxJS version: 5.4.0**

**Code to reproduce:**
When we upgrade the [project](https://github.com/cdmbase/fullstack-pro) to typescript@2.4.0 we getting these errors but we don't see them in version 2.3.0
**Expected behavior:**
No errors
**Actual behavior:**
```
[at-loader] ./node_modules/rxjs/Subject.d.ts:16:22
    TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.

[at-loader] ./node_modules/rxjs/observable/dom/WebSocketSubject.d.ts:24:22
    TS2415: Class 'WebSocketSubject<T>' incorrectly extends base class 'AnonymousSubject<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => WebSocketSubject<R>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<T>'.
      Type 'WebSocketSubject<R>' is not assignable to type 'Observable<T>'.
        Types of property 'operator' are incompatible.
          Type 'Operator<any, R>' is not assignable to type 'Operator<any, T>'.
            Type 'R' is not assignable to type 'T'.
```
**Additional information:**

**Comment by kwonoj** [comment] 2017-07-01 20:22
dupe of #2699 , #2539, #2700 . #2701 #2702 #2703 https://github.com/ReactiveX/rxjs/issues/2704 https://github.com/ReactiveX/rxjs/issues/2705 https://github.com/ReactiveX/rxjs/issues/2706 https://github.com/ReactiveX/rxjs/issues/2707

**Closed by kwonoj** 2017-07-01 20:22 UTC

**Comment by amitgaur208** [comment] 2017-09-07 09:40
This problem is not solved using version change of typescript please help.
