### ISSUE TITLE
I am connecting to a websocket and I get this error after a some time: SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by xtianus79** [ReactiveX/rxjs#5517] opened 2020-06-22 04:49 UTC
## Bug Report

**Current Behavior**
I don't know why this is occurring. I am testing on my localhost with a wss type socket connection. When it is connected the data comes through the socket fine. When I use external testing tools, they stay connected to the socket fine. I don't know why this is occurring but when the error emits, afterwards no more messages get emitted. 

```javascript
   if (this.isBrowser) {
      console.log('THIS WORKEDDDDD ');
      const subject = webSocket("wss://directline.botframework.com/v3/directline/conversations/1zRgrgUTSnkPiFuLYjSDS-5/stream?watermark=-&t=xxxxxxxxx");
      subject.subscribe(
        msg => console.log('message received: ' + JSON.stringify(msg['activities'][0]['text'])), // Called whenever there is a message from the server.
        err => console.log('ERROR from socket ', err), // Called if at any point WebSocket API signals some kind of error.
        () => console.log('complete') // Called when connection is closed (for whatever reason).
      );

> messages comes through but then after about a minute this error appears 

ERROR from socket  SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at deserializer (WebSocketSubject.js:8)
    at WebSocket.socket.onmessage [as __zone_symbol__ON_PROPERTYmessage] (WebSocketSubject.js:173)
    at WebSocket.wrapFn (zone-evergreen.js:1218)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41632)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:480)
    at invokeTask (zone-evergreen.js:1621)
```

**Reproduction**
download directline api and try to connect with a websocket
```js
var your => (code) => here;
```

**Expected behavior**
For this not to happen

**Environment**
chrome, node, express, Angular 9 Universal and RXJS 6+
- (If bug is related) Loader, build configuration: [e.g webpack, angular-cli version, config]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by kwonoj** [comment] 2020-06-22 04:51
It is not easily able to determine if this is core lib issue or application code side issue. Please provide reproducible code without the application code involved.

**Comment by xtianus79** [comment] 2020-06-22 15:39
@kwonoj I know what's happening I can walk through it because otherwise you would need a Microsoft botframework scenario setup. 

So what's happening is that the websocket will emit MessageEvents that have data, and when they don't have data the error gets emitted. 

Now, right there to me that seems very odd. Like data doesn't get emitted so an error is thrown. Now the error is recognized but it is not handled so the stream dies and any subsequent messages don't make it through the stream. 

So what i've done, or have tried to do is filter out the errors. MULTIPLE, lol multiple ways, but what's odd is that filtering doesn't work when the error is emitted. 

Here is what is what I mean. 
This is a correct message. 
```javascript
message received:  
MessageEvent {isTrusted: true, data: "{
↵  "activities": [
↵    {
↵      "type": "messag…hT-5|0000007"
↵    }
↵  ],
↵  "watermark": "8"
↵}", origin: "wss://directline.botframework.com", lastEventId: "", source: null, …}
bubbles: false
cancelBubble: false
cancelable: false
composed: false
currentTarget: WebSocket {__zone_symbol__openfalse: Array(1), __zone_symbol__errorfalse: Array(1), __zone_symbol__ON_PROPERTYopen: ƒ, __zone_symbol__ON_PROPERTYerror: ƒ, __zone_symbol__ON_PROPERTYclose: ƒ, …}
data: "{
↵  "activities": [
↵    {
↵      "type": "message",
↵      "id": "IB4EjWeat0ttVlDCylFhT-5|0000008",
↵      "timestamp": "2020-06-22T15:19:51.3151486Z",
↵      "channelId": "directline",
↵      "from": {
↵        "id": "xxxx-xxxx-bot",
↵        "name": "xxxx-xxxx-bot"
↵      },
↵      "conversation": {
↵        "id": "IB4EjWeat0ttVlDCylFhT-5"
↵      },
↵      "text": "Before I begin, do you give me permission to know your location?",
↵      "speak": "Before I begin, do you give me permission to know your location?",
↵      "inputHint": "expectingInput",
↵      "suggestedActions": {
↵        "actions": [
↵          {
↵            "type": "imBack",
↵            "title": "Yes",
↵            "value": "Yes"
↵          },
↵          {
↵            "type": "imBack",
↵            "title": "No",
↵            "value": "No"
↵          }
↵        ]
↵      },
↵      "replyToId": "IB4EjWeat0ttVlDCylFhT-5|0000007"
↵    }
↵  ],
↵  "watermark": "8"
↵}"
defaultPrevented: false
```
Now, because I have deserialized the event output i can mitigate the error BUT I still can't filter it. So when it propagates through this is what it looks like now. 
This message will be pushed through every minute or so when there is no activity. There is an empty data string. I have no control over this service.
```javascript
message received:  
MessageEvent {isTrusted: true, data: "", origin: "wss://directline.botframework.com", lastEventId: "", source: null, …}
bubbles: false
cancelBubble: false
cancelable: false
composed: false
currentTarget: WebSocket {__zone_symbol__openfalse: Array(1), __zone_symbol__errorfalse: Array(1), __zone_symbol__ON_PROPERTYopen: ƒ, __zone_symbol__ON_PROPERTYerror: ƒ, __zone_symbol__ON_PROPERTYclose: ƒ, …}
**data: ""**
```
Now as I subscribe to it and I try to do any filtering at all it will break the same way as before as if I did NOT serialize the output. The commented out code is me trying to filter. 

```javascript
subject
      .subscribe(
        // msg => console.log('message received: ' + JSON.stringify(msg['activities'][0]['text'])), // Called whenever there is a message from the server.
        msg => {
          //   const message = JSON.parse(msg.data);
          //  if (message && Object.keys(message).length >= 0) {
          //     console.log(' message.activities[0].text === ', message)
          //     console.log(' message.activities[1].text === ', message.activities)
          //     if (message.activities && message.activities.length >= 0 && message.activities[0].type === 'message') {
          //       console.log('THI IS E ', message.activities[0]);
          //     }
          //   }
          if (msg) {
            console.log('YOUR MOM landed here', typeof msg);
          }
          console.log('message received: ', msg)
          this.test = msg;
        }, // Called whenever there is a message from the server.
        err => console.log('ERROR from socket ', err), // Called if at any point WebSocket API signals some kind of error.
        () => console.log('complete') // Called when connection is closed (for whatever reason).
      );
```
Next I tried to use the multiplex feature which isn't explained very well but I assume it is for filtering and multiple subscription streams... please correct me if I have misunderstanding about that. 

This does not work either on an empty message data stream. It will break. I turned off the deserializer here so it would work properly. 

Here is that code
```javascript
 const observableA = subject.multiplex(
        () => ({subscribe: '*'}), // When server gets this message, it will start sending messages for 'A'...
        () => ({unsubscribe: 'A'}), // ...and when gets this one, it will stop.
        message => message['activities'][0].type === 'message' // If the function returns `true` message is passed down the stream. Skipped if the function returns false.
      );
      const subA = observableA.subscribe(messageForA => console.log('messageForA', messageForA));
```
I am at a loss for this. I've tried everything I can think of but it seems very odd that it can't handle an empty data return on the messageevent stream. 

Also, it is very difficult to work with the data inside of the subscription. It seems ultra rigid and final it a sense that if I do something to the data returned in the message stream it will break very easily and the data mutated is very specific to what happened upstream rather than a resultant downstream object.

**Comment by xtianus79** [comment] 2020-06-22 16:44
@kwonoj OK!!! I got this working. 
```javascript
const subject = webSocket({
        url: "wss://directline.botframework.com/v3/directline/conversations/6CfcaVC16kS5DWANERytzW-j/stream?watermark=-&t=xxxxxxxxxxxxxxxx",
        deserializer: (events) => {
          // if (events.data && events.data.activities) {
          //   console.log('your dad is here');
          // }
          console.log('HEREO')
          return events
        }
      });
      // Object.keys(message.data).length >= 1
      const observableA = subject.multiplex(
        () => ({subscribe: '*'}), // When server gets this message, it will start sending messages for 'A'...
        () => ({unsubscribe: 'A'}), // ...and when gets this one, it will stop.
        message => Object.keys(message.data).length >= 1
        // message => message['activities'][0].type === 'message' // If the function returns `true` message is passed down the stream. Skipped if the function returns false.
      );
      const subA = observableA.subscribe(messageForA => {
        const message = JSON.parse(messageForA.data);
        console.log('message HERE <<<<< ', message)
        if (message.activities && message.activities.length >= 0 && message.activities[0].type === 'message') {
          console.log('THIS IS E ', message.activities[0].text);
        }
        // console.log('messageForA', messageForA);
      }); 
``` 

So, I mean JESUS lol. This will now hold a websocket connection without breaking. And I can now filter on the result. So 2 good things. However, to me a little bit of code smell. I should be able to filter empty data sets naturally without all this. 

Now, my next question is... Can I subscribe.next? in the flow to print out to the dom? How would I do that?

**Comment by cartant** [comment] 2021-05-01 05:30
Closing this because:

> It is not easily able to determine if this is core lib issue or application code side issue. Please provide reproducible code without the application code involved.

And:

> OK!!! I got this working.

**Closed by cartant** 2021-05-01 05:30 UTC
Labels: status: needs info
