### ISSUE TITLE
using Rx.Observable.from in Angular-cli meet this problem

### ISSUE THREAD

**Issue by xiehongyang** [ReactiveX/rxjs#2622] opened 2017-05-28 03:03 UTC
**RxJS version:**
^5.1.0
**Code to reproduce:**
```
var set = new Set([1,2,3,4,5]);

// Converts a Set to an observable sequence
var source = Rx.Observable.from(set);

// Prints out each item
var subscription = source.subscribe(
  x => console.log('onNext: %s', x),
  e => console.log('onError: %s', e),
  () => console.log('onCompleted'));
```

**Expected behavior:**
print 1, 2, 3, 4, 5 on screen
**Actual behavior:**
doesn't work and some errors
**Additional information:**
using Webstorm and complier tell me this : 
**ERROR in D:/my_project/rxjs/src/app/app.component.ts (17,24): Argument of type 'Set<string | Window>' is not assignable to parameter of type 'ArrayLike<{}>'.
  Property 'length' is missing in type 'Set<string | Window>'.**

**Comment by kwonoj** [comment] 2017-05-28 03:29
Description: https://github.com/ReactiveX/rxjs/blob/master/src/MiscJSDoc.ts#L329-L335

dupe of #2306.

**Closed by kwonoj** 2017-05-28 03:29 UTC
