### ISSUE TITLE
Strange behavior from forkJoin on a Map.prototype.values iterable

### ISSUE THREAD

**Issue by jasonbaker** [ReactiveX/rxjs#4748] opened 2019-04-29 17:33 UTC
## Bug Report

I'm trying to build a Map where the key is a string and value is an observable. I want to make an Observable that waits on all of the values in this map.

**Current Behavior**
The behavior seems to be weird whenever you pass in an iterable from Map.prototype.values()

**Reproduction**
- REPL or Repo link:
https://stackblitz.com/edit/rxjs-jmnxda

The key part is here:

```js
forkJoin(obsMap.values()).subscribe(x => console.log(x));
```
This makes the console.log statement log an array that contains a single observable with the last value of the iterable. However, if I [plug the iterable](https://stackblitz.com/edit/rxjs-tflvyk) into Array.from it works as I'd expect it:

```js
forkJoin(Array.from(obsMap.values())).subscribe(x => console.log(x));
```

**Expected behavior**
I'd expect the behavior to be the same for the iterable version and the array version.

**Environment**
- Runtime: Chrome 74.0.3729.108 
- RxJS version: 6.4

**Comment by kwonoj** [comment] 2019-04-29 17:43
This is due to we expect specific (i.e `length` property) to determine certain execution paths of given inputs, reason why `Array.from` will makes this work. 

I personally don't have any opinion at this moment if we'd need to support mapiterator for this or not, but curious if other operator we have supports iterables would work same way.

**Comment by cartant** [comment] 2019-04-29 19:45
It's likely that this is related to the problem solved in https://github.com/ReactiveX/rxjs/pull/4741

**Comment by jasonbaker** [comment] 2019-04-30 22:14
If the code isn't intended to support mapiterator (or other iterators), that may be ok. But if that's the case, I would expect to get an error of some kind that says iterators aren't supported rather than code that silently does the wrong thing and gives a weird resposne.

**Comment by cartant** [comment] 2019-05-02 09:22
Closing this because this is the expected behaviour. If [an array is passed as a single argument](https://github.com/ReactiveX/rxjs/blob/986be2f1a1186cbbd1b2dc68fe6d11ba1f32247e/src/internal/observable/forkJoin.ts#L146-L148), that array is interpreted as the array of observable inputs.

This can be seen in the [TypeScript signatures](https://github.com/ReactiveX/rxjs/blob/986be2f1a1186cbbd1b2dc68fe6d11ba1f32247e/src/internal/observable/forkJoin.ts#L11-L34), too.

The behaviour is by-design. However, there is an ongoing discussion about how this sort of thing can rationalised in v7 - so that there are fewer surprises. And I agree with you that, as  it is, the API's behaviour is strange.

**Closed by cartant** 2019-05-02 09:22 UTC
