### ISSUE TITLE
Wrong behavior of Observable<never> type

### ISSUE THREAD

**Issue by Webbrother** [ReactiveX/rxjs#5373] opened 2020-04-02 11:34 UTC
## Bug Report

**Current Behavior**
If I define `Observable<never>` I expect a TS error when I subscribe to the Observable.
But at the moment no related error.

**Reproduction**
- link: https://stackblitz.com/edit/observable-never

```ts
let o: Observable<never> = new Observable((observer) => {});

// no TS error here
o.subscribe(() => {
  
});
```

**Expected behavior**
TS throws an error when I subscribe to Observable<never>.

**Environment**
- Runtime: Node v13.12.0, npm 6.14.4
- RxJS version: 6.5.4

**Comment by cartant** [comment] 2020-04-02 11:52
Not a bug. TypeScript knows nothing about the semantics of `subscribe` and there is no type conflict with the passed callback.

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#the-never-type

**Comment by Webbrother** [comment] 2020-04-02 11:59
@cartant 
If this is not a bug when should I use `Observable<never>`? What advantages does such a type provide to programmer? What are the use cases for such a type?

**Comment by martinsik** [comment] 2020-04-02 12:19
@Webbrother Angular source code has plenty of use-cases:

- https://github.com/angular/angular/blob/f8096d499324cf0961f092944bbaedd05364eea1/packages/service-worker/src/update.ts#L42-L43

- https://github.com/angular/angular/blob/5eb7426216b1597cca3a7923cc714e59464fec89/packages/zone.js/test/rxjs/rxjs.never.spec.ts#L20

- https://github.com/angular/angular/blob/65aaffcfe450b0e2149cf82b910db595909456e4/packages/service-worker/src/push.ts#L130

**Comment by cartant** [comment] 2021-03-15 12:18
Closing for reasons outlined in comments above.

**Closed by cartant** 2021-03-15 12:18 UTC
