### ISSUE TITLE
Testing with Jasmine - Async object not exists

### ISSUE THREAD

**Issue by nischi** [ReactiveX/rxjs#2564] opened 2017-04-19 05:03 UTC
**RxJS version:**
5.3.0

**Code to reproduce:**
https://github.com/nischi/angular-testing
https://github.com/angular/angular/issues/15889

**Expected behavior:**
Test should fail because array do not exists

**Actual behavior:**
Test pass

**Additional information:**
https://github.com/angular/angular/issues/15889
I have discussed that with the angular team, but they said its a problem with rxjs and jasmine not angular itself, thats the reason why i put the issue here as well.

**Comment by kwonoj** [comment] 2017-04-19 05:25
It doesn't seem like Rx issue, jasmine seems try to be smart to catch some of unexpected exceptions thrown, and it's shallowed somehow. So in your test code, it asserts

```js
expect(obj.data.length).toBe(100);
```
and `obj.data` is `undefined`, so evaluating `obj.data.length`  will throws exception - so there isn't any execution to assertion actually occurred. 

instead, if you make `data` property actually available,

```
class myObject {
  count = 0;
  data: mySecondObject[] = []; //empty array instance exposes `length`
}
```

now you can see test fails. If you change your assertion like below,
```js
try {
  const a = obj.data.length;
  expect(a).toBe(100);
} catch (e) {
  console.log(e);
}
```
you can see exception more clear like 

![image](https://cloud.githubusercontent.com/assets/1210596/25164463/d6e05952-2485-11e7-9097-2ddd20689cad.png)

It is hard to say what makes this causes exactly though, my current assumption is it's somewhat unrelated to Rx's regression - if you're throwing unhandled exception in observer callbacks, Observable can't do lot of things pretty much.

**Comment by nischi** [comment] 2017-04-19 07:28
Sure i can set the Array to a default value. But if i do a async call to an api it could be taht the "data" is not existing. If that is the case it should be fail. And not pass as it does right now. 

Do you think i should open an issue on jasmin project?

**Comment by kwonoj** [comment] 2017-04-19 15:35
So it seems like #2565 is exact same symptom. Since it isolates cases more clear without involving ng or jasmine, I'm closing this issue and track this under #2565. I need to dig into history if this is intended changes or not.

**Closed by kwonoj** 2017-04-19 15:35 UTC
