### ISSUE TITLE
rxjs@6.5.2 has no rxjs-compat refference at package.json

### ISSUE THREAD

**Issue by brainee** [ReactiveX/rxjs#5129] opened 2019-11-07 06:43 UTC
## Bug Report

**Current Behavior**
when i use 
import { BehaviorSubject } from 'rxjs/BehaviorSubject';
i got an error:
Module not found: Error: Can't resolve 'rxjs-compat/BehaviorSubject' in '/Users/zolad/work/app/cw/cw4/node_modules/rxjs'
 @ /Users/zolad/work/app/cw/cw4/node_modules/rxjs/BehaviorSubject.js 6:9-47

**Reproduction**

```js
import { BehaviorSubject } from 'rxjs/BehaviorSubject';

```

**Expected behavior**
add  rxjs-compat refference at package.json for rxjs@6.5.2 

**Environment**
- Runtime: [e.g. Node v10, Chrome v58]
- RxJS version:6.5.2 
- (If bug is related) Loader, build configuration: [e.g webpack, angular-cli version, config]

**Possible Solution**

add  rxjs-compat refference at package.json for rxjs@6.5.2

**Comment by cartant** [comment] 2019-11-07 06:47
`import { BehaviorSubject } from 'rxjs/BehaviorSubject';` is not a valid import location unless `rxjs-compat` is installed. This is not a bug.

The valid import locations for v6 are listed here:

https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md#import-paths

**Comment by kwonoj** [comment] 2019-11-12 17:01
Closing as answered above.

**Closed by kwonoj** 2019-11-12 17:01 UTC
