### ISSUE TITLE
TypeError in Scheduler

### ISSUE THREAD

**Issue by NiKlimenko** [ReactiveX/rxjs#3309] opened 2018-02-11 13:58 UTC
**RxJS version:** 5.5.6

**Code to reproduce:**
 ```
import {observeOn} from 'rxjs/operators/observeOn';
import {Scheduler} from 'rxjs/Rx';

someObservable.pipe(
      observeOn(Scheduler.asap)
    )
      .subscribe(() => {});
```

**Expected behavior:**
Should work correctly, without compilation errors.

**Actual behavior:**
```
ERROR in node_modules/rxjs/scheduler/VirtualTimeScheduler.d.ts(24,15): error TS2416: Property 'work' in type 'VirtualAction<T>' is not assignable to the same property in base type
'AsyncAction<T>'.
  Type '(this: VirtualAction<T>, state?: T | undefined) => void' is not assignable to type '(this: AsyncAction<T>, state?: T | undefined) => void'.
    The 'this' types of each signature are incompatible.
      Type 'AsyncAction<T>' is not assignable to type 'VirtualAction<T>'.
        Property 'index' is missing in type 'AsyncAction<T>'.
````

**Additional information:** 
TypeScript 2.7

**Comment by kwonoj** [comment] 2018-02-11 15:35
Dupe of https://github.com/ReactiveX/rxjs/issues/3031 .

**Closed by kwonoj** 2018-02-11 15:35 UTC
