### ISSUE TITLE
combineLatest on synchronous sources

### ISSUE THREAD

**Issue by staltz** [ReactiveX/rxjs#2414] opened 2017-02-24 20:41 UTC
**RxJS version:** 5.1.0

**Code to reproduce:**

```js
const a$ = Rx.Observable.of(1, 2);
const b$ = Rx.Observable.of(10);

const c$ = Rx.Observable.combineLatest(a$, b$, (a,b)=>a+b);

c$.subscribe(c => console.log(c));
```

**Expected behavior:**

```
11
12
```

**Actual behavior:**

```
12
```

**Additional information:**

I'm not sure is this a bug or a "feature". What should we do about this case? Is it just one of those "let's instruct people to choose a different scheduler if they want to have the expected behavior"? 

For reference:
xstream: https://github.com/staltz/xstream/issues/173
most.js: https://github.com/cujojs/most/issues/414

**Comment by trxcllnt** [comment] 2017-02-25 02:27
While zip is generally applicable to lists, combineLatest is undefined without the time dimension. The current behavior is fine, because the solution is to introduce your own notion of time. Rx generally shies away from defining one for you.

**Comment by mattpodwysocki** [comment] 2017-03-06 15:22
@trxcllnt no, this is a bug and a breaking change from RxJS v4.x.  Please fix

**Comment by trxcllnt** [comment] 2017-03-06 17:44
@mattpodwysocki you get this behavior from the recursive scheduler in v4. The "fix" in v5 is to use the queue scheduler. If you know of a solution that doesn't impact throughput performance, I'd be happy to change my recommendation.

**Comment by benlesh** [comment] 2017-10-12 14:50
I tend to agree with @trxcllnt on this one, although I haven't commented. Forcing queue scheduling on an operator in JavaScript is like trying to force the library to mimic some sort of gated/threaded model, which the majority of JS developers know it isn't. Once it's sunk in that `Observable.of` is synchronous by default the current behavior is obvious. What's outlined as the expected behavior here is less obvious as it deviates from how JavaScript fundamentally works.

Given this issue has been here this long and there's been little interest, I'd say the current behavior is fine and we can close the issue.

The "fix" if you want to change the behavior is to use the queue scheduler on incoming sources.

**Comment by c-dante** [comment] 2018-04-02 03:24
I like the recommendation to define your own scheduling here. I disagree that `11, 12` is expected when using a synchronous observable like that. I think at best this is an item for the docs to make the Scheduler argument of `Observable.of` more explicit?

**Closed** 2018-04-02 05:14 UTC
Labels: type: bug

**Comment by brucou** [comment] 2018-05-08 22:15
The biggest problem I see with Rxjs v5 semantics is that order matters, which is confusing at least to me.

That is to say 

```javascript
const a$ = Rx.Observable.of(1, 2);
const b$ = Rx.Observable.of(10);

const c$ = Rx.Observable.combineLatest(a$, b$, (a,b)=>a+b);

c$.subscribe(c => console.log(c));
```

will output `12` as Andre mentioned.

However, switch `a` and `b` and you will get `11, 12`.

```javascript
const a$ = Rx.Observable.of(1, 2);
const b$ = Rx.Observable.of(10);

const c$ = Rx.Observable.combineLatest(b$, a$, (a,b)=>a+b);

c$.subscribe(c => console.log(c));
```

**Comment by brucou** [comment] 2018-05-09 02:27
For what is worth, `Bacon.js` has the same behavior as rxjs v5: http://jsfiddle.net/wp3xp50e/
