### ISSUE TITLE
Add RxJs version to website for clarity:  http://reactivex.io/rxjs/

### ISSUE THREAD

**Issue by MatteoNY** [ReactiveX/rxjs#3705] opened 2018-05-17 13:45 UTC
Many thanks for the great work with Rxjs6. When I do a Google search on Rxjs6 I still find links to version 4 and 5.  On the RxJS website I do not see any reference to the version and it would be great if the website could either post it on the toolbar header , home or an about page. 

It would be great if you could follow what Angular.io is doing with current and past versions which helps to eliminate confusion on syntax. Thanks in advance.

**Comment by kwonoj** [comment] 2018-05-17 18:56
dupe of https://github.com/ReactiveX/rxjs/issues/2258, and tracking in https://github.com/ReactiveX/rxjs-docs also.

**Closed by kwonoj** 2018-05-17 18:56 UTC
