### ISSUE TITLE
Uncaught AjaxError - React Native / Android

### ISSUE THREAD

**Issue by tuomohopia** [ReactiveX/rxjs#3878] opened 2018-06-29 16:01 UTC
I'm getting the following error on React Native:
![ajaxerror](https://user-images.githubusercontent.com/25904171/42100941-504f5044-7bca-11e8-83f1-66861444e75f.png)

I'm using `redux-observable` with the following code snippet:
```javascript
const tokenEpic = (action$, state$) => action$.pipe(
  ofType(UPDATE_DEVICE_TOKEN),
  mergeMap((action) => {
    const updatePath = `${API}/users/${action.id}`;
    const updateBody = {
      action: "update_token",
      new_token: action.token,
    };
    const settings = {
      url: updatePath,
      method: "PATCH",
      body: updateBody,
      timeout: 1000,
    };
    return ajax(settings).pipe(
      map((result) => {
        const data = result;
        return updateTokenSuccess(data.response.data.token);
      }),
      retry(3),
      catchError(error => of(showApiCallFailed())),
    );
  }),
);
```

Observations:
- React Native (Android Emulator) _instantly_ produces this error whenever the server responds with a HTTP 501 error
- It does not even seem to retry before throwing that uncaught error
- If there is no server responding to the HTTP call, it takes 75 seconds (a timeout?) to produce the same error, regardless of the `timeout` config
- If I run React Native's javascript in the debugger (`Debug JS Remotely` - I think it's running on Chrome V8), not on the emulator:
    - this uncaught error does not appear to be thrown - `showApiCalled()` gets produced as expected
    - the long timeout (75 sec) still applies regardless of the config
    - if `retry(3)` is there, the timeout is 5 minutes before producing `showApiCallFailed()`

All in all, it seems to have something to do with how JS is run on Android in React Native.

Versions:
```
react-native@0.55.3
redux-observable@1.0.0
rxjs@6.2.1
```

**Comment by kwonoj** [comment] 2018-06-29 16:15
dupe of https://github.com/ReactiveX/rxjs/issues/3738 .

**Closed by kwonoj** 2018-06-29 16:15 UTC
