### ISSUE TITLE
Module not found: Error: Can't resolve 'rxjs/Observable'

### ISSUE THREAD

**Issue by Gajendrasinh** [ReactiveX/rxjs#4896] opened 2019-07-01 07:47 UTC
Hello

I am getting below errors when i was try to run ng build command in angular 8

    "rxjs": "^6.5.2",
    "rxjs-compat": "^6.5.2",

ERROR in ~/node_modules/@angular/core/src/facade/async.js
Module not found: Error: Can't resolve 'rxjs/Observable' in 'C:\Users\gazala\Desktop\node_modules\@angular\core\src\facade'
ERROR in ~/node_modules/@angular/forms/src/facade/async.js
Module not found: Error: Can't resolve 'rxjs/Observable' in 'C:\Users\gazala\Desktop\node_modules\@angular\forms\src\facade'
ERROR in ~/node_modules/@angular/http/src/backends/xhr_backend.js
Module not found: Error: Can't resolve 'rxjs/Observable' in 'C:\Users\gazala\Desktop\node_modules\@angular\http\src\backends'
ERROR in ~/node_modules/@angular/http/src/backends/jsonp_backend.js
Module not found: Error: Can't resolve 'rxjs/Observable' in 'C:\Users\gazala\Desktop\node_modules\@angular\http\src\backends'
ERROR in ~/node_modules/ng2-translate/src/translate.service.js
Module not found: Error: Can't resolve 'rxjs/Observable' in 'C:\Users\gazala\Desktop\node_modules\ng2-translate\src'
ERROR in ~/node_modules/@angular/core/src/facade/async.js
Module not found: Error: Can't resolve 'rxjs/Subject' in 'C:\Users\gazala\Desktop\node_modules\@angular\core\src\facade'
ERROR in ~/node_modules/@angular/forms/src/facade/async.js
Module not found: Error: Can't resolve 'rxjs/Subject' in 'C:\Users\gazala\Desktop\node_modules\@angular\forms\src\facade'
ERROR in ~/node_modules/ng2-translate/src/translate.service.js
Module not found: Error: Can't resolve 'rxjs/add/observable/of' in 'C:\Users\gazala\Desktop\node_modules\ng2-translate\src'
ERROR in ~/node_modules/ng2-translate/src/translate.service.js
Module not found: Error: Can't resolve 'rxjs/add/operator/map' in 'C:\Users\gazala\Desktop\node_modules\ng2-translate\src'
ERROR in ~/node_modules/ng2-translate/src/translate.service.js
Module not found: Error: Can't resolve 'rxjs/add/operator/merge' in 'C:\Users\gazala\Desktop\node_modules\ng2-translate\src'
ERROR in ~/node_modules/ng2-translate/src/translate.service.js
Module not found: Error: Can't resolve 'rxjs/add/operator/share' in 'C:\Users\gazala\Desktop\node_modules\ng2-translate\src'
ERROR in ~/node_modules/ng2-translate/src/translate.service.js
Module not found: Error: Can't resolve 'rxjs/add/operator/take' in 'C:\Users\gazala\Desktop\node_modules\ng2-translate\src'
ERROR in ~/node_modules/ng2-translate/src/translate.service.js
Module not found: Error: Can't resolve 'rxjs/add/operator/toArray' in 'C:\Users\gazala\Desktop\node_modules\ng2-translate\src'
ERROR in ~/node_modules/@angular/forms/src/model.js
Module not found: Error: Can't resolve 'rxjs/observable/fromPromise' in 'C:\Users\gazala\Desktop\node_modules\@angular\forms\src'
ERROR in ~/node_modules/@angular/forms/src/validators.js
Module not found: Error: Can't resolve 'rxjs/operator/toPromise' in 'C:\Users\gazala\Desktop\node_modules\@angular\forms\src'
ERROR in ~/node_modules/@angular/core/src/util/lang.js
Module not found: Error: Can't resolve 'rxjs/symbol/observable' in 'C:\Users\gazala\Desktop\node_modules\@angular\core\src\util'

**Comment by PavelStencl** [comment] 2019-07-04 08:59
It is probably because you have stable 6.5 version of RxJs installed instead of 7 alpha.
v6 import: import {Observable} from "rxjs";
v7 import: import {Observable} from rxjs/Observable;

**Comment by Gajendrasinh** [comment] 2019-07-05 01:47
@PavelStencl 

I have stable 6.5 version of RxJs installed.

import like this : import {Observable} from "rxjs";

**Comment by kwonoj** [comment] 2019-07-16 23:14
Please provide reproducible repo, and ensure if there's any other version of rx is installed more than one.

**Comment by kwonoj** [comment] 2019-09-24 17:26
closing as lacks of info.

**Closed by kwonoj** 2019-09-24 17:26 UTC
Labels: status: needs info
