### ISSUE TITLE
Cannot find type definition file for 'chai'

### ISSUE THREAD

**Issue by jefbarn** [ReactiveX/rxjs#2112] opened 2016-11-06 16:19 UTC
New in rc.2:

C:\projects\dayapp\node_modules\rxjs\observable\PairsObservable.d.ts
Error:(1, 1) TS2688: Cannot find type definition file for 'chai'.
C:\projects\dayapp\node_modules\rxjs\observable\dom\AjaxObservable.d.ts
Error:(1, 1) TS2688: Cannot find type definition file for 'chai'.

workaround
``` 
npm install --save-dev @types/chai
```

**Comment by kwonoj** [comment] 2016-11-06 18:11
Some of transpiled results has unexpected type references, 

```js
/// <reference types="chai" />
import { Observable } from '../../Observable';
import { Subscriber } from '../../Subscriber';
import { TeardownLogic } from '../../Subscripti
```

while those file does not uses those type references. Seems it's known issue of TS, updated compiler to latest dev to avoid this.

**Comment by Skuriles** [comment] 2016-11-08 10:36
Update to TS 2.1 Dev didn't help. Used 'next' version of TS in package.json.
Gone back to rxjs 5 rc1 and using TS latest (2.0.8) is working so far. 
Waiting for fix.

**Comment by iamdanfox** [comment] 2016-11-08 14:14
I don't have a solution to this yet, but I think the problem is caused by [Typescript's automatic @types detection][3] of `node_modules/@types/chai` leaking into prod code, caused after switching away from Typings.

## 1. Local repro

After running `npm run build_es6` (with master at 922d04e), I can see four `.d.ts` files have the problematic line:

```
/// <reference types="chai" />
```

![screen shot 2016-11-08 at 13 21 29](https://cloud.githubusercontent.com/assets/3473798/20100630/45f7894a-a5b6-11e6-8ba1-960637682e9c.png)

## 2. Minimal example case

`src/util/assign.ts` is a particularly small source file that ends up with the problematic chai dependency.  The problem goes away if we remove any mention of `Object` from the file - specifically, I changed the signature of `assignImpl` from:

```
export function assignImpl(target: Object, ...sources: Object[]) {
```
to 
```
export function assignImpl(target: any, ...sources: any[]) {
```

(The three other files also have mentions of `Object`).

It seems that the `@types/chai` package that is installed as part of 5.0.0-rc2 mentions `Object` at line 414:

```
interface Object {
    should: Chai.Assertion;
}
```

## 3. Narrow down the cause

Between 5.0.0-rc.1 and 5.0.0-rc.2, the dist output may have been affected by:

- rxjs switching from using `npm install` to `yarn`
- switching from Typings to using the npm @types/<dep> packages. ([before][1], [after][2])

Note, the version of chai never changed from `^3.5.0` and the content of the chai typings file isn't the problem.  If I copy `typings/globals/chai/index.d.ts` from 5.0.0-rc.1 and paste it into `node_modules/@types/chai/index.d.ts`, I still get four unwanted chai references in the built dist.

I can't see any evidence that yarn is the problem here, it seems much more likely that switching from Typings to the [new @types modules][3] caused the problem.  Despite having two `tsconfig.json` files (one for main, one for spec), it seems like the typescript compiler is happily pulling `node_modules/@types/chai` into main code.  

## 4. Solutions

Ideally, if we could switch off tsc's `node_modules/@types` resolution for the main dist, I think this would solve everything.  (Not sure if typescript supports this, or is even aware this can be a problem).  Alternatively, rxjs could just switch back to using Typings instead of the new npm modules.

I'm sure there are lots of other possible solutions, I defer to the rxjs team to pick a sensible one!

[1]: https://github.com/ReactiveX/rxjs/blob/5.0.0-rc.1/typings.json#L4
[2]: https://github.com/ReactiveX/rxjs/blob/5.0.0-rc.2/package.json#L147
[3]: https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

**Comment by Skuriles** [comment] 2016-11-08 14:31
JFYI: 
I'm actually using some @types (e.g. highcharts , jquery) and this is working with my above mentioned combination (rc1 + TS 2.0.8)

**Comment by kwonoj** [comment] 2016-11-08 14:54
@iamdanfox yes, I suspect it's related to https://github.com/Microsoft/TypeScript/issues/11948
@Skuriles it'll not be resolved by consumer side TSC version, since type definition is already published includes those references.

I'm seeing couple of options here
- bump up to TS@2.1-dev (https://github.com/ReactiveX/rxjs/pull/2113) : failing tests due to changed behavior
- back to `typings`
- simply include  `@types/` as dependency instead of devDependency while waiting compiler issue resolved

**Comment by karlbohlmark** [comment] 2016-11-09 14:04
Why not just publish a new version to npm that fixes the issue while waiting for the fix in TS?

**Comment by kwonoj** [comment] 2016-11-09 14:57
@karlbohlmark I think we will.

**Comment by karlbohlmark** [comment] 2016-11-09 15:00
@kwonoj Great, thanks!

**Comment by jayphelps** [comment] 2016-11-15 03:32
5.0.0-rc3 was just published, which solved this. If not, please reopen!

**Comment by saneyuki** [comment] 2016-11-15 06:05
@jayphelps 

I confirm this problem is __not__ resolved in 5.0.0-rc3.
We need to republish it.

## Environment

- https://registry.npmjs.org/rxjs/-/rxjs-5.0.0-rc.3.tgz (sha1: d8bc390d83277846b2d2afa1acf3c5f4f114a8d5)

## Problems

1. These files contains `/// <reference types="chai" />`
  - observable/PairsObservable.d.ts
  - observable/dom/AjaxObservable.d.ts
2. So TypeScript compilers still requires `@types/chai`.

**Comment by jayphelps** [comment] 2016-11-15 06:22
@kwonoj any guesses?

**Comment by kwonoj** [comment] 2016-11-15 06:33
@jayphelps is it possible to confirm `node_modules` have remaining `@types` packages when pack new package? if it does, force clear `node_modules` then retry `npm pack`.

**Comment by Skuriles** [comment] 2016-11-15 07:08
I can confirm this error in RC3. Still 

PairsObservable.d.ts(1,1): error TS2688: Cannot find type definition file for 'chai'.
AjaxObservable.d.ts(1,1): error TS2688: Cannot find type definition file for 'chai'.

error on compile.

**Comment by slowtrailrunner** [comment] 2016-11-15 15:32
I can also confirm that this error still exists in RC3 after clearing `node_modules`

```
[08:26:37] [tsc] > node_modules/rxjs/observable/PairsObservable.d.ts(1,1): error TS2688: Cannot find type definition file for 'chai'.
[08:26:37] [tsc] > node_modules/rxjs/observable/dom/AjaxObservable.d.ts(1,1): error TS2688: Cannot find type definition file for 'chai'.
```

**Comment by jayphelps** [comment] 2016-11-15 18:07
I'm still not seeing these `/// <reference types="chai" />` references when I build locally...Can someone else fetch the latest, build, and confirm they do or do not see `/// <reference types="chai" />` in `observable/PairsObservable.d.ts` or `observable/dom/AjaxObservable.d.ts`?

**Comment by kwonoj** [comment] 2016-11-15 18:13
@jayphelps as commented above, I am currently suspect when packing current one there was remaining types module in local node_modules, which makes package have old behavior and explains why local build works. To confirm this, may need check machine being used for package and check those modules are remaining, then republish new package as needed if it's confirmed in those way. (Just fyi, local build also works for me after force clear node_modules and reinstall)

**Comment by jayphelps** [comment] 2016-11-15 18:15
@kwonoj sorry, I misunderstood what you meant in your original comment. I suspect the same thing. I've pinged @blesh.

**Comment by zackarychapple** [comment] 2016-11-16 08:36
I can confirm this is happening with rc.3 in a fresh install. 
![image](https://cloud.githubusercontent.com/assets/2133184/20340076/bd6719f4-ac1a-11e6-8508-4b60596a1153.png)

**Comment by endel** [comment] 2016-11-17 10:37
Confirmed. Still happening using latest TypeScript version. Previously reported on this issue https://github.com/Microsoft/TypeScript/issues/11948

**Comment by kwonoj** [comment] 2016-11-17 11:47
@here it is known and reproducible issue with latest package and currently expected to resolve in next package publish.

**Comment by kwonoj** [comment] 2016-11-20 12:09
I believe this issue is fixed with latest rc.4 package publish.

**Closed by kwonoj** 2016-11-20 12:09 UTC
