### ISSUE TITLE
ConnectableObservable & publish typings are wrong

### ISSUE THREAD

**Issue by joshribakoff** [ReactiveX/rxjs#5651] opened 2020-08-17 20:12 UTC
## Bug Report

**Current Behavior**
Typings for connectableObservable when using publish are wrong

**Reproduction**
- REPL or Repo link:
https://stackblitz.com/edit/rxjs-nsj1hs?file=index.ts

```js
import { of, ConnectableObservable,timer } from 'rxjs'; 
import { map, publish } from 'rxjs/operators';


const stall$: ConnectableObservable<number> = timer(100).pipe(publish());
stall$.connect();
```

There is a TS error on declaration of stall$

**Expected behavior**
Should infer the type w/o annotating. If I do chose to annotate, no type error should occur.

**Comment by voliva** [comment] 2020-08-18 21:41
I think it's a duplicate of #2972

**Comment by kwonoj** [comment] 2021-01-22 20:44
Closing as dupe as commented.

**Closed by kwonoj** 2021-01-22 20:44 UTC
