### ISSUE TITLE
[Bug] Typings startWith

### ISSUE THREAD

**Issue by niklas-wortmann** [ReactiveX/rxjs#5382] opened 2020-04-07 20:22 UTC
It seems like there is a bug in the typing for `startWith`.
It seems like it is introduced with #5376 

TS throws following error:

```
Type `...` is missing the following properties from type `SchedulerLike`...
```

This occurs when ts is falling back to the following type signature of `startWith`: 

```
export function startWith<T>(scheduler: SchedulerLike): MonoTypeOperatorFunction<T>;
```

This could occur for example by doing the following:

```
of(true).pipe(
    startWith<boolean>(undefined)
);
```

In general, this problem occurred recently in G3 so it is at least some kind of breaking behavior

**Comment by cartant** [comment] 2020-04-07 20:46
Not a bug, IMO.

**Comment by niklas-wortmann** [comment] 2020-04-07 20:59
It also doesn't work if you set the explicit type parameter to `boolean`. And for some reason this was just popping up at google, so I don't know, but it seems like a regression or something.

**Comment by cartant** [comment] 2020-04-07 21:02
The answer is to not use an explicit type parameter - this is Google's own advice. Or, if one is to be specified, specify one that's compatible with the argument being passed:

```ts
of(true).pipe(startWith<boolean | undefined>(undefined));
```

Not a bug, IMO.

**Comment by leggechr** [comment] 2020-04-08 14:15
Even `of(true).pipe(startWith<boolean | undefined>(undefined));` is not working.  It gives the same error Jan-Niklas mentioned above. The only way I could get it to work is with 
```js 
startWith(undefined as boolean|undefined)
```

**Comment by Airblader** [comment] 2020-10-07 14:47
This is particularly annoying on `void` observables, such as `Subject<void>`. I really just want `startWith()` which doesn't work, and because of this issue `startWith(undefined)` works but shows as a deprecated signature. The only way to truly have it work is then something like `startWith(undefined as void)` which is slightly insane. :-)

**Comment by cartant** [comment] 2021-03-13 23:39
Addressed in https://github.com/ReactiveX/rxjs/pull/6114

**Closed by cartant** 2021-03-13 23:39 UTC
Labels: type: bug
