### ISSUE TITLE
Errors being trapped by merge operations like switchMaps

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#3183] opened 2017-12-12 22:56 UTC
**RxJS version:** 5.5.5

**Code to reproduce:**

**EDIT: Ugh, the code I had to reproduce this didn't reproduce it as expected**... but I've seen a non-trivial reproduction. cc @IgorMinar 

**Expected behavior:**
Error "final error" should be reported in console

**Actual behavior:**
Error is squeltched.

**Additional information:**
This only happens if the observable in the merge operation is asynchronous. The error thrown by the subscription unwinds the stack back to the  switchMap's subscriber (via parent.notifyError from InnerSubscriber), and it's swallowed because the switchMap subscriber `isStopped`.

**Comment by benlesh** [comment] 2017-12-12 22:57
cc @IgorMinar

**Comment by kwonoj** [comment] 2017-12-13 17:18
maybe related: https://github.com/ReactiveX/rxjs/pull/3161

**Comment by jayphelps** [comment] 2017-12-13 19:38
@IgorMinar can you give #3161 a try? (the example above doesn't seem to suffer from the described error)

I've attached a build from that PR you could copy/pasta from into your node_modules

[dist.zip](https://github.com/ReactiveX/rxjs/files/1556801/dist.zip)

**Comment by benlesh** [comment] 2017-12-13 20:30
Apparently my minimal repro doesn't repro like I thought. :\

**Comment by IgorMinar** [comment] 2017-12-13 21:24
@jayphelps that build didn't work because it's not complete (all add/operator/* files are missing), but I was able to diff it and extract this patch that I applied to my current build:

```
--- node_modules/rxjs.patched/src/Subscriber.ts 2017-12-06 09:58:33.000000000 -0800
+++ node_modules/rxjs/src/Subscriber.ts 2017-12-05 01:29:16.000000000 -0800
@@ -68,6 +68,7 @@
         }
         if (typeof destinationOrNext === 'object') {
           if (destinationOrNext instanceof Subscriber) {
+            this.syncErrorThrowable = destinationOrNext.syncErrorThrowable;
             this.destination = (<Subscriber<any>> destinationOrNext);
             (<any> this.destination).add(this);
           } else {

--- node_modules/rxjs.patched/src/Observable.ts 2017-12-06 09:58:33.000000000 -0800
+++ node_modules/rxjs/src/Observable.ts 2017-12-05 01:29:16.000000000 -0800
@@ -199,7 +199,7 @@
     if (operator) {
       operator.call(sink, this.source);
     } else {
-      sink.add(this.source ? this._subscribe(sink) : this._trySubscribe(sink));
+      sink.add(this.source || !sink.syncErrorThrowable ? this._subscribe(sink) : this._trySubscribe(sink));
     }

     if (sink.syncErrorThrowable) {
```

With this patch applied to the JS files by hand, I was able to confirm that the errors now get propagated correctly, so if I extracted the change correctly, then what you did resolves the problem.

**Comment by IgorMinar** [comment] 2018-01-02 02:20
@jayphelps was this fixed by #3161? should this issue be closed now?

**Comment by jayphelps** [comment] 2018-01-02 02:41
I was never able to reproduce the issue described here (see above). Can you give it a try in your app?

**Comment by IgorMinar** [comment] 2018-01-02 22:18
Was this change released? I tested the zip from @jayphelps referenced above and that worked with the caveat mentioned in https://github.com/ReactiveX/rxjs/issues/3183#issuecomment-351529702

**Comment by jayphelps** [comment] 2018-01-02 22:21
@IgorMinar yeah my PR was released as part of 5.5.6

**Comment by IgorMinar** [comment] 2018-01-03 05:59
I can't repro the issue any more with 5.5.6. So let's consider this fixed. :-) thanks

**Comment by jayphelps** [comment] 2018-01-03 06:03
Yayayayay! 🕺

**Closed by jayphelps** 2018-01-03 06:03 UTC
Labels: type: bug
