### ISSUE TITLE
possible front-end bug

### ISSUE THREAD

**Issue by ORESoftware** [ReactiveX/rxjs#2301] opened 2017-01-20 05:58 UTC
I am loading v 5.0.1 with RequireJS in the browser like so:

'rxjs': '//cdnjs.cloudflare.com/ajax/libs/rxjs/5.0.1/Rx'

I just added rxjs to my build, I get this error immediately when the page loads:

```
Rx.js:388 Uncaught TypeError: __extends is not a function
    at Rx.js:388
    at Object.<anonymous> (Rx.js:399)
    at Object.execCb (require.js:1693)
    at Module.check (require.js:881)
    at Module.enable (require.js:1173)
    at Module.init (require.js:786)
    at callGetModule (require.js:1200)
    at Object.completeLoad (require.js:1587)
    at HTMLScriptElement.onScriptLoad (require.js:1714)
```

Here is my RequireJS config:

```js

requirejs.config({

    enforceDefine: false,
    waitSeconds: 7,
    baseUrl: '/',
    paths: {
    
        'rxjs': '//cdnjs.cloudflare.com/ajax/libs/rxjs/5.0.1/Rx',
        'async': '//cdnjs.cloudflare.com/ajax/libs/async/2.1.4/async',
        'react-dom': '//cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react-dom',
        'react': '//cdnjs.cloudflare.com/ajax/libs/react/15.4.2/react-with-addons',
        'socketio': '//cdnjs.cloudflare.com/ajax/libs/socket.io/1.4.5/socket.io',
        '@hot-reload-handler': 'js/hot-reload-handler',
        '@hot-reloader': 'js/hot-reloader',
        'immutable':'//cdnjs.cloudflare.com/ajax/libs/immutable/3.8.1/immutable',
        'rxjs': '//cdnjs.cloudflare.com/ajax/libs/rxjs/5.0.1/Rx'
    },

    'shim': { }

});

const deps = [
    'react-dom',
    'react',
    'socketio',
    'async',
    'rxjs',
    'immutable'
];

require(deps, function () {

    require(['js/application'], function (Application) {

        Application.start();

    });

});


```

just wondering if you have seen this error before, seems problematic, since all I am doing is loading the script, doubt it's me/my code. Notice I am loading rxjs twice...I will see if tthat's the issue...

**Comment by kwonoj** [comment] 2017-01-20 05:59
Closing as dupe of https://github.com/ReactiveX/rxjs/issues/2177 .

**Comment by ORESoftware** [comment] 2017-01-20 06:00
thank you will read the link

**Closed by kwonoj** 2017-01-20 05:59 UTC

**Comment by ORESoftware** [comment] 2017-01-20 06:14
I am using TypeScript + Rxjsv5.0.1 + RequireJS, I solved this by using a shim in my RequireJS config

```js
    'shim': {
        'rxjs':{
            deps: ['tslib']
        }
    }
```

tslib is library from TypeScript that apparently exports some global helper functions
