### ISSUE TITLE
fromFetch cannot abort all responses

### ISSUE THREAD

**Issue by cartant** [ReactiveX/rxjs#4744] opened 2019-04-27 03:14 UTC
## <s>Bug Report</s> Feature Request

**Current Behavior**

`fromFetch` returns an observable that emits the request's `Response` object. When `json()` or `text()` is called on the `Response`, a promise is returned. My understanding is that the `AbortController` used in the `fetch` call also aborts promises returned by the aforementioned methods.

In #4742, a bug was fixed: `fromFetch` was calling `abort` as part of the implicit unsubscribe that occurs after completion. This would abort any still pending responses. When `fetch` resolves, a flag is now set to prevent `abort` being called in the unsubscribe teardown.

However, that means there is no way of aborting the promises returned by calls to `Response` methods.

**Possible Solution**

Add another signature to `fromFetch` so that a selector can be passed:

```ts
export function fromFetch<R>(
  input: string | Request,
  init: RequestInit | undefined,
  selector: (response: Response) => Observable<R>,
): Observable<R>;
```

Much like the selector passed to `multicast`, observables composed within the selector will be 'contained' within the observable returned by `fromFetch` and unsubscribing from said observable will facilitate the aborting of any promises returned by `Response` methods within the selector.

If a selector is not passed, `fromFetch` should continue to behave as in #4742 and not abort upon unsubscription if the promise returned by `fetch` has resolved.

**Additional Information**

Note that the changes introduced in https://github.com/ReactiveX/rxjs/pull/3963/files will ensure that unsubscription from the observable returned by `fromFetch` will occur ASAP if said observable serves as the source for, say, `concatMap`. So extending the 'life' of the `AbortController` for an emitted `Response` - if the selector is not used - would be a non-trivial undertaking.

**Comment by benlesh** [comment] 2019-05-11 00:08
This is resolved in 6.5.2

**Comment by cartant** [comment] 2019-05-11 00:18
Nope. This isn't resolved.

**Comment by kambing86** [comment] 2019-05-29 15:35
I have the same issue and found one very interesting finding about this

I can abort the fromFetch if I change the code in `fromFetch.js` from

```js
    fetch(input, init).then(response => {
      abortable = false;
      subscriber.next(response);
      subscriber.complete();
    }).catch(err => {
      abortable = false;
      if (!unsubscribed) {
        // Only forward the error if it wasn't an abort.
        subscriber.error(err);
      }
    });
```

to async/await
```js
    (async () => {
      try {
        const response = await promise;
        abortable = false;
        subscriber.next(response);
        subscriber.complete();
      } catch (err) {
        abortable = false;
        if (!unsubscribed) {
          // Only forward the error if it wasn't an abort.
          subscriber.error(err);
        }
      }
    })();
```

**Comment by kambing86** [comment] 2019-05-29 16:13
I'm having the same issue, but it does not seems like the code got issue

if I copy the `fromFetch` function from `https://github.com/ReactiveX/rxjs/blob/master/src/internal/observable/dom/fetch.ts` and put it into my application code, then comment out the `import { fromFetch } from "rxjs/fetch";`, it works just fine

still investigating the root cause

**Comment by kambing86** [comment] 2019-05-29 16:58
uploaded a recording https://www.youtube.com/watch?v=ZaMm_n1K4Y8 for this issue, not sure if it helps, will see if I can use stackblitz or codesandbox to create one to test

**Comment by kambing86** [comment] 2019-05-29 17:53
I compared the code in `node_modules\rxjs\internal\observable\dom\fetch.js` with the typescript one, not seeing any issue, I copied the js code and use in my application, it's still working fine

but another interesting finding, if I try to use `Observable` from

```
import { Observable } from "rxjs/internal/Observable";
```

then I will see the issue

**Comment by cartant** [comment] 2019-05-29 21:49
I cannot see how using the `await` syntax will make any difference. I think it is far more likely that the differences that you are seeing are effected by browser caching.

**Comment by kambing86** [comment] 2019-05-30 00:40
> I cannot see how using the `await` syntax will make any difference. I think it is far more likely that the differences that you are seeing are effected by browser caching.

Sorry, I actually found that is not because of the `await` syntax, and removed that comment already.

Please check my other comments, I suspected is because of using the internal `Observable`

**Comment by cartant** [comment] 2019-05-30 00:45
TBH, I don't understand what it is you are saying. IMO, it's clear that responses that - with the current implementation - are emitted from `fromFetch` cannot be aborted after they are emitted. Which means that the promise returned from a call to `json()`, etc. cannot be aborted. This is a straightforward, logical implication of the current API.

**Comment by kambing86** [comment] 2019-05-30 00:53
> TBH, I don't understand what it is you are saying. IMO, it's clear that responses that - with the current implementation - are emitted from `fromFetch` cannot be aborted after they are emitted. Which means that the promise returned from a call to `json()`, etc. cannot be aborted. This is a straightforward, logical implication of the current API.

1) try to use the same implementation but put that code into your application code, and use `import { Observable } from "rxjs";`, you will see that it works just fine
2) then change that import statement to `import { Observable } from "rxjs/internal/Observable";` to see it fails

**Comment by cartant** [comment] 2019-05-30 01:02
You should *never* import from internal locations. I don't see a connection between what you are talking about and the concerns I raised in this issue.

**Comment by kambing86** [comment] 2019-05-30 01:07
hmm, ok, now I see your point, we are talking different stuffs

so you are trying to cancel the promise `.json()` or `.text()`

and I'm talking another more worrying part, which is

the `abort` is not working at all, the cleanup function is not being called at all when `fetch` is not resolved

**Comment by cartant** [comment] 2019-05-30 01:16
Then raise an issue and fill out the template.

**Closed** 2020-04-22 22:12 UTC
Labels: type: feature

**Comment by curiousercreative** [comment] 2020-05-27 16:27
@cartant should the canceling of a chunked response via `fromFetch` be working? Perhaps a new issue is warranted, but I'm observing the following (v6.5.5):
1. If the fetch in question has no received any body, unsubscribing from the observable will cancel the fetch request properly (hooray!)
1. If the fetch has received any body, then the fetch won't be canceled when observable is unsubscribed.

**Comment by cartant** [comment] 2020-05-27 23:14
@curiousercreative Nope. The PR with the selector - a selector has to be passed in the `InitRequest` options for responses with content that is received after the headers - wasn't merged until May 19 and 6.5.5 was published on April 3. So this functionality won't be available until 6.5.6 - @benlesh.

**Comment by curiousercreative** [comment] 2020-05-27 23:17
@cartant hey, that's great news! I'll be looking forward to the next release. Thanks for adding this feature.

**Comment by cartant** [comment] 2020-05-27 23:20
@curiousercreative BTW, if you are interested, the reason for the selector is explained here: https://ncjamieson.com/understanding-fromfetch/

**Comment by curiousercreative** [comment] 2020-05-27 23:41
@cartant thanks for that follow-up. My implementation actually doesn't have to wait for the next release. In my case, I'm streaming my chunked response using `response.body.getReader()` and after reading through your article and this [MDN reference](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStreamDefaultReader), I found that I can simply cancel the reader stream when my custom Observable unsubscribes (from a `switchMap`). Works like a charm, but I wouldn't have gotten it there without your help!
