### ISSUE TITLE
No Observables out if piping debounceTime and switchMap/ mergeMap returning empty observable

### ISSUE THREAD

**Issue by stuku** [ReactiveX/rxjs#4617] opened 2019-03-04 14:54 UTC
## Bug Report

**Current Behavior**
No result would be output if I piped `debounceTime` with `siwtchMap`/ `mergeMap` returning `empty`.

**Reproduction**
- REPL or Repo link:
```js
import { fromEvent, timer, empty } from 'rxjs';
import { debounceTime, map, switchMap } from 'rxjs/operators';

const input = document.getElementById('example');

//  for every keyup, map to current input value
const example = fromEvent(input, 'keyup').pipe(map(i => i.currentTarget.value));

// wait .5s between keyups to emit current value
//throw away all other values
const debouncedInput = example.pipe(debounceTime(500), switchMap(() => empty()));

// log values
const subscribe = debouncedInput.subscribe(val => {
  console.log(`Debounced Input: ${val}`);
});
```

**Expected behavior**
`empty` observables are emitted. 

**Environment**
- Runtime: any
- RxJS version: v6.2.0

**Comment by martinsik** [comment] 2019-03-05 08:09
You're returning `empty()` in `switchMap(() => empty())` so it never emits any `next` notifications which is correct behavior.

**Comment by stuku** [comment] 2019-03-18 04:29
I thought `emit` would emit a `complete` notification.

**Comment by kosich** [comment] 2019-03-18 09:37
Both `mergeMap` and `switchMap` ignore its inner Observable `complete` notification. They only merge `next` values and propagate `errors`. So `switchMap(() => empty())` is effectively equal to `ignoreElements()`.

Also, to clarify: here `debounceTime` doesn't affect the resulting output. The issue is particularly in `switchMap(() => empty())`.

**Comment by cartant** [comment] 2019-03-19 02:21
Closing because it's the expected behaviour.

**Closed by cartant** 2019-03-19 02:21 UTC
