### ISSUE TITLE
[QUESTION] Observable.getValue as in RxJava

### ISSUE THREAD

**Issue by AlexShafir** [ReactiveX/rxjs#2556] opened 2017-04-15 14:07 UTC
Is there a reason why `Observale.getValue()` not present in contrast to RxJava?

P.S. 
This question would be useful for ones from Java background

**Comment by kwonoj** [comment] 2017-04-15 14:25
https://github.com/ReactiveX/rxjs/issues/2469#issuecomment-287074444

sams as #2469. It is not a goal of RxJS 5 to create fully conpliant operator set between language bindings or previous version. Especially each language has different language design and syntaxes, it does not have strong meaning to create every operator set.

I believe question itself is answered so closing issue. If there is request to have new operator,  you may refer https://github.com/ReactiveX/rxjs/issues/2299 and https://github.com/ReactiveX/rxjs/pull/2524 as primary guideline while it's yet finalized.

**Closed by kwonoj** 2017-04-15 14:25 UTC

**Comment by AlexShafir** [comment] 2017-04-17 17:28
@kwonoj  probably my question was a bit vague, so I will elaborate this:

Ability to get value in blocking manner would allow use of library for data processing, where observable itself is not needed.

For instance, one needs to process (format) array of time strings. Rx allows to do it with a breeze.
However, there is no way to get resulting value but subscription, thus making use of Rx impossible here.

As `getValue` was implemented for `BehaviourSubject` only, I wonder what was the reason to not include it in `Rx.Observable`?

**Comment by kwonoj** [comment] 2017-04-17 17:52
@AlexShafir so, the question in here is actually opposite - it's not `what was the reason to not include it in Rx.Observable`, instead it is `RxJava (and some other) only have getValue() in Observable pattern for their own specific reason`.  `getValue()` in your question is actually available in few language bindings only, instead of most language bindings are having it while only RxJS does missing it. By design of Observable contract itself and nature of JS runtime, there isn't strong reason to bringing blocking or either imperative way to access values other than observer. 

As said earlier, there are lot of differences between language design / runtime differences, and other various reason does not makes all Rx bindings between languages does not create full-compliant set compare to other languages. If you look into operator, or interface set of Rx.NET for exmaple, you'll also able to notice there are quite lot of differences compare to RxJAVA. 

We are not considering to fulfill those differences unless there are usecases to be applied with JS.

**Comment by AlexShafir** [comment] 2017-04-17 18:50
@kwonoj Thanks for great explanation!

My question essentially **is** what was the reason to not include it in Rx.Observable. 
Here I suppose blocking `getValue` may be needed irregardless of underlying language, for instance,  time string processing, merging observables in imperative fashion instead of `zip` (useful in grabbing).

Java is for demonstration purpose only.

> By design of Observable contract itself and nature of JS runtime, there isn't strong reason to bringing blocking or either imperative way to access values other than observer

Does it mean that RxJava consciously violates Observer pattern?

**Comment by kwonoj** [comment] 2017-04-17 19:14
> Does it mean that RxJava consciously violates Observer pattern?

No, all I said is strictly limited for JS implementation and you shouldn't consider it applies to other language bindings. For reasoning behind RxJava, I canxt say anything as I'm not even user of it.

**Comment by AlexShafir** [comment] 2017-04-17 20:16
@kwonoj thanks, now it is clear
