### ISSUE TITLE
Observable does not complete using Sync/Async between two instances of RxJS

### ISSUE THREAD

**Issue by hansl** [ReactiveX/rxjs#3475] opened 2018-03-26 18:27 UTC
Smallest reproduction: https://stackblitz.com/edit/rxjs-3475-reproduction?file=index.ts

This is an issue we found in the Angular DevKit when updating projects and RxJS does not get properly hoisted (either because different versions or no peer deps).

Basically:

1. create an observable using Library 1
1. pipe a sync operator from Library 2
1. pipe an async operator from Library 1 (or 2)
1. the original SafeSubscriber is stopped, but did not complete or error, therefore the new pipeline will never next or complete the first pipeline.

**Comment by kwonoj** [comment] 2018-03-26 18:30
Dupe of https://github.com/ReactiveX/rxjs/issues/3443. Rx doesn't support multiple instance due to internal core behavior.

**Comment by hansl** [comment] 2018-03-26 18:35
@kwonoj Talking to @benlesh, it seems like this behaviour _is_ officially supported.

You only use `instanceof` when whether or not you need a SafeSubscriber. All other instances you use the `symbol-observable`, which is the right behaviour. The problem is in SafeSubscriber, which Ben is looking at.

**Comment by kwonoj** [comment] 2018-03-26 18:37
@benlesh mind chime in to share discussion in issue? I doubt even without instanceof check it'll work across different version / instances.

**Comment by benlesh** [comment] 2018-04-02 17:09
This was fixed by #3477

**Closed by benlesh** 2018-04-02 17:09 UTC
