### ISSUE TITLE
getting "Types of property 'lift' are incompatible." with typescript 2.4.0

### ISSUE THREAD

**Issue by foxel** [ReactiveX/rxjs#2702] opened 2017-06-28 02:21 UTC
**RxJS version:** 5.1.0

**Code to reproduce:** linting a code using Subject

**Expected behavior:** no errors

**Actual behavior:** 
```
Types of property 'lift' are incompatible.
Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
Type 'Observable<T>' is not assignable to type 'Observable<R>'.
Type 'T' is not assignable to type 'R'.
```

**Additional information:**
The bug popped up after typescript updated to 2.4.0

see https://github.com/angular/angular/issues/17800 also

**Comment by kwonoj** [comment] 2017-06-28 02:22
dupe of https://github.com/ReactiveX/rxjs/issues/2699 , https://github.com/ReactiveX/rxjs/issues/2539, https://github.com/ReactiveX/rxjs/issues/2700 . https://github.com/ReactiveX/rxjs/issues/2701

**Closed by kwonoj** 2017-06-28 02:22 UTC

**Comment by bobheath33435** [comment] 2017-07-02 12:40
If kwonoj would list the problem that lists the solution, that would be helpful. Kwonoj's practice of listing umpteen different dupes only confuses the problem.

**Comment by kwonoj** [comment] 2017-07-02 17:42
There is open issue to track this one and it is on discussion. I'm closing all dupues on behalf of opened one - it doesn't have meaning to open issue without searching dupes.

**Comment by bobheath33435** [comment] 2017-07-02 17:46
I understand that you only should track the problem on one ticket. How about specifying on which ticket the problem is being tracked instead having the user go through all four tickets to find the issue tracking the problem?

**Comment by kwonoj** [comment] 2017-07-02 17:47
I'd rather suggest people search issue first before filing redundant issue that I have to just close.

**Comment by bobheath33435** [comment] 2017-07-02 17:50
OK I will do it for you. This issue is being tracked here: https://github.com/ReactiveX/rxjs/issues/2539

**Comment by jamie-pate** [comment] 2017-07-15 18:25
uhm, so what is the canonical issue for this? None of the dupes you mention seem canonical.

**Comment by kwonoj** [comment] 2017-07-15 18:30
All of them are same dupe issue and latest update resolved it.

**Comment by arnjmllr** [comment] 2018-01-20 05:25
@kwonoj what was the update to that fixed the issue rsjx, typescript or angular?  I am getting this error now, any help would be greatly appreciated. thanks!

**Comment by Morpheous7** [comment] 2018-02-25 01:29
Same here. I'm searching for the fix on this issue and can't find it anywhere...
