### ISSUE TITLE
map() does not work with forkJoin

### ISSUE THREAD

**Issue by atgillette** [ReactiveX/rxjs#3432] opened 2018-03-13 23:52 UTC
Hi,
I'm trying to make parallel api calls with forkJoin.  But it doesn't seem to work with map().  But forkJoin works with subscribe().

**RxJS version:**
5.4.0

**Code to reproduce:**

```ts
return Observable.forkJoin(apiCalls).map(responses => {
        console.info('var added');
        this.isLoading = false;

        return responses;
    });
```

**Expected behavior:**
Expect Map function to be invoked and fire console.info.

**Actual behavior:**
Map function is not invoked

**Additional information:**

**Comment by kwonoj** [comment] 2018-03-13 23:54
Do you mean you chained map then not subscribe? (Code snippet looks so)

**Comment by jasonaden** [comment] 2018-03-14 23:58
This is broken. Here's repro code:

```
import {Observable, forkJoin} from 'rxjs';

const aOfObs = [1, 2, 3].map(n => Observable.of(n));

forkJoin(aOfObs)
.subscribe(n => n.map(n => n * 2));
```

This works fine prior to #3304 and works at runtime, but doesn't compile.

**Comment by benlesh** [comment] 2018-03-15 01:13
So this is a typings issue?

**Comment by benlesh** [comment] 2018-03-15 02:47
Jason, I'm not seeing the error.

[Here's a Stackblitz using TypeScript](https://stackblitz.com/edit/typescript-hdurwy?file=index.ts)

It seems to be totally fine. Other than the code that you have up there has a bug in it `Observable.of` should just be `of` and you'll need to import it.

**Comment by benlesh** [comment] 2018-03-15 02:53
@jasonaden I'm unable to reproduce this bug with your code either in `6.0.0-alpha.4` or in `5.4.0` (which the bug was reported against)

@atgillette The problem with the code you have there is that you never subscribe to the observable. Observables are like functions, they don't do anything until you "call" them, and in the case of observables, "calling" means calling `subscribe()`, which you're not doing in your example code.

@jasonaden Your code has at least one bug even for `6.0.0-alpha.4`: `Observable.of` isn't in 6, it would just be `of`, and you'd still need to import it.

I think we can close this one for now.

**Closed by benlesh** 2018-03-15 02:53 UTC
Labels: status: more information needed

**Comment by atgillette** [comment] 2018-03-15 15:52
@benlesh - Thanks for looking into this and your feedback.  You were correct about the "subscribe" not being used.
