### ISSUE TITLE
endWidth no longer being triggered n 7.5.4

### ISSUE THREAD

**Issue by paulflo150** [ReactiveX/rxjs#6849] opened 2022-02-27 14:46 UTC
### Describe the bug

I am having issues where my endWidth is no longer being triggered after upgrading from 7.3.0.

Working version (7.3.0):
https://stackblitz.com/edit/count-up-animation-with-angular-and-rxjs-wgfpqr?file=src%2Fapp%2Fcount-up.directive.ts

Not working (7.5.4):
https://stackblitz.com/edit/count-up-animation-with-angular-and-rxjs-ttajfe?file=src%2Fapp%2Fcount-up.directive.ts

### Expected behavior

The expected behavior is to have endWidth triggered as well.

### Reproduction code

```typescript
return interval(0, animationFrameScheduler).pipe(
        // calculate elapsed time
        map(() => animationFrameScheduler.now() - startTime),
        // calculate progress
        map((elapsedTime: number): number => elapsedTime / duration),
        // complete when progress is greater than 1
        takeWhile((progress: number): boolean => progress <= 1),
        // apply quadratic ease-out
        // for faster start and slower end of counting
        map(easeOutQuad),
        // calculate current count
        map((progress: number): number => Math.round(progress * count)),
        // make sure that last emitted value is count
        endWith(count),
        distinctUntilChanged()
      );
```

### Version

7.5.4

**Comment by benlesh** [comment] 2022-02-28 17:50
Hi, @paulflo150, thanks for reporting.

Your example wasn't minimal, unfortunately. I'm not sure what the examples you sent were attempting to do. Try creating an example that _only_ uses RxJS and not Angular or any other framework.

Right now, looking at a minimal example using `endWith` in both a simple scenario, and a scenario using `animationFrameScheduler` with `interval`, it appears to be working fine: https://stackblitz.com/edit/rxjs-wyk9da?file=index.ts

```ts
import { of, endWith, take, animationFrameScheduler, interval } from 'rxjs';

// BASIC
of(1)
  .pipe(endWith('ended with'))
  .subscribe((value) => console.log(`sync: ${value}`));

// animationFrameScheduler test
interval(0, animationFrameScheduler)
  .pipe(take(1), endWith('ended with'))
  .subscribe((value) => console.log(`animationFrameScheduler: ${value}`));
```

In other words, I'm unable to reproduce your issue.

### Unrelated

I want to call out a few things I saw in your examples that you sent:

1. You were not unsubscribing from subscriptions you created in `ngOnInit` from your `ngOnDestroy`. If possible, I'd recommend using `| async` in your template to manage this for you.
2. RxJS version 7 has an `animationFrames` API that allows you to get the elapsed time in an rAF without needing to know the secret `interval` recipe:

```ts
import { animationFrames } from 'rxjs';

animationFrames().subscribe(({ elapsed }) => console.log(`Elapsed milliseconds: ${elapsed}`));
```

3. I'd recommend breaking something like that down into a reusable function like a `fromDuration` or something:

I've updated the example a bit here: https://stackblitz.com/edit/count-up-animation-with-angular-and-rxjs-ikr3si?file=src/app/count-up.directive.ts

```ts
function fromDuration({
  easing,
  duration,
}: {
  easing?: (progress: number) => number;
  duration: number;
}) {
  return animationFrames().pipe(
    map(({ elapsed }) => elapsed / duration),
    takeWhile((progress) => progress < 1),
    easing ? map(easing) : identity,
    endWith(1)
  );
}
```

I'm going to close this because I can't reproduce the issue and I'm not sure what the examples were trying to show.

### If you can reproduce this with a minimal RxJS-only example, I'd love to see it.

**Closed by benlesh** 2022-02-28 17:50 UTC

**Comment by benlesh** [comment] 2022-02-28 17:53
Follow up: I added a couple of `taps` around the `endWith` in question in your example, and they're logging that it's behaving as expected:

![image](https://user-images.githubusercontent.com/1540597/156033416-bc803dc1-f917-4a5e-a406-7474f9a54d54.png)


https://stackblitz.com/edit/count-up-animation-with-angular-and-rxjs-vkuztu?file=src/app/count-up.directive.ts
