### ISSUE TITLE
takeUntil output does not complete when notifier emits according to expectObservable helper

### ISSUE THREAD

**Issue by Dari-K** [ReactiveX/rxjs#5330] opened 2020-02-27 21:18 UTC
## Bug Report

**Current Behavior**
The output from takeUntil never completes, even when the notifier observable emits.

**Reproduction**
https://stackblitz.com/edit/typescript-c7iuyj

```ts
testScheduler.run(({hot, expectObservable}) => {
    const actions = hot('-a-----b-');
    const result = actions.pipe(
        filter(val => val === 'a'),
        switchMap(() => interval(1).pipe(
            takeUntil(actions.pipe(filter(val => val === 'b')))
    )));
    const expectedValues = { 0: 0, 1: 1, 2: 2, 3: 3, 4: 4};

    expectObservable(result).toBe('--01234-', expectedValues);
    //Actual length: 5
    //Expected length: 5
    //Equal: true

    expectObservable(result).toBe('--01234|', expectedValues);
    //Actual length: 5
    //Expected length: 6
    //Equal: false
});
```

**Expected behavior**
The observable output by takeUntil should complete when the notifier observable emits.

**Environment**
- RxJS version: 6.5.4

**Comment by martinsik** [comment] 2020-02-28 10:16
You're only completing the inner Observable (that starts with `interval(1)`) not the source Observable (that starts with `actions`). You should put `takeUntil()` after `switchMap` if you want to complete whole chain.

For more info: https://medium.com/angular-in-depth/rxjs-avoiding-takeuntil-leaks-fb5182d047ef

**Comment by cartant** [comment] 2020-02-28 12:40
Closing this because it's not a bug. As Martin has explained, it's the expected behaviour.

**Closed by cartant** 2020-02-28 12:40 UTC
