### ISSUE TITLE
component variables inside a RxJS subscribe() function are undefined

### ISSUE THREAD

**Issue by vijender1256** [ReactiveX/rxjs#2026] opened 2016-10-11 17:51 UTC
Variables inside subscribe are undefined but when i put breakpoint before hitting service subscribe I have the variable defined.

In Service:
```ts
    getCashierRiskProfiles(): Observable<ICashierRiskProfile[]> {
        return this.http.get(this._baseUrl + "src/HTTPJson/cashierriskprofile.json")
            .map((res: Response) => res.json())
            .catch((error: any) => Observable.throw(error.json().error || 'Server error'));
    }
```
In Component:

   
```ts
    import { Component, OnInit} from "@angular/core";
    import { CashierRiskProfileService}   from "./cashierriskprofile.service";
    import { ICashierRiskProfile} from "../shared/interfaces";
    import { Observable } from 'rxjs/Observable';
                
      @Component({
                selector: "cashierriskprofile",
                templateUrl: "../src/app/cashierriskprofile/cashierriskprofile.component.html"
                })
            
        export class CashierRiskProfileComponent implements OnInit {
                filterText : string;
                cashierRiskProfiles: ICashierRiskProfile[];
            
             constructor(private sorter: Sorter,
                    private service: CashierRiskProfileService) {
            
                }
            
             ngOnInit() {
                    this.filterText = "Filter Exceptions:";
                    //// Observable technique
                    this.service.getCashierRiskProfiles()
                        .subscribe((riskProfiles) => {
                       this.cashierRiskProfiles = riskProfiles;
                       this.filterText = "Inside Subscribe:";
    
                        }, 
                        err => {
                            // Log errors if any
                            console.log(err);
                        });
                }
```
In above component code inside ngonInit() service call, this.cashierRiskProfiles inside the subscribe is undefined, but after I put breakpoint before the service callI have that variable available and defined. I have seen lot of people having this issue with component variables with this.variablename gettting undefined inside subscribe. When you notice this.filterText I can get the values assigned to it outside dataservice call, but when I put breakpoint inside subscribe, this.filterText is underfined dont know how I am losing variable inside subscribe. Can anyone tell what's going on  ?

**Comment by blesh** [comment] 2016-10-11 18:09
I'm having a hard time discerning what you're asking.

If you put a breakpoint on the line `this.cashierRiskProfiles = riskProfiles;`, then `this.cashierRiskProfiles` will, of course, be `undefined`, because nothing has set it yet. `riskProfiles` should be whatever your service responded with. However, *after* that line, `this.cashierRiskProfiles === riskProfiles` should be `true`, because you've set it. Other than that, I don't see any errors in your Rx code, and there is no behavior in RxJS that would cause arrow functions to treat `this` differently.

If that doesn't answer your question, I'd recommend posting the question on StackOverflow and tagging it with angular2 or ng2.

As this doesn't seem to be a RxJS related issue or bug, I'm going to close it for now, but feel free to continue to comment if you have more questions.

**Closed by blesh** 2016-10-11 18:09 UTC

**Comment by vijender1256** [comment] 2016-10-11 19:29
@blesh thank you, below code will explain it better:
```
 this.service.getCashierRiskProfiles().subscribe((cashiersProfiles) => {
            this.cashierRiskProfiles = cashiersProfiles;
            console.log(this.cashierRiskProfiles);
        });
```
If i put break point at console.log, by the time this.cashierRiskProfiles should have values assigned to it, but still when I hover on it, it still is undefined, but console.log is printing in console developer tools, the object that is getting returned from service, but on the hover on it I see value for this.cashierRiskProfiles is undefined.

But the real issue is unlike promises, may be observable is not waiting until the data is available and before that UI biding is done and I couldn't see the data on UI page. Promises is just working fine until I tried replacing it with Observable UI binding is not happening and when I tried to debug I see this.cashierRiskProfiles undefined inside subscribe.

I asked in stackoverflow but did not get any proper response: 
http://stackoverflow.com/questions/39899595/component-variables-inside-a-rxjs-subscribe-function-are-undefined

Thanks for responding :)

**Comment by david-driscoll** [comment] 2016-10-11 21:25
@vijender1256 are you sure that the `this` is undefined?

It may be that `this` is undefined in the chrome debugger, but that is related to TypeScript / Sourcemaps.

When TypeScript compiles

```typescript
(riskProfiles) => {
    this.cashierRiskProfiles = riskProfiles;
    console.log(this.cashierRiskProfiles);
}
```

It basically desugars down to...
```javascript
var _this = this;
this.service.getCashierRiskProfiles().subscribe(function (riskProfiles) {
    _this.cashierRiskProfiles = riskProfiles;
    console.log(_this.cashierRiskProfiles);
});
```

In this scenario the debugger looks at `this` and sees undefined, when in fact the `this` you are looking for is `_this`.

**Comment by david-driscoll** [comment] 2016-10-11 21:34
Another note, this is how the fat arrow function is supposed to work, the desugaring is for JavaScript support in browsers that do not yet support `=>`.

MDN has a great article on the behaviors of arrow functions.  See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#No_binding_of_this

**Comment by RajashekharGampa** [comment] 2017-02-18 15:23
Hi David and Vijender, I am facing the same undefined issue after assigning the value in subscribe.  What is the solution for this.  Thanks in advance.

**Comment by MFProduction** [comment] 2017-03-06 19:47
Hi, are there any news about this issue?

**Comment by trxcllnt** [comment] 2017-03-06 21:10
@MFProduction this is a chrome debugger issue, nothing to do with Rx

**Comment by MFProduction** [comment] 2017-03-07 10:05
thank you

**Comment by redoc123** [comment] 2017-05-30 18:14
add let self = this; before subscribe;
inside the subscribe instead of this.cashierRiskProfiles do self. cashierRiskProfiles

**Comment by cesarvarela** [comment] 2017-06-16 22:29
@trxcllnt Do you know where can I find information about the status of the issue?

**Comment by kkopiec** [comment] 2017-07-07 13:29
I am not too sure if the issue is the same but here is my solution:
service.getsth().subscribe(x => onSubscription(this.variableToAccess, x));

kind regards
K.

**Comment by finalxcode** [comment] 2017-11-17 08:16
look this,  https://github.com/angular/angular-cli/issues/8421

**Comment by kboucher** [comment] 2017-12-12 17:25
@david-driscoll Bravo, sir! I never suspected for a second that this might be an issue with Chrome debugger.

Whoever down-voted your post should be severely reprimanded.

For anyone else who know how `this` works and still can't get pass this issue, please refer to @david-driscoll 's comments above.

**Comment by sebaquevedo** [comment] 2018-01-09 15:34
i implemented the @kkopiec type of solution, i stablished my subscribe function on a service class, and on another component got the need to use properties of the component , set them inside of the function that class the service i mentioned.

i first tried using a named function to receive data from a callback in the service.

i ended using the arrow way on the component...
