### ISSUE TITLE
Observable.timer fires immediately for very large values

### ISSUE THREAD

**Issue by GregRos** [ReactiveX/rxjs#3282] opened 2018-01-31 20:16 UTC
**RxJS version:**
5.5.6
**Code to reproduce:**

    Observable.timer(10 ** 20);
    //or:
    Observable.timer(Infinity);

**Expected behavior:**
An observable that will fire after an incredibly long amount of time or never.

Alternatively, (less desireable), throwing an Error indicating the time is out of range.

**Actual behavior:**
An observable that emits immediately.

**Additional information:**

**Comment by kwonoj** [comment] 2018-01-31 20:23
dupe of https://github.com/ReactiveX/rxjs/issues/3015 .

**Closed by kwonoj** 2018-01-31 20:23 UTC
