### ISSUE TITLE
Observable does not implement InteropObservable

### ISSUE THREAD

**Issue by felixfbecker** [ReactiveX/rxjs#3890] opened 2018-07-04 00:13 UTC
## Bug Report

**Current Behavior**
I am trying to write a library interface that accepts `InteropObservable` for two reasons:
- to allow any Observable implementation to be passed
- I don't want to use `Observable` as an input type, because it is a class, and TypeScript will therefor reject passing in an instance of RxJS `Observable` if it is an instance of `Observable` from a different file (different package version, or duplicate because of `npm link`). Coding against interfaces is better than coding against implementations

I get the error: 
```ts
Type 'Observable<T>' is not assignable to type 'InteropObservable<T>'.
      Property '[Symbol.observable]' is missing in type 'Observable<T>'.
```

**Reproduction**
- REPL or Repo link:
https://stackblitz.com/edit/typescript-3v2qer

**Expected behavior**

I would expect to be able to have my interface accept `InteropObservable`, and pass in an RxJS concrete `Observable` without a compile error. 

**Environment**
- Runtime: any
- RxJS version: 6.2.1

**Possible Solution**
Add `symbol.observable` to `Observable`, and make it `implement InteropObservable`?

**Comment by kwonoj** [comment] 2018-07-04 00:23
Interesting. afaik `InteropObservable` is supposed to let rx's `Observable` accepts other observables, not in opposite way (that `InteropObservable` doesn't represent `Observable`). 

Still, I thought Observable already implemented `Symbole.observable` at least? 🤔 Don't recall exact history around those.

**Comment by cartant** [comment] 2018-07-04 00:48
`Observable` does [appear to be implement](https://github.com/ReactiveX/rxjs/blob/6.2.1/src/internal/Observable.ts#L279-L286) `[Symbol.observable]`.

**Comment by felixfbecker** [comment] 2018-07-04 00:57
It definitely is not in the published .d.ts: https://unpkg.com/rxjs@6.2.1/internal/Observable.d.ts

**Comment by cartant** [comment] 2018-07-04 00:58
This looks to be a TypeScript issue, as  this:

```ts
import { EMPTY, InteropObservable } from "rxjs";
import { observable } from "rxjs/internal/symbol/observable";

class Something {
  [observable]() { return EMPTY; }
}
declare const s: Something;
const i: InteropObservable<never> = s;
```

effects this error:

```
[ts]
Type 'Something' is not assignable to type 'InteropObservable<never>'.
  Property '[Symbol.observable]' is missing in type 'Something'.
```

**Comment by cartant** [comment] 2018-07-04 00:59
@felixfbecker Its being missing could be related to what appears to be a TypeScript problem.

**Comment by cartant** [comment] 2018-07-04 01:05
Actually, it's not TypeScript. The problem is that the `InteropObservable` declaration does not use the `const` that's in [`src/internal/symbol/observable.ts`](https://github.com/ReactiveX/rxjs/blob/master/src/internal/symbol/observable.ts#L13). It uses `Symbol.observable` directly:

```ts
export type InteropObservable<T> = { [Symbol.observable]: () => Subscribable<T>; };
```

Changing the snippet to this works fine:

```ts
import { EMPTY, InteropObservable } from "rxjs";

class Something {
  [Symbol.observable]() { return EMPTY; }
}
declare const s: Something;
const i: InteropObservable<never> = s;
```

**Comment by BioPhoton** [comment] 2019-08-12 22:58
@cartant as we have a solution posted in your last comment I believe we can close this issue

**Comment by benlesh** [comment] 2020-07-08 23:25
I believe that there's not much more we can do for this issue at this time. There's an adequate workaround in [this comment](https://github.com/ReactiveX/rxjs/issues/3890#issuecomment-402333046)

**Closed by benlesh** 2020-07-08 23:25 UTC
Labels: type: TS types

**Comment by jesseschalken** [comment] 2025-12-16 19:41
@benlesh The linked comment is about implementing `InteropObservable` for a custom type, but the OP is about `InteropObservable` not being implemented by `Observable`.

I understand this has been closed for a while but this still appears to be an issue with the latest RxJS 7.8.2, as this code does not typecheck:

```typescript
import { Observable, InteropObservable } from "rxjs";

function foo<T>(o: Observable<T>): InteropObservable<T> {
  return o;
}
```

```
Property '[Symbol.observable]' is missing in type 'Observable<T>' but required in type 'InteropObservable<T>'.ts(2741)
types.d.ts(93, 5): '[Symbol.observable]' is declared here.
```

The reason is that even though `Observable` implements `[Symbol_observable]()` [here](https://github.com/ReactiveX/rxjs/blob/e5351d02e225e275ac0e497c7b66eaa5f0c88791/src/internal/Observable.ts#L332), `Symbol_observable` has type `string | symbol` [here](https://github.com/ReactiveX/rxjs/blob/e5351d02e225e275ac0e497c7b66eaa5f0c88791/src/internal/symbol/observable.ts#L7) instead of `typeof Symbol.observable`.

The fix may be to just change that `string | symbol` to `typeof Symbol.observable`.

My use case is to provide an API that directly accepts RxJS Observables or custom observable implementations. At runtime this works, but the use of `string | symbol` in `Observable` doesn't allow the types to work out.
