### ISSUE TITLE
timer(x) does not work with very large numbers

### ISSUE THREAD

**Issue by bene-starzengruber** [ReactiveX/rxjs#6979] opened 2022-05-25 12:51 UTC
### Describe the bug

`timer(Number.MAX_SAFE_INTEGER)` emits immediately after subscription
the largest possible number is `47899622768639`, from `47899622768640` on it emits immediately

it is a small issue and can easily be workarounded but it makes for a nice default value for optional configurations.

### Expected behavior

`timer(Number.MAX_SAFE_INTEGER)` can be read as "never emit"

### Reproduction code

```typescript
timer(Number.MAX_SAFE_INTEGER) // emits immediately
timer(47899622768640) // emits immediately
timer(47899622768639) // emits "never"
```

### Reproduction URL

https://stackblitz.com/edit/rxjs-kbuxzw?devtoolsheight=60&file=index.ts

### Version

7.5.5

**Comment by kwonoj** [comment] 2022-05-26 02:20
Dupe of https://github.com/ReactiveX/rxjs/issues/3015

**Closed by kwonoj** 2022-05-26 02:20 UTC
