### ISSUE TITLE
The TS definition of Observable.form is incomplete

### ISSUE THREAD

**Issue by NoahSun** [ReactiveX/rxjs#2966] opened 2017-10-17 11:44 UTC
Name | Type | Attribute | Description
-- | -- | -- | --
ish | ObservableInput<T> |   | A subscribable object, a Promise, an Observable-like, an Array, an iterable or an array-like object to be converted.

when use this types will throw error:
[ts]
Argument of type 'IterableIterator<any>' is not assignable to parameter of type 'ArrayLike<{}>'.
  Property 'length' is missing in type 'IterableIterator<any>'.

```javascript
function* genterateDoubles(seed) {
    let i = seed;
    while (true) {
        yield i;
        i = 2 * i;
    }
}

const iterator = genterateDoubles(3);
const resultItr = Observable.from(iterator); //tip error
resultItr.subscribe(x => console.log(x));
```
[ts]
Argument of type 'Set<string | Window>' is not assignable to parameter of type 'ArrayLike<{}>'.
  Property 'length' is missing in type 'Set<string | Window>'.
```javascript
const s = new Set(['foo', window]);
Observable.from(s).subscribe( //s is error
    x => console.log(`onNext: ${x}`),
    e => console.log(`onError: ${e}`),
    () => console.log('onCompleted'),
);
```

Or did I make a coding error? what should i do?

**RxJS version: 5.4.3**

**Comment by kwonoj** [comment] 2017-10-17 16:18
closing as dupe of https://github.com/ReactiveX/rxjs/issues/2306 .

**Closed by kwonoj** 2017-10-17 16:18 UTC

**Comment by NoahSun** [comment] 2017-10-18 15:18
thank you. I find it.

```javascript
import { IteratorObservable } from 'rxjs/observable/IteratorObservable';

// 可迭代对象
function* genterateDoubles(seed) {
    let i = seed;
    while (true) {
        yield i;
        i = 2 * i;
    }
}

const iterator = genterateDoubles(3);
// 使用迭代器可观察对象来创建
const resultItr = IteratorObservable.create(iterator).take(3);
resultItr.subscribe(x => console.log(x));

// Set
const s = new Set(['foo', 1]);
// 使用迭代器可观察对象来创建
IteratorObservable.create(s).subscribe(
    x => console.log(`onNext: ${x}`),
    e => console.log(`onError: ${e}`),
    () => console.log('onCompleted'),
);
```
