### ISSUE TITLE
finalize docs are incomplete

### ISSUE THREAD

**Issue by cartant** [ReactiveX/rxjs#4578] opened 2019-02-19 06:06 UTC
### Documentation Related To Component:

The `finalize` operator.

### Please check those that apply

- [ ] typo
- [ ] documentation doesn't exist
- [x] documentation needs clarification
- [ ] error(s) in example
- [x] needs example

### Description Of The Issue

The docs state:

> Returns an Observable that mirrors the source Observable, but will call a specified function when the source terminates on complete or error.

`finalize` will also call its callback if the subscriber explicitly unsubscribes. See [this test](https://twitter.com/1StevieKilner/status/1097228842194948096).

The documentation needs an example, too.

---

Okay. I clearly pasted the wrong link. It's [this test](https://github.com/ReactiveX/rxjs/blob/6.4.0/spec/operators/finalize-spec.ts#L43-L52).

**Comment by dzhavat** [comment] 2019-02-19 08:16
@cartant Hilarious :D The `this test` link points to a tweet of a dog holding two boiled eggs in its mouth 😂

**Comment by cartant** [comment] 2019-02-19 08:40
@dzhavat I've added the correct link. And I've left the mistakenly-pasted link for the amusement of others.)

**Comment by lukk84** [comment] 2019-05-10 11:03
Here is another reproduction of this issue
https://stackblitz.com/edit/rxjs-bsv8sg

**Comment by avrim** [comment] 2019-06-11 08:18
HI, can we confirm that indeed finalize calls it's method in case we unsubscribe manually, before observable's execution reached complete  / error ? 
This is sad that I discovered this issue here :(

**Comment by BioPhoton** [comment] 2019-08-12 03:22
@cartant thanks a lot for the link with the dog. It was really nice having this in between all the issue stuff. Haha

Anyway, i will put it on my todo list.

**Comment by ClementVidal** [comment] 2019-08-29 14:31
Same behavior observed and discussed here:
https://stackoverflow.com/questions/57696249/rxjs-switchmap-and-tap-issue

IMHO this should deserve attention as it somehow introduce a new hookable "moment" in the lifetime of an observable which is not described yet .

**Comment by PDavid** [comment] 2019-10-09 17:16
Hi, I'd like to help with this issue. 
I have some experience with RxJS with developing Angular applications at my job.
Maybe this is a silly question, but to which branch should the PR of the documentation improvement be targeted? Should it be master or 6.x branch?

**Comment by cartant** [comment] 2019-10-09 19:36
@PDavid Please target `master`. Thanks.

**Comment by PDavid** [comment] 2019-10-10 06:55
@cartant Thanks, then I'll redo my changes and open a new PR to master.

**Comment by cartant** [comment] 2019-10-10 07:03
@PDavid Note that you can rebase your local branch, push to the PR and then change the PR's branch to `master` - a dropdown is made available to do so when you edit the PR's title.

**Comment by PDavid** [comment] 2019-10-11 09:29
@cartant Thanks for the rebase --onto hint. ;-) I rebased my branch onto master but needed to open a new PR because I already closed the original PR.
How can we move forward with this?
Who can have a look on the PR and provide feedback?

**Comment by cartant** [comment] 2019-10-11 09:32
It's in the queue. I can assure you that your work is appreciated, but we are all busy people. I will try to make some time on the weekend to go through the PR backlog.

**Comment by PDavid** [comment] 2019-10-11 09:56
Sure, thank you! Just wanted to make sure. :)

**Comment by JWO719** [comment] 2019-12-04 11:57
closed by #5065

**Closed by JWO719** 2019-12-04 11:57 UTC
Labels: status: Help Wanted, type: docs
