### ISSUE TITLE
Problems with distinctUntilChanged in combination with combineLatest

### ISSUE THREAD

**Issue by joeldatabox** [ReactiveX/rxjs#4998] opened 2019-09-02 20:48 UTC
When upgrading to version 6.5.2 I started to get weird behaviors previously reported in issue #1686 .

In version 6.5.0 this problem does not occur!

**Comment by chriszrc** [comment] 2020-05-02 15:16
It appears that distinctUntilChanged does not keep a copy of the previous value, only a reference to it:

https://github.com/ReactiveX/rxjs/blob/04ba6621fe9e09238e1796217d04107e52dd36d5/src/internal/operators/distinctUntilChanged.ts#L121

I've been running into this problem a fair amount, working with Angular forms and a single state store. I have the form values syncing to a store, but because sometimes I was merging observables that were looking at the form values directly, the previous values that distinctUntilChanged were storing were already updated, since they were holding references to the form variables. 

I understand there could be some serious performance hits making clones of previous values, but at a minimum, I think this behavior has to be really clearly stated in the docs, as I don't think it's what people are expecting.

**Comment by cartant** [comment] 2020-05-02 20:19
> In version 6.5.0 this problem does not occur!

@joeldatabox When opening an issue, please fill out the issue template. Without a clearly stated problem and without a minimal reproduction of the problem, it is unlikely a maintainer will allocate time to the issue.

> ... making clones of previous values

@chriszrc Nowhere in RxJS are values or keys cloned. Tondo so would be impractical.

Closing this because the issue template has not been filled out and because cloning keys is not going to happen.

**Closed by cartant** 2020-05-02 20:19 UTC
