### ISSUE TITLE
switch, concatAll, and mergeAll operators break generics on Observable/Subject

### ISSUE THREAD

**Issue by robwormald** [ReactiveX/rxjs#1538] opened 2016-03-26 03:38 UTC
**RxJS version:**
beta3 / TS 1.8+

**Code to reproduce:**
With the new typings augmentation setup:

``` typescript

import {Observable} from 'rxjs/Observable'

//define something with a typed observable property

class Test {
  ticks: Observable<string> = new Observable()
}
```

As expected, ticks is an Observable of strings with no operators - now, import a non-broken operator, like map:

``` typescript

import {Observable} from 'rxjs/Observable'
import 'rxjs/add/operator/map'

class Test {
  ticks: Observable<string> = new Observable()
}
```

All good up until here.

Now, import one of the following operators: `switch`, `concatAll` or `mergeAll`:

``` typescript

import {Observable} from 'rxjs/Observable'
import 'rxjs/add/operator/switch'

class Test {
  ticks: Observable<string> = new Observable()
}
```

**Expected behavior:**

No TS errors should be seen.

**Actual behavior:**

IDE and TS compilation complain with `Type Observable<{}> is not assignable to type Observable<string>. Type '{}' is not assignable to Type 'string'`

**Additional information:**

This manifests because the root Rx.ts file imports all the operators, and the listed 3 operators pollute the whole environment - so `import {Observable} from 'rxjs/Rx'` is unusable without casting. Importing from `rxjs/Observable` and any other operator other than these three works fine.

**Comment by robwormald** [comment] 2016-03-26 03:38
cc @vladima and @david-driscoll for their typings expertise.

**Comment by robwormald** [comment] 2016-03-26 03:41
also @kwonoj as this would probably make tests explode.

**Comment by vladima** [comment] 2016-03-26 05:45
this behavior in TypeScript is by design. TypeScript compiler always assumes that type parameters are covariant and the only place where this assumption changes - function parameters - in this cases type parameters are treated as [bivariant](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Type%20Compatibility.md#function-parameter-bivariance). In this particular case apparently all other operators except  `switch`, `concatAll` and `mergeAll` use type parameter of enclosing class only as type of parameter and it never appear i.e. in return type or as type of property.
```ts
    export interface ConcatAllSignature<T> {
    (): T; // T from Observable<T> flows here as a return type of call signature
}
```

**Comment by vladima** [comment] 2016-03-27 02:42
just to clarify, this behavior is the part of the compiler for quite a long time and was not caused by some recent change,

**Comment by david-driscoll** [comment] 2016-03-27 19:15
I believe this is also a consequence of #1475, relevant notes about this particular behavior were made in #1474.

broken:
```typescript
ticks: Observable<string> = new Observable()
```

working:
```typescript
ticks: Observable<string> = new Observable<string>()
// or
ticks = new Observable<string>()
```

**Comment by vladima** [comment] 2016-03-27 21:54
No, I'd say #1475 is unrelated. If #1474 was applied it will have the same effect (`T` will appear as a type of property) however #1475 uses different strategy

**Comment by n00dl3** [comment] 2017-02-20 17:14
I have the same kind of problem with this code :

> property 'do' does not exist on type 'Event' 

```
import {Observable, Subject} from "rxjs";

export class AutoComplete {
    typeEvents = new Subject<Event>();

    doStuff(): void {
        Observable.merge(
            this.typeEvent.debounceTime(300).switch().do((event: Event) => {
                // collateral damages
            })
        ).subscribe();
    }
}
```

I thought it was related, but maybe I just missed something, forgive me if that's the case...

I'm using `rxjs@5.1.1` and `typescript @2.1.6`

**Comment by blesh** [comment] 2017-02-20 23:17
@n00dl3 ... there's at least one typo in there... `this.typeEvent.debounceTime` should be `this.typeEvents.debounceTime`.

Your error seems unrelated to this issue, though. At least at first glance.

**Comment by david-driscoll** [comment] 2017-02-21 03:59
@n00dl3 it appears you are using switch incorrectly.

Switch will unwrap to the underlying object (in this case `Event`).  The general use case for `switch` is when you have an Observable of Observables, where you want to `subscribe` to the latest observer to be emitted by the outer observable.

Something like
```typescript
Observable.of(1, 2, 3)
    .map(x => Observable.timer(1000).map(z => x))
    .switch();

// or switchMap combines the two

Observable.of(1, 2, 3)
    .switchMap(x => Observable.timer(1000).map(z => x));
```

In your scenario you should be able to simplify it to:

```typescript
        Observable.merge(
            this.typeEvents.debounceTime(300)
            .do((event: Event) => {
                // collateral damages
            })
        ).subscribe();
```

You may be able to even reduce it to (unless you are merging additional events)

```typescript
    this.typeEvents.debounceTime(300)
            .do((event: Event) => {
                // collateral damages
            }).subscribe();
```

**Comment by blesh** [comment] 2017-02-21 05:13
@robwormald This appears to be an issue with TypeScript, more than something we can correct on our end.

I'm going to close this for now with the advice that people should be more specific like so, which will resolve their problems:

```js
class Test {
  ticks = new Observable<string>();
}
```

**Closed by blesh** 2017-02-21 05:13 UTC

**Comment by n00dl3** [comment] 2017-02-21 08:23
Oh yes, thank you, I was missing something then, I didn't get the "higher order observable", my bad. Sorry for bothering you, guys.
