### ISSUE TITLE
fromPromise support in TestScheduler

### ISSUE THREAD

**Issue by ncuillery** [ReactiveX/rxjs#2633] opened 2017-06-02 15:11 UTC
**RxJS version:** 
5.4.0

**Code to reproduce:** 
I've added two test cases to the TestScheduler test suite:

```javascript
it('should handle of', () => {
  expectObservable(Rx.Observable.of(1)).toBe('(a|)', {a: 1});
});

it('should handle fromPromise', () => {
  expectObservable(Rx.Observable.fromPromise(Promise.resolve(1))).toBe('(a|)', {a: 1});
});
```

See: https://github.com/ncuillery/rxjs/commit/09b09a056d50e630c976183b20ffe03f8c4e8781

**Expected behavior:**
The tests pass ✅ 

**Actual behavior:**
The first test using `Observable.of` passes, but the second fails: the output array of notifications is empty. I don't even have the completed event. Actually if I replace the marble with an empty string, the test passes:
```
expectObservable(Rx.Observable.fromPromise(Promise.resolve(1))).toBe('', {});
```

**Additional information:**
- On [SO](https://stackoverflow.com/questions/32602671/how-can-i-use-the-testscheduler-with-promises-and-delays) I saw that RXJS 4 embedded a promise support in the TestScheduler with `createResolvedPromise` but it seems to be gone in RxJS 5: https://github.com/ReactiveX/rxjs/search?utf8=%E2%9C%93&q=createResolvedPromise&type=

**Comment by kwonoj** [comment] 2017-06-02 15:56
Yes, native promise probably won't work in testscheduler as there's no way to reschedule promise in synchronous scheduler. I've migrated sort of similar from v4 for compat scheduler (https://github.com/kwonoj/rxjs-testscheduler-compat/blob/master/src/VirtualPromise.ts) and guess that'll probably work as well, haven't tried it though. 

I was trying to rewrite testscheduler and integrate both interfaces at once, but wasn't able to make progress yet.

**Comment by staltz** [comment] 2017-06-03 17:42
Duplicate of https://github.com/ReactiveX/rxjs/issues/701 and basically impossible because https://github.com/ReactiveX/rxjs/pull/745

**Comment by kwonoj** [comment] 2017-06-05 00:37
I'll closing issue as @staltz provided additional descriptions in current testscheduler.

**Closed by kwonoj** 2017-06-05 00:37 UTC
