### ISSUE TITLE
fromEvent can't select DOM??? by using document.querySelector( )???

### ISSUE THREAD

**Issue by Tonysmark** [ReactiveX/rxjs#4939] opened 2019-07-31 08:11 UTC
## currently version
- Angular ~8.1.2
- rxjs ~6.4.0
## troubles
I expect to see mouse event show up in my console , but it didn't work that well .
Here is the code I'm using: 
```ts
class Drag implements AfterViewInit {
  ngAfterViewInit() {
    const bodyDom = document.body;
    const dragDom = document.querySelector('#drag');
    const mouseDown = fromEvent(dragDom, 'mousedown');
    const mouseMoive = fromEvent(bodyDom, 'mousemoive');
    const mouseUp = fromEvent(bodyDom, 'mouseup');
    mouseDown.pipe(
      map(e => mouseMoive),
      takeUntil(mouseUp),
      concatAll()
    );
    mouseDown.subscribe(console.log);
  }
}
const drag = new Drag();
drag.ngAfterViewInit();
```
and here is the trouble i've got;
![image](https://user-images.githubusercontent.com/22767695/62194689-f6ed3b80-b3ac-11e9-9d20-4d812f5ef678.png)

FYI:
I've read the documentation from rxjs site which is this [fromEvent](https://rxjs-dev.firebaseapp.com/api/index/function/fromEvent) and that's what I see from youtube video [rxjs in 30 days](https://www.youtube.com/watch?v=bgi3Uaab1ok) in 29:08 
he was successfully make the dom event work.

**Comment by cartant** [comment] 2019-07-31 08:18
Subscribe to the observable returned by `pipe` - you ignore it - rather than the source.

**Comment by Tonysmark** [comment] 2019-07-31 08:21
> Subscribe to the observable returned by `pipe` - you ignore it - rather than the source.

but when I use document rather than dragDom this will work !!

**Comment by jgbpercy** [comment] 2019-07-31 14:34
It's probably because there is no element with id `drag` when that code runs. Try debugging and check what the value of `dragDom` is?

@cartant is also correct of course, the obs you're subscribing to in that code wont have the piped operators applied to it. For that you need:
```
mouseDown.pipe(
    map(e => mouseMoive),
    takeUntil(mouseUp),
    concatAll()
).subscribe(console.log);
```

Finally, this isn't really the place for this but just a little pointer than Angular style tends to discourage direct DOM access using things like `document`. Obviously it's fine for test code, which this may be, but in general it's best to use abstractions like @ViewChild - anyway there's plenty in the Angular docs about that, but I just thought I'd mention.

**Comment by cartant** [comment] 2019-07-31 15:10
Closing this as there is insufficient information in the issue - no one here can know if any elements will match your selector - and, in any case, this has more to do with Angular than RxJS.

If you really think that `fromEvent` has a bug, create a minimal, vanilla reproduction. You will likely find that it works just fine.

**Closed by cartant** 2019-07-31 15:10 UTC
