### ISSUE TITLE
Uncaught error is not being thrown in certain situation

### ISSUE THREAD

**Issue by olessavluk** [ReactiveX/rxjs#2623] opened 2017-05-28 22:24 UTC
**RxJS version:**
versions after 5.1.0 (including)

**Code to reproduce:**
```javascript
Rx.Observable.of(null)
  .delay(1)
  .flatMap(v => (new Rx.BehaviorSubject(null)).map(() => v))
  .map(() => {
    throw new Error('tasty error');
  })
  .startWith('error should go next')
  .subscribe(
    v => console.log(v)
  );
```
you can also [run this code in JSBin](http://jsbin.com/qetusat/edit?html,js,console)

**Expected behavior:**
`Uncaught Error: tasty error` should be thrown

**Actual behavior:**
Error was swallowed

**Additional information:**
 - This was introduced in v.5.1.0 (previous works fine for me)
 - If you try to remove `delay` or `flatMap` + `BehaviourSubject` error is thrown

**Comment by kwonoj** [comment] 2017-05-28 22:27
this is dupe of https://github.com/ReactiveX/rxjs/issues/2565, there seems some odds around subject.

**Closed by kwonoj** 2017-05-28 22:27 UTC
