### ISSUE TITLE
Rewrite ajax module to use abortable `fetch`

### ISSUE THREAD

**Issue by OliverJAsh** [ReactiveX/rxjs#4534] opened 2019-02-06 14:56 UTC
## Feature Request

The ajax module is currently built on top of `XHR`. IIUC, this is because `fetch` did not initially support cancellation (and maybe also for browser support?). However, [`fetch` does not support cancellation](https://developers.google.com/web/updates/2017/09/abortable-fetch).

There might be benefits to using `fetch` under the hood instead of `XHR`. One that I've just stumbled across is, when using `XHR`, there is [no way to reliably detect network errors](https://github.com/ReactiveX/rxjs/issues/1926#issuecomment-246131172), whereas [with `fetch` there is](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Checking_that_the_fetch_was_successful).

Is this something we should consider? Or perhaps it should exist in user land.

**Comment by kwonoj** [comment] 2019-02-06 15:04
Dupe of https://github.com/ReactiveX/rxjs/issues/4128. We have long term plan but not able to polyfill abortcontroller makes whole rewrite will take time to happen. My userland module https://github.com/kwonoj/oxid/issues/71 plan to have it in userlans first.

**Comment by OliverJAsh** [comment] 2019-02-15 11:24
Related: `abortable-rx` allows you to use `fetch` inside `switchMap` https://github.com/felixfbecker/abortable-rx/tree/0b60bfc80e61904e720f99e9ca8c662c72dc4f51#using-fetch-inside-switchmap

**Comment by kwonoj** [comment] 2019-07-16 23:06
This is achieved, closing. Each issue may need to be filed separately if found.

**Closed by kwonoj** 2019-07-16 23:06 UTC
