### ISSUE TITLE
Trailing value in auditTime

### ISSUE THREAD

**Issue by ivan7237d** [ReactiveX/rxjs#3325] opened 2018-02-17 11:51 UTC
**RxJS version:**
6.0.0-alpha.3 (but would also work with previous versions)

**Code to reproduce:**
```ts
Rx.Observable.of(1)
  .concat(Rx.Observable.never())
  .auditTime(1000)
  .subscribe(console.log);
```

**Expected behavior:**
The same values should be emitted whether the second line `.concat(Rx.Observable.never())` is present or not.

**Actual behavior:**
A value is emitted only when that line is present.

**Additional information:**
A completion of the source observable (`of(1)` or `of(1).concat(Rx.Observable.never())`) should not have any meaning beyond indicating that no more values will be emitted, so it shouldn't cause `auditTime` to drop the value.

**Comment by dengwanc** [comment] 2018-03-06 15:13
dose `throttleTime` have the same actual meaning with `auditTime` ? @benlesh

**Comment by deadbeef84** [comment] 2018-03-13 10:57
We just ran into this issue. The behavior doesn't seem to be defined by the auditTime-spec either. We recently had a similar issue with `throttleTime` #3351.

**Comment by benlesh** [comment] 2018-03-15 18:55
Seems like a duplicate of #3430 and probably similar to #2859

**Closed** 2020-08-18 17:32 UTC
Labels: PR: needs review
