### ISSUE TITLE
ERROR in node_modules/rxjs/internal/types.d.ts(81,44): error TS1005: ';' expected.

### ISSUE THREAD

**Issue by Skewled** [ReactiveX/rxjs#4540] opened 2019-02-07 21:07 UTC
## Bug Report

**Current Behavior**
There is a missing ';' reported for types.d.ts

````** Angular Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **
                                                                                          
Date: 2019-02-07T20:57:38.886Z
Hash: d01965b30f3394f9889f
Time: 2174ms
chunk {main} main.js, main.js.map (main) 1.93 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 683 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 15.6 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 335 kB [initial] [rendered]

ERROR in node_modules/rxjs/internal/types.d.ts(81,44): error TS1005: ';' expected.
node_modules/rxjs/internal/types.d.ts(81,74): error TS1005: ';' expected.
node_modules/rxjs/internal/types.d.ts(81,77): error TS1109: Expression expected.```

**Reproduction**
```
Install Angular and NPM current versions.
ng new test
npm install
ng serve --host 0.0.0.0 
Output will show the error on the missing ';'
```

**Expected behavior**
Expect it to work and have the correction made for the missing semi-colon.

**Environment**
Angular CLI: 6.0.8
Node: 11.6.0
OS: darwin x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.4.0
typescript                        2.7.2
webpack                           4.8.3

**Possible Solution**
<!--- Only if you have suggestions on a fix for the bug -->

**Comment by cartant** [comment] 2019-02-07 21:10
Closing this as a dupe of https://github.com/ReactiveX/rxjs/issues/4512 as I believe that is the underlying problem.

**Closed by cartant** 2019-02-07 21:10 UTC

**Comment by AliAdravi** [comment] 2019-02-23 18:56
Change to from rxjs 6.4.0 TO "rxjs": "6.0.0",
It worked for me

**Comment by aleRozo** [comment] 2019-02-25 22:46
> Cambie de rxjs 6.4.0 a "rxjs": "6.0.0", 
> funcionó para mí

@AliAdravi can you show me how did you do it?

**Comment by patriziofilloramo** [comment] 2019-02-27 10:11
@aleRozo 
npm install rxjs@6.0.0 rxjs-compat@6.0.0 --save

thanks @AliAdravi

**Comment by dherenj** [comment] 2019-03-01 18:25
I just upgraded the Angular CLI and Core for my project to the latest versions using "ng update @angular/cli @angular/core" inside the project and the problem went away. Hope this helps!

**Comment by rahulpagada** [comment] 2019-03-02 05:38
>1) "rxjs": "^6.0.0"   change "rxjs": "6.0.0"
>2) and next go to terminal
>3) and install npm using this command "npm i"

**Comment by aleRozo** [comment] 2019-03-04 15:18
thank you for your help. My problem continue because is a problem of a dependency of "angular-resizable"
________________________________
De: dherenj <notifications@github.com>
Enviado: viernes, 1 de marzo de 2019 1:25 p.m.
Para: ReactiveX/rxjs
Cc: Alejandra Rozo; Mention
Asunto: Re: [ReactiveX/rxjs] ERROR in node_modules/rxjs/internal/types.d.ts(81,44): error TS1005: ';' expected. (#4540)


I just upgraded the Angular CLI and Core for my project to the latest versions using "ng update @angular/cli @angular/core" inside the project and the problem went away. Hope this helps!

**Comment by rahulpagada** [comment] 2019-03-05 03:58
If you are using rxjs-compat then you also need to do following in order to fixed the issue. change the rxjs-compat version from "rxjs-compat": "^6.2.2" to "rxjs-compat": "6.2.2"

**Comment by Charuka09** [comment] 2019-03-17 05:27
if you are still facing the problem, go to package.json

remove rxjs and add rxjs-compat also, "rxjs-compat": "^6.4.0" to "rxjs-compat": "6.4.0",

change the typscript version to 2.8

run npm install
This will work for you!

**Comment by aleRozo** [comment] 2019-03-20 03:03
> Si aún estás enfrentando el problema, ve a package.json
> 
> quite rxjs y agregue rxjs-compat también, "rxjs-compat": "^ 6.4.0" a "rxjs-compat": "6.4.0",
> 
> cambiar la versión de typscript a 2.8
> 
> ejecutar npm instalar 
> Esto funcionará para usted!

g

**Comment by rafmos** [comment] 2019-03-20 08:00
> @aleRozo
> npm install rxjs@6.0.0 --save
> 
> thanks @AliAdravi

Worked for me. Thanks.

**Comment by realsony** [comment] 2019-03-20 16:43
Nothing of these solutions worked for me.

Still `ERROR in node_modules/rxjs/internal/types.d.ts(81,44): error TS1005: ';' expected.
node_modules/rxjs/internal/types.d.ts(81,74): error TS1005: ';' expected.
node_modules/rxjs/internal/types.d.ts(81,77): error TS1109: Expression expected.`

-arrived here by google

**Comment by FahriMZ** [comment] 2019-03-23 12:18
@realsony 
I got the same error. Changing "rxjs": "^6.0.0" to "6.0.0" fix the error

**Comment by akshay-zz** [comment] 2019-03-31 11:42
@realsony , Did you find the solution for this.

**Comment by akshay-zz** [comment] 2019-03-31 11:43
@FahriMZ , It didn't solved for me.

**Comment by realsony** [comment] 2019-03-31 11:47
> @realsony , Did you find the solution for this?

i solved it but right now I cannot remember in detail how to. Sorry. Right now I use:
"rxjs": "~6.3.3" and "typescript": "~3.2.2" which works

**Comment by cordsac** [comment] 2019-04-01 17:05
You need to do some changes in `package.json` 

1. Go to `package.json` and modify `"rxjs": "^6.0.0"` to` "rxjs": "6.0.0"`

2. Then run `npm update` in your project

**Comment by andersondealmeidasp** [comment] 2019-04-02 00:05
Thank you @cordsac ...

**Comment by kamleshbiloniya** [comment] 2019-04-04 16:50
This worked for me  in ionic@3
>>>sudo npm install -g typescript@latest
>>>npm i rxjs@6.3.3 rxjs-compat@6.3.3 promise-polyfill --save

**Comment by shailugit** [comment] 2019-04-07 20:44
Go to your project directory and run the command >npm install rxjs@6.0.0 --save

**Comment by joaovitormarques** [comment] 2019-04-17 16:16
> @realsony
> I got the same error. Changing "rxjs": "^6.0.0" to "6.0.0" fix the error

Indeed it fixes the error! Remember to run 'npm install' after you made this canges.

**Comment by jerry-rana** [comment] 2019-04-18 17:12
npm install rxjs@6.0.0 --save
Worked for me,
thanks

**Comment by sranmanpreet** [comment] 2019-04-19 01:30
As for most of you, below command works for me as well:
npm install rxjs@6.0.0 --save

**Comment by ankurbalyan** [comment] 2019-04-25 19:02
Started using yarn today and i fixed it with 

yarn add rxjs@6.0.0

**Comment by AnshulRatlam** [comment] 2019-05-07 07:39
> @aleRozo
> npm install rxjs@6.0.0 --save
> 
> thanks @AliAdravi

it work for me

**Comment by fabiosoli** [comment] 2019-05-11 10:40
> You need to do some changes in `package.json`
> 
> 1. Go to `package.json` and modify `"rxjs": "^6.0.0"` to` "rxjs": "6.0.0"`
> 2. Then run `npm update` in your project

It worked for me

**Comment by Anyoks** [comment] 2019-05-15 09:44
> > @aleRozo
> > npm install rxjs@6.0.0 --save
> > thanks @AliAdravi

Worked for me!

**Comment by basantkumarpogeyan** [comment] 2019-05-25 09:42
npm install rxjs@6.0.0 --save 
work for me
Thanks very much

**Comment by Marimuthu-Aathi** [comment] 2019-06-11 12:55
npm install rxjs@6.0.0 --save
Worked for me,
thanks

**Comment by dssagar93** [comment] 2019-06-17 11:57
It worked. Thanks

**Comment by fabriciodev9** [comment] 2019-06-28 16:53
> You need to do some changes in `package.json`
> 
> 1. Go to `package.json` and modify `"rxjs": "^6.0.0"` to` "rxjs": "6.0.0"`
> 2. Then run `npm update` in your project

Thank you, @cordsac.

**Comment by lianmaung** [comment] 2019-06-28 18:16
Doing this "npm install rxjs@6.0.0 --save" solved my problem. Thanks!

**Comment by NarenShalem** [comment] 2019-07-10 04:26
npm uninstall rxjs (higher version of rxjs above 6.0.0)
npm install rxjs@6.0.0 --save

This is worked for me!

**Comment by jocelo** [comment] 2019-07-11 19:30
> Change to from rxjs 6.4.0 TO "rxjs": "6.0.0",
> It worked for me

Worked for me as well!

**Comment by feryuk** [comment] 2019-07-12 10:33
> > Cambie de rxjs 6.4.0 a "rxjs": "6.0.0",
> > funcionó para mí
> 
> @AliAdravi can you show me how did you do it?

Open up package.json, and change "rxjs": "^6.0.0", to "rxjs": "6.0.0" 
I hope it helps.

**Comment by RyanOC** [comment] 2019-07-12 14:47
Why did this work?

**Comment by esteban-gs** [comment] 2019-07-14 04:58
> > 1. "rxjs": "^6.0.0"   change "rxjs": "6.0.0"
> > 2. and next go to terminal
> > 3. and install npm using this command "npm i"
> > 4. enjoy

This worked for me. Thanks
