### ISSUE TITLE
Pipe signature changes in 6.3 broke valid(?) type check

### ISSUE THREAD

**Issue by jgbpercy** [ReactiveX/rxjs#4157] opened 2018-09-19 15:32 UTC
## Bug Report

**Current Behavior**
The following does not type check:
```
import { Observable, OperatorFunction } from 'rxjs';

function pipeLike(obs: Observable<any>, ...operators: OperatorFunction<any, any>[]): Observable<any> {
  return obs.pipe(...operators); // error here: "[ts] Expected at least 0 arguments, but got 0 or more."
}
```

**Reproduction**
Paste the above into an editor or try to compile with tsc (I would put it into a stackblitz but it seems flaky with rxjs/type checks). You get the rather perplexing ts error "[ts] Expected at least 0 arguments, but got 0 or more."

**Expected behavior**
I believe this should type check ok? It does in 6.2.x, and it does if I clone rxjs and restore the old Observable.pipe overload.

**Environment**
- RxJS version: 6.3.2

**Possible Solution** / **Additional context/Screenshots**
This will probably break a million other things that I'm not thinking of, but making all of the pipe overload's params optional seems like it would fix this issue (i.e. `pipe<A, B>(op1?: OperatorFunction<T, A>, op2?: OperatorFunction<A, B>): Observable<B>;` and so on)

Anyway, this was definitely introduced by https://github.com/ReactiveX/rxjs/pull/3945 , but reading that pull and the associated issue, I get that there's are some compromises and issues around the pipe overloads/signature. It may be that this failing type checking is worth the trade off for the other fixes that PR made?

I only came across this in a small personal project, and it may not be the best way to achieve what I'm trying to do anyway, so I don't want to make out that I have a super solid use case that this is breaking. But if this wont be fixed it would be good to know the 'right' way to do something along the lines of the code above? I guess something like
```
function pipeLike(obs: Observable<any>, ...operators: OperatorFunction<any, any>[]): Observable<any> {
  return obs.pipe(operators[0], operators[1], operators[2], operators[3], operators[4],
    operators[5], operators[6], operators[7], operators[8], ...operators.slice(9)
  );
}
```
But I think that wont work exactly like that because you end up passing something that looks like [op1, op2, op3, undefined, undefined, undefined ...] which will break? (can't test right now).

**Comment by cartant** [comment] 2018-09-19 17:35
This looks like a dupe of https://github.com/ReactiveX/rxjs/issues/3989

**Comment by jgbpercy** [comment] 2018-09-19 17:58
Gah, sorry, I searched but I didn't search thoroughly enough!

**Closed** 2018-09-19 18:03 UTC

**Comment by cartant** [comment] 2018-09-19 18:06
No worries. Note that the spread syntax only ever worked for the general case in two minor versions and at the expense of forsaking pretty much all type checking in `pipe`.

**Comment by jgbpercy** [comment] 2018-09-19 18:29
Not to seem more invested in this than I actually am, but it worked for _my_ purposes before 6.2.1... I had overloads matching my rxjs pipe for my pipe-like thing, so the fact that my function implementation relied on the weird signatured overload that was changed in #3789 didn't matter because the actual implemented call through that function had any for the type params. The #3789 change didn't affect me one way or the other.

**Comment by cartant** [comment] 2018-09-19 19:26
This is one of those "someone's bug fix is someone else's breaking change" and, unfortunately, you happen to be the "someone else".

You could probably make this work with TypeScript 3.0 - see the original issue - but the real solution is for `pipeFromArray` to be exported as part of the public API, IMO.

**Comment by jgbpercy** [comment] 2018-09-19 21:32
Yeah no biggie, I'll keep an eye on the other issue, thanks for taking the time to respond :)
