### ISSUE TITLE
chore(operator): Remove ensure alias

### ISSUE THREAD

**Issue by blesh** [ReactiveX/RxJS#175] opened 2015-08-14 23:06 UTC
As @mattpodwysocki pointed out in #169, ensure was removed from Rx 3.X, so we don't need that alias. [This](https://github.com/ReactiveX/RxJS/blob/47b178bddba65272f957602b8a6c69f79cc73da6/src/Observable.ts#L155) just needs removed, along with [it's assignment in Rx.ts](https://github.com/ReactiveX/RxJS/blob/47b178bddba65272f957602b8a6c69f79cc73da6/src/Rx.ts#L150)

**Comment by mattpodwysocki** [comment] 2015-08-14 23:06
@blesh marked as duplicate of #174

**Closed by mattpodwysocki** 2015-08-14 23:06 UTC
Labels: status: PRs welcome

**Comment by blesh** [comment] 2015-08-14 23:07
HEH... [too many cooks](https://www.youtube.com/watch?v=QrGrOK8oZG8). :)
