### ISSUE TITLE
[Request] Make WebSocketSubject distinguish between client and server message

### ISSUE THREAD

**Issue by datrinh** [ReactiveX/rxjs#3617] opened 2018-04-28 13:17 UTC
I created an observable for my websocket connection using WebSocketSubject from rxjs. So far so good the server-client communication is working. Now the thing is: I can't distinguish between the origins of the message in my client. I send messages by calling next() on the subject. All subscriptions on the client get those messages too. It would be very useful to have the option to only send from client to server. Or is this already possible?

The implementation mainly stems from this article: https://medium.com/factory-mind/angular-websocket-node-31f421c753ff

My code:
```ts
socket$: WebSocketSubject<any>;

constructor() {
  this.socket$ = WebSocketSubject.create(SOCKET_URL);

  this.socket$.subscribe(
    (message) => console.log('<-- ' + message),
    (err) => console.error('Error on WebSocket:', err),
    () => console.warn('Completed!')
   );
}

send(message: SocketMessage) {
  const tmp: any = {};
  tmp.type = message.type;
  tmp.payload = message.payload;
  // This will be received by the server but also by client subscriptions = bad
  this.socket$.next(JSON.stringify(tmp));
}
```

**Comment by benlesh** [comment] 2018-05-04 18:32
I can't reproduce this, do you have a minimal reproduction?

**Comment by sebastianvog** [comment] 2018-05-04 18:55
@datrinh as your implementation is based on the medium article, are you sure your websocket server doesn't just send back the messages you sent it? Just a thought.... since their Demo websocket server does this.

**Comment by benlesh** [comment] 2018-05-21 03:53
Closing as cannot reproduce.

**Closed by benlesh** 2018-05-21 03:53 UTC
Labels: status: more information needed
