### ISSUE TITLE
Memory Leak with .publish.refCount and Angular2 http

### ISSUE THREAD

**Issue by Guardiannw** [ReactiveX/rxjs#1630] opened 2016-04-15 19:28 UTC
**RxJS version:**
5.0.0-beta-6
**Code to reproduce:**
See [http://embed.plnkr.co/T0timA2kSvHwuIkARgOp/](http://embed.plnkr.co/T0timA2kSvHwuIkARgOp/)
**Expected behavior:**
It should not memory leak.

**Actual behavior:**
The leak is shown when high volume of requests are called, (e.g. using the repeat operator) using the .publish.refCount (and others) operators are used.  When run, it causes a continuous memory leak until the hot observable no longer has any subscribers.

**Additional information:**
I have not been able to find the code that is causing the problem.  I only know 2 things.

1. It doesn't occur when I refrain from using the .publish.refCount (or others, e.g., share()) operators.
2. It seems to be only happening when i use angular 2's http observables.  (i.e., I tried it using Observable.of([0,1,2,3]) and it did not leak).

@blesh Please help me solve this, it is crucial for use on a production system.  
@trxcllnt @kwonoj Thank you both for helping me with my last set of leaks.  I would appreciate any insights you can offer in this one as well please.

Thank you,

**Comment by trxcllnt** [comment] 2016-04-15 19:30
@Guardiannw have you filed this with the Angular 2 team?

**Comment by Guardiannw** [comment] 2016-04-15 19:33
@trxcllnt Just now.

**Comment by kwonoj** [comment] 2016-04-15 20:18
I gave a quick try with raw Rx only (`Observable.interval(100).take(1).repeat().share()...`) and haven't observed noticeable leak yet. Trying with `http`..

**Comment by kwonoj** [comment] 2016-04-15 20:39
@Guardiannw , honestly I'm not sure if this is related or not - 
when `http` makes request in your plunkr, `addEventListener('load')` (https://github.com/angular/angular/blob/60727c4d2ba1e4b0b9455c767d0ef152bcedc7c2/modules/angular2/src/http/backends/xhr_backend.ts#L81) throws for some reason makes error object is continuously being created, `getStacktraceWithUncaughtError` in `angular2-polyfill`.

Would you mind give it a try if you're seeing same as I saw? Below's whole stack I see: (I've replaced minified cdn to dev build)

![image](https://cloud.githubusercontent.com/assets/1210596/14574255/54ba5768-030f-11e6-9113-20f6fd137d1b.png)

**Comment by kwonoj** [comment] 2016-04-15 20:40
fyi: chrome 50, windows 10.

**Comment by Guardiannw** [comment] 2016-04-15 20:42
@kwonoj Thanks for showing that to me.  I do not get that in my browser.  Chrome 49 windows 7.

**Comment by Guardiannw** [comment] 2016-04-15 20:43
@kwonoj Let me try with your dev build

**Comment by kwonoj** [comment] 2016-04-15 20:44
@Guardiannw dev build I mean is just replaced `.min` to `.dev` etcs hosted in `npmcdn` and `angular`.

**Comment by kwonoj** [comment] 2016-04-15 20:44
```
    <script data-require="rxjs@5.0.0-beta.6" data-semver="5.0.0-beta.6" src="https://npmcdn.com/rxjs@5.0.0-beta.6/bundles/Rx.js"></script>
    <script data-require="angular.js@2.0.0" data-semver="2.0.0" src="https://code.angularjs.org/2.0.0-beta.15/angular2.dev.js"></script>
    <script data-require="angular.js@2.0.0" data-semver="2.0.0" src="https://code.angularjs.org/2.0.0-beta.15/http.dev.js"></script>
```

**Comment by Guardiannw** [comment] 2016-04-15 20:44
@kwonoj Yes I know, Thank you though!

**Comment by Guardiannw** [comment] 2016-04-15 20:47
@kwonoj No, It doesn't appear in my browser.

**Comment by kwonoj** [comment] 2016-04-15 20:48
Interesting, I tried FF dev as well and got same. maybe my machine's doing something weird.. :/

**Comment by Guardiannw** [comment] 2016-04-15 20:57
@kwonoj It might be something like that.  It works in my firefox version too.

**Comment by kwonoj** [comment] 2016-04-15 20:58
Yup, sorry for bringing confusion :(

**Comment by Guardiannw** [comment] 2016-04-15 20:58
@kwonoj my new plnkr, [http://embed.plnkr.co/T0timA2kSvHwuIkARgOp/](http://embed.plnkr.co/T0timA2kSvHwuIkARgOp/)

I do get an error, but it says, 

undefined:1 Uncaught (in promise) TypeError: object is not a constructor
    at then (native)

**Comment by blesh** [comment] 2016-04-15 21:10
@Guardiannw: you'll want to memory profile your application to see what's being long-lived. [Here is a solid guide on memory profiling](https://developer.chrome.com/devtools/docs/javascript-memory-profiling). I wish we could be more help, but it could literally be anything. DOM references hanging around. Listeners you're not removing. Listeners ng2 isn't removing. A carried `this` context across an arrow function that ends up being long-lived. Anything. Until you run the profile and dig in, it'll be hard to tell.

Please keep us aware of your findings. And do reference this issue in the Angular 2 issue you file.

cc/ @jeffbcross @robwormald for visibility

**Comment by blesh** [comment] 2016-04-15 21:11
@Guardiannw ... also, if you can narrow it down to an rx-only implementation that leaks, then we can definitely help with that. But I've been unable to do so.

**Comment by Guardiannw** [comment] 2016-04-20 18:22
@kwonoj I think that error you found is indeed the source of the leak.  It looks like zone.js is keeping around event listeners and I have a bulk amount of long stack traces.  Not sure why this is doing this, I thought the zone.js rewrite was supposed to fix this.
cc/ @mhevery, do you know what is going on?

**Comment by blesh** [comment] 2016-04-22 04:10
@Guardiannw, since we can't reproduce it with just RxJS, I'm going to close this issue for now. If you're able to reproduce it with a minimal RxJS-only example, please do open another ticket. Thanks for submitting the issue to begin with!

**Closed by blesh** 2016-04-22 04:10 UTC

**Comment by Guardiannw** [comment] 2016-04-22 04:20
Thats fine, thanks for your time
