### ISSUE TITLE
This reference is lost in catch handler of an Observable

### ISSUE THREAD

**Issue by CaselIT** [ReactiveX/RxJS#1366] opened 2016-02-19 13:21 UTC
I'm not sure if this is a bug of RxJS or not.
Taking as an example the code below with creates an observer and handles its exception in a method of the class.
```ts
import { Observable } from 'rxjs';
class ObservableTest {
  methodReference() {
    return new Observable((obs) => obs.error('Method reference')).catch(this.handler);
  }
  fatArrow() {
    return new Observable((obs) => obs.error('Fat Arrow')
    ).catch((err, src, c) => this.handler(err, src, c));
  }
  handler(err, src, c) {
    console.log(`${err}: `, this === observableTest);
    return Observable.empty();
  }
}
var observableTest = new ObservableTest()
observableTest.methodReference().subscribe();
observableTest.fatArrow().subscribe();
```
In `methodReference()` in the catch function call I use the method reference, while in `fatArrow()` I use the fat arrow syntax to invoke the handler.
The problem I have is that I lose the reference to the class instance in the `this` variable when using the method reference.
For instance the above code prints
```
Method reference:  false
Fat Arrow:  true
```
Again I'm not sure if the problem is of RxJS. I'm using typescript and RxJS 5.0.0-beta.2, but the above code should be valid es6.

**Comment by kwonoj** [comment] 2016-02-19 18:13
Interesting question, I recently hit similar (not exactly though) cases.

This is basically occur by TypeScript's context capture is not exactly same as javascript. Ruling out Rx in this code snippet, let's simplify such as below snippet. (I haven't strictly followed type definition, etcs for just poc)

```js
function _catch(source: string, selector: Function): void {
  selector(source);
}

class ObservableTest {
  methodReference(): Function {
    return () => _catch('Method reference', this.handler);
  }

  fatArrow(): Function {
    return () => _catch('fat arrow', (err, src, c) => this.handler(err, src, c));
  }

  handler(err, src, c) {
    console.log(`${err}: `, this === observableTest);
    return Rx.Observable.empty();
  }
}
var observableTest = new ObservableTest()
let methodReference = observableTest.methodReference();
let lambda = observableTest.fatArrow();

methodReference();
lambda();
```

you may notice now each function returns function, simply invokes class instance method. Executing this code will results

```
Method reference:  false
fat arrow:  true
```

as same as before. TypeScript actually explains this behavior at this [document](https://github.com/Microsoft/TypeScript/wiki/'this'-in-TypeScript#red-flags-for-this), 
> The biggest red flag you can keep in mind is the use of a class method without immediately invoking it. Any time you see a class method being referenced without being invoked as part of that same expression, this might be incorrect.

So as simplest way to just make it work if changing invocation like

`return () => _catch('_', () => this.handler('Method reference', null, null));`

then now you can see context is captured as expected. 

```
Method reference:  true
fat arrow:  true
```

Course above snippet won't be application for catch operator, to have expected behavior using typescript you may refer same [doument](https://github.com/Microsoft/TypeScript/wiki/'this'-in-TypeScript#fixes) to figure out which way would be feasible in your cases. You actually did use 2nd suggestion of local fat arrow (https://github.com/Microsoft/TypeScript/wiki/'this'-in-TypeScript#local-fat-arrow).

Hope this answers for your question, and let me close this since I believe this is TypeScript behavior than Rx side issue. Please feel freely reopen if you think there's something unexpected behavior in Rx side.

**Closed by kwonoj** 2016-02-19 18:13 UTC

**Comment by david-driscoll** [comment] 2016-02-19 18:34
Just as a note this isn't really TypeScript behavior, but how the fat arrow is defined by the spec.  fat-arrow methods are explicitly scoped to the context of it's creation.  This means that the method returned in `fatArrow`, is contextually bound to the instance of the class when invoked.

In the second case `methodReference` you are literally handing off a reference to `this.handler` to the `catch` method.  `catch` itself has no reference to `this` so it, by design, doesn't apply a `this` context when invoking your method, so it behaves as just a normal function.  You can work around this by using `Function.bind` or fat arrows whatever works.

eg. `return new Observable((obs) => obs.error('Method reference')).catch(this.handler.bind(this));`

**Comment by kwonoj** [comment] 2016-02-19 18:35
Thanks for clarification, @david-driscoll :)

**Comment by CaselIT** [comment] 2016-02-19 18:46
@kwonoj Thanks for the reply. 
@david-driscoll  I was also thinking about the bind solution.
Yes I guess the problem, if we want to call it that, is really of javascript, since it has no notion of the the instance of the class, so the this.handler passed to catch is just a function.
I don't think this will change of es6, correct?

**Comment by david-driscoll** [comment] 2016-02-19 18:48
That is correct, that is the "intended" behavior for JavaScript.  No matter how confusing it might be when you compare the behavior in other languages, such as C# where that's my main background.

**Comment by CaselIT** [comment] 2016-02-19 18:55
I'm new to JS so at first I was comparing it to the C# behavior. Still the syntax is not really clear at first.
