### ISSUE TITLE
delayWhen operator doesn't delay the events if delayDurationSelector returns a Subject.

### ISSUE THREAD

**Issue by EarthyOrange** [ReactiveX/rxjs#5318] opened 2020-02-16 08:34 UTC
## Bug Report

**Current Behavior**
The delayWhen operator doesn't delay the events if delayDurationSelector returns a Subject.

**Reproduction**
- https://stackblitz.com/edit/rxjs-qzqjvf

**Expected behavior**
In the reproducible example, values 1-4 should not be printed.

**Environment**
- RxJS version: ^6.5.1

**Comment by cartant** [comment] 2020-02-16 08:50
It's because the subject - that you are using as the notifier - completes. The implementation of `delayWhen` does not delay if the notifier completes. There is some discussion [here](https://github.com/ReactiveX/rxjs/issues/3665#issuecomment-387758861) relating to this.

I've edited that issue's title to better reflect the problem.

**Comment by cartant** [comment] 2020-02-17 00:15
Closing this as a dupe of #3665, as I've had a play with the repro and if the `take` - that's applied to the observable to whicht the subject is subscribed - is bumped to, say, 100, the delay is applied. So this is the same problem as in the above issue - the subject completes when the `take` completes its source.

**Closed by cartant** 2020-02-17 00:15 UTC

**Comment by EarthyOrange** [comment] 2020-02-17 00:58
Thank you for looking in to it so quickly!!
