### ISSUE TITLE
Passing observer to do() completely breaks asynchronous observable

### ISSUE THREAD

**Issue by mattflix** [ReactiveX/rxjs#2503] opened 2017-03-29 22:33 UTC
**RxJS version:**
5.1.1

**Code to reproduce:**
This code may look contrived, but it is the boiled-down version of a technique that can be legitimately useful (i.e., passing an observer to the ```.do()``` operator):

```javascript
Rx.Observable
  .create(
    observer => {
      Rx.Observable
        .of(1, 2, 3)    
        .do(observer) // <-- passing observer to do()
        .subscribe();
    }
  )
  .delay(1) // <-- this asynchrony (any form will do) is required
            // to exhibit the problem reported in this issue
  .subscribe(
    next => console.log(`next ${ next }`),
    error => console.log(`error ${ error }`),
    () => console.log(`complete`)
  );
```

**Expected behavior:**
Outputs:
```
next 1
next 2
next 3
complete
```

**Actual behavior:**
Outputs nothing.  The overall observable just "dies".

It seems that the internals of the ```.delay()``` operator are somehow prematurely unsubscribed when ```.do()``` processes the ```complete()``` notification from upstream, and then not much else happens after that.

Note that the overall observable doesn't even complete, nor emit an error.

**Additional information:**
With Rx 4.0.6, the repro code emits the expected output.

With rxjs 5.1.1, the following "tweaks" to the repro code will cause the expected output to be emitted.  (Possibly these tweaks will help highlight the root problem to the developers.)

* Tweak 1: Wrap the observer.

```javascript
Rx.Observable
  .create(
    observer => {
      Rx.Observable
        .of(1, 2, 3)
        .do({  // <-- wrapper object
          next(v) { observer.next(v); },
          error(e) { observer.error(e); },
          complete() { observer.complete(); },
        })
        .subscribe();
    }
  )
  .delay(1)
  .subscribe(
    next => console.log(`next ${ next }`),
    error => console.log(`error ${ error }`),
    () => console.log(`complete`)
  );
```

Outputs:
```
next 1
next 2
next 3
complete
```

It is my theory that ```.do()``` is interacting badly with the rest of the observable chain when passed directly the same ```Observer``` implementation that an ```Observable.create()``` callback receives.  Wrapping the implementation object in another object (without changing the behavior) hides the actual implementation from ```.do()``` and somehow avoids triggering the bad behavior.  In my investigation, the bad behavior is triggered when ```.do()``` processes the upstream ```.complete()``` notification.

* Tweak 2: Pass the observer to ```.subscribe()``` instead.

```javascript
Rx.Observable
  .create(
    observer => {
      Rx.Observable
        .of(1, 2, 3)
        // .do(observer) instead of this...
        .subscribe(observer); // <-- do this
    }
  )
  .delay(1)
  .subscribe(
    next => console.log(`next ${ next }`),
    error => console.log(`error ${ error }`),
    () => console.log(`complete`)
  );
```

Outputs:
```
next 1
next 2
next 3
complete
```

* Tweak 3: Add another operator before the asynchronous part of the chain.

```javascript
Rx.Observable
  .create(
    observer => {
      Rx.Observable
        .of(1, 2, 3)
        .do(observer)
        .subscribe();
    }
  )
  .do({}) // <-- intermediary (using a "no-op" .do() works, perhaps any operator will?)
  .delay(1)
  .subscribe(
    next => console.log(`next ${ next }`),
    error => console.log(`error ${ error }`),
    () => console.log(`complete`)
  );
```

Outputs:
```
next 1
next 2
next 3
complete
```

I have no idea why adding an intermediary no-op should change the overall behavior (but again, perhaps it will help to highlight the internal issue for the developers).

* Tweak 4: Remove the asynchrony.

```javascript
Rx.Observable
  .create(
    observer => {
      Rx.Observable
        .of(1, 2, 3)
        .do(observer)
        .subscribe();
    }
  )
  // .delay(1) <-- removed
  .subscribe(
    next => console.log(`next ${ next }`),
    error => console.log(`error ${ error }`),
    () => console.log(`complete`)
  );
```

Outputs:
```
next 1
next 2
next 3
complete
```

Fully synchronous execution somehow side-steps the bad behavior.

**Comment by staltz** [comment] 2017-03-30 14:53
Thanks for the detailed report. There **may** be a bug somewhere, but the use case you described is very close to what I would call an anti-pattern. 

Observable.create is an advanced method because the programmer needs to guarantee the Observable contract, and is usually used simply to implement a low-level source of data. In our case the low-level source of data is `of(1,2,3)` and hence you wouldn't need Observable.create anymore. You should probably have used Observable.defer:

```js
Rx.Observable
  .defer(
    () => 
      Rx.Observable
        .of(1, 2, 3)
  )
  .delay(1)
  .subscribe(
    next => console.log(`next ${ next }`),
    error => console.log(`error ${ error }`),
    () => console.log(`complete`)
  );
```

Note also that the `observer` in `Observable.create(observer =>` is actually a Subscriber, which is an internal mechanism, which I'd recommend not messing with. Furthermore, `.do(observer).subscribe()` is certainly screaming anti-pattern, when the correct use is `.subscribe(observer)`.

Indeed there may still be a bug somewhere, but I'd prefer the reproducible use case to reflect a normal use case instead of a contrived and risky use case.

**Comment by mattflix** [comment] 2017-03-30 18:49
@staltz, thanks for the response.

As mentioned (first sentence above), the example is purposely contrived to be as simple as I could possibly make it and still exhibit the problem.  (This is usually what one wants in a bug report, no?)

We can debate the merits of my use-case of passing an Observer directly to ```.do()``` as an "anti-pattern", but I'm not sure if this is an appropriate forum for that discussion?  If it is, or if it would help resolve this issue, please let me know.

In short, the actual application is a serialized task executor, where tasks are ```Observable```s.  I am using ```.do()``` to have a side-effect in one ```Observable``` from another, which just happens to require the effects of ```next()```, ```error()```, and ```complete()``` -- the exact contract supported by ```.do()```.  I would be happy to learn of an improved technique for solving my application.

That said, my conjecture is still that ```.do()``` somehow "knows more than it should" about the incoming object, and its behavior is badly affected when the object happens to be an instance of rxjs's own ```Observer``` implementation.  This is clearly proved by Tweak 1 above.  (Btw, a variation of this tweak, where all three ```Observer``` methods are wrapped up as three separate methods and then passed to ```.do()```, also produces the expected result.)

I think if ```.do()``` would strictly limit its knowledge of the incoming object to simply whether or not it implements ```next()```, ```error()```, and ```complete()```, this issue would probably be solved.  There is likely some unintentional leak in the internal abstractions where ```.do()``` looks at other aspects of the incoming object, which it has no reason to, leading to unintended behavior.

**Comment by davidwdan** [comment] 2017-03-30 20:43
This issue will be fixed with https://github.com/ReactiveX/rxjs/pull/2238

**Comment by mattflix** [comment] 2017-03-30 21:15
@davidwdan, will it really?  You may have jumped to a conclusion (partially my fault, though).

I realize now that I should have probably also mentioned that I am also aware of the "no-arguments" ```subscribe()``` issue and that I have my own local patch for that.  My patch was in effect when I discovered this issue, but I did not reflect the patching in any way in my repro code above.  (See below for updated repro code.)

So, please note:  The  "no-arguments" ```subscribe()``` issue is likely NOT affecting the behavior described in this issue, and so #2238 might not actually fix this issue as suggested.

That said, I will be pleased if it is somehow fixed.

But, to make things clear, if I apply a simple workaround for the "no-arguments" ```subscribe()``` issue to my original repro code, it still exhibits the problem behavior.

*(Modified) Code to reproduce*

```
Rx.Observable
  .create(
    observer => {
      Rx.Observable
        .of(1, 2, 3)    
        .do(observer) // <-- passing observer to do()
        .subscribe({}); // <-- modification:  workaround for "no-arguments" issue
    }
  )
  .delay(1) // <-- this asynchrony (any form will do) is required
            // to exhibit the problem reported in this issue
  .subscribe(
    next => console.log(`next ${ next }`),
    error => console.log(`error ${ error }`),
    () => console.log(`complete`)
  );
```

*Expected behavior:*
Outputs:

```
next 1
next 2
next 3
complete
```

*Actual behavior:*
Outputs nothing. The overall observable just "dies".

**Comment by trxcllnt** [comment] 2017-03-31 08:47
@mattflix this does seem strange. I'll take a look this weekend and report back.

**Comment by mattflix** [comment] 2017-04-24 21:55
@trxcllnt, any progress?

**Comment by trxcllnt** [comment] 2017-04-25 02:31
@mattflix sorry for the delay -- I see the issue. There's a bug in the `do` operator that's causing it to dispose the DelaySubscriber when the Observable inside the create callback completes. As you noted in tweak 3, any operator between the do and create will make it work as expected.

I haven't validated this locally, but I think there are two issues:
1. [this line](https://github.com/ReactiveX/rxjs/blob/master/src/operator/do.ts#L86) should be `toSubscriber(nextOrObserver, error, complete)` like in [Observable#subscribe](https://github.com/ReactiveX/rxjs/blob/master/src/Observable.ts#L93), so we avoid wrapping Rx Subscribers inside a SafeSubscriber, and
2. [this line](https://github.com/ReactiveX/rxjs/blob/master/src/operator/do.ts#L88) seems to have the subscription reference order backwards, and should probably be `safeSubscriber.add(this)`. This change would mirror the relationship between source and destination Subscribers set in the [Subscriber ctor](https://github.com/ReactiveX/rxjs/blob/master/src/Subscriber.ts#L72)

**Comment by mattflix** [comment] 2017-04-26 00:07
Excellent @trxcllnt.  Thanks, and hopefully you've pinned down the issue(s?).

Any idea when what you've spotted can be corrected, but you or someone else?

**Comment by mattflix** [comment] 2017-07-05 22:18
*Bump*

@trxcllnt, any chance for a fix soon?

**Comment by benlesh** [comment] 2018-05-21 17:42
Closing as stale

**Closed by benlesh** 2018-05-21 17:42 UTC

**Comment by mattflix** [comment] 2018-05-21 23:14
@benlesh, why did you close this?

You claim it is stale, but the repro case (unchanged) still demonstrates the issue when run against `rxjs@5.5.10`.
