### ISSUE TITLE
takeUntil not cooperating with toPromise

### ISSUE THREAD

**Issue by omarmeky** [ReactiveX/rxjs#5689] opened 2020-09-02 16:07 UTC
## (Potential) Bug Report

**Current Behavior**

For:

```
A.pipe(takeUntil(B)).subscribe(doSomething);
```

If `B` fires, then `doSomething` is never called (as expected).

But if I convert to a promise:

```
A.pipe(takeUntil(B)).toPromise().then(doSomething);
```

Now `doSomething` is called as soon as `B` fires!

**Expected behavior**
Scenario 2 should behave like scenario 1. I.e. `B` should not trigger the promise.

**Environment**
- Runtime: [Chrome 84]
- RxJS version: 6.5.4

**Comment by niklas-wortmann** [comment] 2020-09-02 17:51
This is not a big but works as designed. Takeuntil will complete the observable (which is key for to promise to work). If you would use the 'complete' callback inside subscribe and call doSomething there, it would behave the same. Close this as this is intended behavior

**Closed** 2020-09-02 17:51 UTC
