### ISSUE TITLE
Compilation failes with TypeScript 2.4.X

### ISSUE THREAD

**Issue by alan-agius4** [ReactiveX/rxjs#2706] opened 2017-06-28 18:16 UTC
The new release of typesriptes break the usage of rxjs library due to stricter generics.

https://github.com/Reactive-Extensions/RxJS/issues/1487

**Comment by kwonoj** [comment] 2017-06-28 18:17
dupe of #2699 , #2539, #2700 . #2701 #2702 #2703 https://github.com/ReactiveX/rxjs/issues/2704 https://github.com/ReactiveX/rxjs/issues/2705

**Closed by kwonoj** 2017-06-28 18:17 UTC

**Comment by alan-agius4** [comment] 2017-06-28 18:19
Which one is the main post for this issue?

**Comment by kwonoj** [comment] 2017-06-28 18:20
not closed one.

**Comment by whymarrh** [comment] 2017-06-28 21:20
Spoiler for future readers: #2539 is the "not closed one."
