### ISSUE TITLE
'Subscription' is not a class derived from 'Subscription'.

### ISSUE THREAD

**Issue by kdshop** [ReactiveX/rxjs#5259] opened 2020-01-23 10:13 UTC
## Bug Report

**Current Behavior**
Type `Subscription` from `6.5` appears to be incompatible with type `Subscription` from `6.4`

Error msg:
`Property '_parentOrParents' is protected but type 'Subscription' is not a class derived from 'Subscription'.`

**Comment by cartant** [comment] 2020-01-23 10:19
To be actionable, this needs a minimal reproduction.

**Comment by kdshop** [comment] 2020-01-26 08:35
Sure, will provide asap

**Comment by MzoroHaHa** [comment] 2021-01-06 02:11
```
Error: node_modules/rxjs/src/internal/scheduled/scheduled.ts:25:7 - error TS2322: Type 'import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/src/internal/Observable").Observable<T>' is not assignable to type 'import("D:/workspace/
git/barn/web/barn-ng/node_modules/rxjs/internal/Observable").Observable<T>'.
  The types of 'source.operator.call' are incompatible between these types.
    Type '(subscriber: import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/src/internal/Subscriber").Subscriber<any>, source: any) => import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/src/internal/types").TeardownLogic'
 is not assignable to type '(subscriber: import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/internal/Subscriber").Subscriber<any>, source: any) => import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/internal/types").Tear
downLogic'.
      Types of parameters 'subscriber' and 'subscriber' are incompatible.
        Type 'import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/internal/Subscriber").Subscriber<any>' is not assignable to type 'import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/src/internal/Subscriber").Subscriber<
any>'.
          Property 'isStopped' is protected but type 'Subscriber<T>' is not a class derived from 'Subscriber<T>'.

25       return scheduleObservable(input, scheduler);
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/rxjs/src/internal/scheduled/scheduled.ts:25:40 - error TS2345: Argument of type 'import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/internal/types").SchedulerLike' is not assignable to parameter of type 'import("D:/
workspace/git/barn/web/barn-ng/node_modules/rxjs/src/internal/types").SchedulerLike'.
  Types of property 'schedule' are incompatible.
    Type '<T>(work: (this: import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/internal/types").SchedulerAction<T>, state?: T) => void, delay?: number, state?: T) => import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/int
ernal/Subscription").Subscription' is not assignable to type '<T>(work: (this: import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/src/internal/types").SchedulerAction<T>, state?: T) => void, delay?: number, state?: T) => import(
"D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/src/internal/Subscription").Subscription'.
      Types of parameters 'work' and 'work' are incompatible.
        The 'this' types of each signature are incompatible.
          Type 'import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/internal/types").SchedulerAction<T>' is not assignable to type 'import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/src/internal/types").SchedulerAction<
T>'.
            The types returned by 'schedule(...)' are incompatible between these types.
              Type 'import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/internal/Subscription").Subscription' is not assignable to type 'import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/src/internal/Subscription").Subs
cription'.
                Property '_parentOrParents' is protected but type 'Subscription' is not a class derived from 'Subscription'.

25       return scheduleObservable(input, scheduler);
                                          ~~~~~~~~~
node_modules/rxjs/src/internal/scheduled/scheduled.ts:27:70m - error TS2322: Type 'import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/src/internal/Observable").Observable<T>' is not assignable to type 'import("D:/workspace/git/b
arn/web/barn-ng/node_modules/rxjs/internal/Observable").Observable<T>'.

27       return schedulePromise(input, scheduler);
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/rxjs/src/internal/scheduled/scheduled.ts:27:37 - error TS2345: Argument of type 'import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/internal/types").SchedulerLike' is not assignable to parameter of type 'import("D:/
workspace/git/barn/web/barn-ng/node_modules/rxjs/src/internal/types").SchedulerLike'.

27       return schedulePromise(input, scheduler);
                                       ~~~~~~~~~
node_modules/rxjs/src/internal/scheduled/scheduled.ts:29:7 - error TS2322: Type 'import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/src/internal/Observable").Observable<T>' is not assignable to type 'import("D:/workspace/git/bar
n/web/barn-ng/node_modules/rxjs/internal/Observable").Observable<T>'.

29       return scheduleArray(input, scheduler);
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/rxjs/src/internal/scheduled/scheduled.ts:29:35 - error TS2345: Argument of type 'import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/internal/types").SchedulerLike' is not assignable to parameter of type 'import("D:/
workspace/git/barn/web/barn-ng/node_modules/rxjs/src/internal/types").SchedulerLike'.

29       return scheduleArray(input, scheduler);
                                     ~~~~~~~~~
node_modules/rxjs/src/internal/scheduled/scheduled.ts:31:7 - error TS2322: Type 'import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/src/internal/Observable").Observable<T>' is not assignable to type 'import("D:/workspace/git/bar
n/web/barn-ng/node_modules/rxjs/internal/Observable").Observable<T>'.

31       return scheduleIterable(input, scheduler);
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/rxjs/src/internal/scheduled/scheduled.ts:31:38 - error TS2345: Argument of type 'import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/internal/types").SchedulerLike' is not assignable to parameter of type 'import("D:/
workspace/git/barn/web/barn-ng/node_modules/rxjs/src/internal/types").SchedulerLike'.

31       return scheduleIterable(input, scheduler);
                                        ~~~~~~~~~
node_modules/rxjs/src/internal/observable/from.ts:116:5 - error TS2322: Type 'import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/internal/Observable").Observable<T>' is not assignable to type 'import("D:/workspace/git/barn/web/b
arn-ng/node_modules/rxjs/src/internal/Observable").Observable<T>'.
  The types of 'source.operator.call' are incompatible between these types.
    Type '(subscriber: import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/internal/Subscriber").Subscriber<any>, source: any) => import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/internal/types").TeardownLogic' is not
assignable to type '(subscriber: import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/src/internal/Subscriber").Subscriber<any>, source: any) => import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/src/internal/types").Tear
downLogic'.
      Types of parameters 'subscriber' and 'subscriber' are incompatible.
        Type 'import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/src/internal/Subscriber").Subscriber<any>' is not assignable to type 'import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/internal/Subscriber").Subscriber<
any>'.
          Property 'isStopped' is protected but type 'Subscriber<T>' is not a class derived from 'Subscriber<T>'.

116     return scheduled(input, scheduler);
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/rxjs/src/internal/observable/from.ts:116:29 - error TS2345: Argument of type 'import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/src/internal/types").SchedulerLike' is not assignable to parameter of type 'import("D:
/workspace/git/barn/web/barn-ng/node_modules/rxjs/internal/types").SchedulerLike'.
  Types of property 'schedule' are incompatible.
    Type '<T>(work: (this: import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/src/internal/types").SchedulerAction<T>, state?: T) => void, delay?: number, state?: T) => import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs
/src/internal/Subscription").Subscription' is not assignable to type '<T>(work: (this: import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/internal/types").SchedulerAction<T>, state?: T) => void, delay?: number, state?: T) => imp
ort("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/internal/Subscription").Subscription'.
      Types of parameters 'work' and 'work' are incompatible.
        The 'this' types of each signature are incompatible.
          Type 'import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/src/internal/types").SchedulerAction<T>' is not assignable to type 'import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/internal/types").SchedulerAction<
T>'.
            The types returned by 'schedule(...)' are incompatible between these types.
              Type 'import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/src/internal/Subscription").Subscription' is not assignable to type 'import("D:/workspace/git/barn/web/barn-ng/node_modules/rxjs/internal/Subscription").Subs
cription'.
                Property '_parentOrParents' is protected but type 'Subscription' is not a class derived from 'Subscription'.

116     return scheduled(input, scheduler);
                                ~~~~~~~~~

```

**Comment by kwonoj** [comment] 2021-01-22 20:48
Closing as lacks of info / and we'd like to recommend to test 7.x since there are lot of internal changes.

**Closed by kwonoj** 2021-01-22 20:48 UTC
Labels: status: needs info
