### ISSUE TITLE
forkJoin dictionary syntax deprecation in V8

### ISSUE THREAD

**Issue by anup11** [ReactiveX/rxjs#6420] opened 2021-05-24 15:21 UTC
forkJoin dictionary syntax is showing warning for deprecation in V8.

Current Rxjs version used: 7.0.0

From documenation 
```
const observable = forkJoin({
  foo: of(1, 2, 3, 4),
  bar: Promise.resolve(8),
  baz: timer(4000),
});
observable.subscribe({
 next: value => console.log(value),
 complete: () => console.log('This is how it ends!'),
});
 
// Logs:
// { foo: 4, bar: 8, baz: 0 } after 4 seconds
// "This is how it ends!" immediately after
```
But it is showing deprecation warring.

I have exactly same scenario where I want to make several http calls in parallel and create a map of observables. On success of all observables I should get the map with values returned by corresponding observables.

```
const observable = forkJoin({
  service_1: observable_returned_by_httClient.get(service1),
  service_2: observable_returned_by_httClient.get(service2),
  service_3: observable_returned_by_httClient.get(service3),
});
observable.subscribe({
 next: value => console.log(value);
});

Expected:
{
  service_1: value_returned_by_observable,
  service_1: value_returned_by_observable,
  service_1: value_returned_by_observable
}
```

If it is going to be deprecated, please help in solving this scenario.
Thanks in advance...!!

**Comment by cartant** [comment] 2021-05-24 22:13
Closing this because it's not deprecated in the source:

https://github.com/ReactiveX/rxjs/blob/5de9e1b355234158ea4320eb4ffd08cbee988c32/src/internal/observable/forkJoin.ts#L43-L47

 and because the behaviour cannot be reproduced with the latest versions of RxJS and TypeScript:

<img width="381" alt="Capture" src="https://user-images.githubusercontent.com/3878593/119413479-08959500-bd31-11eb-81c8-2843cf3cf27b.PNG">

**Closed by cartant** 2021-05-24 22:13 UTC

**Comment by anup11** [comment] 2021-05-25 04:07
Hi @cartant ,
Thanks..!!
Can you please suggest the resolution for the issue I am facing.
Here is the plunkr link for the issue.
[](https://plnkr.co/edit/6V3gjkM6GSVuZIhk?open=lib%2Fapp.ts&deferRun=1)

**Comment by frankiedrake** [comment] 2021-07-07 08:18
Have the same problem
Angular 12.0.3
Typescript 4.2.3
