### ISSUE TITLE
`error` attribute is not available in throwError?

### ISSUE THREAD

**Issue by mkHun** [ReactiveX/rxjs#4507] opened 2019-01-29 08:00 UTC
## Bug Report

**Current Behavior**
Angular 2
```
    let throwEr = Observable.throw(error || 'Server error');
    console.log(throwEr);
   // console.log
   ErrorObservable {_isScalar: false, error: Response, scheduler: undefined}
```
After updating to Angular 7

```
import { Observable, throwError } from 'rxjs';
...

let throwEr =  throwError(error || 'Server error');
console.log(throwEr);
// console.log
Observable {_isScalar: false, _subscribe: ƒ}
```
After updating to Angular 7 error attribute is missing from the object and not able to handle the error response.

**Comment by kwonoj** [comment] 2019-01-29 08:11
This is technically breaking changes in v6 (https://github.com/ReactiveX/rxjs/pull/3288) and somehow it is not written as breaking change in changelog.

In either cases, imperatively reading properties in Observable was never recommended practice, I don't think we want to bring back this behavior.

**Comment by BioPhoton** [comment] 2019-08-12 11:40
@mkHun

As the problem is explained in the answer of @kwonoj and the requested feature will not get implemented I recommend closing this issue. 

Also maybe @JWO719 could consider closing this.

**Comment by cartant** [comment] 2021-03-14 11:23
Closing because - as mentioned above - the properties are internal.

**Closed by cartant** 2021-03-14 11:23 UTC
