### ISSUE TITLE
Idenitifier self is not declared, breaks when `self` its leaked.

### ISSUE THREAD

**Issue by anodynos** [ReactiveX/rxjs#1930] opened 2016-09-09 11:18 UTC
The `self` identifier is NOT declared locally in the module and hence it comes from global - in https://github.com/ReactiveX/rxjs/blob/3793e4768dd2655300b67a82be9b30c4c065bac1/src/util/root.ts#L21

So, depending on what `window.self` value might be (i.e from leaked variables, a common mistake of devs), RxJS might break. 

**RxJS version:**
`5.0.0-beta.11`

**Code to reproduce:**
Add a `window.self` variable with different values and run tests.

**Comment by kwonoj** [comment] 2016-09-09 14:52
As far as I know as same as other global variables like `window`, it is looking existing global variable to check if global already has defined 
(The Window.self read-only property returns the window itself - https://developer.mozilla.org/ko/docs/Web/API/Window/self).

I think it's expected behavior to allow setup your own environment.

/cc @blesh , @jayphelps since I could be wrong..

**Comment by anodynos** [comment] 2016-09-09 15:16
Well, it's not read only in Chrome Version 53.0.2785.92 (64-bit) - I assume in other browsers also... 
```
-> window.self
Window {speechSynthesis: SpeechSynthesis, caches: CacheStorage, localStorage: Storage, sessionStorage: Storage, webkitStorageInfo: DeprecatedStorageInfo…}
->  window.self = {some:'value'};
Object {some: "value"}
->  window.self
Object {some: "value"}
```

This makes RxJS very prone to errors, especially for libs etc that run in uncontrolled code sites.

**Comment by anodynos** [comment] 2016-09-09 15:43
Same for *Firefox 48.0*
```
-> window.self = {'some':'value'}; window.self
Object { some="value"}
```

**Comment by jayphelps** [comment] 2016-09-09 16:52
Did this actually happen in real life or just discussing the possibility?

`self` is important because in WebWorkers `window` does not exist. Using it is common, even some of the most popular libraries around like [underscore](https://github.com/jashkenas/underscore/blob/master/underscore.js#L14).

Any alternatives?

**Comment by blesh** [comment] 2016-09-09 17:14
This seems like trying to defend against developers defining `undefined`.

**Comment by jayphelps** [comment] 2016-09-09 17:27
I see @blesh's point--but this is indeed a bit more insidious:

```js

function UserClassOfSomething() {
  self = this;
}

user = new UserClassOfSomething();
// self === user
// whoops
```

where as `undefined = 'something'` would be much more obviously stupid to do, and also in every compliant ES5 runtime (all browsers I tested several years ago) redefining it in this way is a noop. `undefined = 123; alert(undefined);` does not alert 123.

It's only a problem in ES5 when shadowing with a new declaration `var undefined = 123;` and only within a function's scope, not globally.

```js
(function () { var undefined = 132; alert(undefined); })()
```

..but that's even less likely to affect us cause it would mean someone did this in code that wraps our code. There's little point to worrying about that because there are a billion similar things people _could_ do to fuck up our code if they're wrapping it in another function.

**that said** I don't think in practice this `self` business is a major issue. We could certainly make it a safer for the 99% case..something like `typeof self === 'object' && self.self === self && self`. Then it's only an issue if you reassign it inside a Worker that uses Rx..at which point you're SOL. Reasonable vs. exhaustive efforts I think applies in these cases given the nature of JavaScript.

**Comment by anodynos** [comment] 2016-09-09 19:53
@jayphelps yes, it's a real case, we had an incident with a client's code that was overwriting `self` by mistake, and we found out the hard way that RxJs was the issue... It certainly needs to have a guard like the above and default to `window` or `global` if they are available.

**Closed** 2016-09-15 23:31 UTC
